import type { LessonGuide } from "../types"
import type { QuizQuestion } from "@/lib/types"

export const week24Guides: Record<string, LessonGuide> = {
    "py-w24-1": {
        lessonId: "py-w24-1",
        background: [
            "【Matplotlib pyplot】matplotlib.pyplot 是 MATLAB 风格的绑定接口。通过函数调用隐式管理当前图形和坐标轴。",
            "【基本图表】plt.plot() 折线图；plt.scatter() 散点图；plt.bar() 柱状图；plt.hist() 直方图。",
            "【格式字符串】plt.plot(x, y, 'ro') 中 'ro' 表示红色圆点。格式：[颜色][标记][线型]，如 'b--' 蓝色虚线。",
            "【标签与标题】plt.xlabel()、plt.ylabel() 设置轴标签；plt.title() 设置标题；plt.legend() 显示图例。",
            "【保存图表】plt.savefig('figure.png') 保存为文件，支持 PNG、PDF、SVG 等格式。",
        ],
        keyDifficulties: [
            "【plt.show()】显示图表并阻塞程序。在脚本中通常放在最后，Jupyter 中可省略。",
            "【subplot 语法】plt.subplot(nrows, ncols, index) 或 plt.subplot(211) 表示 2 行 1 列第 1 个。",
            "【数据格式】所有序列内部转换为 NumPy 数组。可直接传入列表或 Pandas Series。",
            "【对数刻度】plt.xscale('log')、plt.yscale('log') 设置对数刻度。",
        ],
        handsOnPath: [
            "1. 导入：import matplotlib.pyplot as plt",
            "2. 折线图：plt.plot([1, 2, 3], [1, 4, 9])",
            "3. 添加标签：plt.xlabel('X'); plt.ylabel('Y'); plt.title('My Plot')",
            "4. 散点图：plt.scatter(x, y, c='red', s=50)",
            "5. 直方图：plt.hist(data, bins=20)",
            "6. 保存：plt.savefig('plot.png', dpi=300)",
        ],
        selfCheck: [
            "'ro' 格式字符串表示什么？",
            "如何设置 x 轴和 y 轴标签？",
            "如何保存图表为 PNG 文件？",
            "plt.subplot(211) 表示什么？",
            "如何设置对数刻度？",
            "plt.show() 的作用是什么？",
        ],
        extensions: [
            "学习更多标记和线型选项",
            "了解 annotate() 添加注释",
            "探索颜色映射（colormap）",
            "学习 3D 绑定（mplot3d）",
        ],
        sourceUrls: [
            "https://matplotlib.org/stable/contents.html",
            "https://matplotlib.org/stable/users/explain/quick_start.html",
            "https://matplotlib.org/stable/tutorials/pyplot.html",
        ],
    },
    "py-w24-2": {
        lessonId: "py-w24-2",
        background: [
            "【面向对象接口】fig, ax = plt.subplots() 显式创建 Figure 和 Axes 对象。更灵活，推荐用于复杂图表。",
            "【Figure 和 Axes】Figure 是整个图形容器；Axes 是实际绑定区域，包含数据、坐标轴、标题等。",
            "【子图布局】plt.subplots(2, 2) 创建 2×2 子图网格；plt.subplot_mosaic() 支持复杂布局。",
            "【样式表】plt.style.use('ggplot') 应用预定义样式。可用样式：seaborn、ggplot、bmh 等。",
            "【保存格式】savefig() 支持 PNG、PDF、SVG、EPS。dpi 参数控制分辨率。",
        ],
        keyDifficulties: [
            "【ax 方法命名】面向对象接口方法带 set_ 前缀：ax.set_xlabel()、ax.set_title()（而非 plt.xlabel）。",
            "【layout 参数】layout='constrained' 或 'tight' 自动调整子图布局避免重叠。",
            "【多子图访问】subplots 返回的 ax 是数组。ax[0, 1] 访问第一行第二列。单行/列时是一维数组。",
            "【figsize 参数】figsize=(width, height) 单位是英寸，控制图形大小。",
        ],
        handsOnPath: [
            "1. 创建子图：fig, ax = plt.subplots(figsize=(8, 6))",
            "2. 绑定数据：ax.plot(x, y, label='line 1')",
            "3. 设置属性：ax.set_xlabel('X'); ax.set_ylabel('Y'); ax.set_title('Title')",
            "4. 多子图：fig, axes = plt.subplots(2, 2)",
            "5. 应用样式：plt.style.use('seaborn-v0_8')",
            "6. 保存图片：fig.savefig('figure.pdf', dpi=150)",
        ],
        selfCheck: [
            "plt.subplots() 返回什么？",
            "Figure 和 Axes 的区别是什么？",
            "面向对象接口的方法命名有什么特点？",
            "如何创建 2×2 的子图网格？",
            "如何应用预定义样式？",
            "layout='constrained' 的作用是什么？",
        ],
        extensions: [
            "学习 GridSpec 精细布局控制",
            "了解 colorbar 添加色彩条",
            "探索 twinx()/twiny() 双轴图",
            "学习自定义样式表",
        ],
        sourceUrls: [
            "https://matplotlib.org/stable/gallery/subplots_axes_and_figures/index.html",
            "https://matplotlib.org/stable/gallery/style_sheets/style_sheets_reference.html",
            "https://matplotlib.org/stable/plot_types/index.html",
        ],
    },
    "py-w24-3": {
        lessonId: "py-w24-3",
        background: [
            "【Seaborn】基于 Matplotlib 的统计可视化库。提供美观的默认样式和高级统计图表。",
            "【主要函数】relplot() 关系图；displot() 分布图；catplot() 分类图。kind 参数切换图表类型。",
            "【DataFrame 集成】直接接受 Pandas DataFrame，通过列名指定变量。data 参数传入数据。",
            "【自动统计】自动计算并显示置信区间、回归线等统计信息。",
            "【主题设置】set_theme() 设置整体风格；set_palette() 设置调色板。",
        ],
        keyDifficulties: [
            "【hue 参数】按类别着色，自动创建图例。适用于分组可视化。",
            "【FacetGrid】catplot/relplot 返回 FacetGrid 对象，可以进一步自定义。",
            "【统计估计】默认显示均值和 95% 置信区间。可通过 estimator 和 ci 参数调整。",
            "【与 Matplotlib 配合】Seaborn 图表基于 Matplotlib，可用 plt 函数进一步自定义。",
        ],
        handsOnPath: [
            "1. 导入：import seaborn as sns",
            "2. 设置主题：sns.set_theme(style='whitegrid')",
            "3. 散点图：sns.scatterplot(data=df, x='x', y='y', hue='category')",
            "4. 分布图：sns.histplot(data=df, x='value', kde=True)",
            "5. 箱线图：sns.boxplot(data=df, x='group', y='value')",
            "6. 热力图：sns.heatmap(corr_matrix, annot=True)",
        ],
        selfCheck: [
            "Seaborn 与 Matplotlib 的关系是什么？",
            "hue 参数的作用是什么？",
            "如何设置 Seaborn 的主题风格？",
            "relplot、displot、catplot 分别用于什么？",
            "如何在直方图上叠加核密度估计？",
            "如何创建热力图？",
        ],
        extensions: [
            "学习 pairplot() 探索多变量关系",
            "了解 lmplot() 回归可视化",
            "探索 violinplot() 小提琴图",
            "学习自定义调色板",
        ],
        sourceUrls: [
            "https://seaborn.pydata.org/",
            "https://seaborn.pydata.org/tutorial.html",
            "https://seaborn.pydata.org/examples/index.html",
        ],
    },
    "py-w24-4": {
        lessonId: "py-w24-4",
        background: [
            "【Jupyter Notebook】交互式计算环境，结合代码、文本、可视化于一体。广泛用于数据分析和教学。",
            "【Cell 类型】Code Cell 执行代码；Markdown Cell 编写格式化文本；Raw Cell 原始内容。",
            "【Magic 命令】IPython 特殊命令。% 行魔法（单行），%% 单元魔法（整个单元格）。",
            "【%matplotlib inline】在 Notebook 中内嵌显示图表，无需 plt.show()。",
            "【常用魔法】%time 计时；%timeit 多次计时取平均；%run 运行脚本；%%writefile 写入文件。",
        ],
        keyDifficulties: [
            "【执行顺序】Cell 可以任意顺序执行，可能导致状态不一致。Kernel → Restart 重置状态。",
            "【Markdown 语法】支持标题（#）、列表（-）、链接、图片、代码块、LaTeX 公式（$...$）。",
            "【变量作用域】所有 Cell 共享同一个命名空间，变量在 Cell 间共享。",
            "【自动补全】Tab 键自动补全；Shift+Tab 显示函数文档。",
        ],
        handsOnPath: [
            "1. 启动：jupyter notebook 或 jupyter lab",
            "2. 新建笔记本：New → Python 3",
            "3. 运行代码：Shift+Enter 执行并跳到下一个 Cell",
            "4. 内嵌图表：%matplotlib inline",
            "5. 计时：%time slow_function(); %timeit fast_function()",
            "6. Markdown：切换 Cell 类型为 Markdown，编写文档",
        ],
        selfCheck: [
            "Jupyter Notebook 的主要用途是什么？",
            "%matplotlib inline 的作用是什么？",
            "%time 和 %timeit 的区别是什么？",
            "如何在 Notebook 中编写 Markdown？",
            "Cell 的执行顺序问题如何解决？",
            "如何重置 Notebook 的状态？",
        ],
        extensions: [
            "学习 JupyterLab 进阶环境",
            "了解 nbconvert 导出为其他格式",
            "探索 ipywidgets 交互式控件",
            "学习 papermill 参数化执行",
        ],
        sourceUrls: [
            "https://jupyter.org/documentation",
            "https://jupyter-notebook.readthedocs.io/en/latest/",
            "https://ipython.readthedocs.io/en/stable/interactive/magics.html",
        ],
    },
}

export const week24Quizzes: Record<string, QuizQuestion[]> = {
    "py-w24-1": [
        {
            id: "py-w24-1-q1",
            question: "'ro' 格式字符串表示什么？",
            options: [
                "红色虚线",
                "红色圆点",
                "蓝色圆点",
                "红色方块",
            ],
            answer: 1,
            rationale: "文档说明：r 表示红色（red），o 表示圆点标记。",
        },
        {
            id: "py-w24-1-q2",
            question: "如何保存图表为 PNG 文件？",
            options: [
                "plt.save('plot.png')",
                "plt.savefig('plot.png')",
                "plt.export('plot.png')",
                "plt.write('plot.png')",
            ],
            answer: 1,
            rationale: "文档说明：plt.savefig() 保存当前图形到文件。",
        },
        {
            id: "py-w24-1-q3",
            question: "plt.subplot(211) 表示什么？",
            options: [
                "21 行 1 列",
                "2 行 1 列的第 1 个子图",
                "2 行 11 列",
                "第 211 个子图",
            ],
            answer: 1,
            rationale: "文档说明：三位数格式 nmi 表示 n 行 m 列的第 i 个子图。",
        },
        {
            id: "py-w24-1-q4",
            question: "如何创建直方图？",
            options: [
                "plt.bar(data)",
                "plt.hist(data)",
                "plt.histogram(data)",
                "plt.barchart(data)",
            ],
            answer: 1,
            rationale: "文档说明：plt.hist() 创建直方图，bins 参数控制柱数。",
        },
        {
            id: "py-w24-1-q5",
            question: "plt.show() 的作用是什么？",
            options: [
                "保存图片",
                "显示图形并阻塞程序",
                "清除图形",
                "刷新图形",
            ],
            answer: 1,
            rationale: "文档说明：show() 显示所有打开的图形并阻塞直到窗口关闭。",
        },
        {
            id: "py-w24-1-q6",
            question: "如何设置对数刻度？",
            options: [
                "plt.log_scale('x')",
                "plt.xscale('log')",
                "plt.set_log('x')",
                "plt.logx()",
            ],
            answer: 1,
            rationale: "文档说明：plt.xscale('log') 和 plt.yscale('log') 设置对数刻度。",
        },
        {
            id: "py-w24-1-q7",
            question: "'b--' 格式字符串表示什么？",
            options: [
                "蓝色虚线",
                "黑色虚线",
                "蓝色实线",
                "蓝色点线",
            ],
            answer: 0,
            rationale: "文档说明：b 表示蓝色（blue），-- 表示虚线。",
        },
        {
            id: "py-w24-1-q8",
            question: "如何添加图例？",
            options: [
                "plt.show_legend()",
                "plt.legend()",
                "plt.add_legend()",
                "plt.labels()",
            ],
            answer: 1,
            rationale: "文档说明：plt.legend() 显示图例，使用 plot 的 label 参数。",
        },
        {
            id: "py-w24-1-q9",
            question: "如何设置 x 轴标签？",
            options: [
                "plt.set_xlabel('X')",
                "plt.xlabel('X')",
                "plt.x_label('X')",
                "plt.label_x('X')",
            ],
            answer: 1,
            rationale: "文档说明：plt.xlabel() 和 plt.ylabel() 设置轴标签。",
        },
        {
            id: "py-w24-1-q10",
            question: "plt.scatter() 创建什么图表？",
            options: [
                "折线图",
                "散点图",
                "柱状图",
                "饼图",
            ],
            answer: 1,
            rationale: "文档说明：plt.scatter() 创建散点图。",
        },
        {
            id: "py-w24-1-q11",
            question: "如何设置图表标题？",
            options: [
                "plt.set_title('Title')",
                "plt.title('Title')",
                "plt.name('Title')",
                "plt.header('Title')",
            ],
            answer: 1,
            rationale: "文档说明：plt.title() 设置当前图表的标题。",
        },
        {
            id: "py-w24-1-q12",
            question: "dpi 参数控制什么？",
            options: [
                "图像大小",
                "分辨率（每英寸点数）",
                "颜色深度",
                "压缩率",
            ],
            answer: 1,
            rationale: "文档说明：dpi（dots per inch）控制保存图像的分辨率。",
        },
    ],
    "py-w24-2": [
        {
            id: "py-w24-2-q1",
            question: "plt.subplots() 返回什么？",
            options: [
                "只返回 Figure",
                "返回 (Figure, Axes) 元组",
                "只返回 Axes",
                "返回图表数据",
            ],
            answer: 1,
            rationale: "文档说明：plt.subplots() 返回 (fig, ax) 元组。",
        },
        {
            id: "py-w24-2-q2",
            question: "Figure 和 Axes 的关系是什么？",
            options: [
                "Figure 是 Axes 的子类",
                "Figure 是容器，Axes 是绑定区域",
                "它们是同一个对象",
                "Axes 包含 Figure",
            ],
            answer: 1,
            rationale: "文档说明：Figure 是整个图形容器，Axes 是实际的绑定区域。",
        },
        {
            id: "py-w24-2-q3",
            question: "面向对象接口设置标题用什么方法？",
            options: [
                "ax.title('Title')",
                "ax.set_title('Title')",
                "ax.label('Title')",
                "ax.name('Title')",
            ],
            answer: 1,
            rationale: "文档说明：面向对象接口使用 set_ 前缀，如 ax.set_title()。",
        },
        {
            id: "py-w24-2-q4",
            question: "plt.subplots(2, 3) 返回的 ax 是什么形状？",
            options: [
                "一维数组",
                "2×3 二维数组",
                "单个 Axes 对象",
                "字典",
            ],
            answer: 1,
            rationale: "文档说明：subplots(nrows, ncols) 返回对应形状的 Axes 数组。",
        },
        {
            id: "py-w24-2-q5",
            question: "如何应用 'ggplot' 样式？",
            options: [
                "plt.set_style('ggplot')",
                "plt.style.use('ggplot')",
                "plt.ggplot()",
                "plt.theme('ggplot')",
            ],
            answer: 1,
            rationale: "文档说明：plt.style.use() 应用预定义样式表。",
        },
        {
            id: "py-w24-2-q6",
            question: "figsize=(8, 6) 的单位是什么？",
            options: [
                "像素",
                "英寸",
                "厘米",
                "点",
            ],
            answer: 1,
            rationale: "文档说明：figsize 的单位是英寸。",
        },
        {
            id: "py-w24-2-q7",
            question: "layout='constrained' 的作用是什么？",
            options: [
                "固定图形大小",
                "自动调整子图布局避免重叠",
                "锁定坐标轴",
                "限制数据范围",
            ],
            answer: 1,
            rationale: "文档说明：layout 参数自动调整子图间距，避免标签重叠。",
        },
        {
            id: "py-w24-2-q8",
            question: "如何保存 Figure 对象为 PDF？",
            options: [
                "fig.export('file.pdf')",
                "fig.savefig('file.pdf')",
                "fig.save('file.pdf')",
                "fig.write('file.pdf')",
            ],
            answer: 1,
            rationale: "文档说明：fig.savefig() 保存图形，格式由扩展名决定。",
        },
        {
            id: "py-w24-2-q9",
            question: "subplot_mosaic 的优势是什么？",
            options: [
                "更快的绘制速度",
                "支持复杂的不规则子图布局",
                "更少的内存使用",
                "自动生成图例",
            ],
            answer: 1,
            rationale: "文档说明：subplot_mosaic 支持用字符串描述复杂布局。",
        },
        {
            id: "py-w24-2-q10",
            question: "如何在子图数组中访问第一行第二列的 Axes？",
            options: [
                "ax(0, 1)",
                "ax[0, 1]",
                "ax.get(0, 1)",
                "ax[1][2]",
            ],
            answer: 1,
            rationale: "文档说明：使用数组索引 ax[row, col] 访问特定子图。",
        },
        {
            id: "py-w24-2-q11",
            question: "为什么推荐使用面向对象接口？",
            options: [
                "更快",
                "更灵活，适合复杂图表和可复用代码",
                "更少代码",
                "更好的颜色",
            ],
            answer: 1,
            rationale: "文档推荐：面向对象接口更灵活，适合复杂图表和生产代码。",
        },
        {
            id: "py-w24-2-q12",
            question: "ax.legend() 和 plt.legend() 的区别是什么？",
            options: [
                "没有区别",
                "ax.legend() 作用于特定 Axes，plt.legend() 作用于当前 Axes",
                "ax.legend() 更快",
                "plt.legend() 不工作",
            ],
            answer: 1,
            rationale: "文档说明：面向对象方法明确指定目标，pyplot 函数作用于当前对象。",
        },
    ],
    "py-w24-3": [
        {
            id: "py-w24-3-q1",
            question: "Seaborn 与 Matplotlib 的关系是什么？",
            options: [
                "完全独立",
                "Seaborn 基于 Matplotlib 构建",
                "Matplotlib 基于 Seaborn",
                "它们互相竞争",
            ],
            answer: 1,
            rationale: "文档说明：Seaborn 是基于 Matplotlib 的高级统计可视化库。",
        },
        {
            id: "py-w24-3-q2",
            question: "hue 参数的作用是什么？",
            options: [
                "设置透明度",
                "按类别着色并自动创建图例",
                "设置线宽",
                "添加标题",
            ],
            answer: 1,
            rationale: "文档说明：hue 参数根据类别变量为数据点着色。",
        },
        {
            id: "py-w24-3-q3",
            question: "如何设置 Seaborn 主题？",
            options: [
                "sns.style('whitegrid')",
                "sns.set_theme(style='whitegrid')",
                "sns.theme('whitegrid')",
                "sns.use_style('whitegrid')",
            ],
            answer: 1,
            rationale: "文档说明：set_theme() 设置整体风格、调色板等。",
        },
        {
            id: "py-w24-3-q4",
            question: "catplot 用于什么类型的数据？",
            options: [
                "连续数据",
                "分类数据",
                "时间序列",
                "地理数据",
            ],
            answer: 1,
            rationale: "文档说明：catplot() 用于分类数据可视化（箱线图、小提琴图等）。",
        },
        {
            id: "py-w24-3-q5",
            question: "如何在直方图上叠加核密度估计？",
            options: [
                "sns.histplot(data, density=True)",
                "sns.histplot(data, kde=True)",
                "sns.histplot(data, kernel=True)",
                "sns.histplot(data, smooth=True)",
            ],
            answer: 1,
            rationale: "文档说明：kde=True 参数在直方图上叠加核密度估计曲线。",
        },
        {
            id: "py-w24-3-q6",
            question: "如何创建热力图？",
            options: [
                "sns.heat(matrix)",
                "sns.heatmap(matrix)",
                "sns.thermal(matrix)",
                "sns.colormap(matrix)",
            ],
            answer: 1,
            rationale: "文档说明：sns.heatmap() 创建热力图，常用于相关性矩阵。",
        },
        {
            id: "py-w24-3-q7",
            question: "data 参数接受什么类型？",
            options: [
                "只能是列表",
                "Pandas DataFrame",
                "只能是字典",
                "NumPy 数组",
            ],
            answer: 1,
            rationale: "文档说明：Seaborn 与 Pandas 集成，data 参数接受 DataFrame。",
        },
        {
            id: "py-w24-3-q8",
            question: "relplot 和 scatterplot 的区别是什么？",
            options: [
                "没有区别",
                "relplot 支持 FacetGrid 多子图",
                "scatterplot 更快",
                "relplot 只能画线",
            ],
            answer: 1,
            rationale: "文档说明：relplot 返回 FacetGrid，支持 col/row 参数创建多子图。",
        },
        {
            id: "py-w24-3-q9",
            question: "boxplot 显示什么统计信息？",
            options: [
                "均值和标准差",
                "中位数、四分位数和异常值",
                "众数和范围",
                "频率分布",
            ],
            answer: 1,
            rationale: "文档说明：箱线图显示中位数、四分位数范围和异常值。",
        },
        {
            id: "py-w24-3-q10",
            question: "pairplot 的作用是什么？",
            options: [
                "画两个变量的关系",
                "探索所有变量对之间的关系",
                "配对数据",
                "比较两个数据集",
            ],
            answer: 1,
            rationale: "文档说明：pairplot() 绘制所有变量对的散点图矩阵。",
        },
        {
            id: "py-w24-3-q11",
            question: "Seaborn 默认显示什么统计信息？",
            options: [
                "原始数据点",
                "均值和 95% 置信区间",
                "中位数",
                "众数",
            ],
            answer: 1,
            rationale: "文档说明：Seaborn 默认进行统计估计，显示均值和置信区间。",
        },
        {
            id: "py-w24-3-q12",
            question: "如何自定义调色板？",
            options: [
                "sns.colors('palette')",
                "sns.set_palette('palette')",
                "sns.palette = 'name'",
                "sns.use_colors('palette')",
            ],
            answer: 1,
            rationale: "文档说明：set_palette() 设置全局调色板。",
        },
    ],
    "py-w24-4": [
        {
            id: "py-w24-4-q1",
            question: "Jupyter Notebook 的主要用途是什么？",
            options: [
                "编译代码",
                "交互式数据分析和文档",
                "版本控制",
                "部署应用",
            ],
            answer: 1,
            rationale: "文档说明：Jupyter 是交互式计算环境，结合代码、文本和可视化。",
        },
        {
            id: "py-w24-4-q2",
            question: "%matplotlib inline 的作用是什么？",
            options: [
                "导入 Matplotlib",
                "在 Notebook 中内嵌显示图表",
                "保存图表",
                "设置样式",
            ],
            answer: 1,
            rationale: "文档说明：这个魔法命令使图表在输出区域内嵌显示。",
        },
        {
            id: "py-w24-4-q3",
            question: "%time 和 %timeit 的区别是什么？",
            options: [
                "没有区别",
                "%time 单次计时，%timeit 多次取平均",
                "%timeit 更快",
                "%time 只能计时函数",
            ],
            answer: 1,
            rationale: "文档说明：%time 计时一次，%timeit 重复多次取平均更准确。",
        },
        {
            id: "py-w24-4-q4",
            question: "如何将 Cell 切换为 Markdown？",
            options: [
                "按 C 键",
                "按 M 键（命令模式）",
                "按 T 键",
                "按 D 键",
            ],
            answer: 1,
            rationale: "文档说明：在命令模式下按 M 切换为 Markdown，按 Y 切换为代码。",
        },
        {
            id: "py-w24-4-q5",
            question: "如何执行 Cell 并跳到下一个？",
            options: [
                "Enter",
                "Shift + Enter",
                "Ctrl + Enter",
                "Alt + Enter",
            ],
            answer: 1,
            rationale: "文档说明：Shift+Enter 执行并移到下一个 Cell。",
        },
        {
            id: "py-w24-4-q6",
            question: "%% 开头的魔法命令叫什么？",
            options: [
                "行魔法",
                "单元魔法",
                "系统魔法",
                "模块魔法",
            ],
            answer: 1,
            rationale: "文档说明：%% 是单元魔法，作用于整个 Cell；% 是行魔法。",
        },
        {
            id: "py-w24-4-q7",
            question: "如何重置 Notebook 的状态？",
            options: [
                "关闭窗口",
                "Kernel → Restart",
                "清空所有 Cell",
                "刷新页面",
            ],
            answer: 1,
            rationale: "文档说明：重启 Kernel 会清除所有变量和导入，重置状态。",
        },
        {
            id: "py-w24-4-q8",
            question: "Notebook 中变量的作用域是什么？",
            options: [
                "每个 Cell 独立",
                "所有 Cell 共享同一命名空间",
                "按文件分隔",
                "按函数分隔",
            ],
            answer: 1,
            rationale: "文档说明：所有 Cell 共享同一个 Python 命名空间。",
        },
        {
            id: "py-w24-4-q9",
            question: "%%writefile 命令的作用是什么？",
            options: [
                "读取文件",
                "将 Cell 内容写入文件",
                "执行文件",
                "删除文件",
            ],
            answer: 1,
            rationale: "文档说明：%%writefile filename 将 Cell 内容保存到文件。",
        },
        {
            id: "py-w24-4-q10",
            question: "如何在 Markdown 中编写 LaTeX 公式？",
            options: [
                "用 ` 包裹",
                "用 $ 或 $$ 包裹",
                "用 % 包裹",
                "用 @ 包裹",
            ],
            answer: 1,
            rationale: "文档说明：$ 行内公式，$$ 独立公式，使用 LaTeX 语法。",
        },
        {
            id: "py-w24-4-q11",
            question: "%run script.py 的作用是什么？",
            options: [
                "导入模块",
                "运行外部 Python 脚本",
                "保存脚本",
                "编译脚本",
            ],
            answer: 1,
            rationale: "文档说明：%run 在当前命名空间中运行外部脚本。",
        },
        {
            id: "py-w24-4-q12",
            question: "JupyterLab 与 Jupyter Notebook 的关系是什么？",
            options: [
                "完全相同",
                "JupyterLab 是更现代的进阶环境",
                "Notebook 更新",
                "它们不兼容",
            ],
            answer: 1,
            rationale: "文档说明：JupyterLab 是下一代界面，功能更丰富。",
        },
    ],
}
