import type { LessonGuide } from "../types"
import type { QuizQuestion } from "@/lib/types"

export const week3Guides: Record<string, LessonGuide> = {
    "py-w3-1": {
        lessonId: "py-w3-1",
        background: [
            "【if 语句结构】官方文档：'if/elif/else' 是条件执行的核心语句。语法为 if condition: suite，elif 是 'else if' 的缩写，用于避免过度缩进。零个或多个 elif 部分是允许的，else 部分是可选的。",
            "【条件表达式】Python 支持三元运算符（条件表达式）：'x if C else y'。先求值条件 C，若为真则求值并返回 x，否则求值并返回 y。这是一个表达式，可以出现在任何需要值的地方。",
            "【表达式 vs 语句】条件表达式与 if 语句的区别：条件表达式返回一个值，可以嵌入其他表达式中；if 语句执行代码块但不返回值。条件表达式采用惰性求值，只有被选中的分支会被求值。",
            "【替代 switch/case】Python 3.10 之前没有 switch/case 语句，使用 if...elif...elif 序列作为替代。Python 3.10+ 引入了 match/case 模式匹配语句。",
            "【逻辑运算符】条件判断中常用 and、or、not 逻辑运算符。and 和 or 是短路运算符：and 返回第一个假值或最后一个值，or 返回第一个真值或最后一个值。",
        ],
        keyDifficulties: [
            "【缩进敏感性】Python 使用缩进标识代码块，而非花括号。嵌套的复合语句必须使用缩进形式以避免悬空 else 问题。混用 Tab 和空格会导致 IndentationError。",
            "【条件表达式优先级】条件表达式的优先级较低，复杂表达式中可能需要括号。例如 (a if cond else b) + c 需要括号确保正确解析。",
            "【赋值表达式】Python 3.8+ 支持海象运算符 :=，可在条件中同时赋值和测试：if (n := len(a)) > 10:。这在 while 条件中特别有用。",
            "【链式比较】Python 支持链式比较：1 < x < 10 等价于 1 < x and x < 10，但 x 只求值一次。这比手写两个比较更简洁且高效。",
        ],
        handsOnPath: [
            "1. 编写一个程序，使用 if/elif/else 判断输入数字的正负零",
            "2. 使用条件表达式：result = 'even' if n % 2 == 0 else 'odd'",
            "3. 测试链式比较：判断一个数是否在某个范围内 if 0 < x < 100:",
            "4. 使用逻辑运算符组合多个条件：if age >= 18 and has_license:",
            "5. 尝试嵌套条件表达式：'adult' if age >= 18 else ('teen' if age >= 13 else 'child')",
            "6. 测试短路求值：print(1 or print('not printed'))",
        ],
        selfCheck: [
            "if/elif/else 语句中，elif 和 else 部分是否必须？",
            "条件表达式 x if C else y 的求值顺序是什么？",
            "Python 为什么使用缩进而非花括号表示代码块？",
            "and 和 or 运算符的返回值是什么？是布尔值吗？",
            "链式比较 a < b < c 与 a < b and b < c 有什么区别？",
            "海象运算符 := 的作用是什么？在什么场景下有用？",
        ],
        extensions: [
            "学习 Python 3.10+ 的 match/case 模式匹配语句",
            "了解 PEP 572 海象运算符的设计动机",
            "探索 functools.singledispatch 实现类似多态分派",
            "学习断言语句 assert 用于调试时的条件检查",
        ],
        sourceUrls: [
            "https://docs.python.org/3/tutorial/controlflow.html#if-statements",
            "https://docs.python.org/3/reference/expressions.html#conditional-expressions",
            "https://docs.python.org/3/reference/compound_stmts.html",
        ],
    },
    "py-w3-2": {
        lessonId: "py-w3-2",
        background: [
            "【for 语句语义】官方文档：'The for statement iterates over the items of any sequence in the order that they appear in the sequence.'。Python 的 for 是迭代器循环，不是计数循环。",
            "【range 类型】range 表示'immutable sequence of numbers'，常用于循环固定次数。range(stop) 或 range(start, stop, step)。只存储 start/stop/step 三个值，内存效率极高。",
            "【enumerate 函数】使用 enumerate() 同时获取索引和值：'for i, v in enumerate(list):'。比手动维护索引变量更简洁、更 Pythonic。",
            "【zip 函数】zip() 用于同时遍历多个序列：'for q, a in zip(questions, answers):'。返回一个迭代器，元素数量由最短序列决定。",
            "【修改集合的安全方式】文档警告：修改正在迭代的集合时，应遍历副本或创建新集合。直接修改可能导致意外行为或 RuntimeError。",
        ],
        keyDifficulties: [
            "【循环变量作用域】for 循环结束后，循环变量仍然存在于当前作用域，值为最后一次迭代的值。如果序列为空，变量不会被赋值。",
            "【range 边界理解】range(n) 生成 0 到 n-1，不包含 n。range(1, 11) 生成 1 到 10。这与数学上的半开区间 [start, stop) 一致。",
            "【循环中的赋值无效】在循环体内给循环变量赋值不会影响迭代：'for i in range(10): i = 5' 下次迭代 i 仍会被 range 覆盖。",
            "【range 的惰性求值】range 是惰性的，不会一次性生成所有数字。range(10**18) 是合法的，不会占用大量内存。",
        ],
        handsOnPath: [
            "1. 使用 for 循环遍历列表：for item in ['a', 'b', 'c']: print(item)",
            "2. 使用 range 循环固定次数：for i in range(5): print(i)",
            "3. 使用 enumerate 获取索引：for idx, val in enumerate(['x', 'y', 'z']): print(idx, val)",
            "4. 使用 zip 同时遍历两个列表：for a, b in zip([1,2,3], ['x','y','z']): print(a, b)",
            "5. 测试负步长：for i in range(10, 0, -1): print(i)",
            "6. 验证 range 的内存效率：import sys; print(sys.getsizeof(range(10**9)))",
        ],
        selfCheck: [
            "Python 的 for 循环与 C/Java 的 for 循环有什么本质区别？",
            "range(5) 和 range(1, 6) 分别生成什么？",
            "enumerate() 返回什么类型的对象？",
            "如何在遍历列表时安全地删除元素？",
            "range 对象为什么内存效率高？",
            "zip() 对不等长序列的行为是什么？",
        ],
        extensions: [
            "学习 itertools.zip_longest 处理不等长序列",
            "了解 reversed() 和 sorted() 在循环中的用法",
            "探索迭代器协议 __iter__ 和 __next__",
            "学习生成器表达式 (x for x in range(10))",
        ],
        sourceUrls: [
            "https://docs.python.org/3/tutorial/controlflow.html#for-statements",
            "https://docs.python.org/3/library/stdtypes.html#range",
            "https://docs.python.org/3/tutorial/datastructures.html#looping-techniques",
        ],
    },
    "py-w3-3": {
        lessonId: "py-w3-3",
        background: [
            "【while 语句】官方文档：'The while statement is used for repeated execution as long as an expression is true.'。while 条件为真时持续执行循环体。",
            "【break 语句】break 立即退出最内层的 for 或 while 循环。文档示例：在找到因数时用 break 跳出内层循环。",
            "【continue 语句】continue 跳过当前迭代的剩余代码，继续下一次迭代。常用于过滤：遇到不需要处理的元素时跳过。",
            "【循环的 else 子句】Python 独特特性：循环可以有 else 子句，'executes only if the loop completes normally without hitting a break'。常用于搜索场景：找到则 break，未找到则执行 else。",
            "【pass 语句】pass 是空操作，用于语法需要语句但无需执行代码时。常见用途：占位符、空类/函数定义。也可使用省略号 ... 作为替代。",
        ],
        keyDifficulties: [
            "【else 子句语义】循环的 else 在循环正常结束（未触发 break）时执行，在触发 break、return 或异常时不执行。名称容易误导，实际含义是 'no break'。",
            "【无限循环风险】while True: 创建无限循环，必须有 break 退出条件，否则程序永远不会终止。忙等待循环如 while True: pass 会占用 100% CPU。",
            "【continue 与嵌套循环】continue 只跳过当前迭代，不会跳出循环。在嵌套循环中，continue 只影响最内层循环。",
            "【break 与嵌套循环】break 只退出最内层循环。如需退出多层循环，可使用标志变量、函数返回或异常。",
        ],
        handsOnPath: [
            "1. 编写简单 while 循环：while n > 0: print(n); n -= 1",
            "2. 使用 break 提前退出：while True: x = input(); if x == 'quit': break",
            "3. 使用 continue 跳过偶数：for i in range(10): if i % 2 == 0: continue; print(i)",
            "4. 测试循环 else 子句：for n in range(2, 10): ... else: print('Loop completed')",
            "5. 使用 pass 创建占位函数：def todo(): pass",
            "6. 编写素数检测，使用 else 子句标记完整循环",
        ],
        selfCheck: [
            "while 和 for 循环什么时候应该选择哪个？",
            "break 和 continue 的区别是什么？",
            "循环的 else 子句在什么情况下执行？",
            "如何安全地退出无限循环？",
            "pass 语句的典型使用场景有哪些？",
            "如何从嵌套循环中完全跳出？",
        ],
        extensions: [
            "学习 itertools.takewhile 和 dropwhile",
            "了解 walrus 运算符在 while 条件中的应用",
            "探索递归作为循环的替代方案",
            "学习 Python 的尾递归优化限制",
        ],
        sourceUrls: [
            "https://docs.python.org/3/reference/compound_stmts.html#the-while-statement",
            "https://docs.python.org/3/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops",
            "https://docs.python.org/3/tutorial/controlflow.html#pass-statements",
        ],
    },
    "py-w3-4": {
        lessonId: "py-w3-4",
        background: [
            "【input 函数】官方文档：input() 'reads a line from input, converts it to a string (stripping a trailing newline), and returns that'。可选参数 prompt 在读取前输出提示。遇到 EOF 会抛出 EOFError。",
            "【print 函数】print(*objects, sep=' ', end='\\n', file=None, flush=False)。将对象转换为字符串并输出，sep 指定分隔符，end 指定结尾字符，file 指定输出目标，flush 强制刷新缓冲区。",
            "【f-string 格式化】Python 3.6+ 推荐使用 f-string：f'{expr}'。支持格式说明符如 {x:.2f}，支持转换标志 !r（repr）、!s（str）、!a（ascii），支持自文档化 {x=}。",
            "【str.format 方法】旧式格式化方法：'{} and {}'.format('spam', 'eggs')。支持位置参数 {0}、关键字参数 {name}、以及格式说明符。",
            "【str 与 repr】str() 生成人类可读的字符串，repr() 生成解释器可读的表示。对于字符串，str('hello') 是 'hello'，repr('hello') 是 \"'hello'\"。",
        ],
        keyDifficulties: [
            "【input 返回类型】input() 总是返回字符串，即使用户输入数字。需要使用 int()、float() 等进行类型转换：age = int(input('Age: '))。",
            "【print 缓冲行为】print() 默认行缓冲（tty）或块缓冲（文件）。实时输出需要 flush=True 或使用 -u 启动参数禁用缓冲。",
            "【格式说明符语法】f'{x:10.2f}' 表示总宽度 10、小数点后 2 位的浮点数。{x:>10} 右对齐、{x:<10} 左对齐、{x:^10} 居中对齐。",
            "【旧式 % 格式化】遗留代码中常见 'name: %s, age: %d' % (name, age)。不推荐使用，但阅读旧代码时需要理解。",
        ],
        handsOnPath: [
            "1. 使用 input 获取用户输入：name = input('Your name: ')",
            "2. 类型转换输入：age = int(input('Your age: '))",
            "3. 使用 print 的参数：print('a', 'b', 'c', sep='-', end='!')",
            "4. 使用 f-string 格式化：print(f'Name: {name}, Age: {age}')",
            "5. 测试格式说明符：print(f'{3.14159:.2f}', f'{42:05d}')",
            "6. 使用 repr 调试：print(f'{s!r}') 显示字符串的引号",
        ],
        selfCheck: [
            "input() 函数返回什么类型？",
            "如何让 print 不换行？",
            "f-string 中 {x:.2f} 的含义是什么？",
            "str() 和 repr() 的区别是什么？",
            "如何将多个值用逗号分隔输出？",
            "print 的 flush 参数有什么作用？",
        ],
        extensions: [
            "学习 sys.stdin 和 sys.stdout 进行底层 I/O",
            "了解 string 模块的 Template 类",
            "探索 logging 模块替代 print 进行日志输出",
            "学习 argparse 解析命令行参数",
        ],
        sourceUrls: [
            "https://docs.python.org/3/tutorial/inputoutput.html",
            "https://docs.python.org/3/library/functions.html#print",
            "https://docs.python.org/3/library/functions.html#input",
        ],
    },
}

export const week3Quizzes: Record<string, QuizQuestion[]> = {
    "py-w3-1": [
        {
            id: "py-w3-1-q1",
            question: "Python 中 elif 是什么的缩写？",
            options: [
                "else if",
                "elif statement",
                "elseif",
                "else-if-then",
            ],
            answer: 0,
            rationale: "官方文档说明：'elif' is short for 'else if' and is useful to avoid excessive indentation。",
        },
        {
            id: "py-w3-1-q2",
            question: "条件表达式 x if C else y 的求值顺序是什么？",
            options: [
                "先求值 x，再求值 C，最后求值 y",
                "先求值 C，若为真则求值 x，否则求值 y",
                "同时求值 x、y 和 C",
                "先求值 y，再求值 C，最后求值 x",
            ],
            answer: 1,
            rationale: "文档说明：The expression x if C else y first evaluates C; if true, x is evaluated; otherwise, y is evaluated.",
        },
        {
            id: "py-w3-1-q3",
            question: "关于 if 语句的 else 部分，以下哪项是正确的？",
            options: [
                "else 部分是必须的",
                "else 部分是可选的",
                "每个 elif 后必须有 else",
                "else 必须在 elif 之前",
            ],
            answer: 1,
            rationale: "文档明确指出：The else part is optional。",
        },
        {
            id: "py-w3-1-q4",
            question: "Python 使用什么来标识代码块？",
            options: [
                "花括号 {}",
                "begin/end 关键字",
                "缩进",
                "方括号 []",
            ],
            answer: 2,
            rationale: "Python 使用缩进表示代码块，这是其独特的语法特征。",
        },
        {
            id: "py-w3-1-q5",
            question: "5 or 3 的返回值是什么？",
            options: [
                "True",
                "5",
                "3",
                "8",
            ],
            answer: 1,
            rationale: "or 运算符返回第一个真值或最后一个值。5 为真，所以返回 5，而非布尔值 True。",
        },
        {
            id: "py-w3-1-q6",
            question: "链式比较 1 < x < 10 等价于什么？",
            options: [
                "1 < x or x < 10",
                "1 < x and x < 10",
                "(1 < x) < 10",
                "1 < (x < 10)",
            ],
            answer: 1,
            rationale: "文档说明：链式比较 x < y <= z 等价于 x < y and y <= z，但 y 只求值一次。",
        },
        {
            id: "py-w3-1-q7",
            question: "Python 3.10 之前，如何实现 switch/case 的功能？",
            options: [
                "使用 switch 语句",
                "使用 if...elif...elif 序列",
                "使用 case 表达式",
                "不支持此功能",
            ],
            answer: 1,
            rationale: "文档说明：An if...elif...elif sequence is a substitute for the switch or case statements found in other languages。",
        },
        {
            id: "py-w3-1-q8",
            question: "not a == b 被解释为什么？",
            options: [
                "(not a) == b",
                "not (a == b)",
                "语法错误",
                "a != b",
            ],
            answer: 1,
            rationale: "not 的优先级低于比较运算符，所以 not a == b 被解释为 not (a == b)。",
        },
        {
            id: "py-w3-1-q9",
            question: "条件表达式（三元运算符）可以用在什么地方？",
            options: [
                "只能用在 if 语句中",
                "只能用在赋值语句中",
                "任何需要表达式的地方",
                "只能用在函数参数中",
            ],
            answer: 2,
            rationale: "条件表达式是一个表达式，可以出现在任何需要值的地方，包括嵌入其他表达式中。",
        },
        {
            id: "py-w3-1-q10",
            question: "0 and 5 的返回值是什么？",
            options: [
                "False",
                "0",
                "5",
                "True",
            ],
            answer: 1,
            rationale: "and 运算符返回第一个假值或最后一个值。0 为假，所以直接返回 0。",
        },
        {
            id: "py-w3-1-q11",
            question: "以下哪种情况会导致 IndentationError？",
            options: [
                "使用 4 个空格缩进",
                "使用 Tab 缩进",
                "混用 Tab 和空格缩进",
                "使用 2 个空格缩进",
            ],
            answer: 2,
            rationale: "Python 3 不允许混用 Tab 和空格进行缩进，会导致 IndentationError。",
        },
        {
            id: "py-w3-1-q12",
            question: "海象运算符 := 的作用是什么？",
            options: [
                "比较两个值是否相等",
                "在表达式中同时赋值和返回值",
                "深拷贝对象",
                "创建常量",
            ],
            answer: 1,
            rationale: "Python 3.8+ 的海象运算符 := 允许在表达式中赋值并返回该值，如 if (n := len(a)) > 10。",
        },
    ],
    "py-w3-2": [
        {
            id: "py-w3-2-q1",
            question: "Python 的 for 语句遍历什么？",
            options: [
                "数字范围",
                "序列中的元素",
                "数组索引",
                "布尔条件",
            ],
            answer: 1,
            rationale: "官方文档：'The for statement iterates over the items of any sequence in the order that they appear in the sequence.'",
        },
        {
            id: "py-w3-2-q2",
            question: "range(5) 生成什么？",
            options: [
                "1, 2, 3, 4, 5",
                "0, 1, 2, 3, 4",
                "0, 1, 2, 3, 4, 5",
                "1, 2, 3, 4",
            ],
            answer: 1,
            rationale: "文档示例：list(range(5)) 生成 [0, 1, 2, 3, 4]，不包含 5。",
        },
        {
            id: "py-w3-2-q3",
            question: "enumerate() 函数返回什么？",
            options: [
                "只返回索引",
                "只返回值",
                "返回 (索引, 值) 的元组",
                "返回字典",
            ],
            answer: 2,
            rationale: "文档示例：for i, v in enumerate(['tic', 'tac', 'toe']) 返回 (0, 'tic'), (1, 'tac'), (2, 'toe')。",
        },
        {
            id: "py-w3-2-q4",
            question: "在遍历列表时想要删除元素，应该怎么做？",
            options: [
                "直接在循环中删除",
                "遍历列表的副本或创建新列表",
                "使用 del 语句",
                "使用 remove 方法",
            ],
            answer: 1,
            rationale: "文档警告：Code that modifies a collection while iterating over that same collection can be tricky to get right. Instead, it is usually more straight-forward to loop over a copy of the collection or to create a new collection。",
        },
        {
            id: "py-w3-2-q5",
            question: "range 对象为什么内存效率高？",
            options: [
                "使用压缩算法",
                "只存储 start、stop、step 三个值",
                "使用链表结构",
                "存储在硬盘上",
            ],
            answer: 1,
            rationale: "文档说明：range objects always take the same (small) amount of memory, no matter the size of the range they represent，因为只存储 start, stop, step。",
        },
        {
            id: "py-w3-2-q6",
            question: "zip() 对不等长序列的行为是什么？",
            options: [
                "抛出异常",
                "用 None 填充短序列",
                "以最短序列长度为准",
                "以最长序列长度为准",
            ],
            answer: 2,
            rationale: "zip() 以最短序列长度为准，多余的元素被忽略。使用 itertools.zip_longest 可以填充短序列。",
        },
        {
            id: "py-w3-2-q7",
            question: "for 循环结束后，循环变量的值是什么？",
            options: [
                "被删除，不存在",
                "最后一次迭代的值",
                "undefined",
                "0",
            ],
            answer: 1,
            rationale: "文档说明：Names in the target list are not deleted when the loop is finished, but if the sequence is empty, they will not have been assigned to at all。",
        },
        {
            id: "py-w3-2-q8",
            question: "range(0, 10, 2) 生成什么？",
            options: [
                "0, 2, 4, 6, 8, 10",
                "0, 2, 4, 6, 8",
                "2, 4, 6, 8, 10",
                "0, 1, 2, 3, 4",
            ],
            answer: 1,
            rationale: "文档示例：list(range(0, 10, 2)) 生成 [0, 2, 4, 6, 8]，步长为 2，不包含 10。",
        },
        {
            id: "py-w3-2-q9",
            question: "10 in range(0, 20, 2) 的时间复杂度是？",
            options: [
                "O(n)",
                "O(log n)",
                "O(1)",
                "O(n²)",
            ],
            answer: 2,
            rationale: "文档说明：Testing range objects for equality with == and != compares them as sequences. In Python 3, containment tests are O(1)。",
        },
        {
            id: "py-w3-2-q10",
            question: "reversed(range(1, 10, 2)) 生成什么顺序？",
            options: [
                "1, 3, 5, 7, 9",
                "9, 7, 5, 3, 1",
                "10, 8, 6, 4, 2",
                "2, 4, 6, 8, 10",
            ],
            answer: 1,
            rationale: "文档示例：for i in reversed(range(1, 10, 2)) 按 9, 7, 5, 3, 1 的顺序输出。",
        },
        {
            id: "py-w3-2-q11",
            question: "在 for 循环体内给循环变量赋值会怎样？",
            options: [
                "改变循环行为",
                "跳过下一次迭代",
                "下次迭代时被覆盖，无效",
                "抛出异常",
            ],
            answer: 2,
            rationale: "文档说明：Assignment to loop variable during iteration has no effect，因为下次迭代时变量会被 for 循环重新赋值。",
        },
        {
            id: "py-w3-2-q12",
            question: "如何同时遍历字典的键和值？",
            options: [
                "for k, v in dict",
                "for k, v in dict.items()",
                "for k, v in dict.values()",
                "for k, v in dict.keys()",
            ],
            answer: 1,
            rationale: "文档示例：When looping through dictionaries, the key and corresponding value can be retrieved at the same time using the items() method。",
        },
    ],
    "py-w3-3": [
        {
            id: "py-w3-3-q1",
            question: "while 语句的执行条件是什么？",
            options: [
                "条件为假时执行",
                "条件为真时执行",
                "固定执行次数",
                "始终执行一次",
            ],
            answer: 1,
            rationale: "官方文档：'The while statement is used for repeated execution as long as an expression is true.'",
        },
        {
            id: "py-w3-3-q2",
            question: "break 语句的作用是什么？",
            options: [
                "跳过当前迭代",
                "退出最内层循环",
                "退出所有循环",
                "退出程序",
            ],
            answer: 1,
            rationale: "文档说明：The break statement breaks out of the innermost enclosing for or while loop。",
        },
        {
            id: "py-w3-3-q3",
            question: "循环的 else 子句在什么情况下执行？",
            options: [
                "每次迭代后执行",
                "循环条件为假时执行",
                "循环正常完成（未触发 break）时执行",
                "触发 break 时执行",
            ],
            answer: 2,
            rationale: "文档说明：Loop statements may have an else clause; it is executed when the loop terminates through exhaustion of the iterable or when the condition becomes false, but not when the loop is terminated by a break statement。",
        },
        {
            id: "py-w3-3-q4",
            question: "continue 语句的作用是什么？",
            options: [
                "退出循环",
                "跳过当前迭代的剩余代码，继续下一次迭代",
                "重新开始循环",
                "暂停循环",
            ],
            answer: 1,
            rationale: "文档说明：The continue statement continues with the next iteration of the loop。",
        },
        {
            id: "py-w3-3-q5",
            question: "pass 语句的作用是什么？",
            options: [
                "跳过循环",
                "什么都不做，用作占位符",
                "传递参数",
                "返回 None",
            ],
            answer: 1,
            rationale: "文档说明：The pass statement does nothing. It can be used when a statement is required syntactically but the program requires no action。",
        },
        {
            id: "py-w3-3-q6",
            question: "以下哪个可以替代 pass 作为占位符？",
            options: [
                "None",
                "return",
                "... (省略号)",
                "skip",
            ],
            answer: 2,
            rationale: "文档提到：Another place pass can be used is as a place-holder...This is commonly done using ellipsis literal (...)。",
        },
        {
            id: "py-w3-3-q7",
            question: "在 while True: 循环中，如何安全退出？",
            options: [
                "设置条件变量",
                "使用 break 语句",
                "使用 return 语句",
                "以上都可以",
            ],
            answer: 3,
            rationale: "无限循环可以通过 break 退出，在函数中可用 return，也可以设置标志变量修改条件。",
        },
        {
            id: "py-w3-3-q8",
            question: "break 退出循环后，else 子句会执行吗？",
            options: [
                "会执行",
                "不会执行",
                "取决于条件",
                "有时会有时不会",
            ],
            answer: 1,
            rationale: "文档明确：else clause is not executed if the loop is terminated by a break statement。",
        },
        {
            id: "py-w3-3-q9",
            question: "以下代码输出什么？for i in range(3): pass else: print('done')",
            options: [
                "什么都不输出",
                "done",
                "0 1 2 done",
                "抛出错误",
            ],
            answer: 1,
            rationale: "循环正常完成（没有 break），else 子句会执行，输出 'done'。",
        },
        {
            id: "py-w3-3-q10",
            question: "在嵌套循环中，break 退出哪个循环？",
            options: [
                "所有循环",
                "最外层循环",
                "最内层循环",
                "指定的循环",
            ],
            answer: 2,
            rationale: "break 只退出最内层（innermost）的 for 或 while 循环。",
        },
        {
            id: "py-w3-3-q11",
            question: "while True: pass 的问题是什么？",
            options: [
                "语法错误",
                "会占用 100% CPU（忙等待）",
                "会自动退出",
                "没有问题",
            ],
            answer: 1,
            rationale: "文档提到这是 busy-wait 忙等待循环，会持续占用 CPU 资源。",
        },
        {
            id: "py-w3-3-q12",
            question: "素数检测中使用循环 else 的典型模式是什么？",
            options: [
                "找到因数时执行 else",
                "找到因数时 break，未找到时执行 else",
                "每次迭代执行 else",
                "else 中检查是否为素数",
            ],
            answer: 1,
            rationale: "文档示例：在内层循环中找到因数时 break，如果完成所有迭代未找到因数，else 子句打印该数是素数。",
        },
    ],
    "py-w3-4": [
        {
            id: "py-w3-4-q1",
            question: "input() 函数返回什么类型？",
            options: [
                "根据输入自动推断",
                "int",
                "str",
                "bytes",
            ],
            answer: 2,
            rationale: "官方文档：input() reads a line from input, converts it to a string (stripping a trailing newline), and returns that。",
        },
        {
            id: "py-w3-4-q2",
            question: "print() 函数默认的 end 参数值是什么？",
            options: [
                "空字符串 ''",
                "空格 ' '",
                "换行符 '\\n'",
                "None",
            ],
            answer: 2,
            rationale: "文档说明：print(*objects, sep=' ', end='\\n', file=None, flush=False)，end 默认为换行符。",
        },
        {
            id: "py-w3-4-q3",
            question: "f'{x:.2f}' 的含义是什么？",
            options: [
                "将 x 转换为二进制",
                "将 x 格式化为保留 2 位小数的浮点数",
                "将 x 重复 2 次",
                "将 x 转换为十六进制",
            ],
            answer: 1,
            rationale: "文档示例：f'The value of pi is approximately {math.pi:.3f}.' 输出 'The value of pi is approximately 3.142.'。",
        },
        {
            id: "py-w3-4-q4",
            question: "如何让 print 不换行？",
            options: [
                "print(x, nonewline=True)",
                "print(x, end='')",
                "print(x, newline=False)",
                "println(x)",
            ],
            answer: 1,
            rationale: "文档说明：使用 end='' 可以让 print 不输出换行符。",
        },
        {
            id: "py-w3-4-q5",
            question: "str() 和 repr() 的区别是什么？",
            options: [
                "str() 用于数字，repr() 用于字符串",
                "str() 生成人类可读表示，repr() 生成解释器可读表示",
                "没有区别",
                "str() 更慢，repr() 更快",
            ],
            answer: 1,
            rationale: "文档说明：str() returns representations of values which are fairly human-readable, while repr() generates representations which can be read by the interpreter。",
        },
        {
            id: "py-w3-4-q6",
            question: "print('a', 'b', 'c', sep='-') 输出什么？",
            options: [
                "a b c",
                "a-b-c",
                "abc",
                "-a-b-c-",
            ],
            answer: 1,
            rationale: "sep 参数指定多个对象之间的分隔符，默认是空格。",
        },
        {
            id: "py-w3-4-q7",
            question: "f-string 中 {x!r} 的作用是什么？",
            options: [
                "将 x 转为整数",
                "对 x 应用 repr()",
                "将 x 反转",
                "将 x 转为原始字符串",
            ],
            answer: 1,
            rationale: "文档说明 f-string 支持转换标志：!r 应用 repr()，!s 应用 str()，!a 应用 ascii()。",
        },
        {
            id: "py-w3-4-q8",
            question: "input() 遇到 EOF 时会怎样？",
            options: [
                "返回空字符串",
                "返回 None",
                "抛出 EOFError",
                "阻塞等待输入",
            ],
            answer: 2,
            rationale: "文档说明：If the prompt argument is present, it is written to standard output without a trailing newline. The function then reads a line from input...Raises an auditing event builtins.input with argument prompt before reading input. If EOF is read, EOFError is raised。",
        },
        {
            id: "py-w3-4-q9",
            question: "Python 3.6+ 推荐使用哪种字符串格式化方式？",
            options: [
                "% 操作符",
                "str.format()",
                "f-string",
                "template strings",
            ],
            answer: 2,
            rationale: "文档说明 f-string（格式化字符串字面量）是 Python 3.6+ 推荐的格式化方式，语法简洁直观。",
        },
        {
            id: "py-w3-4-q10",
            question: "print() 的 flush 参数有什么作用？",
            options: [
                "清空输出内容",
                "强制刷新输出缓冲区",
                "关闭文件",
                "删除换行符",
            ],
            answer: 1,
            rationale: "文档说明：Whether output is buffered is usually determined by file, but if the flush keyword argument is true, the stream is forcibly flushed。",
        },
        {
            id: "py-w3-4-q11",
            question: "f'{x=}' 的作用是什么（Python 3.8+）？",
            options: [
                "检查 x 是否存在",
                "自文档化表达式，输出 'x=值'",
                "给 x 赋默认值",
                "语法错误",
            ],
            answer: 1,
            rationale: "文档说明 f-string 支持 = 说明符用于自文档化表达式，如 f'{x=}' 会输出 'x=42'。",
        },
        {
            id: "py-w3-4-q12",
            question: "如何将输入转换为整数？",
            options: [
                "input(int)",
                "int(input())",
                "input().int()",
                "input(type=int)",
            ],
            answer: 1,
            rationale: "input() 返回字符串，需要使用 int() 函数进行类型转换：age = int(input('Age: '))。",
        },
    ],
}
