import type { LessonGuide } from "../types"
import type { QuizQuestion } from "@/lib/types"

export const week1Guides: Record<string, LessonGuide> = {
    "py-w1-1": {
        lessonId: "py-w1-1",
        background: [
            "【版本选择】Python 官网显示当前最新稳定版为 Python 3.14.2（2025年12月发布），共有 7 个活跃维护版本，其中 3.9 已于 2025 年 10 月结束支持。建议选择 3.11+ 以获得更好的性能和新特性。",
            "【多平台支持】Python 官方提供 Windows（独立安装器和安装管理器）、macOS（11 及以上）、Linux/Unix（源码编译）、Android 等多平台安装包，'the same source code archive can also be used to build the Windows and Mac versions'。",
            "【安装指南结构】官方安装文档包含：命令行和环境、Unix 平台、Windows 平台、macOS 平台、移动平台（Android/iOS）、编辑器和 IDE 等章节，覆盖从安装到配置的完整流程。",
            "【VS Code Python 扩展】Microsoft 官方扩展提供 'rich support for the Python language (for all actively supported Python versions)'，安装后自动附带 Pylance（语言支持）、Python Debugger（调试）、Python Environments（环境管理）三个组件。",
            "【核心功能】VS Code Python 扩展支持：IntelliSense 自动补全和语法检查、调试（包括多线程）、代码格式化（black/autopep/yapf）、单元测试（unittest/pytest）、Jupyter Notebook 编辑、虚拟环境自动激活（virtualenv/venv/pipenv/conda/pyenv）。",
        ],
        keyDifficulties: [
            "【环境变量配置】Windows 用户需注意 PATH 环境变量的配置，确保命令行可以直接运行 python 和 pip 命令。macOS 和 Linux 通常需要使用 python3 而非 python。",
            "【版本共存问题】系统可能预装旧版 Python，安装新版后需确认默认版本。Windows 可使用 py 启动器选择版本，Unix 系统需检查 python3 指向的实际版本。",
            "【IDE 选择权衡】VS Code 轻量灵活但需要手动配置扩展；PyCharm 功能全面但资源占用较大。初学者推荐 VS Code + Python 扩展，获得良好的开发体验同时保持简单。",
            "【扩展配置顺序】VS Code Python 扩展安装后，需要使用 'Python: Select Interpreter' 命令选择正确的 Python 解释器，这是最常见的配置问题来源。",
        ],
        handsOnPath: [
            "1. 访问 python.org/downloads 下载适合你操作系统的最新稳定版安装包",
            "2. 运行安装程序，Windows 用户务必勾选 'Add Python to PATH' 选项",
            "3. 打开终端/命令行，运行 python --version 或 python3 --version 验证安装",
            "4. 安装 VS Code，然后在扩展市场搜索 'Python' 安装 Microsoft 官方扩展",
            "5. 打开 VS Code，使用 Ctrl+Shift+P（Mac: Cmd+Shift+P）打开命令面板",
            "6. 输入 'Python: Select Interpreter' 选择刚安装的 Python 版本",
            "7. 创建测试文件 test.py，输入 print('Hello') 并使用 F5 或右键运行验证配置",
        ],
        selfCheck: [
            "在命令行输入 python --version 能否正确显示版本号？",
            "VS Code 右下角状态栏是否显示正确的 Python 版本？",
            "你知道 Python 3.9 和 3.14 的主要区别在哪里吗？",
            "能否说出 VS Code Python 扩展自动安装的三个组件？",
            "为什么建议初学者选择 VS Code 而非 PyCharm？",
            "Windows 下的 py 启动器有什么作用？",
        ],
        extensions: [
            "了解 pyenv 工具用于管理多个 Python 版本共存",
            "探索 VS Code 的其他 Python 相关扩展如 Python Indent、autoDocstring",
            "学习 Windows 上移除 MAX_PATH 限制的方法",
            "了解从源码编译 Python 的流程（适合需要定制的场景）",
        ],
        sourceUrls: [
            "https://www.python.org/downloads/",
            "https://docs.python.org/3/using/index.html",
            "https://marketplace.visualstudio.com/items?itemName=ms-python.python",
        ],
    },
    "py-w1-2": {
        lessonId: "py-w1-2",
        background: [
            "【教程定位】Python 官方教程面向'已有编程基础的程序员'，非零基础初学者教程。教程强调'非全面性覆盖，而是介绍最值得关注的特性'，学完后能够'阅读和编写Python模块与程序'。",
            "【解释器模式】Python 解释器支持三种执行方式：交互模式（直接启动，使用 >>> 提示符）、单行命令（python -c command）、脚本文件（python script.py 或 python -m module）。",
            "【提示符含义】交互模式中 '>>>' 是主提示符（输入新命令），'...' 是续行提示符（多行代码如函数定义、条件语句）。这是 Python 区别于其他语言 REPL 的特征之一。",
            "【源码编码】Python 源文件默认采用 UTF-8 编码。如需使用其他编码，需在文件第一行（或 shebang 后的第二行）添加 '# -*- coding: cp1252 -*-' 格式的声明。",
            "【教程结构】官方教程共 16 章，从解释器使用、基础语法、控制流、数据结构，到模块、输入输出、异常处理、类、标准库，最后是虚拟环境和进阶主题，提供完整的学习路径。",
        ],
        keyDifficulties: [
            "【缩进语法】Python 使用缩进表示代码块，而非花括号。官方推荐使用 4 个空格，混用 Tab 和空格会导致错误。这是从其他语言转来的开发者最常遇到的问题。",
            "【交互模式调试】使用 python -i script.py 可以在脚本执行后进入交互模式，便于检查变量状态和调试。这是官方推荐的调试技巧。",
            "【sys.argv 理解】脚本参数通过 sys.argv 列表访问，sys.argv[0] 的值取决于调用方式：脚本文件名、'-'（标准输入）、'-c'（-c 选项）或模块全名（-m 选项）。",
            "【退出方式差异】Unix 系统使用 Control-D 退出解释器，Windows 使用 Control-Z，也可以输入 quit() 命令退出。这是平台差异需要注意的地方。",
        ],
        handsOnPath: [
            "1. 打开终端，输入 python3 或 python 进入交互模式，观察 >>> 提示符",
            "2. 在交互模式输入 print('Hello, World!') 并按回车，观察输出",
            "3. 尝试多行代码：输入 if True: 后按回车，观察 ... 提示符，然后输入缩进的 print('Yes')",
            "4. 创建 hello.py 文件，写入 print('Hello from script!')",
            "5. 在终端运行 python hello.py 或 python3 hello.py 执行脚本",
            "6. 修改脚本添加 import sys; print(sys.argv)，然后运行 python hello.py arg1 arg2 观察输出",
            "7. 使用 python -i hello.py 运行，脚本结束后在交互模式检查变量",
        ],
        selfCheck: [
            ">>> 和 ... 两个提示符分别表示什么？",
            "如何在不创建文件的情况下执行一行 Python 代码？",
            "sys.argv[0] 在不同调用方式下分别是什么？",
            "Python 源文件的默认编码是什么？如何指定其他编码？",
            "如何在脚本执行完毕后自动进入交互模式？",
            "为什么 Python 使用缩进而非花括号表示代码块？",
            "Windows 和 Unix 退出交互模式的快捷键有何不同？",
        ],
        extensions: [
            "学习 __name__ == '__main__' 模式，理解模块导入和直接执行的区别",
            "探索 IPython/Jupyter 提供的增强交互环境",
            "了解 Python 教程中 match 语句（3.10+ 新特性）的用法",
            "阅读官方教程第 4 章了解更多控制流工具",
        ],
        sourceUrls: [
            "https://docs.python.org/3/tutorial/index.html",
            "https://docs.python.org/3/tutorial/interpreter.html",
            "https://roadmap.sh/python",
        ],
    },
    "py-w1-3": {
        lessonId: "py-w1-3",
        background: [
            "【虚拟环境必要性】官方文档指出：'不同应用可能需要同一库的不同版本，例如应用 A 需要版本 1.0，应用 B 需要版本 2.0，安装任一版本都会导致另一个应用无法运行'。虚拟环境通过创建隔离的目录树解决这个问题。",
            "【PyPI 定位】'The Python Package Index (PyPI) is a repository of software for the Python programming language'——Python 官方包索引，目前包含超过 720,000 个项目。开发者可以从这里发现、安装包，也可以发布自己的包。",
            "【pip 核心功能】pip 是 Python 的包安装器，支持从 PyPI 安装包。主要命令包括：install（安装）、uninstall（卸载）、list（列出已安装）、show（显示详情）、freeze（导出需求格式）。",
            "【requirements.txt 作用】pip 用户指南强调：'Requirements files enable reproducible installations by listing packages in a single file'。使用 pip freeze > requirements.txt 导出，pip install -r requirements.txt 安装，实现依赖的版本控制和分发。",
            "【约束文件概念】Constraints files 是 pip 的高级特性，'limit package versions without triggering installation'。与 requirements 不同，约束文件只限制版本而不触发安装，适合管理多个依赖共用同一补丁版本的场景。",
        ],
        keyDifficulties: [
            "【全局 vs 虚拟环境】初学者常直接使用 pip install 安装到全局环境，这会导致不同项目间的依赖冲突。官方推荐每个项目使用独立的虚拟环境：python -m venv .venv。",
            "【激活命令差异】虚拟环境激活命令因平台而异：Windows 使用 .venv\\Scripts\\activate，Unix/macOS 使用 source .venv/bin/activate。激活后命令行提示符会显示环境名称如 (.venv)。",
            "【版本指定语法】pip 支持多种版本指定方式：SomePackage（最新版）、SomePackage==1.0.4（精确版本）、'SomePackage>=1.0.4'（最小版本）。注意 >= 等符号在 shell 中需要引号包裹。",
            "【freeze vs list】pip list 显示已安装包的友好列表，pip freeze 输出可直接用于 requirements.txt 的格式。导出依赖时应使用 freeze 而非 list。",
        ],
        handsOnPath: [
            "1. 创建项目目录：mkdir my_project && cd my_project",
            "2. 创建虚拟环境：python -m venv .venv（推荐使用 .venv 作为目录名）",
            "3. 激活虚拟环境：source .venv/bin/activate（Unix）或 .venv\\Scripts\\activate（Windows）",
            "4. 验证激活：观察命令行提示符出现 (.venv) 前缀",
            "5. 安装包：python -m pip install requests（官方推荐 python -m pip 而非直接 pip）",
            "6. 查看已安装包：python -m pip list",
            "7. 导出依赖：python -m pip freeze > requirements.txt",
            "8. 查看 requirements.txt 内容，理解格式",
            "9. 停用虚拟环境：deactivate",
        ],
        selfCheck: [
            "为什么每个项目都应该使用独立的虚拟环境？",
            "pip freeze 和 pip list 的输出有什么区别？",
            "如何安装特定版本的包，比如 requests 2.28.0？",
            "虚拟环境激活后，命令行提示符会有什么变化？",
            "requirements.txt 文件的作用是什么？",
            "如何从 requirements.txt 一次性安装所有依赖？",
            "官方推荐使用什么名称作为虚拟环境目录？",
            "pip 和 python -m pip 有什么区别？",
        ],
        extensions: [
            "了解 pipenv、poetry 等现代依赖管理工具",
            "学习 pip 的约束文件（constraints files）高级用法",
            "探索 PyPI 上的包搜索和筛选功能",
            "了解 pip 的依赖组（dependency groups）功能",
            "学习如何发布自己的包到 PyPI",
        ],
        sourceUrls: [
            "https://pip.pypa.io/en/stable/user_guide/",
            "https://pypi.org/",
            "https://docs.python.org/3/tutorial/venv.html",
        ],
    },
}

export const week1Quizzes: Record<string, QuizQuestion[]> = {
    "py-w1-1": [
        {
            id: "py-w1-1-q1",
            question: "根据 Python 官网，当前最新的稳定版本是？",
            options: [
                "Python 3.12",
                "Python 3.13",
                "Python 3.14",
                "Python 3.15",
            ],
            answer: 2,
            rationale: "Python 官网显示当前最新稳定版为 Python 3.14.2。Python 3.15 仍处于预发布状态。",
        },
        {
            id: "py-w1-1-q2",
            question: "安装 VS Code Python 扩展后，会自动安装哪些组件？",
            options: [
                "仅 Pylance",
                "Pylance、Python Debugger、Python Environments",
                "Black、Pylint、MyPy",
                "Jupyter、Pylance、Black",
            ],
            answer: 1,
            rationale: "官方文档说明：Three companion extensions install by default: Pylance, Python Debugger, Python Environments。",
        },
        {
            id: "py-w1-1-q3",
            question: "在 VS Code 中选择 Python 解释器的命令是？",
            options: [
                "Python: Start Terminal REPL",
                "Python: Run Python File",
                "Python: Select Interpreter",
                "Python: Configure Tests",
            ],
            answer: 2,
            rationale: "VS Code Python 扩展文档列出的快速启动命令中，'Python: Select Interpreter' 用于切换 Python 版本。",
        },
        {
            id: "py-w1-1-q4",
            question: "Python 官方安装指南涵盖了哪些平台？",
            options: [
                "仅 Windows 和 macOS",
                "Windows、macOS、Linux",
                "Windows、macOS、Linux/Unix、Android、iOS",
                "仅桌面操作系统",
            ],
            answer: 2,
            rationale: "官方安装指南包含 Unix、Windows、macOS 以及移动平台（Android 和 iOS）的安装说明。",
        },
        {
            id: "py-w1-1-q5",
            question: "根据官方文档，Python 3.9 的支持状态是？",
            options: [
                "仍在接收 bugfix 更新",
                "仅接收安全更新",
                "已于 2025 年 10 月结束生命周期",
                "处于预发布状态",
            ],
            answer: 2,
            rationale: "官网明确指出：Python 3.9 end of life as of Oct 31, 2025。",
        },
        {
            id: "py-w1-1-q6",
            question: "VS Code Python 扩展支持哪些代码格式化工具？",
            options: [
                "仅 Black",
                "Black 和 Prettier",
                "Black、autopep 和 yapf",
                "Pylint 和 flake8",
            ],
            answer: 2,
            rationale: "扩展文档说明支持：Format code with black, autopep, or yapf。",
        },
        {
            id: "py-w1-1-q7",
            question: "VS Code Python 扩展支持自动激活哪些虚拟环境类型？",
            options: [
                "仅 venv",
                "venv 和 virtualenv",
                "virtualenv、venv、pipenv、conda、pyenv",
                "仅 conda",
            ],
            answer: 2,
            rationale: "文档列出：Automatically activate virtualenv, venv, pipenv, conda, and pyenv environments。",
        },
        {
            id: "py-w1-1-q8",
            question: "在 macOS 上安装 Python 需要什么版本的系统？",
            options: [
                "macOS 10.14 及以上",
                "macOS 10.15 及以上",
                "macOS 11 及以上",
                "任何 macOS 版本",
            ],
            answer: 2,
            rationale: "Python 官网下载页面显示 macOS 需要 version 11 and later。",
        },
        {
            id: "py-w1-1-q9",
            question: "VS Code Python 扩展支持哪些测试框架？",
            options: [
                "仅 pytest",
                "unittest 和 pytest",
                "nose 和 pytest",
                "仅 unittest",
            ],
            answer: 1,
            rationale: "扩展文档说明：Run unit tests via unittest or pytest frameworks。",
        },
        {
            id: "py-w1-1-q10",
            question: "Pylance 组件提供什么功能？",
            options: [
                "代码调试",
                "环境管理",
                "高性能 Python 语言支持",
                "代码格式化",
            ],
            answer: 2,
            rationale: "文档描述 Pylance 为 'performant Python language support'。",
        },
        {
            id: "py-w1-1-q11",
            question: "Python 3.14 的 bugfix 支持将持续到何时？",
            options: [
                "2028 年 10 月",
                "2029 年 10 月",
                "2030 年 10 月",
                "2031 年 10 月",
            ],
            answer: 2,
            rationale: "官网显示 Python 3.14 bugfix support until Oct 2030。",
        },
        {
            id: "py-w1-1-q12",
            question: "关于 VS Code Python 扩展的安装方式，以下哪项是正确的？",
            options: [
                "只能通过命令行安装",
                "可以使用 Quick Open (Ctrl+P/Cmd+P) 粘贴扩展 ID 安装",
                "必须从 GitHub 下载安装",
                "只能在 Windows 上安装",
            ],
            answer: 1,
            rationale: "文档说明：Users can install via VS Code Quick Open using Ctrl+P (Windows/Linux) or Cmd+P (macOS), then paste the extension ID。",
        },
    ],
    "py-w1-2": [
        {
            id: "py-w1-2-q1",
            question: "Python 官方教程的目标受众是？",
            options: [
                "完全没有编程经验的初学者",
                "已有编程基础的程序员",
                "仅限于数据科学家",
                "仅限于 Web 开发者",
            ],
            answer: 1,
            rationale: "官方教程明确说明：目标受众是'已有编程基础的程序员（非零基础初学者）'。",
        },
        {
            id: "py-w1-2-q2",
            question: "Python 交互模式中，>>> 和 ... 分别代表什么？",
            options: [
                ">>> 是错误提示，... 是正常输入",
                ">>> 是主提示符，... 是续行提示符",
                ">>> 是输出，... 是输入",
                "两者功能相同",
            ],
            answer: 1,
            rationale: "文档说明：'>>>' - 主提示符（输入新命令），'...' - 续行提示符（多行代码）。",
        },
        {
            id: "py-w1-2-q3",
            question: "Python 源文件的默认编码是什么？",
            options: [
                "ASCII",
                "Latin-1",
                "UTF-8",
                "GBK",
            ],
            answer: 2,
            rationale: "解释器教程明确指出：Python 源文件默认采用 UTF-8 编码。",
        },
        {
            id: "py-w1-2-q4",
            question: "如果要在脚本执行后进入交互模式，应该使用哪个命令？",
            options: [
                "python -c script.py",
                "python -m script.py",
                "python -i script.py",
                "python --interactive script.py",
            ],
            answer: 2,
            rationale: "文档说明：python -i script.py 执行后进入交互模式。",
        },
        {
            id: "py-w1-2-q5",
            question: "在 Unix 系统上退出 Python 交互模式的快捷键是？",
            options: [
                "Control-C",
                "Control-D",
                "Control-Z",
                "Control-X",
            ],
            answer: 1,
            rationale: "文档说明：Unix 使用 Control-D，Windows 使用 Control-Z。",
        },
        {
            id: "py-w1-2-q6",
            question: "Python 官方教程共有多少章节？",
            options: [
                "10 章",
                "12 章",
                "16 章",
                "20 章",
            ],
            answer: 2,
            rationale: "官方教程分析显示共有 16 个章节，从基础到高级主题。",
        },
        {
            id: "py-w1-2-q7",
            question: "使用 -c 选项执行代码时，sys.argv[0] 的值是什么？",
            options: [
                "脚本文件名",
                "'-'",
                "'-c'",
                "空字符串",
            ],
            answer: 2,
            rationale: "文档说明 sys.argv[0] 根据调用方式而定：使用 -c 选项时为 '-c'。",
        },
        {
            id: "py-w1-2-q8",
            question: "如何在源文件中声明使用 cp1252 编码？",
            options: [
                "# encoding: cp1252",
                "# -*- coding: cp1252 -*-",
                "encoding = 'cp1252'",
                "import cp1252",
            ],
            answer: 1,
            rationale: "文档示例：在文件第一行添加 '# -*- coding: cp1252 -*-'。",
        },
        {
            id: "py-w1-2-q9",
            question: "Python 使用什么方式表示代码块？",
            options: [
                "花括号 {}",
                "begin/end 关键字",
                "缩进",
                "方括号 []",
            ],
            answer: 2,
            rationale: "这是 Python 的核心特性：使用缩进表示代码块，而非花括号。",
        },
        {
            id: "py-w1-2-q10",
            question: "以下哪个命令可以执行单行 Python 代码？",
            options: [
                "python -e 'print(1)'",
                "python -c 'print(1)'",
                "python --eval 'print(1)'",
                "python -x 'print(1)'",
            ],
            answer: 1,
            rationale: "文档说明：python -c command [arg] ... 用于执行单行命令。",
        },
        {
            id: "py-w1-2-q11",
            question: "学完 Python 官方教程后，你应该能够做什么？",
            options: [
                "成为 Python 专家",
                "阅读和编写 Python 模块与程序",
                "开发大型企业应用",
                "精通所有 Python 库",
            ],
            answer: 1,
            rationale: "教程明确说明学习目标：'阅读和编写Python模块与程序，理解Python的风格与特性'。",
        },
        {
            id: "py-w1-2-q12",
            question: "在 Windows 上启动 Python 解释器的推荐方式是？",
            options: [
                "python3.14",
                "py",
                "python.exe",
                "start python",
            ],
            answer: 1,
            rationale: "文档说明 Windows 使用 py（py.exe 启动器）启动 Python。",
        },
    ],
    "py-w1-3": [
        {
            id: "py-w1-3-q1",
            question: "为什么需要虚拟环境？",
            options: [
                "加快代码执行速度",
                "减少内存占用",
                "解决不同应用需要同一库不同版本的问题",
                "提高代码安全性",
            ],
            answer: 2,
            rationale: "官方文档说明：不同应用可能需要同一库的不同版本，虚拟环境通过隔离解决这个问题。",
        },
        {
            id: "py-w1-3-q2",
            question: "创建虚拟环境的命令是？",
            options: [
                "pip create venv",
                "python -m venv .venv",
                "virtualenv create .venv",
                "python --venv .venv",
            ],
            answer: 1,
            rationale: "官方教程示例：python -m venv tutorial-env 或 python -m venv .venv。",
        },
        {
            id: "py-w1-3-q3",
            question: "在 Unix/macOS 上激活虚拟环境的命令是？",
            options: [
                ".venv/bin/activate",
                "source .venv/bin/activate",
                ".venv\\Scripts\\activate",
                "activate .venv",
            ],
            answer: 1,
            rationale: "文档说明 Unix/MacOS 使用：source tutorial-env/bin/activate。",
        },
        {
            id: "py-w1-3-q4",
            question: "PyPI 是什么？",
            options: [
                "Python 的 IDE",
                "Python 的调试器",
                "Python 软件包的仓库",
                "Python 的编译器",
            ],
            answer: 2,
            rationale: "PyPI 官方定义：'The Python Package Index (PyPI) is a repository of software for the Python programming language'。",
        },
        {
            id: "py-w1-3-q5",
            question: "pip freeze 命令的作用是？",
            options: [
                "冻结包的安装",
                "生成 requirements.txt 格式的依赖列表",
                "停止正在运行的进程",
                "锁定 Python 版本",
            ],
            answer: 1,
            rationale: "pip 用户指南说明：Use pip freeze to capture exact versions installed，输出可用于 requirements.txt。",
        },
        {
            id: "py-w1-3-q6",
            question: "安装特定版本包的正确命令是？",
            options: [
                "pip install requests-2.6.0",
                "pip install requests==2.6.0",
                "pip install requests@2.6.0",
                "pip install requests:2.6.0",
            ],
            answer: 1,
            rationale: "官方文档示例：python -m pip install requests==2.6.0 安装特定版本。",
        },
        {
            id: "py-w1-3-q7",
            question: "requirements.txt 的主要作用是？",
            options: [
                "存储源代码",
                "配置 IDE",
                "使依赖安装可重复",
                "记录测试结果",
            ],
            answer: 2,
            rationale: "pip 用户指南：'Requirements files enable reproducible installations by listing packages in a single file'。",
        },
        {
            id: "py-w1-3-q8",
            question: "停用虚拟环境的命令是？",
            options: [
                "exit",
                "quit",
                "deactivate",
                "stop",
            ],
            answer: 2,
            rationale: "官方文档明确指出：使用 deactivate 命令停用虚拟环境。",
        },
        {
            id: "py-w1-3-q9",
            question: "pip 用户指南推荐使用什么命令运行 pip？",
            options: [
                "pip install",
                "python -m pip install",
                "pip3 install",
                "py -m pip install",
            ],
            answer: 1,
            rationale: "官方文档示例始终使用 python -m pip 形式，这确保使用正确的 Python 版本对应的 pip。",
        },
        {
            id: "py-w1-3-q10",
            question: "constraints files 和 requirements files 的主要区别是？",
            options: [
                "constraints files 只支持特定版本",
                "constraints files 限制版本但不触发安装",
                "constraints files 只能用于开发环境",
                "两者功能完全相同",
            ],
            answer: 1,
            rationale: "pip 文档说明：constraints files 'limit package versions without triggering installation'。",
        },
        {
            id: "py-w1-3-q11",
            question: "虚拟环境激活后，命令行提示符会有什么变化？",
            options: [
                "没有变化",
                "显示 Python 版本",
                "显示环境名称前缀如 (.venv)",
                "变成红色",
            ],
            answer: 2,
            rationale: "官方文档说明：激活后，命令行提示符会显示虚拟环境名称：(tutorial-env) $。",
        },
        {
            id: "py-w1-3-q12",
            question: "PyPI 目前大约包含多少个项目？",
            options: [
                "约 10 万个",
                "约 50 万个",
                "超过 72 万个",
                "约 100 万个",
            ],
            answer: 2,
            rationale: "PyPI 官网显示：目前包含 720,947 个项目。",
        },
    ],
}
