import type { LessonGuide } from "../types"
import type { QuizQuestion } from "@/lib/types"

export const week16Guides: Record<string, LessonGuide> = {
    "py-w16-1": {
        lessonId: "py-w16-1",
        background: [
            "【collections 模块】提供专门的容器数据类型，扩展 Python 内置容器（dict、list、set、tuple）的功能。",
            "【Counter】dict 子类，用于计数可哈希对象。most_common(n) 返回 n 个最常见元素，elements() 迭代重复元素。",
            "【defaultdict】dict 子类，为缺失键调用工厂函数提供默认值。常用工厂：list、int、set。",
            "【namedtuple】创建具有命名字段的元组子类。支持通过名称和索引访问，有 _make、_asdict、_replace 等方法。",
            "【deque】双端队列，两端 append/pop 操作都是 O(1)。支持 rotate() 旋转、maxlen 限制长度。",
        ],
        keyDifficulties: [
            "【OrderedDict vs dict】Python 3.7+ dict 保持插入顺序，但 OrderedDict 提供 move_to_end() 和顺序敏感的相等性比较。",
            "【ChainMap 用途】将多个字典组合为单一视图，第一个字典优先。常用于配置优先级：命令行 > 环境变量 > 默认值。",
            "【Counter 运算】支持 +、-、&、| 运算符。减法可能产生负数或零计数，需用 +c 或 c.elements() 过滤。",
            "【namedtuple 默认值】使用 defaults 参数设置默认值，从右侧字段开始应用。",
        ],
        handsOnPath: [
            "1. Counter：from collections import Counter; c = Counter('abracadabra'); c.most_common(3)",
            "2. defaultdict：d = defaultdict(list); d['key'].append(1)",
            "3. namedtuple：Point = namedtuple('Point', ['x', 'y']); p = Point(1, 2)",
            "4. deque：d = deque([1,2,3], maxlen=5); d.appendleft(0); d.rotate(1)",
            "5. ChainMap：from collections import ChainMap; combined = ChainMap(local, env, defaults)",
            "6. OrderedDict：od = OrderedDict(); od.move_to_end('key')",
        ],
        selfCheck: [
            "Counter 的 most_common() 方法返回什么？",
            "defaultdict 如何处理缺失的键？",
            "namedtuple 相比普通元组有什么优势？",
            "deque 两端操作的时间复杂度是多少？",
            "ChainMap 查找键时的优先级是什么？",
            "OrderedDict 和普通 dict 有什么区别？",
        ],
        extensions: [
            "学习 Counter 的数学运算",
            "了解 UserDict、UserList、UserString",
            "探索 deque 实现滑动窗口算法",
            "学习 typing.NamedTuple 类型注解版本",
        ],
        sourceUrls: [
            "https://docs.python.org/3/library/collections.html",
            "https://docs.python.org/3/library/collections.html#collections.Counter",
            "https://docs.python.org/3/library/collections.html#collections.deque",
        ],
    },
    "py-w16-2": {
        lessonId: "py-w16-2",
        background: [
            "【datetime 模块】提供日期和时间处理类：date、time、datetime、timedelta、timezone、tzinfo。",
            "【timedelta】表示两个日期或时间之间的持续时间。支持 days、seconds、microseconds 属性，可进行算术运算。",
            "【date 类】表示日期（年、月、日）。date.today() 获取今天，支持 fromisoformat()、strftime() 等方法。",
            "【datetime 类】组合日期和时间。datetime.now() 获取当前时间，datetime.now(timezone.utc) 获取 UTC 时间。",
            "【aware vs naive】naive 对象没有时区信息（tzinfo=None），aware 对象包含时区信息，表示特定时刻。",
        ],
        keyDifficulties: [
            "【strftime vs strptime】strftime 将日期时间格式化为字符串，strptime 将字符串解析为日期时间。",
            "【时区处理】使用 zoneinfo.ZoneInfo（Python 3.9+）处理 IANA 时区，自动处理夏令时转换。",
            "【timedelta 规范化】timedelta 内部只存储 days、seconds、microseconds，其他单位会被转换。",
            "【timestamp 往返】datetime.timestamp() 转换为 POSIX 时间戳，datetime.fromtimestamp() 反向转换。",
        ],
        handsOnPath: [
            "1. 获取当前时间：from datetime import datetime; now = datetime.now()",
            "2. 创建日期：from datetime import date; d = date(2024, 1, 15)",
            "3. 时间差：from datetime import timedelta; delta = timedelta(days=7, hours=2)",
            "4. 格式化：now.strftime('%Y-%m-%d %H:%M:%S')",
            "5. 解析：datetime.strptime('2024-01-15', '%Y-%m-%d')",
            "6. 时区：from zoneinfo import ZoneInfo; dt = datetime.now(ZoneInfo('Asia/Shanghai'))",
        ],
        selfCheck: [
            "date、time、datetime 类的区别是什么？",
            "如何获取当前 UTC 时间？",
            "strftime 和 strptime 的区别是什么？",
            "aware 和 naive 日期时间有什么区别？",
            "timedelta 支持哪些时间单位？",
            "如何将字符串解析为日期时间？",
        ],
        extensions: [
            "学习 calendar 模块处理日历",
            "了解 dateutil 第三方库",
            "探索 ISO 8601 日期时间格式",
            "学习 Arrow 或 Pendulum 现代日期库",
        ],
        sourceUrls: [
            "https://docs.python.org/3/library/datetime.html",
            "https://docs.python.org/3/library/zoneinfo.html",
            "https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior",
        ],
    },
    "py-w16-3": {
        lessonId: "py-w16-3",
        background: [
            "【re 模块】提供正则表达式匹配操作。使用原始字符串 r'' 定义模式避免转义问题。",
            "【search vs match】re.search() 在字符串任意位置搜索匹配，re.match() 只在字符串开头匹配。",
            "【findall 和 finditer】findall() 返回所有匹配的列表，finditer() 返回匹配对象的迭代器。",
            "【compile】re.compile(pattern) 预编译模式以便重复使用，提高多次匹配的效率。",
            "【sub 替换】re.sub(pattern, repl, string) 替换匹配的内容，repl 可以是字符串或函数。",
        ],
        keyDifficulties: [
            "【分组】(pattern) 创建捕获组，(?:pattern) 非捕获组，(?P<name>pattern) 命名组。",
            "【贪婪 vs 非贪婪】*、+、? 默认贪婪，添加 ? 变为非贪婪：*?、+?、??。",
            "【特殊字符】\\d 数字、\\w 单词字符、\\s 空白、\\b 单词边界。大写版本表示否定。",
            "【flags 参数】re.IGNORECASE 忽略大小写、re.MULTILINE 多行模式、re.DOTALL 点匹配换行。",
        ],
        handsOnPath: [
            "1. 搜索：import re; m = re.search(r'\\d+', 'abc123def')",
            "2. 匹配对象：m.group(), m.start(), m.end(), m.span()",
            "3. 查找所有：re.findall(r'\\w+', 'hello world')",
            "4. 分组：m = re.match(r'(\\w+) (\\w+)', 'Isaac Newton'); m.groups()",
            "5. 命名组：re.match(r'(?P<first>\\w+) (?P<last>\\w+)', 'Isaac Newton').groupdict()",
            "6. 替换：re.sub(r'\\d+', 'NUM', 'abc123def456')",
        ],
        selfCheck: [
            "search() 和 match() 有什么区别？",
            "如何创建命名捕获组？",
            "贪婪匹配和非贪婪匹配的区别是什么？",
            "\\b 表示什么？",
            "如何预编译正则表达式？",
            "sub() 的 repl 参数可以是什么类型？",
        ],
        extensions: [
            "学习 regex 第三方库的高级功能",
            "了解正则表达式性能优化",
            "探索 lookahead 和 lookbehind",
            "学习正则表达式可视化工具",
        ],
        sourceUrls: [
            "https://docs.python.org/3/library/re.html",
            "https://docs.python.org/3/howto/regex.html",
            "https://docs.python.org/3/library/re.html#regular-expression-syntax",
        ],
    },
    "py-w16-4": {
        lessonId: "py-w16-4",
        background: [
            "【zoneinfo 模块】Python 3.9+ 内置的 IANA 时区支持。ZoneInfo 类是 tzinfo 的具体实现。",
            "【ZoneInfo 创建】ZoneInfo('America/New_York') 创建时区对象，使用 IANA 标准时区名称。",
            "【时区转换】datetime.astimezone(tz) 转换时区，自动处理夏令时（DST）转换。",
            "【fold 属性】处理夏令时回退时的歧义时间。fold=0 表示较早时间，fold=1 表示较晚时间。",
            "【缓存机制】ZoneInfo 使用缓存，相同 key 的多次调用返回同一对象。",
        ],
        keyDifficulties: [
            "【时区数据来源】优先使用系统 IANA 数据库，可安装 tzdata 包确保跨平台一致性。",
            "【available_timezones()】返回所有可用时区名称的集合，用于验证时区是否存在。",
            "【TZPATH 配置】通过 PYTHONTZPATH 环境变量或 reset_tzpath() 配置时区数据搜索路径。",
            "【序列化限制】通过 key 构造的 ZoneInfo 可序列化，from_file() 构造的不能序列化。",
        ],
        handsOnPath: [
            "1. 创建时区：from zoneinfo import ZoneInfo; tz = ZoneInfo('Asia/Shanghai')",
            "2. 带时区的时间：from datetime import datetime; dt = datetime.now(tz)",
            "3. 时区转换：dt.astimezone(ZoneInfo('America/New_York'))",
            "4. 查看可用时区：from zoneinfo import available_timezones; print(len(available_timezones()))",
            "5. UTC 时间：from datetime import timezone; utc_dt = datetime.now(timezone.utc)",
            "6. 处理歧义：dt.replace(fold=1)  # 夏令时回退后的时间",
        ],
        selfCheck: [
            "ZoneInfo 使用什么时区命名系统？",
            "如何将 datetime 转换到另一个时区？",
            "fold 属性用于什么场景？",
            "如何获取所有可用的时区？",
            "ZoneInfo 的缓存机制是什么？",
            "如何确保跨平台的时区数据一致性？",
        ],
        extensions: [
            "学习 pytz 库的历史用法",
            "了解 IANA 时区数据库的结构",
            "探索夏令时转换的边界情况",
            "学习国际化应用的时区处理",
        ],
        sourceUrls: [
            "https://docs.python.org/3/library/zoneinfo.html",
            "https://docs.python.org/3/library/datetime.html#datetime.tzinfo",
            "https://www.iana.org/time-zones",
        ],
    },
}

export const week16Quizzes: Record<string, QuizQuestion[]> = {
    "py-w16-1": [
        {
            id: "py-w16-1-q1",
            question: "Counter 的 most_common(n) 方法返回什么？",
            options: [
                "所有元素",
                "n 个最常见的元素及其计数",
                "计数总和",
                "最大计数",
            ],
            answer: 1,
            rationale: "文档说明：most_common([n]) 返回 n 个最常见元素及其计数的列表。",
        },
        {
            id: "py-w16-1-q2",
            question: "defaultdict(list) 访问不存在的键会发生什么？",
            options: [
                "抛出 KeyError",
                "返回 None",
                "自动创建空列表作为值",
                "返回 0",
            ],
            answer: 2,
            rationale: "文档说明：defaultdict 为缺失键调用工厂函数，list 工厂创建空列表。",
        },
        {
            id: "py-w16-1-q3",
            question: "namedtuple 的 _asdict() 方法返回什么？",
            options: [
                "普通元组",
                "字典",
                "列表",
                "集合",
            ],
            answer: 1,
            rationale: "文档说明：_asdict() 返回将字段名映射到值的字典。",
        },
        {
            id: "py-w16-1-q4",
            question: "deque 两端操作的时间复杂度是多少？",
            options: [
                "O(n)",
                "O(1)",
                "O(log n)",
                "O(n²)",
            ],
            answer: 1,
            rationale: "文档说明：deque 支持 O(1) 的两端 append 和 pop 操作。",
        },
        {
            id: "py-w16-1-q5",
            question: "ChainMap 查找键时使用什么优先级？",
            options: [
                "最后一个字典优先",
                "第一个字典优先",
                "随机选择",
                "按字母顺序",
            ],
            answer: 1,
            rationale: "文档说明：ChainMap 第一个映射优先，查找时按顺序检查。",
        },
        {
            id: "py-w16-1-q6",
            question: "OrderedDict 相比普通 dict 有什么额外功能？",
            options: [
                "更快的查找",
                "move_to_end() 方法和顺序敏感的相等性",
                "自动排序",
                "类型检查",
            ],
            answer: 1,
            rationale: "文档说明：OrderedDict 提供 move_to_end() 方法和顺序敏感的相等性比较。",
        },
        {
            id: "py-w16-1-q7",
            question: "Counter('abracadabra') 的结果是什么？",
            options: [
                "{'a': 5, 'b': 2, 'r': 2, 'c': 1, 'd': 1}",
                "['a', 'b', 'r', 'a', 'c', 'a', 'd', 'a', 'b', 'r', 'a']",
                "11",
                "5",
            ],
            answer: 0,
            rationale: "Counter 计数每个字符的出现次数，a 出现 5 次，b 和 r 各 2 次，c 和 d 各 1 次。",
        },
        {
            id: "py-w16-1-q8",
            question: "deque 的 rotate(1) 做什么？",
            options: [
                "删除第一个元素",
                "将最后一个元素移到开头",
                "反转队列",
                "排序队列",
            ],
            answer: 1,
            rationale: "文档说明：rotate(1) 将最后一个元素移到开头，正数右旋，负数左旋。",
        },
        {
            id: "py-w16-1-q9",
            question: "namedtuple 的 _fields 属性返回什么？",
            options: [
                "字段值",
                "字段名称的元组",
                "字段类型",
                "字段数量",
            ],
            answer: 1,
            rationale: "文档说明：_fields 是包含字段名称的元组。",
        },
        {
            id: "py-w16-1-q10",
            question: "Counter.elements() 返回什么？",
            options: [
                "键的列表",
                "按计数重复每个元素的迭代器",
                "值的列表",
                "键值对",
            ],
            answer: 1,
            rationale: "文档说明：elements() 返回迭代器，每个元素重复其计数次数。",
        },
        {
            id: "py-w16-1-q11",
            question: "deque(maxlen=5) 满后再添加元素会怎样？",
            options: [
                "抛出异常",
                "自动移除另一端的元素",
                "忽略新元素",
                "扩展容量",
            ],
            answer: 1,
            rationale: "文档说明：有界 deque 满后，添加新元素会自动移除另一端的元素。",
        },
        {
            id: "py-w16-1-q12",
            question: "namedtuple 的 _replace() 方法做什么？",
            options: [
                "修改原对象",
                "返回替换了指定字段的新实例",
                "删除字段",
                "重命名字段",
            ],
            answer: 1,
            rationale: "文档说明：_replace(**kwargs) 返回替换了指定字段值的新实例，原对象不变。",
        },
    ],
    "py-w16-2": [
        {
            id: "py-w16-2-q1",
            question: "datetime.now() 返回什么类型的对象？",
            options: [
                "date",
                "time",
                "datetime（naive）",
                "timedelta",
            ],
            answer: 2,
            rationale: "文档说明：datetime.now() 返回当前本地时间的 naive datetime 对象。",
        },
        {
            id: "py-w16-2-q2",
            question: "timedelta 支持哪些属性？",
            options: [
                "years, months, days",
                "days, seconds, microseconds",
                "hours, minutes, seconds",
                "weeks, days, hours",
            ],
            answer: 1,
            rationale: "文档说明：timedelta 内部只存储 days、seconds、microseconds 三个属性。",
        },
        {
            id: "py-w16-2-q3",
            question: "strftime 和 strptime 的区别是什么？",
            options: [
                "没有区别",
                "strftime 格式化为字符串，strptime 解析字符串",
                "strptime 格式化为字符串，strftime 解析字符串",
                "一个用于日期，一个用于时间",
            ],
            answer: 1,
            rationale: "文档说明：strftime 将日期时间格式化为字符串，strptime 将字符串解析为日期时间。",
        },
        {
            id: "py-w16-2-q4",
            question: "如何获取当前 UTC 时间？",
            options: [
                "datetime.now()",
                "datetime.utcnow()",
                "datetime.now(timezone.utc)",
                "datetime.utc()",
            ],
            answer: 2,
            rationale: "文档推荐：datetime.now(timezone.utc) 返回带时区信息的 UTC 时间。",
        },
        {
            id: "py-w16-2-q5",
            question: "aware 和 naive 日期时间的区别是什么？",
            options: [
                "精度不同",
                "aware 有时区信息，naive 没有",
                "存储方式不同",
                "支持的操作不同",
            ],
            answer: 1,
            rationale: "文档说明：naive 对象的 tzinfo 为 None，aware 对象包含时区信息。",
        },
        {
            id: "py-w16-2-q6",
            question: "%Y 格式代码表示什么？",
            options: [
                "两位年份",
                "四位年份",
                "年份中的第几天",
                "年份中的第几周",
            ],
            answer: 1,
            rationale: "文档说明：%Y 表示四位数年份，%y 表示两位数年份。",
        },
        {
            id: "py-w16-2-q7",
            question: "date.today() 返回什么？",
            options: [
                "当前时间",
                "当前日期",
                "当前时间戳",
                "UTC 日期",
            ],
            answer: 1,
            rationale: "文档说明：date.today() 返回当前本地日期的 date 对象。",
        },
        {
            id: "py-w16-2-q8",
            question: "datetime.combine() 的作用是什么？",
            options: [
                "合并两个 datetime",
                "将 date 和 time 合并为 datetime",
                "合并两个 timedelta",
                "合并时区信息",
            ],
            answer: 1,
            rationale: "文档说明：datetime.combine(date, time) 将 date 和 time 对象合并为 datetime。",
        },
        {
            id: "py-w16-2-q9",
            question: "timedelta(hours=25) 的 days 属性是多少？",
            options: [
                "0",
                "1",
                "25",
                "抛出错误",
            ],
            answer: 1,
            rationale: "timedelta 会规范化：25 小时 = 1 天 + 1 小时，days=1。",
        },
        {
            id: "py-w16-2-q10",
            question: "datetime.fromisoformat() 接受什么格式？",
            options: [
                "Unix 时间戳",
                "ISO 8601 格式字符串",
                "RFC 2822 格式",
                "自定义格式",
            ],
            answer: 1,
            rationale: "文档说明：fromisoformat() 解析 ISO 8601 格式的日期时间字符串。",
        },
        {
            id: "py-w16-2-q11",
            question: "datetime.timestamp() 返回什么？",
            options: [
                "字符串",
                "POSIX 时间戳（浮点数）",
                "整数秒",
                "timedelta",
            ],
            answer: 1,
            rationale: "文档说明：timestamp() 返回 POSIX 时间戳，是从 1970-01-01 起的秒数。",
        },
        {
            id: "py-w16-2-q12",
            question: "weekday() 方法中星期一是什么值？",
            options: [
                "1",
                "0",
                "7",
                "-1",
            ],
            answer: 1,
            rationale: "文档说明：weekday() 返回 0-6，其中 0 表示星期一，6 表示星期日。",
        },
    ],
    "py-w16-3": [
        {
            id: "py-w16-3-q1",
            question: "re.search() 和 re.match() 的区别是什么？",
            options: [
                "没有区别",
                "search 在任意位置搜索，match 只在开头匹配",
                "match 在任意位置搜索，search 只在开头匹配",
                "search 更快",
            ],
            answer: 1,
            rationale: "文档说明：match() 只在字符串开头匹配，search() 在任意位置搜索。",
        },
        {
            id: "py-w16-3-q2",
            question: "r'\\d+' 中的 r 前缀有什么作用？",
            options: [
                "正则表达式标志",
                "定义原始字符串，避免转义",
                "只读字符串",
                "右对齐",
            ],
            answer: 1,
            rationale: "文档推荐：使用原始字符串 r'' 定义模式，避免双重转义。",
        },
        {
            id: "py-w16-3-q3",
            question: "re.findall() 返回什么？",
            options: [
                "第一个匹配",
                "所有非重叠匹配的列表",
                "匹配对象",
                "布尔值",
            ],
            answer: 1,
            rationale: "文档说明：findall() 返回所有非重叠匹配的列表。",
        },
        {
            id: "py-w16-3-q4",
            question: "如何创建命名捕获组？",
            options: [
                "(name:pattern)",
                "(?P<name>pattern)",
                "[name:pattern]",
                "{name:pattern}",
            ],
            answer: 1,
            rationale: "文档说明：(?P<name>pattern) 创建命名组，可用 group('name') 访问。",
        },
        {
            id: "py-w16-3-q5",
            question: "\\b 在正则表达式中表示什么？",
            options: [
                "退格符",
                "单词边界",
                "换行符",
                "空格",
            ],
            answer: 1,
            rationale: "文档说明：\\b 匹配单词边界，即 \\w 和 \\W 之间的位置。",
        },
        {
            id: "py-w16-3-q6",
            question: "re.compile() 的作用是什么？",
            options: [
                "编译 Python 代码",
                "预编译正则表达式以便重复使用",
                "压缩字符串",
                "验证模式语法",
            ],
            answer: 1,
            rationale: "文档说明：compile() 预编译模式对象，重复匹配时更高效。",
        },
        {
            id: "py-w16-3-q7",
            question: "*? 和 * 的区别是什么？",
            options: [
                "没有区别",
                "*? 是非贪婪，* 是贪婪",
                "*? 匹配 0 或 1 次",
                "*? 更快",
            ],
            answer: 1,
            rationale: "文档说明：* 是贪婪匹配（尽可能多），*? 是非贪婪匹配（尽可能少）。",
        },
        {
            id: "py-w16-3-q8",
            question: "m.group(0) 返回什么？",
            options: [
                "第一个捕获组",
                "整个匹配",
                "空字符串",
                "None",
            ],
            answer: 1,
            rationale: "文档说明：group(0) 返回整个匹配，group(1) 返回第一个捕获组。",
        },
        {
            id: "py-w16-3-q9",
            question: "re.IGNORECASE 标志的作用是什么？",
            options: [
                "忽略空格",
                "忽略大小写",
                "忽略换行",
                "忽略错误",
            ],
            answer: 1,
            rationale: "文档说明：re.IGNORECASE 使匹配忽略大小写。",
        },
        {
            id: "py-w16-3-q10",
            question: "re.sub(r'\\d', 'X', 'a1b2c3') 返回什么？",
            options: [
                "'abc'",
                "'aXbXcX'",
                "'XXX'",
                "'a1b2c3'",
            ],
            answer: 1,
            rationale: "sub 将每个匹配的数字替换为 'X'，结果是 'aXbXcX'。",
        },
        {
            id: "py-w16-3-q11",
            question: "(?:pattern) 和 (pattern) 的区别是什么？",
            options: [
                "没有区别",
                "(?:) 是非捕获组，() 是捕获组",
                "(?:) 是命名组",
                "(?:) 更慢",
            ],
            answer: 1,
            rationale: "文档说明：(?:pattern) 是非捕获组，不创建捕获组但可以分组。",
        },
        {
            id: "py-w16-3-q12",
            question: "\\w 匹配什么字符？",
            options: [
                "只有空格",
                "字母、数字和下划线",
                "只有字母",
                "所有字符",
            ],
            answer: 1,
            rationale: "文档说明：\\w 匹配 Unicode 单词字符，包括字母、数字和下划线。",
        },
    ],
    "py-w16-4": [
        {
            id: "py-w16-4-q1",
            question: "ZoneInfo 使用什么时区命名系统？",
            options: [
                "UTC 偏移量",
                "IANA 时区数据库",
                "Windows 时区名",
                "自定义名称",
            ],
            answer: 1,
            rationale: "文档说明：ZoneInfo 使用 IANA 时区数据库的标准名称，如 'America/New_York'。",
        },
        {
            id: "py-w16-4-q2",
            question: "如何将 datetime 转换到另一个时区？",
            options: [
                "dt.timezone(tz)",
                "dt.astimezone(tz)",
                "dt.convert(tz)",
                "tz.convert(dt)",
            ],
            answer: 1,
            rationale: "文档说明：datetime.astimezone(tz) 将日期时间转换到指定时区。",
        },
        {
            id: "py-w16-4-q3",
            question: "fold 属性用于什么场景？",
            options: [
                "格式化输出",
                "处理夏令时回退时的歧义时间",
                "时区转换",
                "序列化",
            ],
            answer: 1,
            rationale: "文档说明：fold 属性区分夏令时回退时的两个可能时间点。",
        },
        {
            id: "py-w16-4-q4",
            question: "available_timezones() 返回什么？",
            options: [
                "时区列表",
                "所有可用时区名称的集合",
                "时区对象",
                "时区数量",
            ],
            answer: 1,
            rationale: "文档说明：available_timezones() 返回所有可用 IANA 时区名称的集合。",
        },
        {
            id: "py-w16-4-q5",
            question: "ZoneInfo 的缓存机制是什么？",
            options: [
                "不使用缓存",
                "相同 key 的多次调用返回同一对象",
                "每次创建新对象",
                "使用 LRU 缓存",
            ],
            answer: 1,
            rationale: "文档说明：ZoneInfo 使用缓存，相同 key 的调用返回同一对象。",
        },
        {
            id: "py-w16-4-q6",
            question: "如何确保跨平台的时区数据一致性？",
            options: [
                "使用系统时区",
                "安装 tzdata 包",
                "使用 UTC",
                "硬编码偏移量",
            ],
            answer: 1,
            rationale: "文档建议：安装 tzdata 包确保所有平台使用相同的时区数据。",
        },
        {
            id: "py-w16-4-q7",
            question: "ZoneInfo.no_cache(key) 的作用是什么？",
            options: [
                "清除缓存",
                "绕过缓存创建新的 ZoneInfo 对象",
                "禁用缓存功能",
                "检查缓存状态",
            ],
            answer: 1,
            rationale: "文档说明：no_cache(key) 绕过缓存，每次创建新的 ZoneInfo 实例。",
        },
        {
            id: "py-w16-4-q8",
            question: "zoneinfo 模块是在哪个 Python 版本引入的？",
            options: [
                "Python 3.7",
                "Python 3.8",
                "Python 3.9",
                "Python 3.10",
            ],
            answer: 2,
            rationale: "zoneinfo 模块是 Python 3.9 新增的标准库模块。",
        },
        {
            id: "py-w16-4-q9",
            question: "ZoneInfo.from_file() 创建的对象有什么限制？",
            options: [
                "不能使用",
                "不能序列化",
                "不能转换时区",
                "没有限制",
            ],
            answer: 1,
            rationale: "文档说明：from_file() 创建的 ZoneInfo 对象无法通过 pickle 序列化。",
        },
        {
            id: "py-w16-4-q10",
            question: "PYTHONTZPATH 环境变量的作用是什么？",
            options: [
                "设置 Python 路径",
                "配置时区数据搜索路径",
                "设置默认时区",
                "启用时区功能",
            ],
            answer: 1,
            rationale: "文档说明：PYTHONTZPATH 环境变量配置时区数据文件的搜索路径。",
        },
        {
            id: "py-w16-4-q11",
            question: "fold=0 和 fold=1 分别表示什么？",
            options: [
                "之前和之后",
                "夏令时回退前的时间和回退后的时间",
                "UTC 和本地时间",
                "有效和无效",
            ],
            answer: 1,
            rationale: "文档说明：fold=0 表示较早时间（回退前），fold=1 表示较晚时间（回退后）。",
        },
        {
            id: "py-w16-4-q12",
            question: "ZoneInfoNotFoundError 什么时候抛出？",
            options: [
                "时区转换失败",
                "请求的时区在系统中不存在",
                "时区数据损坏",
                "缓存满了",
            ],
            answer: 1,
            rationale: "文档说明：当请求的 IANA 时区名称在系统中找不到时抛出此异常。",
        },
    ],
}
