import type { LessonGuide } from "../types"
import type { QuizQuestion } from "@/lib/types"

export const week17Guides: Record<string, LessonGuide> = {
    "py-w17-1": {
        lessonId: "py-w17-1",
        background: [
            "【os 模块】提供操作系统相关功能的可移植接口。处理文件、目录、环境变量和进程管理。",
            "【os.environ】字典对象，访问和修改环境变量。os.getenv(key, default) 安全获取环境变量值。",
            "【目录操作】os.getcwd() 获取当前目录，os.chdir() 改变目录，os.makedirs() 递归创建目录。",
            "【sys 模块】访问 Python 解释器相关的变量和函数。sys.argv 命令行参数，sys.path 模块搜索路径。",
            "【sys.exit()】退出程序，参数为退出码（0 成功，非 0 失败）或错误消息。",
        ],
        keyDifficulties: [
            "【os.path vs pathlib】os.path 是传统的路径处理模块，pathlib 是现代面向对象的替代方案。",
            "【sys.stdin/stdout/stderr】标准输入输出流对象，可以重定向。print() 默认写入 sys.stdout。",
            "【os.scandir vs os.listdir】scandir() 返回 DirEntry 对象迭代器，性能更好，可获取文件属性。",
            "【sys.modules】已导入模块的字典缓存。删除条目可强制重新导入模块。",
        ],
        handsOnPath: [
            "1. 环境变量：import os; print(os.getenv('HOME', '/default'))",
            "2. 目录操作：os.makedirs('a/b/c', exist_ok=True)",
            "3. 文件列表：for entry in os.scandir('.'): print(entry.name, entry.is_file())",
            "4. 命令行参数：import sys; print(sys.argv)",
            "5. 平台检测：print(sys.platform, sys.version_info)",
            "6. 退出程序：sys.exit(1)  # 非零表示错误",
        ],
        selfCheck: [
            "os.environ 和 os.getenv() 有什么区别？",
            "sys.argv[0] 是什么？",
            "如何递归创建目录且不报错？",
            "sys.path 的作用是什么？",
            "os.scandir() 相比 os.listdir() 有什么优势？",
            "如何获取当前 Python 版本信息？",
        ],
        extensions: [
            "学习 shutil 模块的高级文件操作",
            "了解 platform 模块获取系统信息",
            "探索 os.walk() 递归遍历目录",
            "学习 sys.exc_info() 获取异常信息",
        ],
        sourceUrls: [
            "https://docs.python.org/3/library/os.html",
            "https://docs.python.org/3/library/sys.html",
            "https://docs.python.org/3/library/os.path.html",
        ],
    },
    "py-w17-2": {
        lessonId: "py-w17-2",
        background: [
            "【subprocess 模块】用于创建子进程、连接其输入输出管道、获取返回码。替代 os.system() 等旧函数。",
            "【subprocess.run()】推荐的高级接口，运行命令并等待完成，返回 CompletedProcess 对象。",
            "【capture_output】capture_output=True 捕获 stdout 和 stderr，存储在返回对象的属性中。",
            "【check 参数】check=True 时，非零返回码会抛出 CalledProcessError 异常。",
            "【text 参数】text=True 以文本模式打开流，返回字符串而非字节。",
        ],
        keyDifficulties: [
            "【shell=True 安全风险】使用 shell 执行命令有注入风险，应避免处理不信任的输入。推荐使用列表形式。",
            "【Popen 类】底层接口，提供更细粒度的控制。communicate() 方法发送输入并读取输出。",
            "【管道连接】可以将一个进程的 stdout 连接到另一个的 stdin，实现管道功能。",
            "【超时处理】timeout 参数设置超时，超时会抛出 TimeoutExpired 异常。",
        ],
        handsOnPath: [
            "1. 简单执行：import subprocess; subprocess.run(['ls', '-l'])",
            "2. 捕获输出：result = subprocess.run(['echo', 'hello'], capture_output=True, text=True)",
            "3. 检查返回码：subprocess.run(['false'], check=True)  # 抛出异常",
            "4. 处理输出：print(result.stdout, result.returncode)",
            "5. 超时控制：subprocess.run(['sleep', '10'], timeout=5)",
            "6. shell 命令：subprocess.run('ls | grep py', shell=True, capture_output=True)",
        ],
        selfCheck: [
            "subprocess.run() 返回什么类型的对象？",
            "capture_output=True 有什么效果？",
            "shell=True 有什么安全风险？",
            "如何让命令失败时抛出异常？",
            "Popen 和 run() 有什么区别？",
            "如何设置命令超时？",
        ],
        extensions: [
            "学习 Popen 的高级用法",
            "了解 shlex 模块安全分割命令",
            "探索异步子进程 asyncio.subprocess",
            "学习进程间通信方式",
        ],
        sourceUrls: [
            "https://docs.python.org/3/library/subprocess.html",
            "https://docs.python.org/3/library/subprocess.html#subprocess.run",
            "https://docs.python.org/3/library/subprocess.html#security-considerations",
        ],
    },
    "py-w17-3": {
        lessonId: "py-w17-3",
        background: [
            "【argparse 模块】创建用户友好的命令行接口。自动解析参数、生成帮助信息、验证输入。",
            "【ArgumentParser】主类，创建解析器实例。可设置 prog、description、epilog 等属性。",
            "【add_argument()】定义参数规格。位置参数无前缀，可选参数以 - 或 -- 开头。",
            "【parse_args()】解析命令行参数，返回 Namespace 对象。属性对应参数名。",
            "【子命令】add_subparsers() 创建子命令解析器，如 git commit、git push 模式。",
        ],
        keyDifficulties: [
            "【位置 vs 可选参数】位置参数按顺序必须提供，可选参数通过 -flag 或 --option 指定。",
            "【action 参数】store（默认）、store_true/false（布尔标志）、append（多值）、count（计数）。",
            "【nargs 参数】? 零或一个、* 零或多个、+ 一或多个、整数表示固定数量。",
            "【type 参数】指定类型转换函数，如 int、float 或自定义函数。",
        ],
        handsOnPath: [
            "1. 创建解析器：import argparse; parser = argparse.ArgumentParser(description='My tool')",
            "2. 位置参数：parser.add_argument('filename')",
            "3. 可选参数：parser.add_argument('-v', '--verbose', action='store_true')",
            "4. 带值选项：parser.add_argument('-n', '--number', type=int, default=1)",
            "5. 解析参数：args = parser.parse_args(); print(args.filename, args.verbose)",
            "6. 子命令：subparsers = parser.add_subparsers(dest='command')",
        ],
        selfCheck: [
            "如何创建 ArgumentParser？",
            "位置参数和可选参数有什么区别？",
            "action='store_true' 的效果是什么？",
            "如何指定参数的类型？",
            "nargs='+' 表示什么？",
            "如何创建子命令？",
        ],
        extensions: [
            "学习 click 库的装饰器风格 CLI",
            "了解 typer 基于类型提示的 CLI",
            "探索互斥参数组",
            "学习自定义 Action 类",
        ],
        sourceUrls: [
            "https://docs.python.org/3/library/argparse.html",
            "https://docs.python.org/3/howto/argparse.html",
            "https://docs.python.org/3/library/argparse.html#sub-commands",
        ],
    },
    "py-w17-4": {
        lessonId: "py-w17-4",
        background: [
            "【logging 模块】灵活的日志记录系统。支持多种输出目标、日志级别、格式化和过滤。",
            "【日志级别】DEBUG(10) < INFO(20) < WARNING(30) < ERROR(40) < CRITICAL(50)。默认级别是 WARNING。",
            "【basicConfig()】快速配置日志。设置文件、格式、级别等。只有首次调用有效（除非 force=True）。",
            "【Logger 对象】logging.getLogger(__name__) 获取 logger。支持层级结构，消息向上传递。",
            "【Handler 和 Formatter】Handler 控制输出目标（文件、控制台），Formatter 控制输出格式。",
        ],
        keyDifficulties: [
            "【logger 层级】用点号分隔表示层级（如 myapp.db）。消息会向上传递给父 logger（propagate=True）。",
            "【logger vs root】logging.info() 使用 root logger，logging.getLogger().info() 使用指定 logger。",
            "【线程安全】logging 模块是线程安全的，但不能在信号处理器中使用。",
            "【exception()】在 except 块中使用，自动添加异常堆栈信息。",
        ],
        handsOnPath: [
            "1. 基本配置：import logging; logging.basicConfig(level=logging.INFO)",
            "2. 记录日志：logging.info('Application started')",
            "3. 获取 logger：logger = logging.getLogger(__name__)",
            "4. 带格式：logging.basicConfig(format='%(asctime)s - %(levelname)s - %(message)s')",
            "5. 写入文件：logging.basicConfig(filename='app.log', level=logging.DEBUG)",
            "6. 异常日志：try: ...; except: logging.exception('Error occurred')",
        ],
        selfCheck: [
            "默认日志级别是什么？",
            "如何将日志输出到文件？",
            "logging.getLogger(__name__) 有什么好处？",
            "Handler 和 Formatter 的区别是什么？",
            "propagate 属性的作用是什么？",
            "exception() 方法有什么特殊之处？",
        ],
        extensions: [
            "学习 logging.handlers 的各种 Handler",
            "了解 dictConfig 配置方式",
            "探索 structlog 结构化日志",
            "学习日志轮转和归档",
        ],
        sourceUrls: [
            "https://docs.python.org/3/library/logging.html",
            "https://docs.python.org/3/howto/logging.html",
            "https://docs.python.org/3/library/logging.handlers.html",
        ],
    },
}

export const week17Quizzes: Record<string, QuizQuestion[]> = {
    "py-w17-1": [
        {
            id: "py-w17-1-q1",
            question: "os.environ 是什么类型的对象？",
            options: [
                "列表",
                "字典",
                "元组",
                "集合",
            ],
            answer: 1,
            rationale: "文档说明：os.environ 是一个字典对象，映射环境变量名到值。",
        },
        {
            id: "py-w17-1-q2",
            question: "sys.argv[0] 包含什么？",
            options: [
                "第一个命令行参数",
                "脚本名称",
                "Python 版本",
                "当前目录",
            ],
            answer: 1,
            rationale: "文档说明：sys.argv[0] 是脚本名称，sys.argv[1:] 是传递给脚本的参数。",
        },
        {
            id: "py-w17-1-q3",
            question: "os.makedirs('a/b/c', exist_ok=True) 的作用是什么？",
            options: [
                "创建单个目录",
                "递归创建目录，已存在不报错",
                "删除目录",
                "列出目录内容",
            ],
            answer: 1,
            rationale: "文档说明：makedirs 递归创建所有中间目录，exist_ok=True 使已存在时不抛出异常。",
        },
        {
            id: "py-w17-1-q4",
            question: "sys.path 的作用是什么？",
            options: [
                "当前工作目录",
                "Python 可执行文件路径",
                "模块搜索路径列表",
                "环境变量 PATH",
            ],
            answer: 2,
            rationale: "文档说明：sys.path 是 Python 查找模块时搜索的目录列表。",
        },
        {
            id: "py-w17-1-q5",
            question: "os.scandir() 相比 os.listdir() 有什么优势？",
            options: [
                "更简单",
                "返回 DirEntry 对象，可获取文件属性，性能更好",
                "支持递归",
                "支持通配符",
            ],
            answer: 1,
            rationale: "文档说明：scandir() 返回 DirEntry 迭代器，可以高效获取文件类型等属性。",
        },
        {
            id: "py-w17-1-q6",
            question: "sys.exit(1) 表示什么？",
            options: [
                "成功退出",
                "错误退出",
                "重启程序",
                "暂停程序",
            ],
            answer: 1,
            rationale: "文档说明：非零退出码表示错误，0 表示成功。",
        },
        {
            id: "py-w17-1-q7",
            question: "os.getenv('KEY', 'default') 当 KEY 不存在时返回什么？",
            options: [
                "None",
                "'default'",
                "抛出 KeyError",
                "空字符串",
            ],
            answer: 1,
            rationale: "文档说明：getenv 的第二个参数是默认值，键不存在时返回该值。",
        },
        {
            id: "py-w17-1-q8",
            question: "sys.platform 在 Linux 上返回什么？",
            options: [
                "'linux'",
                "'unix'",
                "'posix'",
                "'gnu'",
            ],
            answer: 0,
            rationale: "文档说明：sys.platform 在 Linux 上返回 'linux'，Windows 上返回 'win32'。",
        },
        {
            id: "py-w17-1-q9",
            question: "os.getcwd() 返回什么？",
            options: [
                "用户主目录",
                "当前工作目录",
                "脚本所在目录",
                "Python 安装目录",
            ],
            answer: 1,
            rationale: "文档说明：os.getcwd() 返回当前工作目录的路径字符串。",
        },
        {
            id: "py-w17-1-q10",
            question: "sys.version_info 是什么类型？",
            options: [
                "字符串",
                "命名元组",
                "字典",
                "整数",
            ],
            answer: 1,
            rationale: "文档说明：sys.version_info 是命名元组，包含 major、minor、micro 等属性。",
        },
        {
            id: "py-w17-1-q11",
            question: "os.remove() 和 os.rmdir() 的区别是什么？",
            options: [
                "没有区别",
                "remove 删除文件，rmdir 删除空目录",
                "remove 删除目录，rmdir 删除文件",
                "rmdir 递归删除",
            ],
            answer: 1,
            rationale: "文档说明：os.remove() 删除文件，os.rmdir() 删除空目录。",
        },
        {
            id: "py-w17-1-q12",
            question: "sys.stdout 是什么？",
            options: [
                "标准输入流",
                "标准输出流",
                "标准错误流",
                "文件对象",
            ],
            answer: 1,
            rationale: "文档说明：sys.stdout 是标准输出流，print() 默认写入这个流。",
        },
    ],
    "py-w17-2": [
        {
            id: "py-w17-2-q1",
            question: "subprocess.run() 返回什么类型的对象？",
            options: [
                "字符串",
                "CompletedProcess",
                "整数",
                "布尔值",
            ],
            answer: 1,
            rationale: "文档说明：run() 返回 CompletedProcess 对象，包含 args、returncode、stdout、stderr。",
        },
        {
            id: "py-w17-2-q2",
            question: "capture_output=True 的效果是什么？",
            options: [
                "打印输出",
                "将 stdout 和 stderr 设为 PIPE 以捕获",
                "保存到文件",
                "丢弃输出",
            ],
            answer: 1,
            rationale: "文档说明：capture_output=True 等同于设置 stdout=PIPE 和 stderr=PIPE。",
        },
        {
            id: "py-w17-2-q3",
            question: "shell=True 有什么安全风险？",
            options: [
                "性能下降",
                "Shell 注入攻击",
                "内存泄漏",
                "没有风险",
            ],
            answer: 1,
            rationale: "文档警告：shell=True 处理不信任的输入时可能导致 shell 注入攻击。",
        },
        {
            id: "py-w17-2-q4",
            question: "check=True 时非零返回码会怎样？",
            options: [
                "返回 None",
                "抛出 CalledProcessError",
                "打印警告",
                "忽略",
            ],
            answer: 1,
            rationale: "文档说明：check=True 时，非零返回码会抛出 CalledProcessError 异常。",
        },
        {
            id: "py-w17-2-q5",
            question: "text=True 参数的作用是什么？",
            options: [
                "启用 Unicode",
                "以文本模式打开流，返回字符串而非字节",
                "启用文本换行",
                "格式化输出",
            ],
            answer: 1,
            rationale: "文档说明：text=True 使 stdin/stdout/stderr 以文本模式工作，返回字符串。",
        },
        {
            id: "py-w17-2-q6",
            question: "subprocess.PIPE 的作用是什么？",
            options: [
                "丢弃输出",
                "创建管道以捕获或发送数据",
                "重定向到文件",
                "继承父进程的流",
            ],
            answer: 1,
            rationale: "文档说明：PIPE 创建新的管道，用于捕获输出或发送输入。",
        },
        {
            id: "py-w17-2-q7",
            question: "如何安全地处理 shell 命令中的用户输入？",
            options: [
                "直接拼接",
                "使用 shlex.quote() 或避免 shell=True",
                "base64 编码",
                "忽略特殊字符",
            ],
            answer: 1,
            rationale: "文档建议：使用 shlex.quote() 转义或避免 shell=True 使用列表形式。",
        },
        {
            id: "py-w17-2-q8",
            question: "Popen.communicate() 的作用是什么？",
            options: [
                "启动进程",
                "发送输入并读取输出，等待进程结束",
                "终止进程",
                "检查状态",
            ],
            answer: 1,
            rationale: "文档说明：communicate() 发送输入到 stdin，读取 stdout/stderr，等待进程结束。",
        },
        {
            id: "py-w17-2-q9",
            question: "timeout 参数超时会抛出什么异常？",
            options: [
                "TimeoutError",
                "TimeoutExpired",
                "CalledProcessError",
                "OSError",
            ],
            answer: 1,
            rationale: "文档说明：超过 timeout 时间会抛出 subprocess.TimeoutExpired 异常。",
        },
        {
            id: "py-w17-2-q10",
            question: "subprocess.DEVNULL 的作用是什么？",
            options: [
                "继承父进程流",
                "丢弃输出",
                "创建管道",
                "重定向到文件",
            ],
            answer: 1,
            rationale: "文档说明：DEVNULL 用于丢弃输出，类似重定向到 /dev/null。",
        },
        {
            id: "py-w17-2-q11",
            question: "CompletedProcess.returncode 为 0 表示什么？",
            options: [
                "失败",
                "成功",
                "超时",
                "未知",
            ],
            answer: 1,
            rationale: "惯例：returncode 为 0 表示命令成功执行，非 0 表示错误。",
        },
        {
            id: "py-w17-2-q12",
            question: "subprocess 模块替代了哪些旧函数？",
            options: [
                "print() 和 input()",
                "os.system() 和 os.spawn*()",
                "open() 和 close()",
                "read() 和 write()",
            ],
            answer: 1,
            rationale: "文档说明：subprocess 替代 os.system()、os.spawn*() 等旧的进程创建函数。",
        },
    ],
    "py-w17-3": [
        {
            id: "py-w17-3-q1",
            question: "ArgumentParser 的 description 参数用于什么？",
            options: [
                "程序名称",
                "在帮助信息中显示的程序描述",
                "版本号",
                "作者信息",
            ],
            answer: 1,
            rationale: "文档说明：description 参数设置在帮助信息中显示的程序描述。",
        },
        {
            id: "py-w17-3-q2",
            question: "位置参数和可选参数的区别是什么？",
            options: [
                "没有区别",
                "位置参数无前缀且必需，可选参数以 -/-- 开头",
                "位置参数可选，可选参数必需",
                "语法不同",
            ],
            answer: 1,
            rationale: "文档说明：位置参数按顺序提供，可选参数通过 -flag 或 --option 指定。",
        },
        {
            id: "py-w17-3-q3",
            question: "action='store_true' 的效果是什么？",
            options: [
                "存储字符串 'true'",
                "参数存在时存储 True，否则存储 False",
                "存储整数 1",
                "总是存储 True",
            ],
            answer: 1,
            rationale: "文档说明：store_true 在参数出现时存储 True，不出现时存储 False（默认值）。",
        },
        {
            id: "py-w17-3-q4",
            question: "nargs='+' 表示什么？",
            options: [
                "可选参数",
                "一个或多个参数值",
                "零个或多个",
                "恰好一个",
            ],
            answer: 1,
            rationale: "文档说明：nargs='+' 要求一个或多个参数值，存储为列表。",
        },
        {
            id: "py-w17-3-q5",
            question: "parse_args() 返回什么类型的对象？",
            options: [
                "字典",
                "Namespace",
                "列表",
                "元组",
            ],
            answer: 1,
            rationale: "文档说明：parse_args() 返回 Namespace 对象，参数作为属性访问。",
        },
        {
            id: "py-w17-3-q6",
            question: "如何指定参数的类型转换？",
            options: [
                "cast='int'",
                "type=int",
                "dtype=int",
                "convert=int",
            ],
            answer: 1,
            rationale: "文档说明：type 参数指定类型转换函数，如 int、float 或自定义函数。",
        },
        {
            id: "py-w17-3-q7",
            question: "choices 参数的作用是什么？",
            options: [
                "设置默认值",
                "限制参数值必须在指定列表中",
                "提供选项说明",
                "启用多选",
            ],
            answer: 1,
            rationale: "文档说明：choices 参数限制参数值必须在指定的选项列表中。",
        },
        {
            id: "py-w17-3-q8",
            question: "action='count' 的用途是什么？",
            options: [
                "计算字符数",
                "计数参数出现的次数（如 -vvv）",
                "计算文件数",
                "统计行数",
            ],
            answer: 1,
            rationale: "文档说明：count 动作计数参数出现的次数，常用于 -v -vv -vvv 详细级别。",
        },
        {
            id: "py-w17-3-q9",
            question: "如何创建子命令？",
            options: [
                "add_subparser()",
                "add_subparsers() 然后 add_parser()",
                "subcommand()",
                "add_command()",
            ],
            answer: 1,
            rationale: "文档说明：先用 add_subparsers() 创建子解析器容器，再用 add_parser() 添加子命令。",
        },
        {
            id: "py-w17-3-q10",
            question: "required=True 用于什么类型的参数？",
            options: [
                "位置参数",
                "可选参数（使其变为必需）",
                "所有参数",
                "子命令",
            ],
            answer: 1,
            rationale: "文档说明：required=True 使可选参数变为必需，位置参数默认就是必需的。",
        },
        {
            id: "py-w17-3-q11",
            question: "metavar 参数的作用是什么？",
            options: [
                "设置属性名",
                "在帮助信息中显示的参数名称",
                "设置默认值",
                "启用元数据",
            ],
            answer: 1,
            rationale: "文档说明：metavar 设置在帮助信息中显示的参数占位符名称。",
        },
        {
            id: "py-w17-3-q12",
            question: "nargs='?' 表示什么？",
            options: [
                "必需参数",
                "零个或一个参数值",
                "任意数量",
                "恰好两个",
            ],
            answer: 1,
            rationale: "文档说明：nargs='?' 表示零个或一个参数值，可选。",
        },
    ],
    "py-w17-4": [
        {
            id: "py-w17-4-q1",
            question: "默认的日志级别是什么？",
            options: [
                "DEBUG",
                "INFO",
                "WARNING",
                "ERROR",
            ],
            answer: 2,
            rationale: "文档说明：默认日志级别是 WARNING（30），低于此级别的日志不会显示。",
        },
        {
            id: "py-w17-4-q2",
            question: "如何将日志输出到文件？",
            options: [
                "logging.file('app.log')",
                "logging.basicConfig(filename='app.log')",
                "logging.output('app.log')",
                "logging.save('app.log')",
            ],
            answer: 1,
            rationale: "文档说明：basicConfig(filename='app.log') 配置日志输出到文件。",
        },
        {
            id: "py-w17-4-q3",
            question: "logging.getLogger(__name__) 有什么好处？",
            options: [
                "更快",
                "创建与模块名对应的 logger，便于追踪日志来源",
                "自动配置",
                "不需要导入",
            ],
            answer: 1,
            rationale: "文档推荐：使用 __name__ 创建 logger，日志会显示模块名，便于调试。",
        },
        {
            id: "py-w17-4-q4",
            question: "Handler 和 Formatter 的区别是什么？",
            options: [
                "没有区别",
                "Handler 控制输出目标，Formatter 控制输出格式",
                "Handler 控制格式，Formatter 控制目标",
                "Handler 是旧版本",
            ],
            answer: 1,
            rationale: "文档说明：Handler 决定日志发送到哪里，Formatter 决定日志的格式。",
        },
        {
            id: "py-w17-4-q5",
            question: "propagate 属性的作用是什么？",
            options: [
                "传播异常",
                "是否将日志传递给父 logger",
                "传播配置",
                "传播级别",
            ],
            answer: 1,
            rationale: "文档说明：propagate=True（默认）时，日志消息会向上传递给父 logger。",
        },
        {
            id: "py-w17-4-q6",
            question: "logging.exception() 有什么特殊之处？",
            options: [
                "只能在 try 块中用",
                "自动添加异常堆栈信息",
                "抛出异常",
                "阻止异常",
            ],
            answer: 1,
            rationale: "文档说明：exception() 在 except 块中使用，自动添加当前异常的堆栈信息。",
        },
        {
            id: "py-w17-4-q7",
            question: "日志级别 DEBUG 的数值是多少？",
            options: [
                "0",
                "10",
                "20",
                "30",
            ],
            answer: 1,
            rationale: "文档说明：DEBUG=10, INFO=20, WARNING=30, ERROR=40, CRITICAL=50。",
        },
        {
            id: "py-w17-4-q8",
            question: "%(asctime)s 格式代码表示什么？",
            options: [
                "日志级别",
                "时间戳",
                "logger 名称",
                "消息内容",
            ],
            answer: 1,
            rationale: "文档说明：%(asctime)s 在日志中插入时间戳。",
        },
        {
            id: "py-w17-4-q9",
            question: "basicConfig() 的 force=True 参数有什么作用？",
            options: [
                "强制写入",
                "强制重新配置，替换已有的 handlers",
                "强制级别",
                "强制格式",
            ],
            answer: 1,
            rationale: "文档说明：force=True 移除已有的 handlers 并重新配置，默认只有首次调用有效。",
        },
        {
            id: "py-w17-4-q10",
            question: "StreamHandler 输出到哪里？",
            options: [
                "文件",
                "流（默认 sys.stderr）",
                "网络",
                "数据库",
            ],
            answer: 1,
            rationale: "文档说明：StreamHandler 输出到流对象，默认是 sys.stderr。",
        },
        {
            id: "py-w17-4-q11",
            question: "logger 名称用什么分隔表示层级？",
            options: [
                "斜杠 /",
                "点号 .",
                "下划线 _",
                "冒号 :",
            ],
            answer: 1,
            rationale: "文档说明：logger 名称用点号分隔表示层级，如 'myapp.db'。",
        },
        {
            id: "py-w17-4-q12",
            question: "logging 模块是否线程安全？",
            options: [
                "不是",
                "是",
                "只有部分函数是",
                "需要额外配置",
            ],
            answer: 1,
            rationale: "文档说明：logging 模块本身是线程安全的，使用锁序列化对共享数据的访问。",
        },
    ],
}
