import type { LessonGuide } from "../types"
import type { QuizQuestion } from "@/lib/types"

export const week23Guides: Record<string, LessonGuide> = {
    "py-w23-1": {
        lessonId: "py-w23-1",
        background: [
            "【NumPy ndarray】NumPy 核心是 ndarray（n 维数组），同类型元素的多维容器。属性：ndim 维度数，shape 形状，dtype 数据类型。",
            "【创建数组】np.array([1,2,3]) 从列表创建；np.zeros()/ones()/empty() 创建填充数组；np.arange()/linspace() 创建序列。",
            "【向量化运算】数组支持向量化运算，自动对所有元素操作：a + b、a * 2、np.sin(a) 等，无需循环。",
            "【索引切片】支持多维索引 a[0, 1]、切片 a[:, 1:3]、布尔索引 a[a > 0]、花式索引 a[[1, 3, 5]]。",
            "【广播机制】不同形状数组运算时自动扩展匹配。规则：较小数组沿缺失维度扩展。",
        ],
        keyDifficulties: [
            "【视图 vs 副本】切片返回视图（共享数据），修改会影响原数组。copy() 创建独立副本。",
            "【axis 参数】聚合函数的 axis 参数：axis=0 沿行方向（压缩行），axis=1 沿列方向（压缩列）。",
            "【reshape vs resize】reshape() 返回新数组，resize() 原地修改。-1 自动推断维度大小。",
            "【矩阵乘法】* 是元素乘法，@ 或 dot() 是矩阵乘法。注意区分！",
        ],
        handsOnPath: [
            "1. 导入：import numpy as np",
            "2. 创建数组：a = np.array([1, 2, 3, 4]); b = np.zeros((3, 4))",
            "3. 基本运算：c = a * 2; d = np.sin(a)",
            "4. 索引切片：a[1:3]; b[:, 0]; b[b > 0]",
            "5. 聚合运算：a.sum(); a.mean(); a.max(axis=0)",
            "6. 变形：a.reshape(2, 2); np.vstack((a, b))",
        ],
        selfCheck: [
            "ndarray 的 shape 和 ndim 属性有什么区别？",
            "如何创建全零或全一数组？",
            "切片返回的是视图还是副本？",
            "axis=0 和 axis=1 在 sum() 中有什么区别？",
            "如何进行矩阵乘法？",
            "广播机制的规则是什么？",
        ],
        extensions: [
            "学习 NumPy 随机数生成",
            "了解结构化数组",
            "探索内存布局（C 顺序 vs F 顺序）",
            "学习 NumPy 文件 I/O",
        ],
        sourceUrls: [
            "https://numpy.org/doc/stable/",
            "https://numpy.org/doc/stable/user/quickstart.html",
            "https://numpy.org/doc/stable/user/basics.html",
        ],
    },
    "py-w23-2": {
        lessonId: "py-w23-2",
        background: [
            "【DataFrame】二维表格数据结构，每列可以是不同类型。类似 Excel 表格或 SQL 表。",
            "【Series】一维带标签数组。DataFrame 的每列是一个 Series。",
            "【创建 DataFrame】pd.DataFrame(dict) 从字典创建；pd.read_csv() 读取 CSV 文件。",
            "【索引选择】df['col'] 选择列；df.loc[label] 按标签选择；df.iloc[pos] 按位置选择。",
            "【基本操作】df.head()/tail() 查看数据；df.describe() 统计摘要；df.sort_values() 排序。",
        ],
        keyDifficulties: [
            "【loc vs iloc】loc 基于标签（包含端点），iloc 基于位置（不包含端点）。推荐使用这两个方法。",
            "【at vs iat】单个标量值的快速访问：at 按标签，iat 按位置。",
            "【链式索引警告】避免 df['A']['B']，使用 df.loc[:, 'A'] 或 df[['A', 'B']]。",
            "【dtype 按列】不同于 NumPy，DataFrame 每列可以有不同的数据类型。",
        ],
        handsOnPath: [
            "1. 导入：import pandas as pd",
            "2. 创建：df = pd.DataFrame({'A': [1,2,3], 'B': ['x','y','z']})",
            "3. 读取：df = pd.read_csv('data.csv')",
            "4. 查看：df.head(); df.info(); df.describe()",
            "5. 选择：df['A']; df.loc[0, 'A']; df.iloc[0:2, 1:3]",
            "6. 筛选：df[df['A'] > 1]; df[df['B'].isin(['x', 'y'])]",
        ],
        selfCheck: [
            "DataFrame 和 Series 的区别是什么？",
            "loc 和 iloc 的区别是什么？",
            "如何读取 CSV 文件？",
            "如何按条件筛选行？",
            "df['A'] 和 df.loc[:, 'A'] 有什么区别？",
            "如何查看 DataFrame 的基本信息？",
        ],
        extensions: [
            "学习 MultiIndex 多级索引",
            "了解 Categorical 类型",
            "探索 query() 方法查询",
            "学习 to_csv()/to_excel() 导出",
        ],
        sourceUrls: [
            "https://pandas.pydata.org/docs/",
            "https://pandas.pydata.org/docs/user_guide/10min.html",
            "https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html",
        ],
    },
    "py-w23-3": {
        lessonId: "py-w23-3",
        background: [
            "【缺失值表示】NaN（Not a Number）表示缺失的浮点数；NaT 表示缺失的时间；pd.NA 是新的统一缺失值。",
            "【检测缺失值】isna()/isnull() 检测缺失值，返回布尔数组；notna()/notnull() 检测非缺失值。",
            "【删除缺失值】dropna() 删除含缺失值的行或列。axis=0 删除行，axis=1 删除列。",
            "【填充缺失值】fillna(value) 用指定值填充；ffill()/bfill() 前向/后向填充。",
            "【处理重复值】duplicated() 检测重复行；drop_duplicates() 删除重复行。",
        ],
        keyDifficulties: [
            "【NaN 比较陷阱】np.nan == np.nan 返回 False！必须用 isna() 检测缺失值。",
            "【inplace 参数】很多方法支持 inplace=True 原地修改，但推荐赋值方式更清晰。",
            "【fillna 与 interpolate】fillna 用固定值填充，interpolate() 使用插值方法填充。",
            "【类型转换】缺失值可能导致整数列变为浮点型。使用 Int64（大写）支持缺失值的整数。",
        ],
        handsOnPath: [
            "1. 检测缺失：df.isna(); df.isna().sum()",
            "2. 删除缺失：df.dropna(); df.dropna(subset=['A'])",
            "3. 填充缺失：df.fillna(0); df['A'].fillna(df['A'].mean())",
            "4. 前向填充：df.ffill(); df.bfill()",
            "5. 检测重复：df.duplicated(); df.duplicated(subset=['A'])",
            "6. 删除重复：df.drop_duplicates(); df.drop_duplicates(keep='last')",
        ],
        selfCheck: [
            "为什么不能用 == 检测 NaN？",
            "dropna() 默认删除的是行还是列？",
            "ffill 和 bfill 的区别是什么？",
            "如何用列的均值填充缺失值？",
            "duplicated() 的 keep 参数有什么作用？",
            "如何只检查特定列的重复值？",
        ],
        extensions: [
            "学习 interpolate() 插值方法",
            "了解 pd.NA 新缺失值类型",
            "探索 replace() 值替换",
            "学习可空类型（Int64、boolean）",
        ],
        sourceUrls: [
            "https://pandas.pydata.org/docs/user_guide/missing_data.html",
            "https://pandas.pydata.org/docs/user_guide/basics.html#essential-basic-functionality",
            "https://pandas.pydata.org/docs/user_guide/basics.html#dtypes",
        ],
    },
    "py-w23-4": {
        lessonId: "py-w23-4",
        background: [
            "【GroupBy 操作】分组-应用-合并模式。groupby() 按列分组，然后应用聚合、转换或过滤函数。",
            "【聚合操作】sum()、mean()、count()、std() 等将每组数据汇总为单个值。",
            "【transform 方法】返回与原数据同形状的结果，常用于组内标准化、填充等。",
            "【pivot_table】创建数据透视表，类似 Excel。指定 values、index、columns 和 aggfunc。",
            "【merge/join】merge() 类似 SQL JOIN，合并两个 DataFrame；concat() 拼接 DataFrame。",
        ],
        keyDifficulties: [
            "【agg 方法】df.groupby('A').agg({'B': 'sum', 'C': 'mean'}) 对不同列应用不同聚合函数。",
            "【as_index 参数】groupby(..., as_index=False) 使分组键成为普通列而非索引。",
            "【多列分组】groupby(['A', 'B']) 按多列分组，结果有多级索引。",
            "【merge 类型】how='inner/left/right/outer' 控制合并方式，on 指定连接键。",
        ],
        handsOnPath: [
            "1. 分组聚合：df.groupby('A')['B'].sum()",
            "2. 多聚合：df.groupby('A').agg({'B': 'sum', 'C': 'mean'})",
            "3. 转换：df.groupby('A')['B'].transform('mean')",
            "4. 透视表：pd.pivot_table(df, values='C', index='A', columns='B', aggfunc='sum')",
            "5. 合并：pd.merge(df1, df2, on='key', how='left')",
            "6. 拼接：pd.concat([df1, df2], axis=0)",
        ],
        selfCheck: [
            "groupby 的分组-应用-合并模式是什么？",
            "agg 方法如何对不同列应用不同函数？",
            "transform 和 agg 的区别是什么？",
            "pivot_table 的主要参数是什么？",
            "merge 的 how 参数有哪些选项？",
            "concat 的 axis 参数有什么作用？",
        ],
        extensions: [
            "学习 crosstab 交叉表",
            "了解 melt/stack/unstack 重塑",
            "探索 rolling 滚动窗口操作",
            "学习 resample 时间重采样",
        ],
        sourceUrls: [
            "https://pandas.pydata.org/docs/user_guide/groupby.html",
            "https://pandas.pydata.org/docs/user_guide/reshaping.html",
            "https://pandas.pydata.org/docs/user_guide/merging.html",
        ],
    },
}

export const week23Quizzes: Record<string, QuizQuestion[]> = {
    "py-w23-1": [
        {
            id: "py-w23-1-q1",
            question: "ndarray.shape 返回什么？",
            options: [
                "数组的维度数",
                "数组各维度大小的元组",
                "数组的总元素数",
                "数据类型",
            ],
            answer: 1,
            rationale: "文档说明：shape 是各维度大小的元组，如 (3, 4) 表示 3 行 4 列。",
        },
        {
            id: "py-w23-1-q2",
            question: "如何创建全零数组？",
            options: [
                "np.zero((3, 4))",
                "np.zeros((3, 4))",
                "np.zeros(3, 4)",
                "np.array.zeros((3, 4))",
            ],
            answer: 1,
            rationale: "文档说明：np.zeros((shape)) 创建指定形状的全零数组。",
        },
        {
            id: "py-w23-1-q3",
            question: "数组切片返回的是什么？",
            options: [
                "副本",
                "视图（共享数据）",
                "新的独立数组",
                "元组",
            ],
            answer: 1,
            rationale: "文档说明：切片返回视图，与原数组共享数据。修改会影响原数组。",
        },
        {
            id: "py-w23-1-q4",
            question: "a.sum(axis=0) 在二维数组上做什么？",
            options: [
                "对每行求和",
                "对每列求和",
                "对所有元素求和",
                "返回最大值",
            ],
            answer: 1,
            rationale: "文档说明：axis=0 沿行方向操作，即对每列求和。",
        },
        {
            id: "py-w23-1-q5",
            question: "如何进行矩阵乘法？",
            options: [
                "A * B",
                "A @ B 或 A.dot(B)",
                "A + B",
                "np.multiply(A, B)",
            ],
            answer: 1,
            rationale: "文档说明：@ 运算符（Python 3.5+）或 dot() 方法进行矩阵乘法。",
        },
        {
            id: "py-w23-1-q6",
            question: "np.arange(0, 10, 2) 生成什么？",
            options: [
                "[0, 2, 4, 6, 8, 10]",
                "[0, 2, 4, 6, 8]",
                "[2, 4, 6, 8, 10]",
                "[0, 1, 2, 3, 4]",
            ],
            answer: 1,
            rationale: "文档说明：arange(start, stop, step) 不包含 stop，类似 range()。",
        },
        {
            id: "py-w23-1-q7",
            question: "a.reshape(2, -1) 中 -1 表示什么？",
            options: [
                "删除该维度",
                "自动推断该维度大小",
                "反转数组",
                "填充零",
            ],
            answer: 1,
            rationale: "文档说明：-1 表示让 NumPy 自动计算该维度的大小。",
        },
        {
            id: "py-w23-1-q8",
            question: "如何获取数组的独立副本？",
            options: [
                "a[:]",
                "a.copy()",
                "a.view()",
                "np.array(a)",
            ],
            answer: 1,
            rationale: "文档说明：copy() 创建完全独立的数组副本，不共享数据。",
        },
        {
            id: "py-w23-1-q9",
            question: "布尔索引 a[a > 5] 返回什么？",
            options: [
                "布尔数组",
                "满足条件的元素组成的一维数组",
                "True 或 False",
                "索引列表",
            ],
            answer: 1,
            rationale: "文档说明：布尔索引返回满足条件的所有元素组成的一维数组。",
        },
        {
            id: "py-w23-1-q10",
            question: "np.vstack((a, b)) 做什么？",
            options: [
                "水平堆叠",
                "垂直堆叠",
                "对角堆叠",
                "按深度堆叠",
            ],
            answer: 1,
            rationale: "文档说明：vstack 垂直（行方向）堆叠数组，hstack 水平堆叠。",
        },
        {
            id: "py-w23-1-q11",
            question: "广播机制的基本规则是什么？",
            options: [
                "数组必须形状完全相同",
                "较小数组沿缺失维度扩展以匹配较大数组",
                "自动转换数据类型",
                "自动调整内存布局",
            ],
            answer: 1,
            rationale: "文档说明：广播时较小数组的形状沿维度为 1 或缺失的维度扩展。",
        },
        {
            id: "py-w23-1-q12",
            question: "np.linspace(0, 1, 5) 生成什么？",
            options: [
                "[0, 0.2, 0.4, 0.6, 0.8]",
                "[0, 0.25, 0.5, 0.75, 1]",
                "[0, 1, 2, 3, 4]",
                "[0.2, 0.4, 0.6, 0.8, 1]",
            ],
            answer: 1,
            rationale: "文档说明：linspace 生成包含端点的等间距数列，共 5 个值。",
        },
    ],
    "py-w23-2": [
        {
            id: "py-w23-2-q1",
            question: "DataFrame 和 Series 的区别是什么？",
            options: [
                "DataFrame 是一维的",
                "DataFrame 是二维表格，Series 是一维带标签数组",
                "Series 可以包含多种类型",
                "没有区别",
            ],
            answer: 1,
            rationale: "文档说明：DataFrame 是二维表格，Series 是一维数组。",
        },
        {
            id: "py-w23-2-q2",
            question: "loc 和 iloc 的区别是什么？",
            options: [
                "loc 更快",
                "loc 基于标签，iloc 基于位置",
                "iloc 支持切片",
                "没有区别",
            ],
            answer: 1,
            rationale: "文档说明：loc 用标签选择，iloc 用整数位置选择。",
        },
        {
            id: "py-w23-2-q3",
            question: "如何读取 CSV 文件？",
            options: [
                "pd.load_csv('file.csv')",
                "pd.read_csv('file.csv')",
                "pd.open_csv('file.csv')",
                "pd.csv('file.csv')",
            ],
            answer: 1,
            rationale: "文档说明：pd.read_csv() 读取 CSV 文件到 DataFrame。",
        },
        {
            id: "py-w23-2-q4",
            question: "df.loc[0:2, 'A'] 选择什么？",
            options: [
                "标签 0 和 1 的行（不含 2）",
                "标签 0、1、2 的行的 A 列（含端点）",
                "前两行",
                "A 列的前两个元素",
            ],
            answer: 1,
            rationale: "文档说明：loc 的切片包含两个端点，与 Python 切片不同。",
        },
        {
            id: "py-w23-2-q5",
            question: "df.iloc[0:2, 0] 选择什么？",
            options: [
                "前两行的第一列（不含索引 2）",
                "标签 0、1、2 的行",
                "第一列所有行",
                "前三行",
            ],
            answer: 0,
            rationale: "文档说明：iloc 的切片不包含端点，与 Python 切片一致。",
        },
        {
            id: "py-w23-2-q6",
            question: "如何按条件筛选行？",
            options: [
                "df.filter(df['A'] > 1)",
                "df[df['A'] > 1]",
                "df.where('A' > 1)",
                "df.select(df['A'] > 1)",
            ],
            answer: 1,
            rationale: "文档说明：使用布尔索引 df[condition] 筛选满足条件的行。",
        },
        {
            id: "py-w23-2-q7",
            question: "df.describe() 返回什么？",
            options: [
                "数据类型信息",
                "数值列的统计摘要",
                "前 5 行",
                "列名列表",
            ],
            answer: 1,
            rationale: "文档说明：describe() 返回计数、均值、标准差、最小值、分位数等统计摘要。",
        },
        {
            id: "py-w23-2-q8",
            question: "df.head(10) 返回什么？",
            options: [
                "最后 10 行",
                "前 10 行",
                "10 个列",
                "随机 10 行",
            ],
            answer: 1,
            rationale: "文档说明：head(n) 返回前 n 行，默认为 5。",
        },
        {
            id: "py-w23-2-q9",
            question: "at 和 iat 的用途是什么？",
            options: [
                "选择多行",
                "快速访问单个标量值",
                "添加新列",
                "删除行",
            ],
            answer: 1,
            rationale: "文档说明：at（标签）和 iat（位置）用于快速获取单个值。",
        },
        {
            id: "py-w23-2-q10",
            question: "df.sort_values(by='A') 做什么？",
            options: [
                "按索引排序",
                "按 A 列的值排序",
                "按列名排序",
                "反转数据",
            ],
            answer: 1,
            rationale: "文档说明：sort_values(by=column) 按指定列排序。",
        },
        {
            id: "py-w23-2-q11",
            question: "df.info() 显示什么？",
            options: [
                "统计摘要",
                "列名、数据类型、非空值数量等信息",
                "前 5 行",
                "形状信息",
            ],
            answer: 1,
            rationale: "文档说明：info() 显示 DataFrame 的简洁摘要，包括列类型和内存使用。",
        },
        {
            id: "py-w23-2-q12",
            question: "df['A'].isin(['x', 'y']) 返回什么？",
            options: [
                "匹配的值",
                "布尔 Series",
                "行数",
                "索引列表",
            ],
            answer: 1,
            rationale: "文档说明：isin() 返回布尔 Series，表示值是否在给定列表中。",
        },
    ],
    "py-w23-3": [
        {
            id: "py-w23-3-q1",
            question: "为什么 np.nan == np.nan 返回 False？",
            options: [
                "这是一个 bug",
                "IEEE 754 标准规定 NaN 不等于任何值，包括自身",
                "需要使用 ===",
                "类型不匹配",
            ],
            answer: 1,
            rationale: "文档说明：NaN 的比较总是返回 False，必须用 isna() 检测。",
        },
        {
            id: "py-w23-3-q2",
            question: "如何检测缺失值？",
            options: [
                "df == np.nan",
                "df.isna() 或 pd.isna(df)",
                "df.is_null()",
                "df.missing()",
            ],
            answer: 1,
            rationale: "文档说明：isna()/isnull() 是检测缺失值的正确方法。",
        },
        {
            id: "py-w23-3-q3",
            question: "dropna() 默认删除什么？",
            options: [
                "含缺失值的列",
                "含缺失值的行",
                "所有缺失值",
                "什么都不删",
            ],
            answer: 1,
            rationale: "文档说明：dropna() 默认 axis=0，删除含缺失值的行。",
        },
        {
            id: "py-w23-3-q4",
            question: "ffill() 做什么？",
            options: [
                "用 0 填充",
                "用前一个有效值向前填充",
                "用后一个有效值向后填充",
                "用均值填充",
            ],
            answer: 1,
            rationale: "文档说明：ffill()（forward fill）用前一个有效值填充缺失值。",
        },
        {
            id: "py-w23-3-q5",
            question: "如何用列均值填充缺失值？",
            options: [
                "df.fillna(mean())",
                "df.fillna(df.mean())",
                "df.fill(df.mean())",
                "df.replace(np.nan, df.mean())",
            ],
            answer: 1,
            rationale: "文档说明：fillna(df.mean()) 用每列的均值填充该列的缺失值。",
        },
        {
            id: "py-w23-3-q6",
            question: "duplicated() 返回什么？",
            options: [
                "重复行的数量",
                "标记每行是否为重复的布尔 Series",
                "重复的值",
                "唯一值",
            ],
            answer: 1,
            rationale: "文档说明：duplicated() 返回布尔 Series，True 表示该行是重复的。",
        },
        {
            id: "py-w23-3-q7",
            question: "drop_duplicates(keep='last') 保留什么？",
            options: [
                "第一个出现的重复行",
                "最后一个出现的重复行",
                "所有重复行",
                "不保留任何重复行",
            ],
            answer: 1,
            rationale: "文档说明：keep='last' 保留最后出现的重复行，删除之前的。",
        },
        {
            id: "py-w23-3-q8",
            question: "pd.NA 是什么？",
            options: [
                "不可用的值",
                "Pandas 的统一缺失值标识",
                "空字符串",
                "零值",
            ],
            answer: 1,
            rationale: "文档说明：pd.NA 是 Pandas 引入的统一缺失值，支持更多数据类型。",
        },
        {
            id: "py-w23-3-q9",
            question: "如何只检查特定列的重复？",
            options: [
                "df.duplicated('A')",
                "df.duplicated(subset=['A', 'B'])",
                "df['A'].duplicated()",
                "df.dup(['A'])",
            ],
            answer: 1,
            rationale: "文档说明：subset 参数指定用于判断重复的列。",
        },
        {
            id: "py-w23-3-q10",
            question: "interpolate() 做什么？",
            options: [
                "删除缺失值",
                "用插值方法填充缺失值",
                "用 0 填充",
                "标记缺失值",
            ],
            answer: 1,
            rationale: "文档说明：interpolate() 使用数学插值方法估算并填充缺失值。",
        },
        {
            id: "py-w23-3-q11",
            question: "NaT 用于表示什么类型的缺失值？",
            options: [
                "整数",
                "日期时间",
                "字符串",
                "浮点数",
            ],
            answer: 1,
            rationale: "文档说明：NaT（Not a Time）是日期时间类型的缺失值。",
        },
        {
            id: "py-w23-3-q12",
            question: "如何删除 A 列含缺失值的行？",
            options: [
                "df.dropna('A')",
                "df.dropna(subset=['A'])",
                "df.drop(na='A')",
                "df[~df['A'].isna()]",
            ],
            answer: 1,
            rationale: "文档说明：dropna(subset=['A']) 只考虑 A 列的缺失值来删除行。",
        },
    ],
    "py-w23-4": [
        {
            id: "py-w23-4-q1",
            question: "groupby 操作遵循什么模式？",
            options: [
                "映射-归约",
                "分组-应用-合并",
                "过滤-排序-输出",
                "读取-处理-写入",
            ],
            answer: 1,
            rationale: "文档说明：GroupBy 实现 split-apply-combine（分组-应用-合并）模式。",
        },
        {
            id: "py-w23-4-q2",
            question: "df.groupby('A')['B'].sum() 做什么？",
            options: [
                "对 A 列求和",
                "按 A 分组后对每组的 B 列求和",
                "计算 A 和 B 的总和",
                "对所有列求和",
            ],
            answer: 1,
            rationale: "文档说明：按 A 列分组，然后计算每组中 B 列的总和。",
        },
        {
            id: "py-w23-4-q3",
            question: "agg 方法如何对不同列应用不同函数？",
            options: [
                "agg(['sum', 'mean'])",
                "agg({'B': 'sum', 'C': 'mean'})",
                "agg(B='sum', C='mean')",
                "agg(sum='B', mean='C')",
            ],
            answer: 1,
            rationale: "文档说明：字典形式 {'列名': '函数'} 可以对不同列应用不同聚合函数。",
        },
        {
            id: "py-w23-4-q4",
            question: "transform 和 agg 的主要区别是什么？",
            options: [
                "transform 更快",
                "transform 返回与原数据同形状的结果",
                "agg 支持更多函数",
                "没有区别",
            ],
            answer: 1,
            rationale: "文档说明：transform 保持原数据形状，agg 返回每组一行的汇总结果。",
        },
        {
            id: "py-w23-4-q5",
            question: "pd.merge(df1, df2, on='key', how='left') 做什么？",
            options: [
                "只保留两个 DataFrame 共有的键",
                "保留左边 DataFrame 的所有行",
                "保留右边 DataFrame 的所有行",
                "保留所有行",
            ],
            answer: 1,
            rationale: "文档说明：how='left' 左连接，保留左边 DataFrame 的所有行。",
        },
        {
            id: "py-w23-4-q6",
            question: "pivot_table 的 values 参数是什么？",
            options: [
                "行索引的列",
                "要聚合的值所在的列",
                "列标签的列",
                "排序依据",
            ],
            answer: 1,
            rationale: "文档说明：values 指定要聚合的数值列。",
        },
        {
            id: "py-w23-4-q7",
            question: "pd.concat([df1, df2], axis=0) 做什么？",
            options: [
                "水平拼接",
                "垂直拼接（行方向）",
                "按键合并",
                "交叉拼接",
            ],
            answer: 1,
            rationale: "文档说明：axis=0 沿行方向拼接，即垂直堆叠。",
        },
        {
            id: "py-w23-4-q8",
            question: "groupby(..., as_index=False) 的效果是什么？",
            options: [
                "不创建索引",
                "分组键成为普通列而非索引",
                "使用默认索引",
                "删除索引",
            ],
            answer: 1,
            rationale: "文档说明：as_index=False 使分组键成为结果的普通列。",
        },
        {
            id: "py-w23-4-q9",
            question: "如何用组均值填充缺失值？",
            options: [
                "df.fillna(df.groupby('A').mean())",
                "df['B'] = df.groupby('A')['B'].transform('mean')",
                "df.groupby('A').fillna('mean')",
                "df.groupby('A').fill('mean')",
            ],
            answer: 1,
            rationale: "文档说明：transform('mean') 返回每个元素对应的组均值，可用于填充。",
        },
        {
            id: "py-w23-4-q10",
            question: "merge 的 how='inner' 做什么？",
            options: [
                "保留左边所有行",
                "只保留两个 DataFrame 共有的键",
                "保留所有行",
                "保留右边所有行",
            ],
            answer: 1,
            rationale: "文档说明：how='inner' 内连接，只保留两边都有的键。",
        },
        {
            id: "py-w23-4-q11",
            question: "groupby 对象的 size() 和 count() 有什么区别？",
            options: [
                "没有区别",
                "size 包含 NaN，count 不包含",
                "count 更快",
                "size 返回 DataFrame",
            ],
            answer: 1,
            rationale: "文档说明：size() 计算组大小（含 NaN），count() 计算非空值数量。",
        },
        {
            id: "py-w23-4-q12",
            question: "如何按多列分组？",
            options: [
                "groupby('A', 'B')",
                "groupby(['A', 'B'])",
                "groupby(A, B)",
                "groupby({'A', 'B'})",
            ],
            answer: 1,
            rationale: "文档说明：传入列名列表 ['A', 'B'] 按多列分组。",
        },
    ],
}
