import type { LessonGuide } from "../types"
import type { QuizQuestion } from "@/lib/types"

export const week22Guides: Record<string, LessonGuide> = {
    "py-w22-1": {
        lessonId: "py-w22-1",
        background: [
            "【sqlite3 模块】Python 内置的 SQLite 数据库接口，遵循 DB-API 2.0 规范。无需安装，无需服务器。",
            "【连接创建】sqlite3.connect('database.db') 创建文件数据库；connect(':memory:') 创建内存数据库。",
            "【游标对象】cursor = con.cursor() 创建游标。execute() 执行 SQL，fetchone()/fetchall() 获取结果。",
            "【参数化查询】使用 ? 占位符防止 SQL 注入：execute('SELECT * FROM t WHERE id=?', (id,))。",
            "【事务控制】con.commit() 提交事务，con.rollback() 回滚。使用 with con: 自动管理事务。",
        ],
        keyDifficulties: [
            "【占位符样式】问号样式 (?, ?) 或命名样式 (:name, :value)。永远不要直接拼接 SQL！",
            "【row_factory】默认返回元组。con.row_factory = sqlite3.Row 支持按列名访问。",
            "【提交必要性】INSERT/UPDATE/DELETE 必须调用 commit() 才会持久化。",
            "【连接快捷方法】con.execute() 可以直接执行 SQL，无需显式创建游标。",
        ],
        handsOnPath: [
            "1. 连接数据库：import sqlite3; con = sqlite3.connect('test.db')",
            "2. 创建表：con.execute('CREATE TABLE users(id INTEGER PRIMARY KEY, name TEXT)')",
            "3. 插入数据：con.execute('INSERT INTO users VALUES(?, ?)', (1, 'Alice'))",
            "4. 提交事务：con.commit()",
            "5. 查询数据：for row in con.execute('SELECT * FROM users'): print(row)",
            "6. 关闭连接：con.close()",
        ],
        selfCheck: [
            "如何创建 SQLite 内存数据库？",
            "参数化查询有什么好处？",
            "fetchone() 和 fetchall() 的区别是什么？",
            "为什么需要调用 commit()？",
            "如何让查询结果支持按列名访问？",
            "使用 with con: 语句有什么好处？",
        ],
        extensions: [
            "学习 sqlite3.Row 的完整功能",
            "了解 executemany() 批量操作",
            "探索 executescript() 执行多条语句",
            "学习 SQLite 的备份功能",
        ],
        sourceUrls: [
            "https://docs.python.org/3/library/sqlite3.html",
            "https://docs.python.org/3/library/sqlite3.html#tutorial",
            "https://peps.python.org/pep-0249/",
        ],
    },
    "py-w22-2": {
        lessonId: "py-w22-2",
        background: [
            "【SQLAlchemy】Python 最流行的数据库工具包，包含 Core（SQL 表达式）和 ORM（对象关系映射）两层。",
            "【Engine】create_engine('sqlite:///test.db') 创建数据库引擎，管理连接池。",
            "【Table 和 Column】使用 Table、Column 定义表结构，MetaData 管理所有表定义。",
            "【SQL 表达式】select()、insert()、update()、delete() 构建类型安全的 SQL 查询。",
            "【执行查询】with engine.connect() as conn: result = conn.execute(stmt) 执行语句。",
        ],
        keyDifficulties: [
            "【Core vs ORM】Core 直接操作 SQL 表达式，更灵活；ORM 操作 Python 对象，更高级。",
            "【连接字符串】'postgresql://user:pass@host/db'、'mysql+pymysql://...'、'sqlite:///file.db'。",
            "【事务提交】conn.execute() 后需要 conn.commit()。使用 with engine.begin() 自动提交。",
            "【Result 对象】result.fetchall()、result.scalars()、result.mappings() 不同返回格式。",
        ],
        handsOnPath: [
            "1. 安装：pip install sqlalchemy",
            "2. 创建引擎：engine = create_engine('sqlite:///test.db', echo=True)",
            "3. 定义表：users = Table('users', metadata, Column('id', Integer, primary_key=True))",
            "4. 创建表：metadata.create_all(engine)",
            "5. 插入数据：with engine.begin() as conn: conn.execute(insert(users).values(name='Alice'))",
            "6. 查询数据：with engine.connect() as conn: result = conn.execute(select(users))",
        ],
        selfCheck: [
            "create_engine() 的作用是什么？",
            "Core 和 ORM 的区别是什么？",
            "如何构建 SELECT 查询？",
            "engine.connect() 和 engine.begin() 的区别是什么？",
            "echo=True 参数的作用是什么？",
            "如何执行带参数的查询？",
        ],
        extensions: [
            "学习 SQLAlchemy 连接池配置",
            "了解 CTE（公共表表达式）",
            "探索 raw SQL 执行方式",
            "学习事务隔离级别设置",
        ],
        sourceUrls: [
            "https://docs.sqlalchemy.org/",
            "https://docs.sqlalchemy.org/en/20/core/",
            "https://docs.sqlalchemy.org/en/20/core/engines.html",
        ],
    },
    "py-w22-3": {
        lessonId: "py-w22-3",
        background: [
            "【DeclarativeBase】ORM 模型的基类。所有模型类继承自 DeclarativeBase 子类。",
            "【Mapped 类型】使用 Mapped[int]、Mapped[str] 声明列类型，自动推断数据库类型。",
            "【mapped_column】mapped_column(primary_key=True) 定义列属性，如主键、外键、默认值。",
            "【relationship】relationship() 定义表间关系，支持一对多、多对多、双向关联。",
            "【Session】Session 管理数据库会话。add()、commit()、query()、delete() 操作对象。",
        ],
        keyDifficulties: [
            "【类型注解】列定义使用类型注解：id: Mapped[int] = mapped_column(primary_key=True)。",
            "【外键关系】ForeignKey('users.id') 定义外键，relationship() 创建对象级关联。",
            "【Session 生命周期】Session 应该使用 with 语句管理，避免资源泄漏。",
            "【级联删除】relationship(..., cascade='all, delete-orphan') 定义级联行为。",
        ],
        handsOnPath: [
            "1. 定义基类：class Base(DeclarativeBase): pass",
            "2. 定义模型：class User(Base): __tablename__ = 'users'",
            "3. 定义列：id: Mapped[int] = mapped_column(primary_key=True)",
            "4. 创建表：Base.metadata.create_all(engine)",
            "5. 添加数据：with Session(engine) as s: s.add(User(name='Alice')); s.commit()",
            "6. 查询数据：user = session.scalars(select(User).where(User.name == 'Alice')).first()",
        ],
        selfCheck: [
            "如何定义 ORM 模型类？",
            "__tablename__ 属性的作用是什么？",
            "Mapped[int] 和 mapped_column 的关系是什么？",
            "如何定义外键关系？",
            "Session 的 add() 和 commit() 分别做什么？",
            "如何使用 select() 查询 ORM 对象？",
        ],
        extensions: [
            "学习混入类（Mixin）复用列定义",
            "了解 lazy loading 和 eager loading",
            "探索 hybrid_property 混合属性",
            "学习多表继承策略",
        ],
        sourceUrls: [
            "https://docs.sqlalchemy.org/en/20/orm/",
            "https://docs.sqlalchemy.org/en/20/orm/declarative_tables.html",
            "https://docs.sqlalchemy.org/en/20/orm/session.html",
        ],
    },
    "py-w22-4": {
        lessonId: "py-w22-4",
        background: [
            "【Alembic】SQLAlchemy 的数据库迁移工具，管理数据库结构版本变更。",
            "【alembic init】初始化迁移环境，生成 alembic.ini 配置文件和 versions/ 目录。",
            "【alembic revision】创建新的迁移脚本，包含 upgrade() 和 downgrade() 函数。",
            "【alembic upgrade】执行迁移，upgrade head 应用所有迁移到最新版本。",
            "【alembic downgrade】回滚迁移，downgrade base 回滚到初始状态。",
        ],
        keyDifficulties: [
            "【版本追踪】alembic_version 表记录当前版本，每个迁移有唯一的 revision ID。",
            "【down_revision】每个迁移引用前一个迁移，形成版本链。",
            "【autogenerate】alembic revision --autogenerate 自动检测模型变化生成迁移。",
            "【相对版本】支持 +1、-2 等相对版本号，upgrade +1 只执行下一个迁移。",
        ],
        handsOnPath: [
            "1. 安装：pip install alembic",
            "2. 初始化：alembic init alembic",
            "3. 配置 alembic.ini：sqlalchemy.url = sqlite:///test.db",
            "4. 创建迁移：alembic revision -m 'create users table'",
            "5. 编写迁移：def upgrade(): op.create_table('users', ...)",
            "6. 执行迁移：alembic upgrade head",
        ],
        selfCheck: [
            "alembic init 创建了什么？",
            "如何创建新的迁移脚本？",
            "upgrade() 和 downgrade() 函数的作用是什么？",
            "如何查看当前迁移版本？",
            "--autogenerate 选项有什么用？",
            "如何回滚到上一个版本？",
        ],
        extensions: [
            "学习分支迁移管理",
            "了解离线迁移生成",
            "探索多数据库迁移",
            "学习迁移测试策略",
        ],
        sourceUrls: [
            "https://alembic.sqlalchemy.org/",
            "https://alembic.sqlalchemy.org/en/latest/tutorial.html",
            "https://alembic.sqlalchemy.org/en/latest/autogenerate.html",
        ],
    },
}

export const week22Quizzes: Record<string, QuizQuestion[]> = {
    "py-w22-1": [
        {
            id: "py-w22-1-q1",
            question: "如何创建 SQLite 内存数据库？",
            options: [
                "sqlite3.connect('memory')",
                "sqlite3.connect(':memory:')",
                "sqlite3.memory()",
                "sqlite3.connect(memory=True)",
            ],
            answer: 1,
            rationale: "文档说明：':memory:' 是特殊的数据库名称，创建内存数据库。",
        },
        {
            id: "py-w22-1-q2",
            question: "参数化查询使用什么占位符？",
            options: [
                "%s",
                "?",
                "$1",
                "{}",
            ],
            answer: 1,
            rationale: "文档说明：sqlite3 使用 ? 占位符（qmark 样式）或 :name（命名样式）。",
        },
        {
            id: "py-w22-1-q3",
            question: "fetchone() 返回什么？",
            options: [
                "所有行",
                "下一行（默认为元组）",
                "行数",
                "布尔值",
            ],
            answer: 1,
            rationale: "文档说明：fetchone() 返回结果集中的下一行，默认为元组。",
        },
        {
            id: "py-w22-1-q4",
            question: "为什么需要调用 commit()？",
            options: [
                "关闭连接",
                "持久化 INSERT/UPDATE/DELETE 的更改",
                "验证 SQL 语法",
                "清空缓存",
            ],
            answer: 1,
            rationale: "文档说明：必须 commit() 才能将更改保存到数据库。",
        },
        {
            id: "py-w22-1-q5",
            question: "sqlite3.Row 的作用是什么？",
            options: [
                "创建新行",
                "支持按列名访问查询结果",
                "计数行数",
                "验证行数据",
            ],
            answer: 1,
            rationale: "文档说明：sqlite3.Row 作为 row_factory 可以按索引和列名访问数据。",
        },
        {
            id: "py-w22-1-q6",
            question: "使用 with con: 语句有什么好处？",
            options: [
                "更快的执行速度",
                "自动事务管理（成功提交，异常回滚）",
                "自动创建表",
                "支持并发",
            ],
            answer: 1,
            rationale: "文档说明：with 语句自动处理事务，成功时提交，异常时回滚。",
        },
        {
            id: "py-w22-1-q7",
            question: "executemany() 的用途是什么？",
            options: [
                "执行多条不同 SQL",
                "用多组参数执行同一条 SQL",
                "并行执行 SQL",
                "执行事务",
            ],
            answer: 1,
            rationale: "文档说明：executemany(sql, parameters) 用多组参数重复执行同一 SQL。",
        },
        {
            id: "py-w22-1-q8",
            question: "con.execute() 和 cur.execute() 有什么区别？",
            options: [
                "con.execute() 更快",
                "con.execute() 是快捷方法，内部创建游标",
                "功能不同",
                "没有区别",
            ],
            answer: 1,
            rationale: "文档说明：连接对象的 execute() 是快捷方法，无需显式创建游标。",
        },
        {
            id: "py-w22-1-q9",
            question: "如何使用命名参数？",
            options: [
                "execute('SELECT :name', {'name': 'Alice'})",
                "execute('SELECT ?', {'name': 'Alice'})",
                "execute('SELECT %s', ('Alice',))",
                "execute('SELECT {name}', name='Alice')",
            ],
            answer: 0,
            rationale: "文档说明：命名样式使用 :name 占位符，参数为字典。",
        },
        {
            id: "py-w22-1-q10",
            question: "cursor.description 包含什么？",
            options: [
                "SQL 语句",
                "列名和元数据",
                "错误信息",
                "行数",
            ],
            answer: 1,
            rationale: "文档说明：description 包含最后一次查询的列名和元数据。",
        },
        {
            id: "py-w22-1-q11",
            question: "lastrowid 属性返回什么？",
            options: [
                "最后一行数据",
                "最后插入行的 rowid",
                "最后的 SQL",
                "行总数",
            ],
            answer: 1,
            rationale: "文档说明：lastrowid 返回最后成功 INSERT 操作的行 ID。",
        },
        {
            id: "py-w22-1-q12",
            question: "防止 SQL 注入的最佳方法是什么？",
            options: [
                "转义特殊字符",
                "使用参数化查询",
                "验证输入长度",
                "使用 ORM",
            ],
            answer: 1,
            rationale: "文档强调：永远使用参数化查询（占位符），不要直接拼接 SQL。",
        },
    ],
    "py-w22-2": [
        {
            id: "py-w22-2-q1",
            question: "create_engine() 的作用是什么？",
            options: [
                "创建数据库",
                "创建数据库引擎，管理连接池",
                "创建表",
                "执行 SQL",
            ],
            answer: 1,
            rationale: "文档说明：Engine 是数据库连接的源头，管理连接池。",
        },
        {
            id: "py-w22-2-q2",
            question: "SQLAlchemy Core 和 ORM 的区别是什么？",
            options: [
                "性能不同",
                "Core 操作 SQL 表达式，ORM 操作 Python 对象",
                "Core 更新，ORM 更旧",
                "没有区别",
            ],
            answer: 1,
            rationale: "文档说明：Core 是 SQL 表达式层，ORM 是对象关系映射层。",
        },
        {
            id: "py-w22-2-q3",
            question: "echo=True 参数的作用是什么？",
            options: [
                "回显用户输入",
                "将执行的 SQL 打印到日志",
                "返回执行结果",
                "启用调试模式",
            ],
            answer: 1,
            rationale: "文档说明：echo=True 会将所有执行的 SQL 语句打印到日志。",
        },
        {
            id: "py-w22-2-q4",
            question: "SQLite 的连接字符串格式是什么？",
            options: [
                "sqlite://file.db",
                "sqlite:///file.db",
                "sqlite:/file.db",
                "sqlite:file.db",
            ],
            answer: 1,
            rationale: "文档说明：SQLite 使用 sqlite:///relative/path 或 sqlite:////absolute/path。",
        },
        {
            id: "py-w22-2-q5",
            question: "engine.connect() 和 engine.begin() 的区别是什么？",
            options: [
                "没有区别",
                "begin() 自动提交事务",
                "connect() 更快",
                "begin() 只读",
            ],
            answer: 1,
            rationale: "文档说明：engine.begin() 返回自动提交的连接上下文。",
        },
        {
            id: "py-w22-2-q6",
            question: "如何构建 SELECT 查询？",
            options: [
                "Query(table)",
                "select(table)",
                "table.select()",
                "SELECT(table)",
            ],
            answer: 1,
            rationale: "文档说明：使用 select() 函数构建 SELECT 语句。",
        },
        {
            id: "py-w22-2-q7",
            question: "MetaData 的作用是什么？",
            options: [
                "存储查询结果",
                "管理所有表定义",
                "记录日志",
                "连接数据库",
            ],
            answer: 1,
            rationale: "文档说明：MetaData 是 Table 对象的容器，管理表定义。",
        },
        {
            id: "py-w22-2-q8",
            question: "如何创建数据库表？",
            options: [
                "Table.create()",
                "metadata.create_all(engine)",
                "engine.create_tables()",
                "create_tables(metadata)",
            ],
            answer: 1,
            rationale: "文档说明：metadata.create_all(engine) 创建 MetaData 中所有表。",
        },
        {
            id: "py-w22-2-q9",
            question: "insert() 函数返回什么？",
            options: [
                "插入的行数",
                "INSERT 语句对象",
                "新行的 ID",
                "布尔值",
            ],
            answer: 1,
            rationale: "文档说明：insert() 返回 Insert 语句对象，需要 execute() 执行。",
        },
        {
            id: "py-w22-2-q10",
            question: "result.scalars() 返回什么？",
            options: [
                "整数标量",
                "单列值的迭代器",
                "行数",
                "布尔值",
            ],
            answer: 1,
            rationale: "文档说明：scalars() 返回结果的第一列值或 ORM 对象。",
        },
        {
            id: "py-w22-2-q11",
            question: "如何添加 WHERE 条件？",
            options: [
                "select(t, where=...)",
                "select(t).where(condition)",
                "select(t).filter(condition)",
                "where(select(t), condition)",
            ],
            answer: 1,
            rationale: "文档说明：使用 .where() 方法添加条件。",
        },
        {
            id: "py-w22-2-q12",
            question: "Column 的 primary_key=True 表示什么？",
            options: [
                "列可为空",
                "定义主键列",
                "自动递增",
                "唯一约束",
            ],
            answer: 1,
            rationale: "文档说明：primary_key=True 将列标记为表的主键。",
        },
    ],
    "py-w22-3": [
        {
            id: "py-w22-3-q1",
            question: "如何定义 ORM 模型的基类？",
            options: [
                "class Base(Model):",
                "class Base(DeclarativeBase):",
                "class Base(ORMBase):",
                "@declarative class Base:",
            ],
            answer: 1,
            rationale: "文档说明：ORM 模型继承自 DeclarativeBase 的子类。",
        },
        {
            id: "py-w22-3-q2",
            question: "__tablename__ 属性的作用是什么？",
            options: [
                "设置模型名称",
                "指定数据库表名",
                "设置列名前缀",
                "定义主键名",
            ],
            answer: 1,
            rationale: "文档说明：__tablename__ 指定模型对应的数据库表名。",
        },
        {
            id: "py-w22-3-q3",
            question: "Mapped[int] 表示什么？",
            options: [
                "映射函数",
                "声明整数类型的列",
                "类型转换",
                "验证规则",
            ],
            answer: 1,
            rationale: "文档说明：Mapped[int] 声明列类型，自动推断数据库类型为 INTEGER。",
        },
        {
            id: "py-w22-3-q4",
            question: "relationship() 的作用是什么？",
            options: [
                "定义列约束",
                "创建表间对象级关联",
                "设置索引",
                "定义触发器",
            ],
            answer: 1,
            rationale: "文档说明：relationship() 定义 ORM 对象之间的关系。",
        },
        {
            id: "py-w22-3-q5",
            question: "Session.add() 做什么？",
            options: [
                "立即插入数据库",
                "将对象标记为待插入",
                "添加到查询",
                "创建新会话",
            ],
            answer: 1,
            rationale: "文档说明：add() 将对象加入 Session，等待 commit() 时持久化。",
        },
        {
            id: "py-w22-3-q6",
            question: "如何查询 ORM 对象？",
            options: [
                "Session.query(Model)",
                "session.scalars(select(Model))",
                "Model.find()",
                "select * from Model",
            ],
            answer: 1,
            rationale: "文档说明：使用 select() 配合 session.scalars() 查询 ORM 对象。",
        },
        {
            id: "py-w22-3-q7",
            question: "ForeignKey 的作用是什么？",
            options: [
                "定义主键",
                "定义外键约束",
                "创建索引",
                "设置默认值",
            ],
            answer: 1,
            rationale: "文档说明：ForeignKey('table.column') 定义外键引用。",
        },
        {
            id: "py-w22-3-q8",
            question: "cascade='all, delete-orphan' 的效果是什么？",
            options: [
                "禁止删除",
                "删除父对象时级联删除子对象",
                "更新时级联",
                "只删除孤儿对象",
            ],
            answer: 1,
            rationale: "文档说明：此级联设置在删除父对象时自动删除关联的子对象。",
        },
        {
            id: "py-w22-3-q9",
            question: "mapped_column(primary_key=True) 定义什么？",
            options: [
                "外键",
                "主键列",
                "唯一约束",
                "索引",
            ],
            answer: 1,
            rationale: "文档说明：primary_key=True 将该列标记为主键。",
        },
        {
            id: "py-w22-3-q10",
            question: "Session 应该如何使用？",
            options: [
                "全局单例",
                "使用 with 语句管理",
                "每个请求新建",
                "不需要关闭",
            ],
            answer: 1,
            rationale: "文档推荐：Session 应该使用 with 语句（上下文管理器）管理。",
        },
        {
            id: "py-w22-3-q11",
            question: "back_populates 参数的作用是什么？",
            options: [
                "反向填充数据",
                "定义双向关系的反向属性名",
                "回滚数据",
                "备份数据",
            ],
            answer: 1,
            rationale: "文档说明：back_populates 指定双向关系中对方的属性名。",
        },
        {
            id: "py-w22-3-q12",
            question: "session.commit() 做什么？",
            options: [
                "回滚事务",
                "刷新并提交所有更改到数据库",
                "关闭会话",
                "清空缓存",
            ],
            answer: 1,
            rationale: "文档说明：commit() 刷新待处理的更改并提交事务。",
        },
    ],
    "py-w22-4": [
        {
            id: "py-w22-4-q1",
            question: "alembic init 创建什么？",
            options: [
                "数据库",
                "迁移环境（配置文件和版本目录）",
                "模型文件",
                "测试文件",
            ],
            answer: 1,
            rationale: "文档说明：alembic init 创建 alembic.ini、env.py 和 versions/ 目录。",
        },
        {
            id: "py-w22-4-q2",
            question: "如何创建新的迁移脚本？",
            options: [
                "alembic create -m 'message'",
                "alembic revision -m 'message'",
                "alembic new -m 'message'",
                "alembic migrate -m 'message'",
            ],
            answer: 1,
            rationale: "文档说明：alembic revision -m 'message' 创建新的迁移脚本。",
        },
        {
            id: "py-w22-4-q3",
            question: "alembic upgrade head 做什么？",
            options: [
                "回滚到初始状态",
                "应用所有迁移到最新版本",
                "只应用下一个迁移",
                "显示迁移历史",
            ],
            answer: 1,
            rationale: "文档说明：upgrade head 执行所有待处理的迁移到最新版本。",
        },
        {
            id: "py-w22-4-q4",
            question: "alembic downgrade base 做什么？",
            options: [
                "应用到基础版本",
                "回滚所有迁移到初始状态",
                "删除迁移文件",
                "重置配置",
            ],
            answer: 1,
            rationale: "文档说明：downgrade base 回滚所有迁移到初始状态。",
        },
        {
            id: "py-w22-4-q5",
            question: "每个迁移脚本包含什么函数？",
            options: [
                "migrate() 和 rollback()",
                "upgrade() 和 downgrade()",
                "apply() 和 revert()",
                "up() 和 down()",
            ],
            answer: 1,
            rationale: "文档说明：迁移脚本包含 upgrade() 前进和 downgrade() 回滚函数。",
        },
        {
            id: "py-w22-4-q6",
            question: "--autogenerate 选项的作用是什么？",
            options: [
                "自动运行迁移",
                "自动检测模型变化生成迁移",
                "自动备份数据库",
                "自动测试迁移",
            ],
            answer: 1,
            rationale: "文档说明：--autogenerate 比较模型和数据库，自动生成差异迁移。",
        },
        {
            id: "py-w22-4-q7",
            question: "alembic current 显示什么？",
            options: [
                "当前模型",
                "当前数据库的迁移版本",
                "当前配置",
                "当前日期",
            ],
            answer: 1,
            rationale: "文档说明：alembic current 显示数据库当前的迁移版本。",
        },
        {
            id: "py-w22-4-q8",
            question: "down_revision 的作用是什么？",
            options: [
                "定义回滚操作",
                "引用前一个迁移版本，形成版本链",
                "设置版本号",
                "定义降级条件",
            ],
            answer: 1,
            rationale: "文档说明：down_revision 指向前一个迁移，建立版本顺序。",
        },
        {
            id: "py-w22-4-q9",
            question: "alembic_version 表的作用是什么？",
            options: [
                "存储 alembic 版本",
                "记录数据库当前的迁移版本",
                "存储表版本",
                "记录创建时间",
            ],
            answer: 1,
            rationale: "文档说明：alembic_version 表存储数据库当前应用的迁移版本。",
        },
        {
            id: "py-w22-4-q10",
            question: "alembic history 显示什么？",
            options: [
                "命令历史",
                "迁移脚本的版本历史",
                "数据库操作历史",
                "配置变更历史",
            ],
            answer: 1,
            rationale: "文档说明：alembic history 显示所有迁移脚本的版本链。",
        },
        {
            id: "py-w22-4-q11",
            question: "如何只回滚一个版本？",
            options: [
                "alembic downgrade 1",
                "alembic downgrade -1",
                "alembic rollback 1",
                "alembic undo",
            ],
            answer: 1,
            rationale: "文档说明：使用相对版本号 -1 表示回滚一个版本。",
        },
        {
            id: "py-w22-4-q12",
            question: "op.create_table() 在哪个函数中使用？",
            options: [
                "downgrade()",
                "upgrade()",
                "migrate()",
                "init()",
            ],
            answer: 1,
            rationale: "文档说明：创建表在 upgrade() 中，删除表在 downgrade() 中。",
        },
    ],
}
