import type { LessonGuide } from "../types"
import type { QuizQuestion } from "@/lib/types"

export const week20Guides: Record<string, LessonGuide> = {
    "w20-1": {
        lessonId: "w20-1",
        background: [
            "【贫血模型定义】Martin Fowler：贫血领域模型是一种反模式，其特征是'看不到任何行为，只有大量的getter和setter'。",
            "【核心问题】所有业务逻辑被提取到服务层，域对象沦为纯数据容器。",
            "【违反 OO 原则】分离了数据与处理过程，本质上是过程式编程风格。",
            "【成本与收益失衡】承担了域模型映射的所有成本，却失去了域模型的优势。",
            "【充血模型对比】真正的领域模型应包含验证、计算和业务规则等业务逻辑。",
        ],
        keyDifficulties: [
            "【识别难度】贫血模型看起来像正确的域模型，但缺乏行为。",
            "【重构挑战】从贫血模型重构为充血模型需要逐步将逻辑移入实体。",
            "【习惯问题】许多开发者习惯于服务层包含所有逻辑的方式。",
            "【框架影响】某些框架鼓励贫血模型的设计方式。",
        ],
        handsOnPath: [
            "识别系统中的贫血模型",
            "分析服务层中的业务逻辑",
            "确定哪些逻辑应该属于实体",
            "逐步将逻辑移入实体",
            "添加测试验证行为正确",
            "重构服务层为协调者角色",
            "验证重构后的设计",
        ],
        selfCheck: [
            "什么是贫血领域模型？",
            "贫血模型的主要特征是什么？",
            "贫血模型为什么是反模式？",
            "如何识别贫血模型？",
            "如何从贫血模型重构为充血模型？",
        ],
        extensions: [
            "学习充血模型的设计模式",
            "了解服务层的正确职责",
            "研究不同框架对贫血模型的影响",
            "探索测试驱动重构技术",
        ],
        sourceUrls: [
            "https://martinfowler.com/bliki/AnemicDomainModel.html",
            "https://enterprisecraftsmanship.com/posts/anemic-domain-model/",
        ],
    },
    "w20-2": {
        lessonId: "w20-2",
        background: [
            "【CRUD 思维】将所有操作视为简单的增删改查，忽视业务行为的意义。",
            "【过大聚合】聚合包含太多实体，导致性能问题和并发冲突。",
            "【忽略限界上下文】在整个系统使用单一模型，导致模型臃肿和概念混乱。",
            "【技术驱动设计】先考虑技术实现，再勉强映射到领域概念。",
            "【统一语言缺失】代码命名与业务术语不一致，导致沟通障碍。",
        ],
        keyDifficulties: [
            "【识别反模式】反模式往往在系统成长过程中逐渐形成，难以立即识别。",
            "【改变思维】从技术思维转向领域思维需要持续练习。",
            "【团队共识】团队需要对什么是正确设计达成共识。",
            "【遗留代码】处理已存在的反模式需要渐进式重构。",
        ],
        handsOnPath: [
            "审查系统中的设计决策",
            "识别是否存在 CRUD 思维",
            "评估聚合大小是否合理",
            "检查是否正确划分了限界上下文",
            "验证统一语言的使用情况",
            "制定反模式修复计划",
            "渐进式修复识别的反模式",
        ],
        selfCheck: [
            "什么是 CRUD 思维？为什么是反模式？",
            "聚合过大有什么问题？",
            "忽略限界上下文会导致什么？",
            "什么是技术驱动设计？",
            "统一语言缺失有什么危害？",
        ],
        extensions: [
            "学习更多 DDD 反模式",
            "了解重构策略",
            "研究代码异味与反模式的关系",
            "探索团队代码审查最佳实践",
        ],
        sourceUrls: [
            "https://enterprisecraftsmanship.com/posts/ddd-pitfalls/",
            "https://www.infoq.com/articles/ddd-anti-patterns/",
        ],
    },
    "w20-3": {
        lessonId: "w20-3",
        background: [
            "【战略设计核心】限界上下文是 DDD 最重要的概念，定义模型的语义边界。",
            "【战术设计要素】实体、值对象、聚合、领域服务、领域事件是核心构建块。",
            "【上下文映射】九种映射模式描述上下文间的关系和集成策略。",
            "【架构模式】分层架构、六边形架构、CQRS、Event Sourcing 是常用架构。",
            "【协作方法】EventStorming 是探索领域的有效协作工具。",
        ],
        keyDifficulties: [
            "【知识整合】DDD 包含大量概念，需要系统性整合理解。",
            "【实践应用】从理论到实践的转化需要经验积累。",
            "【场景选择】判断何时使用哪些 DDD 模式需要经验。",
            "【持续学习】DDD 社区持续发展，需要跟进最新实践。",
        ],
        handsOnPath: [
            "回顾 DDD 的核心概念",
            "整理战略设计和战术设计的关系",
            "建立个人的 DDD 知识图谱",
            "总结学习过程中的收获",
            "识别需要加强的领域",
            "制定后续学习计划",
            "准备在实际项目中应用 DDD",
        ],
        selfCheck: [
            "DDD 的核心概念有哪些？",
            "战略设计和战术设计的区别是什么？",
            "九种上下文映射模式是什么？",
            "什么时候应该使用 DDD？",
            "DDD 的主要收益是什么？",
        ],
        extensions: [
            "重读 Eric Evans 的《领域驱动设计》",
            "学习 Vaughn Vernon 的《实现领域驱动设计》",
            "探索 DDD 社区的最新发展",
            "参与 DDD 相关的开源项目",
        ],
        sourceUrls: [
            "https://github.com/ddd-crew/free-ddd-learning-resources",
            "https://www.domainlanguage.com/ddd/reference/",
        ],
    },
    "w20-4": {
        lessonId: "w20-4",
        background: [
            "【DDD Community】DDD 社区是全球 DDD 实践者的交流平台。",
            "【DDD Europe】DDD Europe 是欧洲最大的 DDD 会议，汇集顶级专家。",
            "【DDD Crew】GitHub 上的 DDD Crew 提供大量免费学习资源和工具。",
            "【持续学习】DDD 是一个持续演进的领域，需要保持学习。",
            "【实践社区】加入实践社区可以获得反馈和支持。",
        ],
        keyDifficulties: [
            "【信息过载】大量资源可能导致学习方向不明确。",
            "【实践机会】找到合适的项目来实践 DDD 是挑战。",
            "【社区参与】语言和时区可能影响社区参与。",
            "【保持更新】跟进社区最新发展需要投入时间。",
        ],
        handsOnPath: [
            "整理学习过程中收藏的资源",
            "加入 DDD 相关的在线社区",
            "关注 DDD 领域的专家和博客",
            "订阅 DDD 相关的播客和视频",
            "参与本地或在线的 DDD 活动",
            "在团队中分享 DDD 知识",
            "制定长期的 DDD 学习路径",
        ],
        selfCheck: [
            "有哪些 DDD 学习资源？",
            "如何参与 DDD 社区？",
            "DDD 领域有哪些重要的专家？",
            "如何保持 DDD 知识的更新？",
            "如何在团队中推广 DDD？",
        ],
        extensions: [
            "参加 DDD Europe 或其他 DDD 会议",
            "阅读 DDD 相关的书籍和论文",
            "贡献 DDD 开源项目",
            "撰写 DDD 相关的博客或文章",
        ],
        sourceUrls: [
            "https://www.dddcommunity.org/",
            "https://dddeurope.com/",
            "https://github.com/ddd-crew",
        ],
    },
}

export const week20Quizzes: Record<string, QuizQuestion[]> = {
    "w20-1": [
        {
            id: "w20-1-q1",
            question: "贫血领域模型的主要特征是什么？",
            options: [
                "包含大量业务逻辑",
                "只有大量的 getter 和 setter，看不到任何行为",
                "高度内聚",
                "良好的封装",
            ],
            answer: 1,
            rationale: "贫血领域模型的特征是'看不到任何行为，只有大量的getter和setter'。",
        },
        {
            id: "w20-1-q2",
            question: "贫血模型中业务逻辑在哪里？",
            options: [
                "在实体中",
                "被提取到服务层",
                "在值对象中",
                "在聚合中",
            ],
            answer: 1,
            rationale: "所有业务逻辑被提取到服务层，域对象沦为纯数据容器。",
        },
        {
            id: "w20-1-q3",
            question: "贫血模型本质上是什么编程风格？",
            options: [
                "面向对象",
                "过程式编程",
                "函数式编程",
                "响应式编程",
            ],
            answer: 1,
            rationale: "分离了数据与处理过程，本质上是过程式编程风格。",
        },
        {
            id: "w20-1-q4",
            question: "贫血模型违反什么原则？",
            options: [
                "SOLID 原则",
                "面向对象原则",
                "REST 原则",
                "敏捷原则",
            ],
            answer: 1,
            rationale: "贫血模型违反面向对象原则，分离了数据与处理过程。",
        },
        {
            id: "w20-1-q5",
            question: "充血模型应该包含什么？",
            options: [
                "只有数据",
                "验证、计算和业务规则等业务逻辑",
                "只有 getter/setter",
                "只有数据库操作",
            ],
            answer: 1,
            rationale: "真正的领域模型应包含验证、计算和业务规则等业务逻辑。",
        },
        {
            id: "w20-1-q6",
            question: "贫血模型有什么成本问题？",
            options: [
                "没有成本",
                "承担了域模型映射的所有成本，却失去了域模型的优势",
                "成本很低",
                "只有开发成本",
            ],
            answer: 1,
            rationale: "承担了域模型映射的所有成本（如O/R映射层），却失去了域模型的优势。",
        },
        {
            id: "w20-1-q7",
            question: "如何识别贫血模型？",
            options: [
                "看代码量",
                "检查实体是否只有数据访问方法而无业务行为",
                "看文件数量",
                "看数据库表数量",
            ],
            answer: 1,
            rationale: "贫血模型的实体只有数据访问方法（getter/setter）而无业务行为。",
        },
        {
            id: "w20-1-q8",
            question: "从贫血模型重构时应该做什么？",
            options: [
                "删除所有代码",
                "逐步将逻辑移入实体",
                "保持不变",
                "增加更多服务",
            ],
            answer: 1,
            rationale: "从贫血模型重构为充血模型需要逐步将逻辑移入实体。",
        },
        {
            id: "w20-1-q9",
            question: "重构后服务层应该是什么角色？",
            options: [
                "包含所有逻辑",
                "协调者角色",
                "数据访问",
                "被删除",
            ],
            answer: 1,
            rationale: "重构服务层为协调者角色，业务逻辑集中在域层。",
        },
        {
            id: "w20-1-q10",
            question: "Eric Evans 建议应该避免什么？",
            options: [
                "使用服务",
                "过早放弃将行为融入合适的对象中",
                "使用实体",
                "使用值对象",
            ],
            answer: 1,
            rationale: "应'避免过早放弃将行为融入合适的对象中，逐步滑向过程式编程'。",
        },
        {
            id: "w20-1-q11",
            question: "某些框架可能鼓励什么？",
            options: [
                "充血模型",
                "贫血模型的设计方式",
                "DDD 设计",
                "领域建模",
            ],
            answer: 1,
            rationale: "某些框架鼓励贫血模型的设计方式，需要警惕。",
        },
        {
            id: "w20-1-q12",
            question: "服务层包含大量业务逻辑意味着什么？",
            options: [
                "好的设计",
                "已经完全丧失了域模型带来的好处",
                "正确的做法",
                "最佳实践",
            ],
            answer: 1,
            rationale: "当服务层包含大量业务逻辑时，'你已经完全丧失了域模型带来的好处'。",
        },
    ],
    "w20-2": [
        {
            id: "w20-2-q1",
            question: "什么是 CRUD 思维？",
            options: [
                "正确的设计思维",
                "将所有操作视为简单的增删改查，忽视业务行为的意义",
                "面向对象思维",
                "领域驱动思维",
            ],
            answer: 1,
            rationale: "CRUD 思维将所有操作视为简单的增删改查，忽视业务行为的意义。",
        },
        {
            id: "w20-2-q2",
            question: "过大聚合会导致什么问题？",
            options: [
                "更好的性能",
                "性能问题和并发冲突",
                "更简单的代码",
                "更好的封装",
            ],
            answer: 1,
            rationale: "过大聚合导致性能问题和并发冲突。",
        },
        {
            id: "w20-2-q3",
            question: "忽略限界上下文会导致什么？",
            options: [
                "更简单的系统",
                "模型臃肿和概念混乱",
                "更好的性能",
                "更少的代码",
            ],
            answer: 1,
            rationale: "在整个系统使用单一模型，导致模型臃肿和概念混乱。",
        },
        {
            id: "w20-2-q4",
            question: "什么是技术驱动设计？",
            options: [
                "正确的设计方法",
                "先考虑技术实现，再勉强映射到领域概念",
                "领域驱动设计",
                "测试驱动设计",
            ],
            answer: 1,
            rationale: "技术驱动设计先考虑技术实现，再勉强映射到领域概念。",
        },
        {
            id: "w20-2-q5",
            question: "统一语言缺失会导致什么？",
            options: [
                "更好的沟通",
                "代码命名与业务术语不一致，导致沟通障碍",
                "更简单的代码",
                "更少的文档",
            ],
            answer: 1,
            rationale: "统一语言缺失导致代码命名与业务术语不一致，导致沟通障碍。",
        },
        {
            id: "w20-2-q6",
            question: "反模式往往在什么时候形成？",
            options: [
                "项目开始时",
                "系统成长过程中逐渐形成",
                "项目结束时",
                "不会形成",
            ],
            answer: 1,
            rationale: "反模式往往在系统成长过程中逐渐形成，难以立即识别。",
        },
        {
            id: "w20-2-q7",
            question: "从技术思维转向领域思维需要什么？",
            options: [
                "一次学习",
                "持续练习",
                "自动完成",
                "不需要转变",
            ],
            answer: 1,
            rationale: "从技术思维转向领域思维需要持续练习。",
        },
        {
            id: "w20-2-q8",
            question: "处理已存在的反模式需要什么？",
            options: [
                "一次性重写",
                "渐进式重构",
                "忽略它们",
                "删除系统",
            ],
            answer: 1,
            rationale: "处理已存在的反模式需要渐进式重构。",
        },
        {
            id: "w20-2-q9",
            question: "团队需要对什么达成共识？",
            options: [
                "工资",
                "什么是正确设计",
                "工作时间",
                "休假安排",
            ],
            answer: 1,
            rationale: "团队需要对什么是正确设计达成共识。",
        },
        {
            id: "w20-2-q10",
            question: "审查系统设计时应该检查什么？",
            options: [
                "只看代码量",
                "是否存在 CRUD 思维、聚合大小、限界上下文划分",
                "只看性能",
                "只看文档",
            ],
            answer: 1,
            rationale: "审查时应检查是否存在 CRUD 思维、聚合大小是否合理、是否正确划分了限界上下文。",
        },
        {
            id: "w20-2-q11",
            question: "CRUD 思维为什么是反模式？",
            options: [
                "因为简单",
                "忽视业务行为的意义，将领域逻辑简化为数据操作",
                "因为流行",
                "因为容易实现",
            ],
            answer: 1,
            rationale: "CRUD 思维忽视业务行为的意义，将丰富的领域逻辑简化为数据操作。",
        },
        {
            id: "w20-2-q12",
            question: "代码异味与反模式有什么关系？",
            options: [
                "没有关系",
                "代码异味往往是反模式的信号",
                "完全相同",
                "互相排斥",
            ],
            answer: 1,
            rationale: "代码异味往往是反模式的信号，需要关注和改进。",
        },
    ],
    "w20-3": [
        {
            id: "w20-3-q1",
            question: "DDD 最重要的战略设计概念是什么？",
            options: [
                "实体",
                "限界上下文",
                "值对象",
                "聚合",
            ],
            answer: 1,
            rationale: "限界上下文是 DDD 最重要的概念，定义模型的语义边界。",
        },
        {
            id: "w20-3-q2",
            question: "DDD 的战术设计核心构建块有哪些？",
            options: [
                "数据库表",
                "实体、值对象、聚合、领域服务、领域事件",
                "API 端点",
                "UI 组件",
            ],
            answer: 1,
            rationale: "实体、值对象、聚合、领域服务、领域事件是核心构建块。",
        },
        {
            id: "w20-3-q3",
            question: "上下文映射有多少种标准模式？",
            options: [
                "三种",
                "九种",
                "五种",
                "十二种",
            ],
            answer: 1,
            rationale: "九种映射模式描述上下文间的关系和集成策略。",
        },
        {
            id: "w20-3-q4",
            question: "DDD 常用的架构模式有哪些？",
            options: [
                "只有 MVC",
                "分层架构、六边形架构、CQRS、Event Sourcing",
                "只有微服务",
                "只有单体",
            ],
            answer: 1,
            rationale: "分层架构、六边形架构、CQRS、Event Sourcing 是常用架构。",
        },
        {
            id: "w20-3-q5",
            question: "EventStorming 是什么？",
            options: [
                "编程框架",
                "探索领域的有效协作工具",
                "数据库工具",
                "测试框架",
            ],
            answer: 1,
            rationale: "EventStorming 是探索领域的有效协作工具。",
        },
        {
            id: "w20-3-q6",
            question: "DDD 知识整合的挑战是什么？",
            options: [
                "概念太少",
                "包含大量概念，需要系统性整合理解",
                "太简单",
                "不需要整合",
            ],
            answer: 1,
            rationale: "DDD 包含大量概念，需要系统性整合理解。",
        },
        {
            id: "w20-3-q7",
            question: "从理论到实践的转化需要什么？",
            options: [
                "只看书",
                "经验积累",
                "不需要实践",
                "只看视频",
            ],
            answer: 1,
            rationale: "从理论到实践的转化需要经验积累。",
        },
        {
            id: "w20-3-q8",
            question: "判断何时使用哪些 DDD 模式需要什么？",
            options: [
                "随机选择",
                "经验",
                "工具决定",
                "不需要判断",
            ],
            answer: 1,
            rationale: "判断何时使用哪些 DDD 模式需要经验。",
        },
        {
            id: "w20-3-q9",
            question: "DDD 社区有什么特点？",
            options: [
                "停滞不前",
                "持续发展，需要跟进最新实践",
                "没有变化",
                "已经完结",
            ],
            answer: 1,
            rationale: "DDD 社区持续发展，需要跟进最新实践。",
        },
        {
            id: "w20-3-q10",
            question: "学习 DDD 后应该做什么？",
            options: [
                "停止学习",
                "建立个人的 DDD 知识图谱，制定后续学习计划",
                "忘记所学",
                "只看书",
            ],
            answer: 1,
            rationale: "建立个人的 DDD 知识图谱，制定后续学习计划是持续提升的关键。",
        },
        {
            id: "w20-3-q11",
            question: "战略设计和战术设计的关系是什么？",
            options: [
                "完全独立",
                "战略设计指导战术设计，战术设计在战略边界内实现",
                "互相排斥",
                "完全相同",
            ],
            answer: 1,
            rationale: "战略设计（限界上下文）指导战术设计（聚合、实体等），战术设计在战略边界内实现。",
        },
        {
            id: "w20-3-q12",
            question: "DDD 的主要收益是什么？",
            options: [
                "写更少的代码",
                "更好地理解和表达领域，提高软件的业务价值",
                "更快的性能",
                "更少的测试",
            ],
            answer: 1,
            rationale: "DDD 帮助更好地理解和表达领域，提高软件的业务价值。",
        },
    ],
    "w20-4": [
        {
            id: "w20-4-q1",
            question: "DDD Community 是什么？",
            options: [
                "编程语言",
                "全球 DDD 实践者的交流平台",
                "数据库",
                "框架",
            ],
            answer: 1,
            rationale: "DDD Community 是全球 DDD 实践者的交流平台。",
        },
        {
            id: "w20-4-q2",
            question: "DDD Europe 是什么？",
            options: [
                "公司名称",
                "欧洲最大的 DDD 会议，汇集顶级专家",
                "框架名称",
                "书籍名称",
            ],
            answer: 1,
            rationale: "DDD Europe 是欧洲最大的 DDD 会议，汇集顶级专家。",
        },
        {
            id: "w20-4-q3",
            question: "DDD Crew 提供什么？",
            options: [
                "付费培训",
                "大量免费学习资源和工具",
                "商业软件",
                "数据库",
            ],
            answer: 1,
            rationale: "GitHub 上的 DDD Crew 提供大量免费学习资源和工具。",
        },
        {
            id: "w20-4-q4",
            question: "DDD 学习有什么特点？",
            options: [
                "一次性学完",
                "需要持续学习，是一个持续演进的领域",
                "没有变化",
                "很快就能掌握",
            ],
            answer: 1,
            rationale: "DDD 是一个持续演进的领域，需要保持学习。",
        },
        {
            id: "w20-4-q5",
            question: "加入实践社区有什么好处？",
            options: [
                "没有好处",
                "可以获得反馈和支持",
                "浪费时间",
                "增加成本",
            ],
            answer: 1,
            rationale: "加入实践社区可以获得反馈和支持。",
        },
        {
            id: "w20-4-q6",
            question: "大量资源可能导致什么问题？",
            options: [
                "学习更快",
                "信息过载，学习方向不明确",
                "没有问题",
                "更简单",
            ],
            answer: 1,
            rationale: "大量资源可能导致信息过载，学习方向不明确。",
        },
        {
            id: "w20-4-q7",
            question: "找到合适的项目来实践 DDD 是什么？",
            options: [
                "容易的事",
                "挑战",
                "不需要实践",
                "自动完成",
            ],
            answer: 1,
            rationale: "找到合适的项目来实践 DDD 是挑战。",
        },
        {
            id: "w20-4-q8",
            question: "跟进社区最新发展需要什么？",
            options: [
                "不需要投入",
                "投入时间",
                "只看书",
                "自动完成",
            ],
            answer: 1,
            rationale: "跟进社区最新发展需要投入时间。",
        },
        {
            id: "w20-4-q9",
            question: "如何保持 DDD 知识的更新？",
            options: [
                "不需要更新",
                "关注专家和博客，参与社区活动",
                "只看书",
                "一次性学完",
            ],
            answer: 1,
            rationale: "关注 DDD 领域的专家和博客，参与社区活动可以保持知识更新。",
        },
        {
            id: "w20-4-q10",
            question: "在团队中推广 DDD 需要什么？",
            options: [
                "强制执行",
                "分享知识，建立共识",
                "不需要推广",
                "只有一个人学习",
            ],
            answer: 1,
            rationale: "在团队中分享 DDD 知识，建立共识是推广 DDD 的关键。",
        },
        {
            id: "w20-4-q11",
            question: "Eric Evans 是谁？",
            options: [
                "程序员",
                "《领域驱动设计》的作者，DDD 的创始人",
                "公司 CEO",
                "数据库专家",
            ],
            answer: 1,
            rationale: "Eric Evans 是《领域驱动设计》的作者，是 DDD 的创始人。",
        },
        {
            id: "w20-4-q12",
            question: "学习 DDD 后的下一步是什么？",
            options: [
                "停止学习",
                "制定长期的 DDD 学习路径，准备在实际项目中应用",
                "忘记所学",
                "等待机会",
            ],
            answer: 1,
            rationale: "制定长期的 DDD 学习路径，准备在实际项目中应用是学习后的重要步骤。",
        },
    ],
}
