import type { LessonGuide } from "../types"
import type { QuizQuestion } from "@/lib/types"

export const week17Guides: Record<string, LessonGuide> = {
    "w17-1": {
        lessonId: "w17-1",
        background: [
            "【事件风暴定义】'EventStorming is a flexible workshop format for collaborative exploration of complex business domains'——用于协作探索复杂业务领域的灵活工作坊格式。",
            "【核心理念】实现'sophisticated cross-discipline conversation between stakeholders with different backgrounds'——不同背景的利益相关者之间的跨学科对话。",
            "【发明者】由 Alberto Brandolini 发明，主要用于领域驱动设计（DDD）中快速挖掘领域知识。",
            "【协作工具】使用彩色便签在大型建模表面（通常是纸卷）上进行集体讲故事。",
            "【打破边界】EventStorming 打破空间限制，降低了主动贡献的门槛。",
        ],
        keyDifficulties: [
            "【空间需求】需要至少 8 米的墙面空间（有时需要 16 米），物理空间是重要约束。",
            "【参与者管理】大图事件风暴可能涉及 25-30 人，需要有效的引导技巧。",
            "【便签颜色】需要至少 5 种不同颜色的便签，颜色编码是核心语法。",
            "【领域专家参与】需要确保领域专家的深度参与，而非仅有开发者。",
        ],
        handsOnPath: [
            "准备物理空间和材料（纸卷、便签、马克笔）",
            "邀请跨职能团队成员和领域专家",
            "从领域事件开始（橙色便签）",
            "探索触发事件的命令（蓝色便签）",
            "识别聚合（黄色便签）",
            "标记痛点和问题区域（紫色便签）",
            "整理和分析结果",
        ],
        selfCheck: [
            "什么是 EventStorming？它的核心价值是什么？",
            "EventStorming 的便签颜色编码是什么？",
            "EventStorming 需要什么物理条件？",
            "为什么 EventStorming 强调跨学科协作？",
            "EventStorming 有哪三种主要级别？",
        ],
        extensions: [
            "学习 Alberto Brandolini 的《Introducing EventStorming》",
            "了解远程 EventStorming 的实践方法",
            "研究 EventStorming 与用户故事映射的结合",
            "探索 EventStorming 的工具支持（如 Miro）",
        ],
        sourceUrls: [
            "https://www.eventstorming.com/",
            "https://en.wikipedia.org/wiki/Event_storming",
        ],
    },
    "w17-2": {
        lessonId: "w17-2",
        background: [
            "【大图定义】'Big Picture is the largest scale flavor'——大图是最大规模的事件风暴，用于端到端探索整个业务线。",
            "【抽象级别】'Big Picture Event Storming is the highest level of abstraction'——大图是事件风暴家族中最高的抽象级别。",
            "【参与规模】典型参与人数为 25-30 人，涉及多个部门和角色。",
            "【快速探索】设计用于在非常短的时间内探索整个业务领域。",
            "【发现问题】通过大图可以发现不一致性、流程瓶颈和改进机会。",
        ],
        keyDifficulties: [
            "【规模控制】大量参与者需要有效的引导和时间管理。",
            "【信息过载】大量便签可能导致信息过载，需要适时整理。",
            "【共识建立】不同部门可能对同一事件有不同理解，需要达成共识。",
            "【后续处理】大图产出需要后续会议深入分析和细化。",
        ],
        handsOnPath: [
            "明确工作坊的目标和范围",
            "邀请各部门关键人员参与",
            "从业务流程的起点开始探索事件",
            "鼓励所有人贴出他们知道的事件",
            "按时间线排列事件",
            "标记痛点和问题区域",
            "识别关键领域和边界",
            "总结发现和后续行动",
        ],
        selfCheck: [
            "什么是大图事件风暴？它的目的是什么？",
            "大图事件风暴适合多少人参与？",
            "如何处理大图事件风暴中的冲突观点？",
            "大图事件风暴的产出是什么？",
            "如何确保大图事件风暴的有效性？",
        ],
        extensions: [
            "学习大规模工作坊的引导技巧",
            "了解如何从大图过渡到流程建模",
            "研究大图事件风暴的常见陷阱",
            "探索虚拟大图事件风暴的最佳实践",
        ],
        sourceUrls: [
            "https://www.qlerify.com/event-storming-concepts/what-is-big-picture-event-storming",
            "https://www.eventstorming.com/",
        ],
    },
    "w17-3": {
        lessonId: "w17-3",
        background: [
            "【流程建模定义】'Process Modelling introduces more rigor in the modeling'——流程建模引入更严格的建模，使用特定语法。",
            "【协作游戏】使用'Collaborative Games'方法，但不进入软件设计领域。",
            "【跨学科参与】'allowing interdisciplinary collaboration of business, technical and UX-CX stakeholders'——允许业务、技术和用户体验利益相关者的跨学科协作。",
            "【流程设计】专注于协作设计有效的流程，使用非专业化的符号。",
            "【细化探索】在大图的基础上深入探索特定流程的细节。",
        ],
        keyDifficulties: [
            "【语法严格】比大图更严格的语法要求，需要培训参与者。",
            "【边界确定】识别流程的起点和终点，确定建模范围。",
            "【政策识别】识别流程中的业务政策和决策规则。",
            "【外部系统】处理与外部系统的交互和依赖。",
        ],
        handsOnPath: [
            "选择要细化的业务流程",
            "定义流程的范围和边界",
            "详细探索流程中的每个事件",
            "识别触发事件的命令",
            "添加执行命令的角色（Actor）",
            "识别业务政策和规则",
            "标记外部系统依赖",
            "识别读模型（查询需求）",
        ],
        selfCheck: [
            "流程建模与大图事件风暴有什么区别？",
            "流程建模使用什么便签类型？",
            "如何识别业务政策？",
            "流程建模适合什么场景？",
            "流程建模的产出如何用于后续设计？",
        ],
        extensions: [
            "学习 BPMN 与 EventStorming 的对比",
            "了解如何从流程建模识别限界上下文",
            "研究流程建模中的读模型设计",
            "探索流程建模的自动化工具",
        ],
        sourceUrls: [
            "https://medium.com/@ziobrando/collaborative-process-modelling-with-eventstorming-17ed363650c0",
            "https://www.eventstorming.com/",
        ],
    },
    "w17-4": {
        lessonId: "w17-4",
        background: [
            "【软件设计级别】'Software Design EventStorming adds a level of depth'——软件设计级别增加深度，探索软件实现的活动部件。",
            "【严格语法】'progressively injecting a more rigorous grammar'——逐步注入更严格的语法。",
            "【聚合识别】'aggregates within which commands are executed and where events happen are identified'——识别执行命令和产生事件的聚合。",
            "【命令与事件】蓝色便签表示命令，橙色便签表示领域事件，放置在相应位置。",
            "【到代码的桥梁】从 EventStorming 产出直接转化为聚合、命令和领域事件的代码设计。",
        ],
        keyDifficulties: [
            "【技术深度】需要参与者理解聚合、命令、事件等 DDD 概念。",
            "【边界决策】确定聚合边界是复杂的设计决策。",
            "【一致性权衡】在强一致性和最终一致性之间权衡。",
            "【粒度选择】命令和事件的粒度选择影响设计质量。",
        ],
        handsOnPath: [
            "在流程建模基础上深入设计",
            "为每个命令识别接收它的聚合",
            "定义聚合产生的领域事件",
            "验证聚合边界保护业务不变量",
            "识别跨聚合的协作（通过事件）",
            "使用 Aggregate Design Canvas 细化设计",
            "将设计转化为代码结构",
        ],
        selfCheck: [
            "软件设计级别与流程建模有什么区别？",
            "如何从 EventStorming 识别聚合？",
            "聚合边界应该保护什么？",
            "什么是 Aggregate Design Canvas？",
            "如何从 EventStorming 转化为代码？",
        ],
        extensions: [
            "学习 Aggregate Design Canvas 的使用",
            "了解 EventStorming 与 Example Mapping 的结合",
            "研究从 EventStorming 到测试用例的转化",
            "探索 EventStorming 的代码生成工具",
        ],
        sourceUrls: [
            "https://github.com/ddd-crew/aggregate-design-canvas",
            "https://www.eventstorming.com/",
        ],
    },
}

export const week17Quizzes: Record<string, QuizQuestion[]> = {
    "w17-1": [
        {
            id: "w17-1-q1",
            question: "EventStorming 的定义是什么？",
            options: [
                "编程方法论",
                "用于协作探索复杂业务领域的灵活工作坊格式",
                "数据库设计工具",
                "项目管理方法",
            ],
            answer: 1,
            rationale: "'EventStorming is a flexible workshop format for collaborative exploration of complex business domains'。",
        },
        {
            id: "w17-1-q2",
            question: "EventStorming 由谁发明？",
            options: [
                "Eric Evans",
                "Alberto Brandolini",
                "Martin Fowler",
                "Kent Beck",
            ],
            answer: 1,
            rationale: "EventStorming 由 Alberto Brandolini 发明。",
        },
        {
            id: "w17-1-q3",
            question: "EventStorming 使用什么作为建模表面？",
            options: [
                "白板",
                "大型纸卷",
                "电子屏幕",
                "文档",
            ],
            answer: 1,
            rationale: "使用彩色便签在大型建模表面（通常是纸卷）上进行集体讲故事。",
        },
        {
            id: "w17-1-q4",
            question: "EventStorming 需要多少种便签颜色？",
            options: [
                "3 种",
                "至少 5 种不同颜色",
                "2 种",
                "10 种",
            ],
            answer: 1,
            rationale: "需要至少 5 种不同颜色的便签。",
        },
        {
            id: "w17-1-q5",
            question: "橙色便签在 EventStorming 中代表什么？",
            options: [
                "命令",
                "领域事件",
                "聚合",
                "痛点",
            ],
            answer: 1,
            rationale: "橙色便签表示领域事件，是主要的构建块。",
        },
        {
            id: "w17-1-q6",
            question: "蓝色便签在 EventStorming 中代表什么？",
            options: [
                "领域事件",
                "命令",
                "聚合",
                "外部系统",
            ],
            answer: 1,
            rationale: "蓝色便签表示命令，放在对应领域事件之前。",
        },
        {
            id: "w17-1-q7",
            question: "紫色便签在 EventStorming 中代表什么？",
            options: [
                "命令",
                "痛点/问题区域",
                "事件",
                "聚合",
            ],
            answer: 1,
            rationale: "紫色便签标记痛点（pain points）和问题区域。",
        },
        {
            id: "w17-1-q8",
            question: "黄色便签在 EventStorming 中代表什么？",
            options: [
                "命令",
                "聚合",
                "事件",
                "角色",
            ],
            answer: 1,
            rationale: "黄色便签表示聚合（Aggregates）。",
        },
        {
            id: "w17-1-q9",
            question: "EventStorming 需要多少墙面空间？",
            options: [
                "1-2 米",
                "至少 8 米（有时需要 16 米）",
                "50 米",
                "不需要墙面",
            ],
            answer: 1,
            rationale: "需要至少 8 米的墙面空间（有时需要 16 米）。",
        },
        {
            id: "w17-1-q10",
            question: "EventStorming 的三种主要级别是什么？",
            options: [
                "小、中、大",
                "大图、流程建模、软件设计",
                "简单、复杂、高级",
                "初级、中级、高级",
            ],
            answer: 1,
            rationale: "三种主要级别：大图（Big Picture）、流程建模（Process Modelling）、软件设计（Software Design）。",
        },
        {
            id: "w17-1-q11",
            question: "EventStorming 的核心价值是什么？",
            options: [
                "减少代码量",
                "实现不同背景利益相关者之间的跨学科对话",
                "提高性能",
                "简化部署",
            ],
            answer: 1,
            rationale: "实现'sophisticated cross-discipline conversation between stakeholders with different backgrounds'。",
        },
        {
            id: "w17-1-q12",
            question: "EventStorming 的第一步是什么？",
            options: [
                "识别聚合",
                "找到领域事件并写在橙色便签上",
                "识别命令",
                "画系统架构",
            ],
            answer: 1,
            rationale: "'The first step is to find the domain events and write them on orange sticky notes'。",
        },
    ],
    "w17-2": [
        {
            id: "w17-2-q1",
            question: "大图事件风暴的定义是什么？",
            options: [
                "详细技术设计",
                "最大规模的事件风暴，用于端到端探索整个业务线",
                "代码审查",
                "数据库设计",
            ],
            answer: 1,
            rationale: "'Big Picture is the largest scale flavor'——大图是最大规模的事件风暴。",
        },
        {
            id: "w17-2-q2",
            question: "大图事件风暴的典型参与人数是多少？",
            options: [
                "5-10 人",
                "25-30 人",
                "100 人以上",
                "2-3 人",
            ],
            answer: 1,
            rationale: "典型参与人数为 25-30 人。",
        },
        {
            id: "w17-2-q3",
            question: "大图事件风暴的抽象级别是什么？",
            options: [
                "最低级别",
                "最高级别",
                "中等级别",
                "技术级别",
            ],
            answer: 1,
            rationale: "'Big Picture Event Storming is the highest level of abstraction in the Event Storming family'。",
        },
        {
            id: "w17-2-q4",
            question: "大图事件风暴的主要目的是什么？",
            options: [
                "编写代码",
                "在非常短的时间内探索整个业务领域",
                "设计数据库",
                "测试系统",
            ],
            answer: 1,
            rationale: "设计用于在非常短的时间内探索整个业务领域。",
        },
        {
            id: "w17-2-q5",
            question: "大图事件风暴可以发现什么？",
            options: [
                "代码 bug",
                "不一致性、流程瓶颈和改进机会",
                "性能问题",
                "安全漏洞",
            ],
            answer: 1,
            rationale: "通过大图可以发现不一致性、流程瓶颈和改进机会。",
        },
        {
            id: "w17-2-q6",
            question: "大图事件风暴的挑战是什么？",
            options: [
                "代码复杂",
                "大量参与者需要有效的引导和时间管理",
                "数据库设计",
                "网络延迟",
            ],
            answer: 1,
            rationale: "大量参与者需要有效的引导和时间管理。",
        },
        {
            id: "w17-2-q7",
            question: "大图事件风暴应该从哪里开始？",
            options: [
                "技术细节",
                "业务流程的起点",
                "数据库表",
                "用户界面",
            ],
            answer: 1,
            rationale: "从业务流程的起点开始探索事件。",
        },
        {
            id: "w17-2-q8",
            question: "大图事件风暴的产出需要什么后续处理？",
            options: [
                "直接编码",
                "后续会议深入分析和细化",
                "不需要后续",
                "删除便签",
            ],
            answer: 1,
            rationale: "大图产出需要后续会议深入分析和细化。",
        },
        {
            id: "w17-2-q9",
            question: "如何处理大图事件风暴中的冲突观点？",
            options: [
                "忽略冲突",
                "需要达成共识",
                "由领导决定",
                "投票选择",
            ],
            answer: 1,
            rationale: "不同部门可能对同一事件有不同理解，需要达成共识。",
        },
        {
            id: "w17-2-q10",
            question: "大图事件风暴涉及哪些人？",
            options: [
                "只有开发者",
                "各部门关键人员和领域专家",
                "只有管理层",
                "只有测试人员",
            ],
            answer: 1,
            rationale: "邀请各部门关键人员参与，涉及多个部门和角色。",
        },
        {
            id: "w17-2-q11",
            question: "大图事件风暴可以识别什么边界？",
            options: [
                "代码边界",
                "关键领域和限界上下文边界",
                "数据库边界",
                "网络边界",
            ],
            answer: 1,
            rationale: "识别关键领域和边界是大图事件风暴的重要产出。",
        },
        {
            id: "w17-2-q12",
            question: "大图事件风暴的事件应该如何排列？",
            options: [
                "随机排列",
                "按时间线排列",
                "按字母排序",
                "按重要性排序",
            ],
            answer: 1,
            rationale: "按时间线排列事件是大图事件风暴的关键步骤。",
        },
    ],
    "w17-3": [
        {
            id: "w17-3-q1",
            question: "流程建模事件风暴的特点是什么？",
            options: [
                "最简单的级别",
                "引入更严格的建模语法",
                "只有开发者参与",
                "不使用便签",
            ],
            answer: 1,
            rationale: "'Process Modelling introduces more rigor in the modeling'——流程建模引入更严格的建模。",
        },
        {
            id: "w17-3-q2",
            question: "流程建模使用什么方法？",
            options: [
                "瀑布方法",
                "协作游戏（Collaborative Games）方法",
                "敏捷冲刺",
                "看板方法",
            ],
            answer: 1,
            rationale: "使用'Collaborative Games'方法。",
        },
        {
            id: "w17-3-q3",
            question: "流程建模允许哪些人参与？",
            options: [
                "只有技术人员",
                "业务、技术和用户体验利益相关者的跨学科协作",
                "只有管理层",
                "只有设计师",
            ],
            answer: 1,
            rationale: "允许业务、技术和 UX-CX 利益相关者的跨学科协作。",
        },
        {
            id: "w17-3-q4",
            question: "流程建模专注于什么？",
            options: [
                "编写代码",
                "协作设计有效的流程",
                "数据库优化",
                "性能测试",
            ],
            answer: 1,
            rationale: "专注于协作设计有效的流程，使用非专业化的符号。",
        },
        {
            id: "w17-3-q5",
            question: "流程建模与大图的关系是什么？",
            options: [
                "完全独立",
                "在大图的基础上深入探索特定流程的细节",
                "替代大图",
                "与大图相同",
            ],
            answer: 1,
            rationale: "在大图的基础上深入探索特定流程的细节。",
        },
        {
            id: "w17-3-q6",
            question: "流程建模需要识别什么？",
            options: [
                "只有事件",
                "业务政策和决策规则",
                "只有命令",
                "只有聚合",
            ],
            answer: 1,
            rationale: "识别流程中的业务政策和决策规则是流程建模的重要部分。",
        },
        {
            id: "w17-3-q7",
            question: "流程建模是否进入软件设计领域？",
            options: [
                "是",
                "否，不进入软件设计领域",
                "只有一部分",
                "取决于情况",
            ],
            answer: 1,
            rationale: "'without entering the software design arena'——不进入软件设计领域。",
        },
        {
            id: "w17-3-q8",
            question: "流程建模需要处理什么依赖？",
            options: [
                "代码依赖",
                "与外部系统的交互和依赖",
                "数据库依赖",
                "网络依赖",
            ],
            answer: 1,
            rationale: "处理与外部系统的交互和依赖是流程建模的挑战。",
        },
        {
            id: "w17-3-q9",
            question: "流程建模中的读模型代表什么？",
            options: [
                "数据库表",
                "查询需求",
                "代码结构",
                "测试用例",
            ],
            answer: 1,
            rationale: "识别读模型（查询需求）是流程建模的步骤之一。",
        },
        {
            id: "w17-3-q10",
            question: "流程建模的第一步是什么？",
            options: [
                "编写代码",
                "选择要细化的业务流程",
                "设计数据库",
                "创建测试",
            ],
            answer: 1,
            rationale: "选择要细化的业务流程是流程建模的第一步。",
        },
        {
            id: "w17-3-q11",
            question: "流程建模需要定义什么边界？",
            options: [
                "代码边界",
                "流程的范围和边界",
                "数据库边界",
                "网络边界",
            ],
            answer: 1,
            rationale: "定义流程的范围和边界是流程建模的关键步骤。",
        },
        {
            id: "w17-3-q12",
            question: "流程建模的语法要求与大图相比如何？",
            options: [
                "更宽松",
                "更严格",
                "完全相同",
                "没有语法",
            ],
            answer: 1,
            rationale: "流程建模比大图有更严格的语法要求。",
        },
    ],
    "w17-4": [
        {
            id: "w17-4-q1",
            question: "软件设计级别事件风暴的特点是什么？",
            options: [
                "最高抽象级别",
                "增加深度，探索软件实现的活动部件",
                "不涉及技术",
                "只有业务人员参与",
            ],
            answer: 1,
            rationale: "'Software Design EventStorming adds a level of depth'——软件设计级别增加深度。",
        },
        {
            id: "w17-4-q2",
            question: "软件设计级别逐步注入什么？",
            options: [
                "更宽松的规则",
                "更严格的语法",
                "更多的人员",
                "更多的便签",
            ],
            answer: 1,
            rationale: "'progressively injecting a more rigorous grammar'——逐步注入更严格的语法。",
        },
        {
            id: "w17-4-q3",
            question: "在软件设计级别识别什么？",
            options: [
                "只有事件",
                "执行命令和产生事件的聚合",
                "只有命令",
                "只有角色",
            ],
            answer: 1,
            rationale: "识别'aggregates within which commands are executed and where events happen'。",
        },
        {
            id: "w17-4-q4",
            question: "软件设计级别是什么的桥梁？",
            options: [
                "业务和销售",
                "EventStorming 产出到代码设计",
                "测试和部署",
                "文档和培训",
            ],
            answer: 1,
            rationale: "从 EventStorming 产出直接转化为聚合、命令和领域事件的代码设计。",
        },
        {
            id: "w17-4-q5",
            question: "软件设计级别需要参与者理解什么？",
            options: [
                "销售技巧",
                "聚合、命令、事件等 DDD 概念",
                "财务知识",
                "人力资源",
            ],
            answer: 1,
            rationale: "需要参与者理解聚合、命令、事件等 DDD 概念。",
        },
        {
            id: "w17-4-q6",
            question: "聚合边界应该保护什么？",
            options: [
                "代码结构",
                "业务不变量",
                "数据库表",
                "网络连接",
            ],
            answer: 1,
            rationale: "验证聚合边界保护业务不变量是软件设计级别的关键步骤。",
        },
        {
            id: "w17-4-q7",
            question: "跨聚合的协作通过什么实现？",
            options: [
                "直接调用",
                "通过事件",
                "共享数据库",
                "全局变量",
            ],
            answer: 1,
            rationale: "识别跨聚合的协作（通过事件）是软件设计级别的步骤。",
        },
        {
            id: "w17-4-q8",
            question: "Aggregate Design Canvas 用于什么？",
            options: [
                "绘制 UI",
                "细化聚合设计",
                "数据库设计",
                "网络设计",
            ],
            answer: 1,
            rationale: "使用 Aggregate Design Canvas 细化设计。",
        },
        {
            id: "w17-4-q9",
            question: "Aggregate Design Canvas 有多少个核心组件？",
            options: [
                "3 个",
                "9 个",
                "5 个",
                "12 个",
            ],
            answer: 1,
            rationale: "Aggregate Design Canvas 有 9 个核心组件。",
        },
        {
            id: "w17-4-q10",
            question: "Aggregate Design Canvas 的'Enforced Invariants'是什么？",
            options: [
                "数据库约束",
                "聚合积极保护的业务规则",
                "代码规范",
                "测试用例",
            ],
            answer: 1,
            rationale: "Enforced Invariants 是聚合积极保护的业务规则。",
        },
        {
            id: "w17-4-q11",
            question: "软件设计级别在什么基础上进行？",
            options: [
                "从零开始",
                "在流程建模基础上深入设计",
                "在代码基础上",
                "在数据库基础上",
            ],
            answer: 1,
            rationale: "在流程建模基础上深入设计是软件设计级别的起点。",
        },
        {
            id: "w17-4-q12",
            question: "大量 Enforced Invariants 可能表示什么？",
            options: [
                "设计完美",
                "高局部复杂性",
                "简单设计",
                "没有问题",
            ],
            answer: 1,
            rationale: "'A large number of enforced invariants can indicate high local complexity'。",
        },
    ],
}
