import type { LessonGuide } from "../types"
import type { QuizQuestion } from "@/lib/types"

export const week2Guides: Record<string, LessonGuide> = {
    "w2-1": {
        lessonId: "w2-1",
        background: [
            "【领域定义】领域（Domain）是软件要解决的业务问题空间，包含业务知识、规则和流程的集合。理解领域是 DDD 的第一步。",
            "【问题空间 vs 解决方案空间】问题空间关注业务需要什么（What），解决方案空间关注如何实现（How）。子域属于问题空间，限界上下文属于解决方案空间。",
            "【子域划分目的】DDD 将大问题域拆分为多个子域，目的是'makes it easier to manage complexity, and separate the important parts of the system from the rest'——降低复杂性，区分重要性。",
            "【协作探索】领域探索需要开发团队与领域专家紧密协作，通过 EventStorming、Domain Storytelling 等技术共同挖掘领域知识。",
            "【持续发现】领域知识的挖掘是持续的过程，'there's always more domain knowledge to uncover'——总有更多知识需要发现。",
        ],
        keyDifficulties: [
            "【边界模糊】初期很难明确划分子域边界，需要随着理解深入不断调整。",
            "【专家依赖】没有领域专家的参与，很难准确理解业务问题空间。",
            "【过度拆分】拆分过细会增加集成复杂度，拆分过粗会混淆关注点。",
            "【技术思维陷阱】开发者容易从技术角度而非业务角度划分领域，需要警惕。",
        ],
        handsOnPath: [
            "选择一个你熟悉的业务场景（如电商、银行、物流）",
            "列出该业务中的核心概念和业务规则",
            "尝试从业务角度（而非技术角度）识别不同的子领域",
            "使用 EventStorming 的方式，在便利贴上写出关键的业务事件",
            "与团队成员讨论你的划分，收集反馈",
        ],
        selfCheck: [
            "什么是领域？什么是子域？",
            "问题空间和解决方案空间有什么区别？",
            "为什么要将大领域拆分为多个子域？",
            "如何与领域专家协作探索问题空间？",
            "过度拆分和拆分不足各有什么问题？",
        ],
        extensions: [
            "学习 EventStorming 的 Big Picture 模式",
            "了解 Domain Storytelling 方法",
            "研究如何建立有效的领域专家协作机制",
            "探索 Impact Mapping 在领域探索中的应用",
        ],
        sourceUrls: [
            "https://www.eventstorming.com/",
            "https://github.com/ddd-crew/ddd-starter-modelling-process",
        ],
    },
    "w2-2": {
        lessonId: "w2-2",
        background: [
            "【核心域定义】核心域（Core Domain）是业务的核心竞争力，'so critical and fundamental to the business that it gives you a competitive advantage'——关键且基础，提供竞争优势。",
            "【核心域特征】Eric Evans 量化：核心域应交付系统总价值的约 20%，占代码库的约 5%，却需要约 80% 的开发努力。",
            "【支撑域定义】支撑域（Supporting Subdomain）是业务成功所必需的，但不属于核心域。'help perform ancillary or supporting functions related directly to what the business does'。",
            "【通用域定义】通用域（Generic Subdomain）是所有公司都以相同方式做的事情，是'solved problems'——已解决的问题，如用户身份管理、发送邮件、支付处理。",
            "【资源分配原则】最有经验的人应该专注于核心域，而非复杂的技术或基础设施问题。通用域应考虑购买 SaaS 或使用开源。",
        ],
        keyDifficulties: [
            "【相对性】同一子域在不同组织可能属于不同类别。'For a company that specializes in identity management, identity management is a core domain'。",
            "【识别难度】区分核心域和支撑域需要深入理解业务战略，不能仅凭技术判断。",
            "【演进性】子域分类会随业务发展而变化，今天的核心域可能明天变成通用域。",
            "【资源错配】常见错误是将最好的人才放在技术挑战而非核心业务上。",
        ],
        handsOnPath: [
            "列出你当前项目的所有业务功能",
            "对每个功能问三个问题：为什么要自建？为什么不购买现成方案？为什么不外包？",
            "根据答案将功能分类为核心域、支撑域或通用域",
            "评估当前团队资源分配是否与子域重要性匹配",
            "识别可以用现成方案替代的通用域功能",
        ],
        selfCheck: [
            "核心域、支撑域、通用域的定义和区别是什么？",
            "Eric Evans 如何量化核心域的价值、代码量和工作量比例？",
            "为什么说子域分类是相对的？能举个例子吗？",
            "如何根据子域类型分配团队资源？",
            "通用域应该如何处理？为什么？",
        ],
        extensions: [
            "学习 Core Domain Chart 工具",
            "了解 Build vs Buy 决策框架",
            "研究如何评估第三方解决方案",
            "探索核心域外包的风险和考量",
        ],
        sourceUrls: [
            "https://blog.jonathanoliver.com/ddd-strategic-design-core-supporting-and-generic-subdomains/",
            "https://deviq.com/domain-driven-design/subdomain/",
        ],
    },
    "w2-3": {
        lessonId: "w2-3",
        background: [
            "【EventStorming】EventStorming 是'超越部门边界的最聪明的协作方法'，通过跨学科参与者交互探索复杂业务领域。",
            "【四种 EventStorming 风格】改进（Improve）分析现有流程、设想（Envision）探索新生态、探索（Explore）设计新服务、设计（Design）为关键流程设计软件。",
            "【Domain Storytelling】一种将领域知识转化为有效商业软件的技术，'brings together domain experts and development teams'使专家能立即验证理解是否正确。",
            "【Wardley Mapping】战略可视化技术，帮助领导者'have better strategy discussions'，围绕目的、景观、气候、原则、领导力五要素展开。",
            "【共同语言建立】这些技术的共同目标是在领域专家与开发团队之间建立统一的术语体系和理解。",
        ],
        keyDifficulties: [
            "【协作组织】需要将不同部门、不同背景的人聚集在一起，组织协调有难度。",
            "【时间投入】这些工作坊需要较大的时间投入，需要获得管理层支持。",
            "【结果转化】工作坊的产出需要有效地转化为设计决策和代码实现。",
            "【持续维护】领域模型会演进，需要定期更新而非一次性活动。",
        ],
        handsOnPath: [
            "准备一面大墙或在线白板（如 Miro）",
            "邀请至少一位了解业务的人参与",
            "用橙色便利贴写出业务中发生的关键事件（过去时态）",
            "按时间顺序排列这些事件",
            "讨论事件之间的因果关系和触发条件",
            "识别事件中涉及的角色、命令和聚合",
        ],
        selfCheck: [
            "EventStorming 的四种风格分别适用于什么场景？",
            "Domain Storytelling 如何帮助验证团队对业务的理解？",
            "Wardley Mapping 的五个核心要素是什么？",
            "这些技术的共同目标是什么？",
            "如何将工作坊的产出转化为设计决策？",
        ],
        extensions: [
            "阅读 Alberto Brandolini 的 EventStorming 书籍",
            "尝试使用 Egon.io 进行 Domain Storytelling",
            "学习 Simon Wardley 的 Wardley Mapping 免费书籍",
            "参加 DDD 社区的线上工作坊",
        ],
        sourceUrls: [
            "https://www.eventstorming.com/",
            "https://domainstorytelling.org/",
            "https://learnwardleymapping.com/",
        ],
    },
    "w2-4": {
        lessonId: "w2-4",
        background: [
            "【电商核心域】在电商系统中，核心域通常包括：产品目录管理、定价策略、促销引擎、推荐系统——这些是竞争差异化的来源。",
            "【电商支撑域】支撑域包括：订单管理、库存管理、客户关系管理——必要但不是竞争优势，可能需要定制开发。",
            "【电商通用域】通用域包括：支付处理、用户认证、邮件发送、日志监控——应优先使用现成方案。",
            "【子域识别方法】通过分析业务流程、访谈领域专家、EventStorming 等方式识别子域，然后评估每个子域的战略重要性。",
            "【边界严格分离】Oliver 强调需要'rigid separation with a context map'——严格分离并用上下文映射记录边界，防止概念泄漏。",
        ],
        keyDifficulties: [
            "【业务理解深度】准确分类需要深入理解公司的业务战略和竞争优势。",
            "【利益相关者共识】不同角色可能对核心域有不同看法，需要达成共识。",
            "【边界维护】随着系统演进，需要持续维护子域边界，防止概念混淆。",
            "【技术债务】历史系统可能没有清晰的子域划分，重构需要渐进进行。",
        ],
        handsOnPath: [
            "绘制电商系统的业务流程图，从用户浏览到支付完成",
            "识别流程中的关键业务概念和规则",
            "将这些概念分组为可能的子域",
            "对每个子域评估：这是我们的竞争优势吗？能用现成方案吗？",
            "绘制子域之间的关系和依赖",
            "与业务专家验证你的分类",
        ],
        selfCheck: [
            "电商系统的典型核心域、支撑域、通用域各有哪些？",
            "为什么推荐系统通常是电商的核心域？",
            "支付处理为什么通常是通用域？",
            "如何防止概念在子域之间泄漏？",
            "如何处理历史系统中模糊的子域边界？",
        ],
        extensions: [
            "分析你熟悉的其他行业（银行、物流、医疗）的子域划分",
            "研究成功电商平台的架构案例",
            "了解如何在遗留系统中逐步引入子域概念",
            "探索微服务架构与子域划分的关系",
        ],
        sourceUrls: [
            "https://blog.jonathanoliver.com/ddd-strategic-design-core-supporting-and-generic-subdomains/",
            "https://github.com/ddd-by-examples/library",
        ],
    },
}

export const week2Quizzes: Record<string, QuizQuestion[]> = {
    "w2-1": [
        {
            id: "w2-1-q1",
            question: "在 DDD 中，什么是问题空间（Problem Space）？",
            options: [
                "代码实现的技术细节",
                "业务需要解决的问题，包含子域划分",
                "数据库设计方案",
                "API 接口定义",
            ],
            answer: 1,
            rationale: "问题空间关注业务需要什么（What），子域属于问题空间。解决方案空间关注如何实现（How），限界上下文属于解决方案空间。",
        },
        {
            id: "w2-1-q2",
            question: "将大领域拆分为多个子域的主要目的是什么？",
            options: [
                "增加代码量",
                "降低复杂性，区分系统各部分的重要性",
                "增加团队规模",
                "提高服务器性能",
            ],
            answer: 1,
            rationale: "文档指出拆分子域的目的是'makes it easier to manage complexity, and separate the important parts of the system from the rest'。",
        },
        {
            id: "w2-1-q3",
            question: "EventStorming 的核心特点是什么？",
            options: [
                "只有开发者参与",
                "超越部门边界的跨学科协作方法",
                "只关注技术实现",
                "只在项目开始时使用一次",
            ],
            answer: 1,
            rationale: "EventStorming 被描述为'超越部门边界的最聪明的协作方法'，强调跨学科参与者交互探索复杂业务领域。",
        },
        {
            id: "w2-1-q4",
            question: "关于领域知识的发现，以下哪个说法是正确的？",
            options: [
                "领域知识可以一次性完全理解",
                "总有更多领域知识需要持续发现",
                "只有领域专家才能理解领域知识",
                "领域知识不会随时间变化",
            ],
            answer: 1,
            rationale: "文档强调'there's always more domain knowledge to uncover'——领域知识的挖掘是持续的过程。",
        },
        {
            id: "w2-1-q5",
            question: "子域（Subdomain）和限界上下文（Bounded Context）的关系是什么？",
            options: [
                "它们是同一个概念",
                "子域属于问题空间，限界上下文属于解决方案空间",
                "限界上下文属于问题空间，子域属于解决方案空间",
                "它们没有关系",
            ],
            answer: 1,
            rationale: "Subdomains lay in the problem space. Bounded Contexts lay in solution space. 子域关注业务划分，限界上下文关注代码边界。",
        },
        {
            id: "w2-1-q6",
            question: "EventStorming 有哪四种主要风格？",
            options: [
                "设计、开发、测试、部署",
                "改进、设想、探索、设计",
                "分析、建模、编码、重构",
                "计划、执行、检查、行动",
            ],
            answer: 1,
            rationale: "EventStorming 的四种风格：Improve（改进）、Envision（设想）、Explore（探索）、Design（设计）。",
        },
        {
            id: "w2-1-q7",
            question: "为什么开发者容易在子域划分时陷入技术思维陷阱？",
            options: [
                "因为技术更重要",
                "因为习惯从技术角度而非业务角度思考问题",
                "因为业务太复杂",
                "因为领域专家不配合",
            ],
            answer: 1,
            rationale: "开发者习惯从技术角度思考，容易按技术分层（如前端、后端、数据库）而非业务能力划分领域。",
        },
        {
            id: "w2-1-q8",
            question: "Domain Storytelling 的主要目的是什么？",
            options: [
                "编写项目文档",
                "将领域知识转化为有效商业软件，弥合开发团队与领域专家的沟通鸿沟",
                "测试软件功能",
                "部署应用程序",
            ],
            answer: 1,
            rationale: "Domain Storytelling 的目的是'brings together domain experts and development teams'，使专家能立即验证团队是否正确理解了业务流程。",
        },
        {
            id: "w2-1-q9",
            question: "子域划分过细会带来什么问题？",
            options: [
                "代码太少",
                "增加集成复杂度",
                "团队太大",
                "性能太好",
            ],
            answer: 1,
            rationale: "拆分过细会增加子域之间的集成复杂度，拆分过粗会混淆关注点。需要找到合适的平衡。",
        },
        {
            id: "w2-1-q10",
            question: "在领域探索阶段，最重要的参与者是谁？",
            options: [
                "只有开发团队",
                "只有项目经理",
                "开发团队与领域专家共同参与",
                "只有架构师",
            ],
            answer: 2,
            rationale: "领域探索需要开发团队与领域专家紧密协作，没有领域专家的参与很难准确理解业务问题空间。",
        },
        {
            id: "w2-1-q11",
            question: "EventStorming 工作坊的主要产出是什么？",
            options: [
                "可运行的代码",
                "共识、一致的故事叙述、对领域的共同理解",
                "详细的技术规格",
                "项目时间表",
            ],
            answer: 1,
            rationale: "EventStorming 旨在收集共识并明确后续行动，在利益相关者间强化一致的故事叙述，管理同一模型上的多个视角。",
        },
        {
            id: "w2-1-q12",
            question: "关于问题空间和解决方案空间，以下哪个对应关系是正确的？",
            options: [
                "问题空间 - 代码实现；解决方案空间 - 业务需求",
                "问题空间 - 业务需要什么；解决方案空间 - 如何实现",
                "两者没有区别",
                "问题空间 - 测试；解决方案空间 - 开发",
            ],
            answer: 1,
            rationale: "问题空间关注业务需要什么（What），解决方案空间关注如何实现（How）。",
        },
    ],
    "w2-2": [
        {
            id: "w2-2-q1",
            question: "核心域（Core Domain）的定义是什么？",
            options: [
                "系统中代码量最多的部分",
                "对业务至关重要、提供竞争优势的基础部分",
                "技术最复杂的部分",
                "用户使用最多的功能",
            ],
            answer: 1,
            rationale: "核心域是'so critical and fundamental to the business that it gives you a competitive advantage'——关键且基础，提供竞争优势。",
        },
        {
            id: "w2-2-q2",
            question: "根据 Eric Evans，核心域的价值、代码量和工作量的比例大约是多少？",
            options: [
                "50% 价值，50% 代码，50% 工作量",
                "20% 价值，5% 代码，80% 工作量",
                "80% 价值，80% 代码，80% 工作量",
                "5% 价值，20% 代码，5% 工作量",
            ],
            answer: 1,
            rationale: "Evans 量化：核心域应交付约 20% 的总价值，占约 5% 的代码库，却需要约 80% 的开发努力。",
        },
        {
            id: "w2-2-q3",
            question: "通用域（Generic Subdomain）的特点是什么？",
            options: [
                "是公司的核心竞争力",
                "所有公司都以相同方式做的事情，是已解决的问题",
                "需要大量定制开发",
                "只有本公司需要",
            ],
            answer: 1,
            rationale: "通用域是'those things that all companies do the same way'，是'solved problems'——已解决的问题，如用户身份管理。",
        },
        {
            id: "w2-2-q4",
            question: "支撑域（Supporting Subdomain）与核心域的主要区别是什么？",
            options: [
                "支撑域不需要开发",
                "支撑域是业务成功所必需但不提供竞争优势",
                "支撑域比核心域更重要",
                "支撑域可以忽略",
            ],
            answer: 1,
            rationale: "支撑域'does not offer any competitive edge for the company'但'required for implementing a Core subdomain'——必要但不提供竞争优势。",
        },
        {
            id: "w2-2-q5",
            question: "关于子域分类的相对性，以下哪个说法是正确的？",
            options: [
                "子域分类是绝对的，不会因组织不同而变化",
                "同一子域在不同组织可能属于不同类别",
                "只有核心域会变化",
                "分类一旦确定就不应改变",
            ],
            answer: 1,
            rationale: "文档指出'the same subdomain can fall into different categories depending on what the organization does'，如身份管理对身份管理公司就是核心域。",
        },
        {
            id: "w2-2-q6",
            question: "最有经验的开发人员应该被分配到哪里工作？",
            options: [
                "复杂的技术基础设施",
                "核心域的基础业务逻辑",
                "通用域的实现",
                "前端界面开发",
            ],
            answer: 1,
            rationale: "文档强调核心域'is where your most experienced developers should focus—not on complex technical infrastructure, but on fundamental business logic'。",
        },
        {
            id: "w2-2-q7",
            question: "对于通用域，推荐的处理方式是什么？",
            options: [
                "投入最多资源自行开发",
                "考虑购买 SaaS 或使用开源解决方案",
                "外包给最便宜的供应商",
                "忽略不实现",
            ],
            answer: 1,
            rationale: "通用域代表'concepts not-unique to our domain'，'we should consider buying SaaS or using open source instead of building Generic Domains'。",
        },
        {
            id: "w2-2-q8",
            question: "以下哪个是典型的通用域示例？",
            options: [
                "电商的推荐系统",
                "银行的风控模型",
                "用户身份认证",
                "物流的路线优化",
            ],
            answer: 2,
            rationale: "用户身份管理、发送邮件、支付处理是典型的通用域，是所有公司都需要但不是竞争差异化的来源。",
        },
        {
            id: "w2-2-q9",
            question: "识别核心域时应该问的关键问题不包括哪个？",
            options: [
                "为什么要自建这个系统？",
                "这个功能用了什么技术栈？",
                "为什么不购买现成方案？",
                "为什么不外包？",
            ],
            answer: 1,
            rationale: "Evans 的三个识别问题是：为什么要自建？为什么不购买？为什么不外包？技术栈不是判断依据。",
        },
        {
            id: "w2-2-q10",
            question: "支撑域的实现可以如何处理？",
            options: [
                "必须由最资深的开发者实现",
                "可以分配给经验较少的开发者或外包",
                "必须购买现成方案",
                "应该忽略不实现",
            ],
            answer: 1,
            rationale: "支撑域'don't require the highest quality implementation and can be assigned to less experienced developers or outsourced'，但要保持与核心域的清晰边界。",
        },
        {
            id: "w2-2-q11",
            question: "为什么说子域分类会随业务发展而变化？",
            options: [
                "技术在不断进步",
                "业务战略和竞争环境会变化，今天的核心域可能明天变成通用域",
                "团队成员会变动",
                "代码会老化",
            ],
            answer: 1,
            rationale: "随着业务发展和市场变化，曾经的竞争优势可能变成通用能力，子域分类需要定期重新评估。",
        },
        {
            id: "w2-2-q12",
            question: "Oliver 强调子域之间需要什么样的分离？",
            options: [
                "不需要分离",
                "严格分离并用上下文映射记录边界",
                "只需要代码分离",
                "只需要数据库分离",
            ],
            answer: 1,
            rationale: "Oliver 强调需要'rigid separation with a context map'——严格分离并用上下文映射记录边界，防止概念泄漏。",
        },
    ],
    "w2-3": [
        {
            id: "w2-3-q1",
            question: "EventStorming 的 'Improve' 风格适用于什么场景？",
            options: [
                "设计全新的系统",
                "深入分析现有业务流程，发现瓶颈",
                "探索新创业生态系统",
                "设计事件驱动软件",
            ],
            answer: 1,
            rationale: "Improve 风格用于'深入分析现有业务流程，发现瓶颈'——适合优化已有系统。",
        },
        {
            id: "w2-3-q2",
            question: "Domain Storytelling 如何帮助团队验证理解？",
            options: [
                "通过自动化测试",
                "使领域专家能立即验证团队是否正确理解了业务流程",
                "通过代码审查",
                "通过用户反馈",
            ],
            answer: 1,
            rationale: "Domain Storytelling'brings together domain experts and development teams'，使专家能立即验证团队是否正确理解了业务流程。",
        },
        {
            id: "w2-3-q3",
            question: "Wardley Mapping 的五个核心要素是什么？",
            options: [
                "需求、设计、开发、测试、部署",
                "目的、景观、气候、原则、领导力",
                "计划、执行、检查、行动、反馈",
                "人员、流程、工具、技术、数据",
            ],
            answer: 1,
            rationale: "Wardley Mapping 围绕五个要素：Purpose（目的）、Landscape（景观）、Climate（气候）、Doctrine（原则）、Leadership（领导力）。",
        },
        {
            id: "w2-3-q4",
            question: "EventStorming 的 'Design' 风格的目的是什么？",
            options: [
                "改进现有流程",
                "探索新创业生态",
                "为关键流程设计事件驱动型软件",
                "设计用户界面",
            ],
            answer: 2,
            rationale: "Design 风格用于'为关键流程设计事件驱动型软件'——是最接近代码实现的风格。",
        },
        {
            id: "w2-3-q5",
            question: "Domain Storytelling 使用什么工具进行可视化建模？",
            options: [
                "PowerPoint",
                "Egon.io",
                "Excel",
                "Word",
            ],
            answer: 1,
            rationale: "Egon.io 是开源的网络化建模工具，支持 Domain Storytelling 的可视化故事表现。",
        },
        {
            id: "w2-3-q6",
            question: "这些领域探索技术的共同目标是什么？",
            options: [
                "编写更多代码",
                "在领域专家与开发团队之间建立统一的术语体系和理解",
                "加快开发速度",
                "减少测试工作",
            ],
            answer: 1,
            rationale: "EventStorming、Domain Storytelling、Wardley Mapping 的共同目标是建立共同语言和理解，弥合业务与技术的鸿沟。",
        },
        {
            id: "w2-3-q7",
            question: "组织 EventStorming 工作坊的主要挑战是什么？",
            options: [
                "技术太复杂",
                "需要将不同部门、不同背景的人聚集在一起",
                "需要太多代码",
                "需要特殊的硬件",
            ],
            answer: 1,
            rationale: "EventStorming 需要跨部门、跨学科的参与者，组织协调不同背景的人是主要挑战之一。",
        },
        {
            id: "w2-3-q8",
            question: "EventStorming 的 'Envision' 风格适用于什么？",
            options: [
                "优化现有系统",
                "探索新创业生态系统的全景",
                "修复 Bug",
                "性能优化",
            ],
            answer: 1,
            rationale: "Envision 风格用于'探索新创业生态系统的全景'——适合新业务探索和战略规划。",
        },
        {
            id: "w2-3-q9",
            question: "Wardley Mapping 主要帮助领导者做什么？",
            options: [
                "编写代码",
                "进行更好的战略讨论",
                "管理团队考勤",
                "审批预算",
            ],
            answer: 1,
            rationale: "Wardley Mapping 帮助领导者'have better strategy discussions'——进行更好的战略讨论。",
        },
        {
            id: "w2-3-q10",
            question: "为什么领域模型需要持续维护而非一次性活动？",
            options: [
                "因为技术会过时",
                "因为领域模型会随业务演进，需要定期更新",
                "因为团队成员会变动",
                "因为服务器会老化",
            ],
            answer: 1,
            rationale: "业务在不断变化，领域模型需要随之演进，工作坊不应该是一次性活动，而是持续的过程。",
        },
        {
            id: "w2-3-q11",
            question: "Domain Storytelling 的核心方法是什么？",
            options: [
                "编写详细的文档",
                "通过故事讲述和可视化使业务流程、人员角色和工作项目变得具体可见",
                "进行代码审查",
                "执行自动化测试",
            ],
            answer: 1,
            rationale: "Domain Storytelling 通过故事讲述和可视化，使业务流程、人员角色和工作项目变得具体可见。",
        },
        {
            id: "w2-3-q12",
            question: "EventStorming 的 'Explore' 风格适用于什么场景？",
            options: [
                "修复生产问题",
                "协作设计新服务，整合多方视角",
                "代码重构",
                "数据库优化",
            ],
            answer: 1,
            rationale: "Explore 风格用于'协作设计新服务，整合多方视角'——适合新服务设计阶段。",
        },
    ],
    "w2-4": [
        {
            id: "w2-4-q1",
            question: "在电商系统中，以下哪个通常是核心域？",
            options: [
                "用户认证",
                "推荐系统和定价策略",
                "邮件发送",
                "日志监控",
            ],
            answer: 1,
            rationale: "推荐系统、定价策略、促销引擎等是电商的核心域——这些是竞争差异化的来源。",
        },
        {
            id: "w2-4-q2",
            question: "在电商系统中，以下哪个通常是通用域？",
            options: [
                "产品目录管理",
                "促销引擎",
                "支付处理",
                "推荐系统",
            ],
            answer: 2,
            rationale: "支付处理、用户认证、邮件发送、日志监控是典型的通用域——应优先使用现成方案。",
        },
        {
            id: "w2-4-q3",
            question: "订单管理在电商系统中通常属于什么类型的子域？",
            options: [
                "核心域",
                "支撑域",
                "通用域",
                "不属于任何子域",
            ],
            answer: 1,
            rationale: "订单管理是支撑域——必要但不是竞争优势，可能需要根据业务定制开发。",
        },
        {
            id: "w2-4-q4",
            question: "Oliver 强调用什么来防止概念在子域之间泄漏？",
            options: [
                "代码注释",
                "上下文映射（Context Map）记录严格分离的边界",
                "详细文档",
                "代码审查",
            ],
            answer: 1,
            rationale: "Oliver 强调需要'rigid separation with a context map'——严格分离并用上下文映射记录边界。",
        },
        {
            id: "w2-4-q5",
            question: "为什么推荐系统通常是电商的核心域？",
            options: [
                "因为技术最复杂",
                "因为代码量最多",
                "因为是竞争差异化的来源，直接影响转化率和用户体验",
                "因为用户使用最频繁",
            ],
            answer: 2,
            rationale: "推荐系统直接影响用户体验和转化率，是电商平台的核心竞争力和差异化来源。",
        },
        {
            id: "w2-4-q6",
            question: "对于历史系统中模糊的子域边界，应该如何处理？",
            options: [
                "一次性全部重构",
                "忽略不处理",
                "渐进式重构，逐步明确边界",
                "推倒重来",
            ],
            answer: 2,
            rationale: "历史系统可能没有清晰的子域划分，重构需要渐进进行，逐步引入和明确边界。",
        },
        {
            id: "w2-4-q7",
            question: "在进行子域分类时，需要与谁达成共识？",
            options: [
                "只有开发团队",
                "只有产品经理",
                "所有利益相关者，包括业务专家",
                "只有架构师",
            ],
            answer: 2,
            rationale: "不同角色可能对核心域有不同看法，需要与所有利益相关者达成共识，特别是业务专家。",
        },
        {
            id: "w2-4-q8",
            question: "库存管理在电商系统中通常属于什么类型的子域？",
            options: [
                "核心域",
                "支撑域",
                "通用域",
                "基础设施域",
            ],
            answer: 1,
            rationale: "库存管理是支撑域——对业务运作必要，但通常不是竞争差异化的来源。",
        },
        {
            id: "w2-4-q9",
            question: "识别子域的方法不包括以下哪个？",
            options: [
                "分析业务流程",
                "访谈领域专家",
                "只看代码结构",
                "EventStorming 工作坊",
            ],
            answer: 2,
            rationale: "识别子域需要从业务角度出发，通过分析业务流程、访谈领域专家、EventStorming 等方式，而非只看代码结构。",
        },
        {
            id: "w2-4-q10",
            question: "为什么支付处理通常是通用域？",
            options: [
                "因为不重要",
                "因为所有电商平台都需要但不是竞争差异化来源，有成熟的第三方方案",
                "因为太复杂",
                "因为法规要求",
            ],
            answer: 1,
            rationale: "支付处理是所有电商都需要的标准功能，有成熟的第三方方案（如 Stripe、PayPal），不是竞争差异化的来源。",
        },
        {
            id: "w2-4-q11",
            question: "准确进行子域分类需要什么？",
            options: [
                "只需要技术知识",
                "深入理解公司的业务战略和竞争优势",
                "只需要看代码",
                "只需要用户调研",
            ],
            answer: 1,
            rationale: "准确分类需要深入理解公司的业务战略和竞争优势，不能仅凭技术判断。",
        },
        {
            id: "w2-4-q12",
            question: "在分析其他行业（如银行、物流）的子域时，应该注意什么？",
            options: [
                "直接套用电商的分类",
                "每个行业的核心域不同，需要根据具体业务战略分析",
                "只关注技术实现",
                "忽略业务差异",
            ],
            answer: 1,
            rationale: "不同行业的核心竞争力不同，子域分类需要根据具体业务战略分析，不能直接套用其他行业的模式。",
        },
    ],
}
