import type { LessonGuide } from "../types"
import type { QuizQuestion } from "@/lib/types"

export const week13Guides: Record<string, LessonGuide> = {
    "w13-1": {
        lessonId: "w13-1",
        background: [
            "【上下文映射定义】上下文映射（Context Mapping）是 DDD 战略设计实践，可视化限界上下文之间的交互关系和维护团队之间的关系。",
            "【组织层面意义】上下文映射不仅描述技术集成，更反映团队之间的协作关系和组织结构。",
            "【三种团队关系】互相依赖（Mutually Dependent）、上游/下游（Upstream/Downstream）、自由（Free）。",
            "【九种映射模式】从合作关系到分离方式，每种模式适用于不同的组织和技术场景。",
            "【分析与设计双重作用】可用于分析现有系统，也可用于前期设计以指导模型如何传播和治理。",
        ],
        keyDifficulties: [
            "【模式选择】不同模式适用于不同场景，选择错误的模式会带来集成问题。",
            "【团队动态】上下文映射需要考虑团队的协作意愿和能力。",
            "【演化管理】上下文关系会随时间变化，映射需要持续更新。",
            "【组织政治】某些映射模式（如 Conformist）反映的是组织政治而非技术选择。",
        ],
        handsOnPath: [
            "识别系统中的所有限界上下文",
            "分析每对上下文之间的数据和功能依赖",
            "确定团队之间的关系类型",
            "为每个关系选择合适的映射模式",
            "绘制初步的上下文映射图",
            "与团队验证映射的准确性",
        ],
        selfCheck: [
            "什么是上下文映射？它的作用是什么？",
            "三种团队关系类型是什么？",
            "上下文映射为什么不仅仅是技术问题？",
            "映射模式的选择应该基于什么？",
            "上下文映射如何支持系统演化？",
        ],
        extensions: [
            "学习 Team Topologies 与上下文映射的结合",
            "了解 Context Mapper 工具的使用",
            "研究上下文映射在微服务架构中的应用",
            "探索动态上下文映射的管理策略",
        ],
        sourceUrls: [
            "https://github.com/ddd-crew/context-mapping",
            "https://deviq.com/domain-driven-design/context-mapping/",
        ],
    },
    "w13-2": {
        lessonId: "w13-2",
        background: [
            "【合作关系 Partnership】两个上下文紧密协作，同步演进，'development failure in either of two contexts would result in delivery failure for both'。",
            "【客户-供应商 Customer/Supplier】上游可独立成功，但下游优先级影响上游规划，'downstream priorities factor into upstream planning'。",
            "【遵从者 Conformist】下游完全采用上游模型，即使不完全符合需求，'downstream team conforms to the model of the upstream team'。",
            "【共享内核 Shared Kernel】两个团队明确共享一小部分领域模型，需要相互协商，'teams agree to share some subset of the domain model'。",
            "【分道扬镳 Separate Ways】上下文完全独立，没有显著关系需要集成。",
        ],
        keyDifficulties: [
            "【Conformist vs Customer/Supplier】Conformist 是非合作模式，上游不支持下游；Customer/Supplier 是合作模式。",
            "【共享内核风险】共享内核增加耦合，变更需要两个团队协调，是潜在的瓶颈。",
            "【模式转换】随着团队关系变化，映射模式可能需要从一种转换到另一种。",
            "【组织约束】技术上最优的模式可能因组织约束而无法实现。",
        ],
        handsOnPath: [
            "分析现有系统中的团队协作模式",
            "识别 Conformist 场景——可能需要改进或接受",
            "评估共享内核的范围和风险",
            "确定 Customer/Supplier 关系中的优先级协商机制",
            "记录 Partnership 中的协调流程",
            "标记 Separate Ways 以避免不必要的集成",
        ],
        selfCheck: [
            "Partnership 和 Customer/Supplier 有什么区别？",
            "Conformist 模式什么时候是合理的选择？",
            "共享内核有什么风险？如何管理？",
            "如何识别系统中的 Separate Ways？",
            "团队关系变化时映射模式如何调整？",
        ],
        extensions: [
            "学习团队拓扑与协作模式的对应关系",
            "了解如何从 Conformist 演进到 Customer/Supplier",
            "研究共享内核的版本管理策略",
            "探索跨组织的上下文映射挑战",
        ],
        sourceUrls: [
            "https://contextmapper.org/docs/customer-supplier/",
            "https://deviq.com/domain-driven-design/context-mapping/",
        ],
    },
    "w13-3": {
        lessonId: "w13-3",
        background: [
            "【开放主机服务 Open Host Service】上游提供文档化的协议供下游集成，'provides accessible protocols for integration that teams can adopt'。",
            "【发布语言 Published Language】标准化的交换格式（如 JSON、XML、Protobuf）实现上下文间清晰通信。",
            "【反腐层 Anti-Corruption Layer】下游用翻译逻辑隔离自己，保护自身模型不受上游污染。",
            "【大泥球 Big Ball of Mud】识别混乱系统中的混合模型，防止腐败扩散——这是一种反模式。",
            "【映射图符号】使用 U（上游）、D（下游）、OHS、ACL、PL 等符号表示关系和模式。",
        ],
        keyDifficulties: [
            "【OHS + PL 组合】Open Host Service 常与 Published Language 结合使用，提供 API 和交换格式。",
            "【ACL 位置】反腐层在下游实现，保护下游模型的纯净性。",
            "【Big Ball of Mud 处理】识别但不美化泥球，记录边界以防止进一步扩散。",
            "【图的粒度】创建小型、聚焦的映射图回答特定问题，而非尝试全面覆盖。",
        ],
        handsOnPath: [
            "为系统创建初始上下文映射图",
            "使用 U/D 标记上下游关系",
            "添加 OHS、ACL、PL 等模式标注",
            "识别并标记 Big Ball of Mud 区域",
            "为不同利益相关者创建不同粒度的视图",
            "使用工具（如 Context Mapper）维护映射图",
        ],
        selfCheck: [
            "Open Host Service 和 Published Language 如何配合？",
            "Anti-Corruption Layer 应该在哪一方实现？为什么？",
            "如何在映射图中表示 Big Ball of Mud？",
            "上下文映射图应该多详细？",
            "如何维护映射图的更新？",
        ],
        extensions: [
            "学习 Context Mapper DSL 语法",
            "了解 PlantUML 绘制上下文映射图",
            "研究 API 网关作为 OHS 的实现",
            "探索可视化工具对团队沟通的影响",
        ],
        sourceUrls: [
            "https://contextmapper.org/docs/open-host-service/",
            "https://github.com/ddd-crew/context-mapping",
        ],
    },
    "w13-4": {
        lessonId: "w13-4",
        background: [
            "【从映射到决策】上下文映射结果应指导架构和集成设计决策，而非仅作为文档。",
            "【识别风险点】Conformist 关系、大泥球区域、过大的共享内核都是风险点。",
            "【优化机会】将 Conformist 升级为 Customer/Supplier、添加 ACL 保护下游、拆分大泥球。",
            "【ADR 记录】使用架构决策记录（ADR）记录基于映射的设计决策和理由。",
            "【持续演化】上下文映射是活文档，需要随系统和组织演化而更新。",
        ],
        keyDifficulties: [
            "【决策优先级】多个优化机会时如何排序——通常先处理最大风险。",
            "【变更成本】改变上下文关系（如添加 ACL）有实现成本，需要权衡。",
            "【组织变革】某些优化需要组织层面的支持，不仅仅是技术变更。",
            "【度量效果】如何度量上下文映射优化的效果——团队满意度、集成问题数量等。",
        ],
        handsOnPath: [
            "基于映射图识别系统中的风险点",
            "为每个风险点评估影响和改进成本",
            "制定优化路线图",
            "创建 ADR 记录关键设计决策",
            "实施优先级最高的改进",
            "定期回顾和更新映射图",
        ],
        selfCheck: [
            "如何从上下文映射识别风险点？",
            "哪些映射模式表示潜在问题？",
            "如何决定优化的优先级？",
            "ADR 如何与上下文映射配合？",
            "如何度量映射优化的效果？",
        ],
        extensions: [
            "学习 ADR 的标准格式和最佳实践",
            "了解技术债务与上下文映射的关系",
            "研究从单体到微服务迁移中的上下文映射",
            "探索上下文映射的自动化分析工具",
        ],
        sourceUrls: [
            "https://adr.github.io/",
            "https://deviq.com/domain-driven-design/context-mapping/",
        ],
    },
}

export const week13Quizzes: Record<string, QuizQuestion[]> = {
    "w13-1": [
        {
            id: "w13-1-q1",
            question: "什么是上下文映射（Context Mapping）？",
            options: [
                "数据库映射技术",
                "可视化限界上下文之间交互关系和团队关系的 DDD 战略设计实践",
                "代码映射工具",
                "UI 设计模式",
            ],
            answer: 1,
            rationale: "上下文映射是 DDD 战略设计实践，可视化限界上下文之间的交互关系和维护团队之间的关系。",
        },
        {
            id: "w13-1-q2",
            question: "上下文映射为什么不仅仅是技术问题？",
            options: [
                "因为需要文档",
                "因为它反映团队之间的协作关系和组织结构",
                "因为需要工具",
                "因为代码复杂",
            ],
            answer: 1,
            rationale: "上下文映射不仅描述技术集成，更反映团队之间的协作关系和组织结构。",
        },
        {
            id: "w13-1-q3",
            question: "三种主要的团队关系类型是什么？",
            options: [
                "开发、测试、运维",
                "互相依赖、上游/下游、自由",
                "前端、后端、数据库",
                "敏捷、瀑布、混合",
            ],
            answer: 1,
            rationale: "三种团队关系：互相依赖（Mutually Dependent）、上游/下游（Upstream/Downstream）、自由（Free）。",
        },
        {
            id: "w13-1-q4",
            question: "上下文映射有多少种标准模式？",
            options: [
                "三种",
                "九种",
                "五种",
                "十二种",
            ],
            answer: 1,
            rationale: "九种映射模式，从合作关系到分离方式，每种模式适用于不同的组织和技术场景。",
        },
        {
            id: "w13-1-q5",
            question: "上下文映射可以用于什么目的？",
            options: [
                "只用于文档",
                "分析现有系统或前期设计，指导模型传播和治理",
                "只用于新系统设计",
                "只用于代码审查",
            ],
            answer: 1,
            rationale: "上下文映射可用于分析现有系统，也可用于前期设计以指导模型如何传播和治理。",
        },
        {
            id: "w13-1-q6",
            question: "选择错误的映射模式会带来什么问题？",
            options: [
                "没有问题",
                "集成问题和团队协作困难",
                "只影响文档",
                "只影响测试",
            ],
            answer: 1,
            rationale: "不同模式适用于不同场景，选择错误的模式会带来集成问题。",
        },
        {
            id: "w13-1-q7",
            question: "上下文映射需要考虑什么团队因素？",
            options: [
                "团队规模",
                "团队的协作意愿和能力",
                "团队工资",
                "团队位置",
            ],
            answer: 1,
            rationale: "上下文映射需要考虑团队的协作意愿和能力。",
        },
        {
            id: "w13-1-q8",
            question: "上下文映射需要多久更新一次？",
            options: [
                "从不更新",
                "需要持续更新，因为关系会随时间变化",
                "每年一次",
                "只在项目开始时",
            ],
            answer: 1,
            rationale: "上下文关系会随时间变化，映射需要持续更新。",
        },
        {
            id: "w13-1-q9",
            question: "某些映射模式（如 Conformist）反映的是什么？",
            options: [
                "技术限制",
                "组织政治而非技术选择",
                "性能需求",
                "安全需求",
            ],
            answer: 1,
            rationale: "某些映射模式（如 Conformist）反映的是组织政治而非技术选择。",
        },
        {
            id: "w13-1-q10",
            question: "互相依赖（Mutually Dependent）团队关系意味着什么？",
            options: [
                "可以独立工作",
                "需要同时交付和紧密协调",
                "没有关系",
                "竞争关系",
            ],
            answer: 1,
            rationale: "互相依赖的团队需要同时交付和紧密协调，因为它们之间有相互的数据、功能和能力链接。",
        },
        {
            id: "w13-1-q11",
            question: "上游/下游关系的特点是什么？",
            options: [
                "双向影响",
                "上游行为影响下游，但反之不显著",
                "下游控制上游",
                "没有影响",
            ],
            answer: 1,
            rationale: "在上游/下游关系中，上游行为影响下游团队，但反之不显著。上游团队可以独立成功。",
        },
        {
            id: "w13-1-q12",
            question: "Team Topologies 与上下文映射有什么关系？",
            options: [
                "没有关系",
                "Team Topologies 提供了讨论组织设计的通用语言，与 DDD 概念结合",
                "完全替代上下文映射",
                "只用于技术团队",
            ],
            answer: 1,
            rationale: "Team Topologies 提供了讨论组织设计的通用语言，与 DDD 概念结合使用。",
        },
    ],
    "w13-2": [
        {
            id: "w13-2-q1",
            question: "Partnership（合作关系）模式的特点是什么？",
            options: [
                "可以独立工作",
                "两个上下文紧密协作，一方失败会导致双方交付失败",
                "单向依赖",
                "没有依赖",
            ],
            answer: 1,
            rationale: "'development failure in either of two contexts would result in delivery failure for both'。",
        },
        {
            id: "w13-2-q2",
            question: "Customer/Supplier（客户-供应商）模式中，下游的角色是什么？",
            options: [
                "控制上游",
                "下游优先级影响上游规划，但上游可独立成功",
                "完全从属",
                "独立工作",
            ],
            answer: 1,
            rationale: "'downstream priorities factor into upstream planning'，但上游可独立成功。",
        },
        {
            id: "w13-2-q3",
            question: "Conformist（遵从者）模式的特点是什么？",
            options: [
                "双向协作",
                "下游完全采用上游模型，即使不完全符合需求",
                "上游适应下游",
                "平等协作",
            ],
            answer: 1,
            rationale: "'downstream team conforms to the model of the upstream team despite that model not meeting their needs'。",
        },
        {
            id: "w13-2-q4",
            question: "Conformist 和 Customer/Supplier 的关键区别是什么？",
            options: [
                "没有区别",
                "Conformist 是非合作模式，上游不支持下游；Customer/Supplier 是合作模式",
                "Conformist 更复杂",
                "Customer/Supplier 更简单",
            ],
            answer: 1,
            rationale: "Conformist 是非合作模式，上游不支持下游；Customer/Supplier 是合作模式，下游需求影响上游规划。",
        },
        {
            id: "w13-2-q5",
            question: "Shared Kernel（共享内核）的定义是什么？",
            options: [
                "共享数据库",
                "两个团队明确共享一小部分领域模型，需要相互协商",
                "共享代码库",
                "共享服务器",
            ],
            answer: 1,
            rationale: "'teams agree to share some subset of the domain model'，需要相互协商变更。",
        },
        {
            id: "w13-2-q6",
            question: "共享内核的主要风险是什么？",
            options: [
                "性能下降",
                "增加耦合，变更需要两个团队协调，是潜在的瓶颈",
                "安全风险",
                "没有风险",
            ],
            answer: 1,
            rationale: "共享内核增加耦合，变更需要两个团队协调，是潜在的瓶颈。",
        },
        {
            id: "w13-2-q7",
            question: "Separate Ways（分道扬镳）模式什么时候使用？",
            options: [
                "所有情况",
                "上下文完全独立，没有显著关系需要集成",
                "紧密耦合时",
                "需要共享数据时",
            ],
            answer: 1,
            rationale: "Separate Ways 表示上下文完全独立，没有显著关系需要集成。",
        },
        {
            id: "w13-2-q8",
            question: "为什么 Conformist 有时是合理的选择？",
            options: [
                "永远不合理",
                "当翻译成本太高或无法控制上游时",
                "当需要创新时",
                "当团队很大时",
            ],
            answer: 1,
            rationale: "当翻译成本太高或对上游上下文没有控制时，Conformist 可能是合理的选择。",
        },
        {
            id: "w13-2-q9",
            question: "如何从 Conformist 演进到更好的关系？",
            options: [
                "不能演进",
                "通过建立沟通渠道和影响力升级为 Customer/Supplier",
                "添加更多代码",
                "删除集成",
            ],
            answer: 1,
            rationale: "可以通过建立沟通渠道和影响力，从 Conformist 演进到 Customer/Supplier。",
        },
        {
            id: "w13-2-q10",
            question: "Partnership 模式需要什么协调机制？",
            options: [
                "不需要协调",
                "协调规划、共同管理集成、合作演进接口",
                "只需要文档",
                "只需要代码审查",
            ],
            answer: 1,
            rationale: "Partnership 需要'coordinated planning of development and joint management of integration'。",
        },
        {
            id: "w13-2-q11",
            question: "技术上最优的模式为什么可能无法实现？",
            options: [
                "技术限制",
                "组织约束可能阻止实现最优模式",
                "工具不支持",
                "没有这种情况",
            ],
            answer: 1,
            rationale: "技术上最优的模式可能因组织约束而无法实现。",
        },
        {
            id: "w13-2-q12",
            question: "Customer/Supplier 关系中的优先级协商如何进行？",
            options: [
                "下游完全控制",
                "下游需求影响上游规划，但上游有最终决定权",
                "上游完全控制",
                "不需要协商",
            ],
            answer: 1,
            rationale: "在 Customer/Supplier 中，下游优先级影响上游规划，但上游仍有最终决定权。",
        },
    ],
    "w13-3": [
        {
            id: "w13-3-q1",
            question: "Open Host Service（开放主机服务）的定义是什么？",
            options: [
                "共享数据库",
                "上游提供文档化的协议供下游集成",
                "开源软件",
                "云服务",
            ],
            answer: 1,
            rationale: "Open Host Service'provides accessible protocols for integration that teams can adopt'。",
        },
        {
            id: "w13-3-q2",
            question: "Published Language（发布语言）的作用是什么？",
            options: [
                "编程语言",
                "标准化的交换格式（如 JSON、XML）实现上下文间清晰通信",
                "文档语言",
                "脚本语言",
            ],
            answer: 1,
            rationale: "Published Language 是标准化的交换格式（如 JSON、XML、Protobuf）实现上下文间清晰通信。",
        },
        {
            id: "w13-3-q3",
            question: "Anti-Corruption Layer（反腐层）应该在哪一方实现？",
            options: [
                "上游",
                "下游，保护下游模型不受上游污染",
                "两边都实现",
                "第三方",
            ],
            answer: 1,
            rationale: "反腐层在下游实现，'downstream isolates itself with translation logic protecting its own model'。",
        },
        {
            id: "w13-3-q4",
            question: "Big Ball of Mud（大泥球）在上下文映射中代表什么？",
            options: [
                "最佳实践",
                "识别混乱系统中的混合模型——这是一种反模式",
                "新技术",
                "设计模式",
            ],
            answer: 1,
            rationale: "Big Ball of Mud 识别混乱系统中的混合模型，防止腐败扩散——这是一种反模式。",
        },
        {
            id: "w13-3-q5",
            question: "OHS 和 PL 如何配合使用？",
            options: [
                "不能配合",
                "OHS 提供 API，PL 定义交换格式，常一起使用",
                "相互替代",
                "只用于测试",
            ],
            answer: 1,
            rationale: "Open Host Service 常与 Published Language 结合使用，OHS 提供 API，PL 定义交换格式。",
        },
        {
            id: "w13-3-q6",
            question: "U 和 D 在上下文映射图中代表什么？",
            options: [
                "用户和开发者",
                "上游（Upstream）和下游（Downstream）",
                "单元和数据",
                "更新和删除",
            ],
            answer: 1,
            rationale: "使用 U（上游）、D（下游）标记关系方向。",
        },
        {
            id: "w13-3-q7",
            question: "如何处理系统中的 Big Ball of Mud？",
            options: [
                "美化它",
                "识别但不美化，记录边界以防止进一步扩散",
                "忽略它",
                "立即重写",
            ],
            answer: 1,
            rationale: "识别但不美化泥球，记录边界以防止进一步扩散。",
        },
        {
            id: "w13-3-q8",
            question: "上下文映射图应该多详细？",
            options: [
                "越详细越好",
                "创建小型、聚焦的映射图回答特定问题，而非尝试全面覆盖",
                "越简单越好",
                "固定格式",
            ],
            answer: 1,
            rationale: "创建'small, focused maps'回答特定问题，而非尝试全面覆盖。",
        },
        {
            id: "w13-3-q9",
            question: "ACL 符号在映射图中标注在哪里？",
            options: [
                "上游",
                "下游上下文",
                "两边",
                "中间",
            ],
            answer: 1,
            rationale: "ACL 标注在下游上下文，表示下游使用反腐层保护自己。",
        },
        {
            id: "w13-3-q10",
            question: "Context Mapper 是什么？",
            options: [
                "编程语言",
                "维护上下文映射图的工具",
                "数据库",
                "测试框架",
            ],
            answer: 1,
            rationale: "Context Mapper 是维护上下文映射图的工具，支持 DSL 语法。",
        },
        {
            id: "w13-3-q11",
            question: "OHS 模式有什么语义约束？",
            options: [
                "没有约束",
                "不能用于 Customer/Supplier 关系",
                "必须用于所有关系",
                "只能单独使用",
            ],
            answer: 1,
            rationale: "'The Open Host Service pattern is not applicable in a Customer/Supplier relationship'。",
        },
        {
            id: "w13-3-q12",
            question: "为不同利益相关者创建不同视图意味着什么？",
            options: [
                "创建多个系统",
                "根据受众需求创建不同粒度的映射图视图",
                "隐藏信息",
                "增加复杂度",
            ],
            answer: 1,
            rationale: "为不同利益相关者创建不同粒度的视图，因为不同受众需要不同详细程度。",
        },
    ],
    "w13-4": [
        {
            id: "w13-4-q1",
            question: "上下文映射结果应该用于什么？",
            options: [
                "只用于文档",
                "指导架构和集成设计决策",
                "只用于演示",
                "只用于审计",
            ],
            answer: 1,
            rationale: "上下文映射结果应指导架构和集成设计决策，而非仅作为文档。",
        },
        {
            id: "w13-4-q2",
            question: "哪些映射模式通常表示风险点？",
            options: [
                "Partnership",
                "Conformist 关系、大泥球区域、过大的共享内核",
                "Separate Ways",
                "Open Host Service",
            ],
            answer: 1,
            rationale: "Conformist 关系、大泥球区域、过大的共享内核都是风险点。",
        },
        {
            id: "w13-4-q3",
            question: "什么是 ADR？",
            options: [
                "自动部署规则",
                "架构决策记录（Architecture Decision Record）",
                "应用数据恢复",
                "异步数据复制",
            ],
            answer: 1,
            rationale: "ADR（Architecture Decision Record）用于记录基于映射的设计决策和理由。",
        },
        {
            id: "w13-4-q4",
            question: "将 Conformist 升级为 Customer/Supplier 是什么类型的优化？",
            options: [
                "性能优化",
                "关系优化，改善团队协作",
                "代码优化",
                "数据库优化",
            ],
            answer: 1,
            rationale: "将 Conformist 升级为 Customer/Supplier 是关系优化，改善下游团队的影响力和协作。",
        },
        {
            id: "w13-4-q5",
            question: "添加 ACL 的目的是什么？",
            options: [
                "提高性能",
                "保护下游模型不受上游变化影响",
                "减少代码",
                "简化部署",
            ],
            answer: 1,
            rationale: "添加 ACL 保护下游模型不受上游变化影响。",
        },
        {
            id: "w13-4-q6",
            question: "有多个优化机会时如何排序？",
            options: [
                "随机选择",
                "通常先处理最大风险",
                "按字母顺序",
                "按时间顺序",
            ],
            answer: 1,
            rationale: "多个优化机会时如何排序——通常先处理最大风险。",
        },
        {
            id: "w13-4-q7",
            question: "改变上下文关系有什么成本？",
            options: [
                "没有成本",
                "有实现成本，需要权衡",
                "只有时间成本",
                "只有金钱成本",
            ],
            answer: 1,
            rationale: "改变上下文关系（如添加 ACL）有实现成本，需要权衡收益和成本。",
        },
        {
            id: "w13-4-q8",
            question: "某些优化为什么需要组织层面的支持？",
            options: [
                "不需要组织支持",
                "因为涉及团队关系变化，不仅仅是技术变更",
                "只是技术问题",
                "只需要管理层批准",
            ],
            answer: 1,
            rationale: "某些优化需要组织层面的支持，因为涉及团队关系变化，不仅仅是技术变更。",
        },
        {
            id: "w13-4-q9",
            question: "如何度量上下文映射优化的效果？",
            options: [
                "代码行数",
                "团队满意度、集成问题数量等",
                "服务器数量",
                "文档页数",
            ],
            answer: 1,
            rationale: "度量上下文映射优化的效果可以通过团队满意度、集成问题数量等指标。",
        },
        {
            id: "w13-4-q10",
            question: "上下文映射是什么类型的文档？",
            options: [
                "静态文档",
                "活文档，需要随系统和组织演化而更新",
                "一次性文档",
                "只读文档",
            ],
            answer: 1,
            rationale: "上下文映射是活文档，需要随系统和组织演化而更新。",
        },
        {
            id: "w13-4-q11",
            question: "拆分大泥球的策略是什么？",
            options: [
                "忽略它",
                "逐步识别边界，提取独立的限界上下文",
                "重写所有代码",
                "删除系统",
            ],
            answer: 1,
            rationale: "拆分大泥球需要逐步识别边界，提取独立的限界上下文。",
        },
        {
            id: "w13-4-q12",
            question: "定期回顾映射图的目的是什么？",
            options: [
                "增加工作量",
                "确保映射反映当前系统状态，识别新的风险和机会",
                "满足审计要求",
                "生成报告",
            ],
            answer: 1,
            rationale: "定期回顾和更新映射图确保其反映当前系统状态，识别新的风险和机会。",
        },
    ],
}
