import type { LessonGuide } from "../types"
import type { QuizQuestion } from "@/lib/types"

export const week19Guides: Record<string, LessonGuide> = {
    "w19-1": {
        lessonId: "w19-1",
        background: [
            "【Organize 步骤】DDD Starter Modelling Process 的'Organize'步骤：构建与上下文边界对齐的自治团队。",
            "【Team Topologies】使用 Team Topologies 确保快速流动和清晰的责任。",
            "【领域专家整合】将领域专家整合到开发团队中，促进持续的知识共享。",
            "【协作文化】建立 DDD 文化需要组织层面的支持和持续的实践。",
            "【跨职能团队】团队应该是跨职能的，包含开发、测试、业务等角色。",
        ],
        keyDifficulties: [
            "【组织阻力】改变团队结构可能遇到组织阻力。",
            "【领域专家参与】确保领域专家持续参与开发过程是挑战。",
            "【知识传递】团队成员变动时的知识传递和统一语言维护。",
            "【远程协作】分布式团队的 DDD 协作更具挑战性。",
        ],
        handsOnPath: [
            "评估当前团队结构与上下文边界的对齐度",
            "识别需要调整的团队边界",
            "建立与领域专家的定期沟通机制",
            "创建统一语言的维护流程",
            "建立 EventStorming 等协作实践的常规节奏",
            "培训团队成员理解 DDD 概念",
            "建立知识传递和文档机制",
        ],
        selfCheck: [
            "团队结构如何与上下文边界对齐？",
            "如何确保领域专家的持续参与？",
            "如何在团队中建立 DDD 文化？",
            "什么是 Team Topologies？",
            "如何处理分布式团队的 DDD 协作？",
        ],
        extensions: [
            "学习 Team Topologies 的详细内容",
            "了解 Conway 定律与团队设计",
            "研究敏捷团队与 DDD 的结合",
            "探索分布式团队的协作工具",
        ],
        sourceUrls: [
            "https://github.com/ddd-crew/ddd-starter-modelling-process",
            "https://teamtopologies.com/",
        ],
    },
    "w19-2": {
        lessonId: "w19-2",
        background: [
            "【框架选择】支持 DDD 的框架可以简化实现，但框架不能替代设计思维。",
            "【Axon Framework】Axon 是流行的 DDD/CQRS/Event Sourcing 框架。",
            "【语言无关】DDD 是设计方法，可以用任何编程语言实现。",
            "【ORM 考量】选择 ORM 时需要考虑其对聚合持久化的支持。",
            "【消息中间件】事件驱动架构需要可靠的消息中间件支持。",
        ],
        keyDifficulties: [
            "【框架锁定】过度依赖框架可能导致供应商锁定。",
            "【学习曲线】DDD 框架通常有较高的学习曲线。",
            "【过度抽象】框架可能引入不必要的抽象层。",
            "【版本兼容】框架升级可能带来兼容性问题。",
        ],
        handsOnPath: [
            "评估项目对 DDD 框架的需求",
            "研究可选的 DDD 框架",
            "评估框架与现有技术栈的兼容性",
            "进行框架的原型验证",
            "考虑团队的学习成本",
            "制定框架使用规范",
            "建立框架升级策略",
        ],
        selfCheck: [
            "什么时候应该使用 DDD 框架？",
            "Axon Framework 提供什么功能？",
            "如何评估 DDD 框架？",
            "框架选择需要考虑什么因素？",
            "如何避免框架锁定？",
        ],
        extensions: [
            "学习 Axon Framework 的详细使用",
            "了解其他 DDD 框架（如 NestJS、Lagom）",
            "研究无框架的 DDD 实现",
            "探索事件存储的选择（EventStoreDB 等）",
        ],
        sourceUrls: [
            "https://docs.axoniq.io/reference-guide/",
            "https://www.eventstoredb.com/",
        ],
    },
    "w19-3": {
        lessonId: "w19-3",
        background: [
            "【模型演进】领域模型不是静态的，需要随着业务理解深入而演进。",
            "【重构信号】当代码不再准确反映领域或统一语言变化时，需要重构。",
            "【安全重构】重构应该有完善的测试覆盖，确保行为不变。",
            "【突破性重构】Eric Evans 提到'Refactoring Toward Deeper Insight'——向更深洞察的重构。",
            "【渐进式演进】大型重构应该分解为小步骤，渐进式进行。",
        ],
        keyDifficulties: [
            "【风险管理】大型模型重构可能引入 bug 或破坏现有功能。",
            "【业务连续性】重构期间需要保持业务连续性。",
            "【团队协调】跨团队的模型变更需要协调。",
            "【版本兼容】API 和事件的版本兼容性管理。",
        ],
        handsOnPath: [
            "识别模型需要演进的信号",
            "评估重构的范围和风险",
            "确保有足够的测试覆盖",
            "制定渐进式重构计划",
            "与领域专家验证新模型",
            "更新统一语言和文档",
            "通知相关团队和系统",
            "监控重构后的系统行为",
        ],
        selfCheck: [
            "什么时候需要演进领域模型？",
            "如何安全地重构领域模型？",
            "什么是'Refactoring Toward Deeper Insight'？",
            "如何管理 API 和事件的版本兼容？",
            "如何协调跨团队的模型变更？",
        ],
        extensions: [
            "学习《重构》书中的重构技术",
            "了解 Strangler Fig 模式",
            "研究事件版本化策略",
            "探索特性开关在重构中的应用",
        ],
        sourceUrls: [
            "https://www.domainlanguage.com/ddd/",
            "https://martinfowler.com/books/refactoring.html",
        ],
    },
    "w19-4": {
        lessonId: "w19-4",
        background: [
            "【渐进式采用】不需要一次性应用所有 DDD 概念，可以从核心域开始逐步推广。",
            "【从核心开始】优先在核心域应用 DDD，这里投资回报最高。",
            "【现有项目】在现有项目中可以逐步引入 DDD 概念，不需要完全重写。",
            "【试点项目】可以选择一个试点项目或模块先行验证 DDD 的价值。",
            "【成功标准】定义清晰的成功标准来评估 DDD 采用的效果。",
        ],
        keyDifficulties: [
            "【遗留系统】与遗留系统的集成是常见挑战。",
            "【团队技能差距】团队可能缺乏 DDD 经验，需要培训。",
            "【投资回报】向管理层证明 DDD 投资的价值。",
            "【持续推进】保持 DDD 实践的持续推进，避免半途而废。",
        ],
        handsOnPath: [
            "评估当前系统和团队的 DDD 准备度",
            "识别核心域作为 DDD 的起点",
            "选择试点项目或模块",
            "培训团队 DDD 基础概念",
            "逐步引入统一语言和领域建模",
            "总结经验教训，调整方法",
            "扩展到更多领域和团队",
        ],
        selfCheck: [
            "如何在现有项目中引入 DDD？",
            "为什么应该从核心域开始？",
            "如何选择 DDD 的试点项目？",
            "如何向管理层证明 DDD 的价值？",
            "如何处理与遗留系统的集成？",
        ],
        extensions: [
            "学习遗留系统现代化策略",
            "了解 Bubble Context 模式",
            "研究 DDD 的组织变革管理",
            "探索 DDD 培训和认证资源",
        ],
        sourceUrls: [
            "https://www.domainlanguage.com/ddd/",
            "https://github.com/ddd-crew/free-ddd-learning-resources",
        ],
    },
}

export const week19Quizzes: Record<string, QuizQuestion[]> = {
    "w19-1": [
        {
            id: "w19-1-q1",
            question: "'Organize'步骤的目标是什么？",
            options: [
                "编写代码",
                "构建与上下文边界对齐的自治团队",
                "设计数据库",
                "创建测试",
            ],
            answer: 1,
            rationale: "'Organize'步骤构建与上下文边界对齐的自治团队。",
        },
        {
            id: "w19-1-q2",
            question: "Team Topologies 用于什么？",
            options: [
                "代码结构",
                "确保快速流动和清晰的责任",
                "数据库设计",
                "测试策略",
            ],
            answer: 1,
            rationale: "使用 Team Topologies 确保快速流动和清晰的责任。",
        },
        {
            id: "w19-1-q3",
            question: "跨职能团队应该包含什么角色？",
            options: [
                "只有开发者",
                "开发、测试、业务等角色",
                "只有测试人员",
                "只有管理者",
            ],
            answer: 1,
            rationale: "团队应该是跨职能的，包含开发、测试、业务等角色。",
        },
        {
            id: "w19-1-q4",
            question: "如何促进领域专家的参与？",
            options: [
                "不需要领域专家",
                "将领域专家整合到开发团队中",
                "只在开始时邀请",
                "只通过邮件沟通",
            ],
            answer: 1,
            rationale: "将领域专家整合到开发团队中，促进持续的知识共享。",
        },
        {
            id: "w19-1-q5",
            question: "建立 DDD 文化需要什么？",
            options: [
                "只有工具",
                "组织层面的支持和持续的实践",
                "只有培训",
                "只有文档",
            ],
            answer: 1,
            rationale: "建立 DDD 文化需要组织层面的支持和持续的实践。",
        },
        {
            id: "w19-1-q6",
            question: "改变团队结构可能遇到什么挑战？",
            options: [
                "技术问题",
                "组织阻力",
                "网络问题",
                "工具问题",
            ],
            answer: 1,
            rationale: "改变团队结构可能遇到组织阻力。",
        },
        {
            id: "w19-1-q7",
            question: "团队成员变动时需要关注什么？",
            options: [
                "代码审查",
                "知识传递和统一语言维护",
                "数据库备份",
                "性能测试",
            ],
            answer: 1,
            rationale: "团队成员变动时的知识传递和统一语言维护是挑战。",
        },
        {
            id: "w19-1-q8",
            question: "分布式团队的 DDD 协作有什么特点？",
            options: [
                "更简单",
                "更具挑战性",
                "完全相同",
                "不需要协作",
            ],
            answer: 1,
            rationale: "分布式团队的 DDD 协作更具挑战性。",
        },
        {
            id: "w19-1-q9",
            question: "如何评估团队结构的合理性？",
            options: [
                "看代码量",
                "评估与上下文边界的对齐度",
                "看团队人数",
                "看工资",
            ],
            answer: 1,
            rationale: "评估当前团队结构与上下文边界的对齐度是重要步骤。",
        },
        {
            id: "w19-1-q10",
            question: "与领域专家应该建立什么机制？",
            options: [
                "只在紧急时联系",
                "定期沟通机制",
                "不需要沟通",
                "只通过邮件",
            ],
            answer: 1,
            rationale: "建立与领域专家的定期沟通机制是保持知识更新的关键。",
        },
        {
            id: "w19-1-q11",
            question: "统一语言需要什么维护流程？",
            options: [
                "不需要维护",
                "创建统一语言的维护流程",
                "自动维护",
                "一次性创建",
            ],
            answer: 1,
            rationale: "创建统一语言的维护流程确保语言的持续准确性。",
        },
        {
            id: "w19-1-q12",
            question: "Conway 定律与团队设计有什么关系？",
            options: [
                "没有关系",
                "系统设计反映组织结构，团队边界影响系统边界",
                "只影响代码",
                "只影响数据库",
            ],
            answer: 1,
            rationale: "Conway 定律指出系统设计反映组织结构，团队边界影响系统边界。",
        },
    ],
    "w19-2": [
        {
            id: "w19-2-q1",
            question: "DDD 框架能替代什么？",
            options: [
                "所有代码",
                "框架不能替代设计思维",
                "数据库",
                "测试",
            ],
            answer: 1,
            rationale: "框架可以简化实现，但框架不能替代设计思维。",
        },
        {
            id: "w19-2-q2",
            question: "Axon Framework 是什么？",
            options: [
                "前端框架",
                "流行的 DDD/CQRS/Event Sourcing 框架",
                "数据库",
                "测试框架",
            ],
            answer: 1,
            rationale: "Axon 是流行的 DDD/CQRS/Event Sourcing 框架。",
        },
        {
            id: "w19-2-q3",
            question: "DDD 可以用什么编程语言实现？",
            options: [
                "只有 Java",
                "任何编程语言",
                "只有 C#",
                "只有 Python",
            ],
            answer: 1,
            rationale: "DDD 是设计方法，可以用任何编程语言实现。",
        },
        {
            id: "w19-2-q4",
            question: "选择 ORM 时需要考虑什么？",
            options: [
                "只考虑性能",
                "对聚合持久化的支持",
                "只考虑价格",
                "只考虑流行度",
            ],
            answer: 1,
            rationale: "选择 ORM 时需要考虑其对聚合持久化的支持。",
        },
        {
            id: "w19-2-q5",
            question: "事件驱动架构需要什么支持？",
            options: [
                "只需要代码",
                "可靠的消息中间件",
                "只需要数据库",
                "只需要缓存",
            ],
            answer: 1,
            rationale: "事件驱动架构需要可靠的消息中间件支持。",
        },
        {
            id: "w19-2-q6",
            question: "过度依赖框架可能导致什么？",
            options: [
                "更好的性能",
                "供应商锁定",
                "更简单的代码",
                "更快的开发",
            ],
            answer: 1,
            rationale: "过度依赖框架可能导致供应商锁定。",
        },
        {
            id: "w19-2-q7",
            question: "DDD 框架通常有什么特点？",
            options: [
                "学习曲线低",
                "学习曲线较高",
                "不需要学习",
                "自动完成一切",
            ],
            answer: 1,
            rationale: "DDD 框架通常有较高的学习曲线。",
        },
        {
            id: "w19-2-q8",
            question: "框架升级可能带来什么问题？",
            options: [
                "没有问题",
                "兼容性问题",
                "性能提升",
                "自动完成",
            ],
            answer: 1,
            rationale: "框架升级可能带来兼容性问题。",
        },
        {
            id: "w19-2-q9",
            question: "评估框架时应该考虑什么？",
            options: [
                "只考虑价格",
                "与现有技术栈的兼容性",
                "只考虑流行度",
                "只考虑文档",
            ],
            answer: 1,
            rationale: "评估框架与现有技术栈的兼容性是重要考量。",
        },
        {
            id: "w19-2-q10",
            question: "选择框架前应该做什么？",
            options: [
                "直接使用",
                "进行框架的原型验证",
                "不需要验证",
                "只看文档",
            ],
            answer: 1,
            rationale: "进行框架的原型验证是选择框架的重要步骤。",
        },
        {
            id: "w19-2-q11",
            question: "如何避免框架锁定？",
            options: [
                "不使用框架",
                "评估退出成本，保持核心逻辑独立",
                "使用所有框架",
                "忽略锁定风险",
            ],
            answer: 1,
            rationale: "评估退出成本并保持核心逻辑独立可以降低框架锁定风险。",
        },
        {
            id: "w19-2-q12",
            question: "EventStoreDB 用于什么？",
            options: [
                "关系数据存储",
                "事件存储",
                "缓存",
                "消息队列",
            ],
            answer: 1,
            rationale: "EventStoreDB 是专用的事件存储数据库。",
        },
    ],
    "w19-3": [
        {
            id: "w19-3-q1",
            question: "领域模型是静态的吗？",
            options: [
                "是",
                "不是，需要随着业务理解深入而演进",
                "只在开始时变化",
                "永不变化",
            ],
            answer: 1,
            rationale: "领域模型不是静态的，需要随着业务理解深入而演进。",
        },
        {
            id: "w19-3-q2",
            question: "什么时候需要重构领域模型？",
            options: [
                "从不重构",
                "当代码不再准确反映领域或统一语言变化时",
                "每天重构",
                "只在开始时",
            ],
            answer: 1,
            rationale: "当代码不再准确反映领域或统一语言变化时，需要重构。",
        },
        {
            id: "w19-3-q3",
            question: "安全重构需要什么？",
            options: [
                "不需要测试",
                "完善的测试覆盖",
                "更多开发者",
                "更多服务器",
            ],
            answer: 1,
            rationale: "重构应该有完善的测试覆盖，确保行为不变。",
        },
        {
            id: "w19-3-q4",
            question: "什么是'Refactoring Toward Deeper Insight'？",
            options: [
                "代码优化",
                "向更深洞察的重构",
                "性能优化",
                "数据库优化",
            ],
            answer: 1,
            rationale: "Eric Evans 提到'Refactoring Toward Deeper Insight'——向更深洞察的重构。",
        },
        {
            id: "w19-3-q5",
            question: "大型重构应该如何进行？",
            options: [
                "一次完成",
                "分解为小步骤，渐进式进行",
                "不进行大型重构",
                "外包给其他团队",
            ],
            answer: 1,
            rationale: "大型重构应该分解为小步骤，渐进式进行。",
        },
        {
            id: "w19-3-q6",
            question: "大型模型重构可能带来什么风险？",
            options: [
                "没有风险",
                "引入 bug 或破坏现有功能",
                "性能提升",
                "代码减少",
            ],
            answer: 1,
            rationale: "大型模型重构可能引入 bug 或破坏现有功能。",
        },
        {
            id: "w19-3-q7",
            question: "重构期间需要保持什么？",
            options: [
                "代码冻结",
                "业务连续性",
                "团队不变",
                "不发布",
            ],
            answer: 1,
            rationale: "重构期间需要保持业务连续性。",
        },
        {
            id: "w19-3-q8",
            question: "跨团队的模型变更需要什么？",
            options: [
                "单方面决定",
                "协调",
                "不需要沟通",
                "自动完成",
            ],
            answer: 1,
            rationale: "跨团队的模型变更需要协调。",
        },
        {
            id: "w19-3-q9",
            question: "重构后应该做什么？",
            options: [
                "不需要做什么",
                "监控重构后的系统行为",
                "立即开始下一个重构",
                "删除测试",
            ],
            answer: 1,
            rationale: "监控重构后的系统行为是确保重构成功的重要步骤。",
        },
        {
            id: "w19-3-q10",
            question: "新模型应该与谁验证？",
            options: [
                "只有开发者",
                "领域专家",
                "只有测试人员",
                "只有管理层",
            ],
            answer: 1,
            rationale: "与领域专家验证新模型确保模型的业务准确性。",
        },
        {
            id: "w19-3-q11",
            question: "模型演进后应该更新什么？",
            options: [
                "只有代码",
                "统一语言和文档",
                "只有数据库",
                "什么都不更新",
            ],
            answer: 1,
            rationale: "更新统一语言和文档是模型演进后的重要步骤。",
        },
        {
            id: "w19-3-q12",
            question: "Strangler Fig 模式用于什么？",
            options: [
                "新系统开发",
                "渐进式替换遗留系统",
                "性能优化",
                "数据库迁移",
            ],
            answer: 1,
            rationale: "Strangler Fig 模式用于渐进式替换遗留系统。",
        },
    ],
    "w19-4": [
        {
            id: "w19-4-q1",
            question: "引入 DDD 需要一次性应用所有概念吗？",
            options: [
                "是",
                "不需要，可以从核心域开始逐步推广",
                "必须一次完成",
                "不能分步",
            ],
            answer: 1,
            rationale: "不需要一次性应用所有 DDD 概念，可以从核心域开始逐步推广。",
        },
        {
            id: "w19-4-q2",
            question: "为什么应该优先在核心域应用 DDD？",
            options: [
                "核心域最简单",
                "核心域投资回报最高",
                "核心域代码最少",
                "核心域不重要",
            ],
            answer: 1,
            rationale: "优先在核心域应用 DDD，这里投资回报最高。",
        },
        {
            id: "w19-4-q3",
            question: "在现有项目中引入 DDD 需要完全重写吗？",
            options: [
                "是，必须重写",
                "不需要，可以逐步引入 DDD 概念",
                "只能新项目用",
                "不能在现有项目用",
            ],
            answer: 1,
            rationale: "在现有项目中可以逐步引入 DDD 概念，不需要完全重写。",
        },
        {
            id: "w19-4-q4",
            question: "什么是试点项目？",
            options: [
                "最大的项目",
                "先行验证 DDD 价值的项目或模块",
                "最小的项目",
                "最老的项目",
            ],
            answer: 1,
            rationale: "可以选择一个试点项目或模块先行验证 DDD 的价值。",
        },
        {
            id: "w19-4-q5",
            question: "评估 DDD 采用效果需要什么？",
            options: [
                "主观感觉",
                "清晰的成功标准",
                "代码量",
                "团队人数",
            ],
            answer: 1,
            rationale: "定义清晰的成功标准来评估 DDD 采用的效果。",
        },
        {
            id: "w19-4-q6",
            question: "与遗留系统的集成是什么？",
            options: [
                "简单任务",
                "常见挑战",
                "不需要集成",
                "自动完成",
            ],
            answer: 1,
            rationale: "与遗留系统的集成是常见挑战。",
        },
        {
            id: "w19-4-q7",
            question: "团队缺乏 DDD 经验时应该怎么办？",
            options: [
                "放弃 DDD",
                "需要培训",
                "忽略问题",
                "外包实现",
            ],
            answer: 1,
            rationale: "团队可能缺乏 DDD 经验，需要培训。",
        },
        {
            id: "w19-4-q8",
            question: "如何向管理层证明 DDD 的价值？",
            options: [
                "不需要证明",
                "定义成功标准并展示投资回报",
                "只说好处",
                "不告诉管理层",
            ],
            answer: 1,
            rationale: "向管理层证明 DDD 投资的价值需要定义成功标准并展示投资回报。",
        },
        {
            id: "w19-4-q9",
            question: "如何保持 DDD 实践的持续推进？",
            options: [
                "一次性完成",
                "持续实践，避免半途而废",
                "只在开始时推进",
                "不需要持续",
            ],
            answer: 1,
            rationale: "保持 DDD 实践的持续推进，避免半途而废。",
        },
        {
            id: "w19-4-q10",
            question: "渐进式采用 DDD 的第一步是什么？",
            options: [
                "全面重写",
                "评估当前系统和团队的 DDD 准备度",
                "购买工具",
                "招聘专家",
            ],
            answer: 1,
            rationale: "评估当前系统和团队的 DDD 准备度是渐进式采用的第一步。",
        },
        {
            id: "w19-4-q11",
            question: "什么是 Bubble Context？",
            options: [
                "气泡图",
                "在遗留系统中创建的隔离的新上下文",
                "数据库",
                "测试环境",
            ],
            answer: 1,
            rationale: "Bubble Context 是在遗留系统中创建的隔离的新上下文，用于引入 DDD。",
        },
        {
            id: "w19-4-q12",
            question: "扩展 DDD 实践前应该做什么？",
            options: [
                "直接扩展",
                "总结经验教训，调整方法",
                "不需要总结",
                "忽略问题",
            ],
            answer: 1,
            rationale: "总结经验教训，调整方法是扩展 DDD 实践前的重要步骤。",
        },
    ],
}
