import type { QuizQuestion } from "../types";

export const week1: Record<string, QuizQuestion[]> = {
  "tw-w1-1": [
    {
      id: "tw-w1-1-q1",
      question: "Write the Docs 指出，为什么“6个月后的自己”也是文档的重要读者？",
      options: [
        "因为人类记忆不可靠，文档是代码意图的快照，能帮助未来的开发者（包括自己）快速回溯上下文",
        "为了满足公司 KPI 要求",
        "为了练习打字速度",
        "因为代码会自动变异",
      ],
      answer: 0,
      rationale: "Write the Docs: Your code from 6 months ago looks like code that someone else wrote.",
    },
    {
      id: "tw-w1-1-q2",
      question: "关于“FAQ（常见问题解答）”作为文档形式，Write the Docs 持什么观点？",
      options: [
        "应尽量避免过度依赖 FAQ，因为它们容易过时、难以检索且往往积压杂乱内容",
        "FAQ 是最好的文档形式，应包含所有内容",
        "每个项目启动时必须先写 FAQ",
        "FAQ 可以完全替代 API 文档",
      ],
      answer: 0,
      rationale: "Write the Docs: FAQs quickly outgrow their use (outdated, disparate content, hard to search).",
    },
    {
      id: "tw-w1-1-q3",
      question: "技术文档如何帮助提升代码质量（Improve your code）？",
      options: [
        "写作过程强迫开发者理清逻辑与 API 设计，将隐性假设显性化，从而反向优化架构",
        "文档越长，代码质量越高",
        "写文档能自动修复 Bug",
        "为了让代码看起来更复杂",
      ],
      answer: 0,
      rationale: "Write the Docs: The process of creating documentation requires focused thought that improves code design.",
    },
    {
      id: "tw-w1-1-q4",
      question: "对于“Users”（用户）这类读者，他们最关心什么？",
      options: [
        "如何使用代码来解决问题，通常不关心内部实现细节",
        "代码使用了哪种设计模式",
        "具体的内存分配算法",
        "贡献指南",
      ],
      answer: 0,
      rationale: "Write the Docs: Users want to use your code and don’t care how it works.",
    },
    {
      id: "tw-w1-1-q5",
      question: "对于“Developers”（潜在贡献者）这类读者，他们最关心什么？",
      options: [
        "如何搭建开发环境、测试以及提交代码（贡献流程）",
        "软件的购买价格",
        "仅仅是安装使用",
        "最终用户的业务场景",
      ],
      answer: 0,
      rationale: "Write the Docs: Developers want to contribute to your code.",
    },
    {
      id: "tw-w1-1-q6",
      question: "如果用户找不到安装说明（Installation Instructions），最可能的后果是？",
      options: [
        "用户会直接放弃使用该项目",
        "用户会通过阅读源码自己通过猜想安装",
        "用户会发邮件赞赏作者",
        "用户会自动获得 root 权限",
      ],
      answer: 0,
      rationale: "Write the Docs: They can’t find how to install your code -> They won’t use your code.",
    },
    {
      id: "tw-w1-1-q7",
      question: "一份好的软件文档入门（README）通常应包含哪个关键要素以展示项目价值？",
      options: [
        "Show what problem your code solves（项目解决什么问题）",
        "作者的个人自传",
        "项目的文件树结构图（无解释）",
        "所有依赖库的源码",
      ],
      answer: 0,
      rationale: "Write the Docs: Show what problem your code solves.",
    },
    {
      id: "tw-w1-1-q8",
      question: "为什么说技术写作是一项需要专门练习的技能？",
      options: [
        "它需要不同于编程的逻辑表达能力与同理心，能将复杂概念转化为易懂的语言",
        "因为它需要背诵字典",
        "因为它不需要逻辑",
        "只要会写代码就天生会写文档",
      ],
      answer: 0,
      rationale: "Write the Docs: Technical writing is a useful skill... but it requires different writing skills than most people have naturally.",
    },
    {
      id: "tw-w1-1-q9",
      question: "在开源项目中，文档对“Contributors”有什么特殊价值？",
      options: [
        "降低参与门槛，对于初次贡献者来说，修改文档往往比修改代码更容易上手",
        "用来以此筛选掉不聪明的开发者",
        "文档只是摆设",
        "强制贡献者必须先付费",
      ],
      answer: 0,
      rationale: "Write the Docs: Documentation changes may be easier than code changes for people who have never contributed.",
    },
    {
      id: "tw-w1-1-q10",
      question: "Diátaxis 框架强调文档的四大分类，其中“Tutorials”的核心目的是？",
      options: [
        "Learning（学习）：手把手带读者完成一个特定任务，建立信心与直觉",
        "Work（工作）：解决具体生产问题",
        "Information（信息）：查阅事实",
        "Explanation（理解）：深入探讨原理",
      ],
      answer: 0,
      rationale: "Diátaxis: A tutorial is a lesson... designed around an encounter that the learner can make sense of.",
    },
    {
      id: "tw-w1-1-q11",
      question: "文档中提供“Small code example”的主要作用是？",
      options: [
        "让用户快速看到代码的实际模样与用法，降低认知门槛",
        "增加文档的字数",
        "展示作者的编程技巧复杂性",
        "用来占位",
      ],
      answer: 0,
      rationale: "Write the Docs: Provide a small code example.",
    },
    {
      id: "tw-w1-1-q12",
      question: "为什么需要明确“License”（许可证）信息？",
      options: [
        "明确用户使用、修改与分发代码的法律边界与权利",
        "为了看起来更正式",
        "为了限制用户阅读代码",
        "没有任何作用",
      ],
      answer: 0,
      rationale: "Write the Docs: State your project’s license.",
    },
    {
      id: "tw-w1-1-q13",
      question: "当用户遇到问题时，“Tell people how to get support”为何重要？",
      options: [
        "避免用户感到孤立无援，提供清晰的求助渠道（如 Issue、邮件、聊天室）",
        "为了收集用户的隐私",
        "为了向用户收费",
        "因为软件永远不会出 Bug",
      ],
      answer: 0,
      rationale: "Write the Docs: Tell people how to get support.",
    },
    {
      id: "tw-w1-1-q14",
      question: "Write the Docs 建议从哪里开始练习技术写作？",
      options: [
        "Start simple（从简单的开始），例如 README 或简单的修正",
        "直接写一本 500 页的书",
        "先去考取语言学学位",
        "等待成为架构师后再写",
      ],
      answer: 0,
      rationale: "Write the Docs: Start simple to achieve the best results.",
    },
    {
      id: "tw-w1-1-q15",
      question: "FAQ 的主要缺点之一是“Accumulate disparate content on unrelated topics”，这意味着？",
      options: [
        "FAQ 往往变成杂乱无章的大杂烩，缺乏逻辑结构，难以系统阅读",
        "FAQ 内容太少",
        "FAQ 过于专业",
        "FAQ 只能写英文",
      ],
      answer: 0,
      rationale: "Write the Docs: Accumulate disparate content on unrelated topics.",
    },
    {
      id: "tw-w1-1-q16",
      question: "一个好的 Issue Tracker 链接在文档中的作用是？",
      options: [
        "让用户能反馈 Bug 或查看已知问题，增加项目的透明度与互动",
        "展示作者很忙",
        "用来发布广告",
        "没有任何作用",
      ],
      answer: 0,
      rationale: "Write the Docs: Link to your code and issue tracker.",
    },
    {
      id: "tw-w1-1-q17",
      question: "Diátaxis 中，“How-to guides”与“Tutorials”的关键区别是？",
      options: [
        "How-to 面向已有一点基础的用户解决具体工作问题；Tutorials 面向初学者进行教学",
        "两者完全一样",
        "How-to 是给机器看的，Tutorials 是给人看的",
        "Tutorials 不需要步骤，How-to 需要",
      ],
      answer: 0,
      rationale: "Diátaxis: A how-to guide addresses a real-world goal... A tutorial is a lesson.",
    },
    {
      id: "tw-w1-1-q18",
      question: "Diátaxis 中，“Reference”文档的特点是？",
      options: [
        "Information-oriented：准确、客观的事实描述，不包含过多解释或指导",
        "包含大量个人观点",
        "手把手教学",
        "解决具体业务问题",
      ],
      answer: 0,
      rationale: "Diátaxis: Reference guides contain the technical description - facts.",
    },
    {
      id: "tw-w1-1-q19",
      question: "Diátaxis 中，“Explanation”文档主要负责？",
      options: [
        "Understanding：解释背景、原理、设计决策，帮助读者建立心理模型",
        "列出 API 参数",
        "指导安装",
        "快速入门",
      ],
      answer: 0,
      rationale: "Diátaxis: Explanation (Understanding).",
    },
    {
      id: "tw-w1-1-q20",
      question: "如果一个项目缺乏文档，Write the Docs 认为最直接的后果是？",
      options: [
        "人们因为不知道它做什么、怎么用而不会去使用它",
        "人们会更喜欢它",
        "代码运行速度变慢",
        "编译失败",
      ],
      answer: 0,
      rationale: "Write the Docs: If you love your project, document it so others can use it.",
    },
    {
      id: "tw-w1-1-q21",
      question: "好的文档能如何帮助“Scale”用户支持？",
      options: [
        "通过回答常见问题和提供自服务指南，减少重复的咨询与工单",
        "并没有帮助",
        "增加支持团队的工作量",
        "让用户更困惑",
      ],
      answer: 0,
      rationale: "Inferred from 'Get people to use your code' and reducing support burden.",
    },
    {
      id: "tw-w1-1-q22",
      question: "在写 README 时，Community / Contributing 部分通常包括？",
      options: [
        "Code of Conduct（行为准则）、贡献流程与联系方式",
        "作者的自拍照",
        "天气预报",
        "无关的新闻",
      ],
      answer: 0,
      rationale: "Standard practice for contributing sections.",
    },
    {
      id: "tw-w1-1-q23",
      question: "技术写作中“Know your audience”意味着？",
      options: [
        "根据读者的技术水平（小白 vs 专家）和目标调整内容的深度与语气",
        "只写给自己看",
        "假设读者什么都懂",
        "假设读者什么都不懂",
      ],
      answer: 0,
      rationale: "Write the Docs: Know which of these common audiences you’re writing for.",
    },
    {
      id: "tw-w1-1-q24",
      question: "为何 Write the Docs 建议“Start simple”？",
      options: [
        "避免因追求完美而迟迟不发布，迭代改进优于没有文档",
        "因为简单的文档没人看",
        "因为复杂的文档会被收费",
        "为了省纸",
      ],
      answer: 0,
      rationale: "Write the Docs: Start simple to achieve the best results.",
    },
    {
      id: "tw-w1-1-q25",
      question: "Markdown 在技术写作中流行的主要原因是？",
      options: [
        "纯文本格式，易通过 Git 版本控制，且能专注于内容结构而非排版",
        "因为它是最复杂的格式",
        "因为它支持 3D 动画",
        "因为它是 Word 文档的变体",
      ],
      answer: 0,
      rationale: "Standard knowledge implicitly supported by 'Tools for writing' section.",
    },
    {
      id: "tw-w1-1-q26",
      question: "文档中的“Prerequisites”（前置条件）部分用于？",
      options: [
        "告知用户在开始前需要准备的环境、工具或知识，避免中途受阻",
        "劝退用户",
        "增加文档长度",
        "测试用户的耐心",
      ],
      answer: 0,
      rationale: "Essential for 'Installation' and 'How-to'.",
    },
    {
      id: "tw-w1-1-q27",
      question: "Write the Docs 提到，文档和代码注释的区别是？",
      options: [
        "注释解释代码的实现细节（How），文档解释代码的用途与背景（Why & Usage）",
        "没有区别",
        "注释是给用户看的，文档是给编译器看的",
        "文档必须写在代码文件里",
      ],
      answer: 0,
      rationale: "Just like code comments explain the why and not the how (context), software docs states the why behind the code.",
    },
    {
      id: "tw-w1-1-q28",
      question: "若发现文档中有错误，开源社区鼓励的最佳做法是？",
      options: [
        "提交 Pull Request 修复它，这不仅帮助了项目，也是参与贡献的好方式",
        "假装没看见",
        "在社交媒体上嘲笑作者",
        "放弃使用该项目",
      ],
      answer: 0,
      rationale: "Supported by 'Increase contributions'.",
    },
    {
      id: "tw-w1-1-q29",
      question: "Technical Writer（技术传播者）的角色核心是？",
      options: [
        "作为产品与用户之间的桥梁，转化复杂信息为可用知识",
        "专门纠正错别字",
        "负责编写代码逻辑",
        "负责销售产品",
      ],
      answer: 0,
      rationale: "General definition aligns with Write the Docs goals.",
    },
    {
      id: "tw-w1-1-q30",
      question: "关于文档维护，以下哪种心态是正确的？",
      options: [
        "文档是活的（Living documentation），需随着代码迭代持续更新",
        "文档写完一次就永久归档",
        "只有发布大版本才更新文档",
        "文档更新落后于代码没关系",
      ],
      answer: 0,
      rationale: "Implicit in 'Improve your code' and 'Outdated FAQs'.",
    },
  ],
  "tw-w1-2": [
    {
      id: "tw-w1-2-q1",
      question: "NN/G 定义的“Persona”（用户画像）主要由什么构成？",
      options: [
        "基于真实数据的虚构典型用户描述，包含行为、目标、技能与痛点",
        "公司 CEO 的个人喜好",
        "市场营销部门的广告口号",
        "完全随机生成的虚构人物",
      ],
      answer: 0,
      rationale: "NN/G: A persona is a fictional, yet realistic, description of a typical or target user... containing behaviors, needs, concerns, goals.",
    },
    {
      id: "tw-w1-2-q2",
      question: "为什么说“The Elastic User”（弹性用户）是设计与写作中的陷阱？",
      options: [
        "因为试图满足所有人（Everybody）往往意味着谁都无法满足（Nobody），导致产品或文档缺乏重点",
        "因为弹性用户适应力很强，不需要文档",
        "因为弹性用户会像橡胶一样反弹",
        "因为用户会经常改名",
      ],
      answer: 0,
      rationale: "Designing for 'everyone' leads to generic, ineffective solutions. Personas force specificity.",
    },
    {
      id: "tw-w1-2-q3",
      question: "“Curse of Knowledge”（知识的诅咒）主要指的是技术专家在写作时容易犯什么错误？",
      options: [
        "默认读者拥有与自己相同的背景知识，从而省略了必要的上下文",
        "写的内容太浅显",
        "使用的词汇太简单",
        "忘记怎么写代码",
      ],
      answer: 0,
      rationale: "Google Tech Writing: Experts assume others have the background to understand what they do.",
    },
    {
      id: "tw-w1-2-q4",
      question: "对于“Novice”（新手）读者，最有效的文档形式通常是？",
      options: [
        "Tutorials（教程）：通过具体的步骤建立信心",
        "API Reference（参考手册）：列出所有参数",
        "Architecture Docs（架构文档）：展示系统全貌",
        "Source Code（源代码）：直接看代码",
      ],
      answer: 0,
      rationale: "Diátaxis: Tutorials are success-oriented lessons for beginners (acquisition of skills).",
    },
    {
      id: "tw-w1-2-q5",
      question: "对于“Expert”（专家）读者，他们更倾向于查阅哪种文档？",
      options: [
        "Reference（参考手册）：快速检索准确信息（如参数、配置项）",
        "Hello World 教程",
        "冗长的背景介绍",
        "营销软文",
      ],
      answer: 0,
      rationale: "Diátaxis: Reference guides serve users who are at work and need facts.",
    },
    {
      id: "tw-w1-2-q6",
      question: "进行读者分析（Audience Analysis）时，首先要问的关键问题是？",
      options: [
        "Who are they?（他们是谁） & What do they need to do?（他们要做什么）",
        "How much money do they have?（他们有多少钱）",
        "What is their favorite color?（他们喜欢什么颜色）",
        "Do they like pizza?（他们喜欢披萨吗）",
      ],
      answer: 0,
      rationale: "Core questions: Who is the reader? Why are they reading?",
    },
    {
      id: "tw-w1-2-q7",
      question: "如果文档中使用了“Prerequisites”（前置知识）章节，这主要是在解决什么问题？",
      options: [
        "显性化假设，告知读者阅读本文档所需的最低知识门槛或环境要求",
        "为了凑字数",
        "为了恐吓读者",
        "为了展示作者的博学",
      ],
      answer: 0,
      rationale: "Addressing the knowledge gap/setting expectations.",
    },
    {
      id: "tw-w1-2-q8",
      question: "在 Tech Writing 中，Quality（质量）的最佳定义是？",
      options: [
        "Fitness for purpose（合目的性）：文档能否有效帮助目标读者达成目标",
        "使用了多少高级词汇",
        "文档的长度（越长越好）",
        "是否使用了彩色字体",
      ],
      answer: 0,
      rationale: "Core principle: Utility over specific style mandates.",
    },
    {
      id: "tw-w1-2-q9",
      question: "针对“Decision Makers”（决策者/高管）的文档，最重要的特点应该是？",
      options: [
        "High-level benefit & cost analysis（高层收益/成本分析），避免陷入技术细节",
        "展示底层代码实现",
        "详细的安装步骤",
        "复杂的数学公式",
      ],
      answer: 0,
      rationale: "Executives focus on business value and decisions.",
    },
    {
      id: "tw-w1-2-q10",
      question: "当读者群的技术水平参差不齐（Mixed Audience）时，最佳的处理策略是？",
      options: [
        "分层写作：提供概览（Overview）给所有人，将深层细节（Deep Dive）放入链接或后续章节；或拆分为不同文档",
        "取平均值，写的不深不浅",
        "只写给专家看，让小白自己通过 Google 补课",
        "只写给小白看，忽略专家需求",
      ],
      answer: 0,
      rationale: "Handling mixed audiences requires layering or separating content.",
    },
    {
      id: "tw-w1-2-q11",
      question: "Persona 中的“Pain Points”（痛点）对文档写作有什么指导意义？",
      options: [
        "帮助作者识别读者最急需解决的问题，从而优先编写相关 Troubleshooting 或 How-to Guide",
        "为了挖掘用户的隐私",
        "为了让作者感到快乐",
        "没有任何意义",
      ],
      answer: 0,
      rationale: "addressing pain points increases relevance and engagement.",
    },
    {
      id: "tw-w1-2-q12",
      question: "“User Story”在文档规划中的常见格式是？",
      options: [
        "As a [role], I want to [action], so that [benefit]（作为...我想...以便...）",
        "I will write about...",
        "Once upon a time...",
        "TODO: fix this",
      ],
      answer: 0,
      rationale: "Standard Agile format useful for docs planning too.",
    },
    {
      id: "tw-w1-2-q13",
      question: "Google Technical Writing 建议如何定义必要的背景知识？",
      options: [
        "Link out（提供链接）：不要在文档里重新解释基础概念，而是链接到权威来源",
        "在每个文档里都从头解释一遍 TCP/IP 协议",
        "假设读者什么都懂",
        "让读者自己去猜",
      ],
      answer: 0,
      rationale: "Efficiently managing scope and prerequisites.",
    },
    {
      id: "tw-w1-2-q14",
      question: "对于“Operators/Sysadmins”（运维人员），他们最关注的文档内容通常是？",
      options: [
        "Deployment, Configuration, Monitoring, Backup/Restore（部署、配置、监控、备份）",
        "算法的时间复杂度",
        "UI 的颜色代码",
        "产品的销售策略",
      ],
      answer: 0,
      rationale: "Role-specific needs: Maintaining the system.",
    },
    {
      id: "tw-w1-2-q15",
      question: "为什么说“Understanding the User's Goal”（理解用户目标）比“Understanding the Software”（理解软件）更重要？",
      options: [
        "软件只是手段，解决用户的问题才是目的。只懂软件写出来的是“System-oriented”（功能说明书），懂用户才能写出“Task-oriented”（任务指南）",
        "因为软件永远是对的",
        "因为用户永远是对的",
        "为了反驳开发人员",
      ],
      answer: 0,
      rationale: "Task-oriented vs System-oriented distinction.",
    },
    {
      id: "tw-w1-2-q16",
      question: "一份面向外部开发者的 API 文档，最忌讳的是？",
      options: [
        "暴露内部实现细节或依赖内部特有的工具/环境",
        "提供太多示例代码",
        "使用了正确的 HTTP 状态码",
        "包含错误响应的说明",
      ],
      answer: 0,
      rationale: "Audience constraint: External users cannot see/use internal tools.",
    },
    {
      id: "tw-w1-2-q17",
      question: "NN/G 提到，Personas 能帮助团队建立“Common Vocabulary”（共同语言），这意味着？",
      options: [
        "团队成员在讨论时可以说“这对 Persona A 目前太难了”，而非模糊的“用户可能会觉得难”",
        "大家使用同一种编程语言",
        "大家因为 Persona 而经常吵架",
        "Persona 是一个真实存在的人",
      ],
      answer: 0,
      rationale: "NN/G: In meetings, the persona’s name acts as shorthand.",
    },
    {
      id: "tw-w1-2-q18",
      question: "在国际化（Localization）场景下，Audience Analysis 需要考虑？",
      options: [
        "文化差异、语言习惯（避免俚语）、日期/数字格式等",
        "只是翻译一下单词",
        "所有人都懂英文，不需要考虑",
        "不同国家的时区",
      ],
      answer: 0,
      rationale: "Cultural sensitivity is part of audience analysis.",
    },
    {
      id: "tw-w1-2-q19",
      question: "Diátaxis 认为“Needs”（需求）决定了文档的形态。如果用户在其工作中遇到阻碍，他的需求是？",
      options: [
        "Practical directions (How-to guide) to solve the specific problem",
        "Theoretical explanation of the universe",
        "A rigid tutorial",
        "A dictionary definition",
      ],
      answer: 0,
      rationale: "How-to guides address work-related problems/goals.",
    },
    {
      id: "tw-w1-2-q20",
      question: "如果 Persona 是“Internal Developer”（内部开发者），文档可以包含？",
      options: [
        "内部架构图、私有仓库链接、内部部署流程",
        "公司股价信息",
        "竞争对手的机密",
        "CEO 的家庭住址",
      ],
      answer: 0,
      rationale: "Internal audience assumes access to internal resources.",
    },
    {
      id: "tw-w1-2-q21",
      question: "“Empathy”（同理心）在技术写作中的具体体现是？",
      options: [
        "预判读者的挫败感，在容易出错的地方给出提示（Note/Warning），并使用包容性语言",
        "替读者写代码",
        "在文档里写笑话",
        "同情读者的遭遇但不提供帮助",
      ],
      answer: 0,
      rationale: "Empathy drives helpful, anticipatory documentation.",
    },
    {
      id: "tw-w1-2-q22",
      question: "当用户只是想“Evaluate”（评估）技术是否适合自己时，他们最看重？",
      options: [
        "Overview（概览）、Use Cases（适用场景）与 Comparison（对比/优缺点）",
        "详细的 API 参数表",
        "低层源码实现",
        "贡献者名单",
      ],
      answer: 0,
      rationale: "Evaluation phase needs high-level fit info.",
    },
    {
      id: "tw-w1-2-q23",
      question: "如果你的文档充斥着“Industry Jargon”（行业黑话），这通常意味着？",
      options: [
        "你假设读者是业内资深人士（或者你犯了知识诅咒的错误）",
        "你的文档非常高级",
        "你的文档无法被翻译",
        "你是行业领袖",
      ],
      answer: 0,
      rationale: "Jargon assumes specific audience knowledge.",
    },
    {
      id: "tw-w1-2-q24",
      question: "User Journey Map（用户旅程图）如何辅助文档写作？",
      options: [
        "揭示用户从“发现”到“精通”的全过程，帮助规划文档的阅读顺序与链接结构",
        "用来画插图",
        "作为旅游指南",
        "用来记录用户的点击量",
      ],
      answer: 0,
      rationale: "User Journey aligns docs structure with user lifecycle.",
    },
    {
      id: "tw-w1-2-q25",
      question: "对于“Visual Learners”（视觉型学习者），最友好的文档元素是？",
      options: [
        "Diagrams（图表）、Screenshots（截图）与 Screencasts（录屏）",
        "大量的纯文本",
        "复杂的表格",
        "音频文件",
      ],
      answer: 0,
      rationale: "Audience preference: Visuals.",
    },
    {
      id: "tw-w1-2-q26",
      question: "Secondary Audience（次要读者）是指？",
      options: [
        "那些不是文档主要目标，但可能偶然查阅或间接受益的人（如非技术型的项目经理）",
        "读者的宠物",
        "文档的第二作者",
        "不喜欢该产品的人",
      ],
      answer: 0,
      rationale: "Definition of secondary audience.",
    },
    {
      id: "tw-w1-2-q27",
      question: "Persona 并非一成不变，这意味着？",
      options: [
        "随着产品迭代和市场变化，需定期更新 Persona",
        "Persona 每天都要换",
        "Persona 是虚构的所以无所谓",
        "用户会变老",
      ],
      answer: 0,
      rationale: "Living documents/personas rule.",
    },
    {
      id: "tw-w1-2-q28",
      question: "在编写 CLI 帮助文档（--help）时，主要假设读者处于什么状态？",
      options: [
        "During the task（正在操作中），需要快速查阅语法或选项，不希望离开终端",
        "在咖啡厅休息",
        "准备学习该工具的历史",
        "正在编写该工具的源码",
      ],
      answer: 0,
      rationale: "Context of use: Immediate, rigorous, minimal context switching.",
    },
    {
      id: "tw-w1-2-q29",
      question: "“Accessibility”（无障碍性）属于 Audience Analysis 的一部分吗？",
      options: [
        "是，必须考虑使用屏幕阅读器、色盲等不同需求的用户",
        "不是，那是前端开发的事",
        "只有大公司才需要考虑",
        "只有盲人才用软件",
      ],
      answer: 0,
      rationale: "Accessibility is inclusive audience analysis.",
    },
    {
      id: "tw-w1-2-q30",
      question: "识别“Negative Persona”（反向画像/非目标用户）的作用是？",
      options: [
        "明确“我们可以不为谁服务”，从而节省资源，避免通过过度设计来取悦非核心用户",
        "为了歧视某些人",
        "为了建立黑名单",
        "没有任何作用",
      ],
      answer: 0,
      rationale: "Defining who you are NOT writing for helps focus.",
    },
  ],
  "tw-w1-3": [
    {
      id: "tw-w1-3-q1",
      question: "Diátaxis 框架的核心理念是将文档划分为哪四个象限？",
      options: [
        "Tutorials (教程), How-to Guides (指南), Reference (参考), Explanation (解释/讨论)",
        "前端、后端、数据库、运维",
        "起因、经过、高潮、结尾",
        "文字、图片、视频、音频",
      ],
      answer: 0,
      rationale: "Diátaxis divides documentation into these 4 distinct types based on user needs.",
    },
    {
      id: "tw-w1-3-q2",
      question: "在 Diátaxis 中，Tutorials（教程）的主要目标是？",
      options: [
        "Learning-oriented（面向学习）：帮助新手获得技能与信心，通常通过“Hello World”式的体验",
        "Problem-oriented（面向问题）：解决具体的工作难题",
        "Information-oriented（面向信息）：提供精确的参数",
        "Understanding-oriented（面向理解）：解释背后的原理",
      ],
      answer: 0,
      rationale: "Tutorials are strictly about the learning experience (acquisition of skills).",
    },
    {
      id: "tw-w1-3-q3",
      question: "How-to Guides（操作指南）与 Tutorials 的主要区别在于？",
      options: [
        "How-to 面向有具体任务的用户（Goal-oriented），假设其已有基础能力；Tutorials 面向纯小白（Learning-oriented）",
        "How-to 必须有视频",
        "Tutorials 不能写代码",
        "没有区别",
      ],
      answer: 0,
      rationale: "Distinction: How-to serves a user with a problem; Tutorial serves a user who wants to learn.",
    },
    {
      id: "tw-w1-3-q4",
      question: "Reference（参考手册）的最佳类比是？",
      options: [
        "地图或字典：你查阅它是为了获取具体信息，而不是从头读到尾",
        "小说：需要通读",
        "食谱：一步步做",
        "历史书：了解过去",
      ],
      answer: 0,
      rationale: "Reference is for looking up information (consulting), not continuous reading.",
    },
    {
      id: "tw-w1-3-q5",
      question: "Explanation（解释/背景知识）关注的是？",
      options: [
        "Understanding（理解）：Why & What。连接上下文，阐述原理与设计哲学",
        "Action（行动）：教用户怎么做",
        "Facts（事实）：列出数据",
        "Steps（步骤）：第一步、第二步",
      ],
      answer: 0,
      rationale: "Explanation provides the context and reasons (understanding).",
    },
    {
      id: "tw-w1-3-q6",
      question: "“Structured Writing”（结构化写作/结构化内容）的核心特征是？",
      options: [
        "Content is separated from formatting（内容与格式分离），且内容被模块化（Modular）以便复用",
        "文章必须有严格的开头和结尾",
        "必须使用 XML 编写",
        "每段话不能超过 3 行",
      ],
      answer: 0,
      rationale: "Key principles of structured content: separation and modularity.",
    },
    {
      id: "tw-w1-3-q7",
      question: "“Every Page is Page One”原则意味着？",
      options: [
        "用户通常通过搜索直接进入某个具体页面，而非从首页导航进入，因此每个页面都需具备自包含（Self-contained）的上下文",
        "所有页面都应该叫 Page One",
        "网站只能有一页",
        "每页只能写一句话",
      ],
      answer: 0,
      rationale: "Users land anywhere; context must be local.",
    },
    {
      id: "tw-w1-3-q8",
      question: "Information Architecture（IA，信息架构）主要解决什么问题？",
      options: [
        "How content is organized, labeled, and navigated（内容的组织、标签与导航逻辑）",
        "服务器的硬件架构",
        "数据库的表结构",
        "办公室的装修风格",
      ],
      answer: 0,
      rationale: "IA is about structural design of information space.",
    },
    {
      id: "tw-w1-3-q9",
      question: "在 Diátaxis 中，如果一篇文档即教你怎么做（How-to），又解释原理（Explanation），通常建议？",
      options: [
        "分离它们：将原理部分移至 Explanation 区域并提供链接，保持 How-to 的简洁与专注",
        "混合在一起，显得内容丰富",
        "删掉原理部分",
        "删掉操作步骤",
      ],
      answer: 0,
      rationale: "Diátaxis advocates separating concerns to avoid confusing the user.",
    },
    {
      id: "tw-w1-3-q10",
      question: "Topic-based Authoring（基于话题的写作）通常把内容分为哪几种核心类型（DITA 标准）？",
      options: [
        "Concept（概念）, Task（任务）, Reference（参考）",
        "Introduction, Body, Conclusion",
        "Unix, Linux, Windows",
        "Gold, Silver, Bronze",
      ],
      answer: 0,
      rationale: "Standard DITA types align with structured writing concepts.",
    },
    {
      id: "tw-w1-3-q11",
      question: "为什么 Reference 文档应该避免包含这就教学步骤（Instructional steps）？",
      options: [
        "因为这会干扰只想快速查找事实（Facts）的用户，且导致内容冗余维护困难",
        "因为参考文档不需要步骤",
        "因为写步骤太累了",
        "因为步骤是商业机密",
      ],
      answer: 0,
      rationale: "Reference should be pure information/facts, concise and scannable.",
    },
    {
      id: "tw-w1-3-q12",
      question: "Tutorials 的基调应该是？",
      options: [
        "Hand-holding（保姆式）：容错率高，提供完整的成功体验，不追求展现所有可能性",
        "严厉的：你做错了就报错",
        "百科全书式的：列出所有选项",
        "随意的：想写什么写什么",
      ],
      answer: 0,
      rationale: "Tutorials must guarantee success to build confidence.",
    },
    {
      id: "tw-w1-3-q13",
      question: "“Conway's Law”在文档结构中的负面体现是？",
      options: [
        "文档结构反映了公司的组织架构（Org Chart），而非产品的用户视角",
        "文档写得太长",
        "文档写得太短",
        "文档充满了 Bug",
      ],
      answer: 0,
      rationale: "Users don't care about your org chart; shipping the org chart is a common IA failure.",
    },
    {
      id: "tw-w1-3-q14",
      question: "如果要在 Tutorials 中使用代码示例，应该是？",
      options: [
        "完整且可运行的代码（Copy-pasteable），避免只有片段导致用户无法复现",
        "伪代码",
        "截图（不可复制）",
        "即使报错也没关系的代码",
      ],
      answer: 0,
      rationale: "Tutorial goal is success; broken/partial code breaks that goal.",
    },
    {
      id: "tw-w1-3-q15",
      question: "How-to Guide 的标题通常应该是什么形式？",
      options: [
        "动词短语（Verb-based），如 'How to install...' 或 'Deploying the app'",
        "名词短语，如 'Installation'",
        "疑问句，如 'Is it installed?'",
        "感叹句，如 'Installation is fun!'",
      ],
      answer: 0,
      rationale: "Task-based titles indicate action.",
    },
    {
      id: "tw-w1-3-q16",
      question: "Explanation 文档的内容通常包括？",
      options: [
        "Background coverage, context, analogies, reasons, history（背景、上下文、类比、理由、历史）",
        "Step 1, Step 2, Step 3",
        "Function parameters",
        "CLI flags",
      ],
      answer: 0,
      rationale: "Components of understanding.",
    },
    {
      id: "tw-w1-3-q17",
      question: "“Chunking”（分块）在信息处理中的作用是？",
      options: [
        "将复杂信息拆解为小的、可消化的单元（Chunks），降低认知负荷",
        "把文件切碎",
        "增加阅读难度",
        "为了增加点击量",
      ],
      answer: 0,
      rationale: "Cognitive science principle applied to structured writing.",
    },
    {
      id: "tw-w1-3-q18",
      question: "Landing Page（文档首页）的主要职责是？",
      options: [
        "Signposting（路标）：快速引导用户分流到 Diátaxis 的不同象限（教程、指南、参考等）",
        "展示公司的所有历史",
        "放置巨大的 Logo",
        "没有什么用",
      ],
      answer: 0,
      rationale: "Landing pages direct traffic based on user needs.",
    },
    {
      id: "tw-w1-3-q19",
      question: "Reference 文档的一个关键质量指标是？",
      options: [
        "Completeness & Accuracy（完整性与准确性）：必须覆盖所有字段/参数且无误",
        "有趣性",
        "故事情节",
        "情感丰富",
      ],
      answer: 0,
      rationale: "Reference is the source of truth.",
    },
    {
      id: "tw-w1-3-q20",
      question: "Modular Content（模块化内容）使得“Single Sourcing”（单一信源）成为可能，这指的是？",
      options: [
        "同一份源内容可以发布为 PDF、HTML、帮助系统等多种格式，且修改一处处处更新",
        "每个人只能用一个显示器",
        "只能有一个作者",
        "只能有一种字体",
      ],
      answer: 0,
      rationale: "Efficiency benefit of structured writing.",
    },
    {
      id: "tw-w1-3-q21",
      question: "在编写 How-to 时，如果某个步骤有可选分支（If-else），最佳做法是？",
      options: [
        "保持主流程清晰，使用子标题或特定排版清晰标示分支条件，或拆分为不同的小节",
        "把所有情况写在一个长段落里",
        "忽略分支情况",
        "让用户自己猜",
      ],
      answer: 0,
      rationale: "Handling complexity while maintaining task flow.",
    },
    {
      id: "tw-w1-3-q22",
      question: "Breadcrumbs（面包屑导航）的作用是？",
      options: [
        "显示当前页面在层级结构中的位置，并提供向上的导航路径",
        "掉落面包屑防止迷路",
        "装饰页面",
        "记录访问历史",
      ],
      answer: 0,
      rationale: "Standard navigation aid.",
    },
    {
      id: "tw-w1-3-q23",
      question: "Google Technical Writing 建议使用“Bulleted Lists”来？",
      options: [
        "Break up complex text, highlight non-sequential items（打散复杂文本，列出无序项）",
        "表示严格的顺序步骤",
        "增加页面长度",
        "为了好玩",
      ],
      answer: 0,
      rationale: "Lists improve scannability.",
    },
    {
      id: "tw-w1-3-q24",
      question: "Numbered Lists（有序列表）应严格限制用于？",
      options: [
        "Sequential steps（有顺序的步骤）",
        "无序的项目",
        "任何列表",
        "表示优先级",
      ],
      answer: 0,
      rationale: "Numbered lists imply order.",
    },
    {
      id: "tw-w1-3-q25",
      question: "“Orphaned Pages”（孤儿页面）是指？",
      options: [
        "没有被任何其他页面链接到的页面，用户很难发现它们",
        "主要作者离职的页面",
        "内容很短的页面",
        "没有标题的页面",
      ],
      answer: 0,
      rationale: "IA hygiene issue.",
    },
    {
      id: "tw-w1-3-q26",
      question: "Diátaxis 中，Tutorials 应该由谁来主导节奏？",
      options: [
        "The teacher/document（作者主导）：用户只需跟随，不需要思考'要做什么'，只需思考'在学什么'",
        "The user（用户主导）",
        "随机",
        "产品经理",
      ],
      answer: 0,
      rationale: "Teacher directs the lesson.",
    },
    {
      id: "tw-w1-3-q27",
      question: "“Glossary”（术语表）在文档结构中的作用是？",
      options: [
        "统一解释专业术语，确保一致性并降低阅读门槛（De-jargonize）",
        "增加文档厚度",
        "展示作者词汇量",
        "用于 SEO 堆砌",
      ],
      answer: 0,
      rationale: "Consistency and clarity aid.",
    },
    {
      id: "tw-w1-3-q28",
      question: "FAQ（常见问题解答）在 Write the Docs 社区中通常被视为？",
      options: [
        "Often a sign of bad structure ('A closet for junk')（往往是结构不良的信号/杂物间），如果信息重要，应放入正文",
        "最好的文档形式",
        "必须包含的部分",
        "唯一需要的文档",
      ],
      answer: 0,
      rationale: "FAQs often indicate content that belongs elsewhere.",
    },
    {
      id: "tw-w1-3-q29",
      question: "“Taxonomy”（分类法）是指？",
      options: [
        "The practice and science of classification（分类的科学与实践），即如何给内容归类",
        "税收政策",
        "生物解剖",
        "排版技术",
      ],
      answer: 0,
      rationale: "Classification of content.",
    },
    {
      id: "tw-w1-3-q30",
      question: "对于 Explanation 类文档，一个好的标题示例是？",
      options: [
        "Authentication Architecture（认证架构） / Understanding OAuth（理解 OAuth）",
        "How to login（如何登录）",
        "Login API Reference（登录 API 参考）",
        "Hello World Login（登录入门）",
      ],
      answer: 0,
      rationale: "Noun-based, conceptual titles.",
    },
  ],
  "tw-w1-4": [
    {
      id: "tw-w1-4-q1",
      question: "为什么大多数技术风格指南（Style Guides）都强烈建议使用主动语态（Active Voice）？",
      options: [
        "明确了'谁做了什么'（Who does what），减少歧义，通常更简洁",
        "看起来更学术",
        "为了增加字数",
        "被动语态是不合法的",
      ],
      answer: 0,
      rationale: "Passive voice often hides the actor; active voice is direct and clear.",
    },
    {
      id: "tw-w1-4-q2",
      question: "以下哪个句子是主动语态（Active Voice）的最佳示例？",
      options: [
        "The script deploys the application.（脚本部署了应用程序）",
        "The application is deployed by the script.",
        "Deployment is effected by the script.",
        "There is a deployment of the application.",
      ],
      answer: 0,
      rationale: "Subject (Script) performs Action (Deploys).",
    },
    {
      id: "tw-w1-4-q3",
      question: "“Simplified Technical English (STE)”的一个核心规则是？",
      options: [
        "一词一义（One word, one meaning）：避免使用同义词，减少认知负担",
        "尽可能使用复杂的词汇",
        "多使用俚语",
        "每一页必须有图片",
      ],
      answer: 0,
      rationale: "Consistency reduces cognitive load.",
    },
    {
      id: "tw-w1-4-q4",
      question: "在编写指令时，第二人称（Second Person）是指使用什么？",
      options: [
        "You（你）或隐含的 You（祈使句）",
        "He/She（他/她）",
        "The user（用户）",
        "We（我们）",
      ],
      answer: 0,
      rationale: "Addressing the user directly ('You') is more engaging and clear.",
    },
    {
      id: "tw-w1-4-q5",
      question: "Google Style Guide 建议如何处理“Future Tense”（将来时，如 will）？",
      options: [
        "尽量避免，优先使用现在时（Present Tense）。例如：'The system responds' 而非 'The system will respond'",
        "必须全部使用将来时",
        "使用过去时",
        "随意混用",
      ],
      answer: 0,
      rationale: "Documentation describes how the software works NOW.",
    },
    {
      id: "tw-w1-4-q6",
      question: "为了保持文档的“一致性（Consistency）”，你应该？",
      options: [
        "对同一个动作始终使用同一个词（例如始终用 'Select'，不要混用 'Click', 'Pick', 'Choose'）",
        "为了不枯燥，经常更换同义词",
        "让每个作者发挥自己的风格",
        "使用不同的字体",
      ],
      answer: 0,
      rationale: "Variation confuses users in technical contexts.",
    },
    {
      id: "tw-w1-4-q7",
      question: "什么是即时/悬垂修饰语（Dangling Modifier）？",
      options: [
        "一种修饰语与其修饰的主语不明确或脱节的语法错误，导致歧义",
        "一种很好的修辞手法",
        "一种悬挂缩进",
        "代码中的悬空指针",
      ],
      answer: 0,
      rationale: "e.g., 'Using the tool, the file was saved.' (Who used the tool?)",
    },
    {
      id: "tw-w1-4-q8",
      question: "对于列表（Lists）的每一项，为了降低认知负荷，应该保持？",
      options: [
        "语法平行（Grammatical Parallelism）：例如都是动词开头，或都是名词短语",
        "长度一致",
        "首字母必须是 A",
        "必须要有子列表",
      ],
      answer: 0,
      rationale: "Parallel structure makes lists easier to scan and understand.",
    },
    {
      id: "tw-w1-4-q9",
      question: "在技术文档中，'Jargon'（行话/术语）的处理原则是？",
      options: [
        "尽量避免不必要的行话；如果必须使用，首次出现时必须定义",
        "多多益善，显得专业",
        "假设用户都懂，不用解释",
        "自己发明新行话",
      ],
      answer: 0,
      rationale: "Jargon alienates readers who are not experts inside your head.",
    },
    {
      id: "tw-w1-4-q10",
      question: "为什么说“Short Sentences”（短句）在技术文档中更好？",
      options: [
        "易于阅读、易于翻译、降低理解难度",
        "节省纸张",
        "显得作者文笔不好",
        "短句没有逻辑",
      ],
      answer: 0,
      rationale: "Complexity impedes comprehension.",
    },
    {
      id: "tw-w1-4-q11",
      question: "“Nominalization”（名词化）是指什么？为什么通常要避免？",
      options: [
        "把动词变成名词（如 'make a decision' 代替 'decide'），它使句子变得沉重且掩盖了动作",
        "给变量命名",
        "使用专有名词",
        "把名词变成动词",
      ],
      answer: 0,
      rationale: "Verbs are stronger and clearer than abstract nouns.",
    },
    {
      id: "tw-w1-4-q12",
      question: "关于“Click here”这种链接文本，最佳实践是？",
      options: [
        "避免使用。应使用描述性文本（例如 'Download the guide'），这对无障碍访问（Accessibility）和 SEO 更友好",
        "推荐使用，因为直观",
        "必须加粗",
        "必须用红色",
      ],
      answer: 0,
      rationale: "Non-descriptive links are bad for screen readers and scanning.",
    },
    {
      id: "tw-w1-4-q13",
      question: "Google Style Guide 推荐使用哪种列表符号来表示非顺序列表？",
      options: [
        "Bullet points（无序列表/圆点）",
        "Numbers（数字）",
        "Letters（字母）",
        "Arrows（箭头）",
      ],
      answer: 0,
      rationale: "Bullets for items where order doesn't matter.",
    },
    {
      id: "tw-w1-4-q14",
      question: "在指代用户的计算机时，Microsoft 建议使用？",
      options: [
        "The computer（计算机）或 Your computer（你的计算机）",
        "The machine（机器）",
        "The box（盒子）",
        "PC",
      ],
      answer: 0,
      rationale: "Neutral, clear terminology.",
    },
    {
      id: "tw-w1-4-q15",
      question: "什么时候应该使用“Alerts”（警告/注意框）？",
      options: [
        "仅在关键时刻（如危险、数据丢失风险或重要提示）使用，避免滥用导致“横幅盲区”（Banner Blindness）",
        "每一段都用，为了引起注意",
        "用于放置广告",
        "用于写作者的个人感悟",
      ],
      answer: 0,
      rationale: "A warnings is only effective if it stands out.",
    },
    {
      id: "tw-w1-4-q16",
      question: "“Gender-neutral formatting”（中性性别格式）意味着？",
      options: [
        "避免使用 he/she，改用 they（单数 they）或直接对用户说话（You），或重写为复数",
        "必须同时写 he 和 she",
        "使用 it 指代人",
        "不使用代词",
      ],
      answer: 0,
      rationale: "Inclusive language is standard practice.",
    },
    {
      id: "tw-w1-4-q17",
      question: "术语表（Glossary）的主要价值在于？",
      options: [
        "作为术语的“单一事实来源（Single Source of Truth）”，确保全团队和用户对词汇理解一致",
        "凑字数",
        "展示生僻字",
        "没有什么价值",
      ],
      answer: 0,
      rationale: "Consistency requires a shared dictionary.",
    },
    {
      id: "tw-w1-4-q18",
      question: "对于代码中的变量、命令或输入，通常推荐的排版格式是？",
      options: [
        "Code font / Monospace（等宽字体/代码体），以便与普通文本区分",
        "Bold（加粗）",
        "Italic（斜体）",
        "Underline（下划线）",
      ],
      answer: 0,
      rationale: "Visual distinction of literal strings is crucial.",
    },
    {
      id: "tw-w1-4-q19",
      question: "“Oxford Comma”（牛津逗号/序列逗号）的作用是？",
      options: [
        "在列表的最后一项前加逗号（A, B, and C），消除分组歧义",
        "在这个位置必须换行",
        "一种特殊的字体",
        "毫无作用",
      ],
      answer: 0,
      rationale: "Prevents ambiguity in lists.",
    },
    {
      id: "tw-w1-4-q20",
      question: "为什么说“Metadiscourse”（关于讨论的讨论，如'本章将讨论...'）通常是多余的？",
      options: [
        "它增加了噪音。应该直接开始讨论内容（Jump straight to the point）",
        "它很有礼貌",
        "必须要有开场白",
        "为了凑篇幅",
      ],
      answer: 0,
      rationale: "Remove fluff.",
    },
    {
      id: "tw-w1-4-q21",
      question: "“Wall of Text”（文字墙）是指？",
      options: [
        "大段密集的文字，缺乏标题、列表或空行，导致用户难以扫描阅读",
        "防火墙配置文本",
        "一种艺术风格",
        "写在墙上的字",
      ],
      answer: 0,
      rationale: "Scannability requires breaking up text.",
    },
    {
      id: "tw-w1-4-q22",
      question: "如果必须使用缩写（Acronyms），正确的做法是？",
      options: [
        "在首次出现时拼写全称并附带缩写，例如：'Content Delivery Network (CDN)'",
        "直接使用缩写，让用户去搜",
        "永远不要用缩写",
        "把缩写列在文末",
      ],
      answer: 0,
      rationale: "Don't assume knowledge.",
    },
    {
      id: "tw-w1-4-q23",
      question: "Sentence Case（句首大写）与 Title Case（标题大写）相比，现代风格指南（如 Google）倾向于？",
      options: [
        "Sentence case：更易读，更随意友好，且规则更简单",
        "Title Case：更正式",
        "ALL CAPS：最醒目",
        "mixed cASE：最独特",
      ],
      answer: 0,
      rationale: "Sentence case is the modern standard for legibility.",
    },
    {
      id: "tw-w1-4-q24",
      question: "“Global English”（全球英语）写作建议避免什么？",
      options: [
        "避免成语（Idioms）、文化隐喻（Cultural metaphors）和幽默，因为非母语读者可能无法理解",
        "避免使用动词",
        "避免使用逗号",
        "避免使用简单句",
      ],
      answer: 0,
      rationale: "Cultural neutrality aids understanding and translation.",
    },
    {
      id: "tw-w1-4-q25",
      question: "对于界面上的按钮名称，应该？",
      options: [
        "完全匹配界面上的拼写和大小写，并可能使用加粗来突出",
        "由作者随意发挥",
        "全部大写",
        "全部小写",
      ],
      answer: 0,
      rationale: "Match reality exactly.",
    },
    {
      id: "tw-w1-4-q26",
      question: "“Vague Modifiers”（模糊修饰语，如 very, quickly, easily）应该？",
      options: [
        "尽量删除或替换为具体数据。'Fast' 是主观的，'50ms' 是客观的",
        "大量使用以增强语气",
        "全部大写",
        "放在句首",
      ],
      answer: 0,
      rationale: "Precision beats exaggeration.",
    },
    {
      id: "tw-w1-4-q27",
      question: "在步骤列表中，每个步骤应该是？",
      options: [
        "一个完整的动作（Action），通常以动词开头的祈使句",
        "一个名词",
        "一个问题",
        "一个笑话",
      ],
      answer: 0,
      rationale: "Steps are for doing.",
    },
    {
      id: "tw-w1-4-q28",
      question: "Microsoft Style Guide 建议用 'Select' 来代替 'Click'，原因是？",
      options: [
        "Select 适用于多种输入设备（鼠标、触屏、键盘），而 Click 仅限鼠标",
        "Select 听起来高级",
        "Click 是商标",
        "没有原因",
      ],
      answer: 0,
      rationale: "Device-agnostic terminology.",
    },
    {
      id: "tw-w1-4-q29",
      question: "什么时候可以使用“被动语态”？",
      options: [
        "当动作执行者未知，或者接受动作的主体比执行者更重要时（尽管应尽量少用）",
        "任何时候",
        "想显得客气的时候",
        "不想承担责任的时候",
      ],
      answer: 0,
      rationale: "Passive voice has niche uses (focus on object), but is generally discouraged.",
    },
    {
      id: "tw-w1-4-q30",
      question: "技术文档写作的目标不是展示文采，而是？",
      options: [
        "帮助用户解决问题（Solving user problems）",
        "写出最长的文章",
        "使用最多的形容词",
        "让用户崇拜作者",
      ],
      answer: 0,
      rationale: "Utility is the ultimate metric.",
    },
  ],
};