import type { LessonGuide } from "../types"
import type { QuizQuestion } from "@/lib/types"

export const week8Guides: Record<string, LessonGuide> = {
    "w8-1": {
        lessonId: "w8-1",
        background: [
            "【模式定义】microservices.io：API Gateway 是 'a single entry point into the application, routing and composing requests to services'——应用的单一入口，路由和组合请求到服务。",
            "【解决的问题】细粒度 API（需要聚合）、客户端多样性（Web/Mobile/第三方）、网络差异（WAN vs LAN）、动态基础设施、协议多样性。",
            "【核心职责】请求路由和代理、请求组合（API Composition）、客户端认证授权、API 翻译和适配、服务实例发现、弹性处理（熔断器）。",
            "【AWS API Gateway】支持三种 API 类型：REST APIs（完整功能）、HTTP APIs（成本优化）、WebSocket APIs（全双工通信）。",
            "【实现技术】microservices.io 推荐：事件驱动/响应式架构处理高负载，JVM 使用 NIO 库（Netty、Spring Reactor），或 Node.js。",
        ],
        keyDifficulties: [
            "【运维复杂性】microservices.io：'It is yet another highly available component that must be developed, deployed, and managed'——需要开发和运维高可用组件。",
            "【网络跳数】增加了一次网络调用，虽然延迟影响通常可忽略。",
            "【单点风险】网关成为系统单点，需要高可用设计和弹性保护。",
            "【功能膨胀风险】容易在网关中添加过多业务逻辑，应聚焦横切关注点。",
            "【性能瓶颈】高并发场景需要事件驱动架构，避免阻塞 I/O。",
        ],
        handsOnPath: [
            "选择网关方案：根据需求选择 Kong、APISIX、AWS API Gateway、Envoy 等。",
            "配置路由规则：定义 URL 路径到后端服务的映射。",
            "实现认证授权：集成 OAuth2/JWT 进行身份验证。",
            "配置限流：设置 Rate Limiting 保护后端服务。",
            "添加熔断器：配置 Circuit Breaker 防止故障级联。",
            "监控和日志：集成 APM 工具监控网关性能。",
        ],
        selfCheck: [
            "API Gateway 模式的定义是什么？",
            "API Gateway 解决哪些微服务架构问题？",
            "API Gateway 的核心职责有哪些？",
            "API Gateway 的主要优势和劣势是什么？",
            "为什么推荐使用事件驱动架构实现网关？",
            "如何避免网关成为性能瓶颈？",
        ],
        extensions: [
            "研究 Service Mesh 与 API Gateway 的关系和区别。",
            "探索 GraphQL Gateway 的实现方式。",
            "学习网关的金丝雀发布和蓝绿部署策略。",
            "了解无服务器架构中的网关模式（如 AWS API Gateway + Lambda）。",
        ],
        sourceUrls: [
            "https://microservices.io/patterns/apigateway.html",
            "https://developer.konghq.com/gateway/",
            "https://docs.aws.amazon.com/apigateway/latest/developerguide/welcome.html",
        ],
    },
    "w8-2": {
        lessonId: "w8-2",
        background: [
            "【模式定义】Sam Newman：BFF 是 'one backend per user experience'——每种用户体验一个后端，紧密耦合到特定 UI，由同一团队维护。",
            "【核心优势】Focus and Simplicity（聚焦和简洁）——每个 BFF 只服务单一 UI 类型，比通用 API 更小更易管理。",
            "【团队自治】前后端由同一团队控制，'可以快速迭代两者'，无需跨团队协调，独立决定功能放在客户端还是服务端。",
            "【减少瓶颈】避免单体 API 的瓶颈问题——前端团队不再依赖独立的后端 API 团队。",
            "【微服务聚合】Sam Newman：单个客户端请求可能需要 'multiple downstream calls'，BFF 优雅地处理这种聚合。",
        ],
        keyDifficulties: [
            "【代码重复】多个 BFF 之间可能存在重复逻辑，需要提取共享库或下沉到微服务。",
            "【边界模糊】BFF 应聚焦于「展示适配」，避免包含核心业务逻辑。",
            "【运维开销】每种客户端一个 BFF 增加了服务数量和运维复杂度。",
            "【一致性挑战】多个 BFF 调用相同后端服务，需要协调 API 版本和行为一致性。",
            "【降级处理】Sam Newman 举例：BFF 需要处理部分服务失败的优雅降级。",
        ],
        handsOnPath: [
            "识别客户端类型：分析 Web、Mobile、第三方等不同客户端的需求差异。",
            "设计 BFF API：为每种客户端定义优化的 API 契约。",
            "实现数据聚合：BFF 调用多个后端服务并组合响应。",
            "处理并行调用：使用异步 I/O 并行调用后端服务提高性能。",
            "实现降级策略：部分服务失败时返回缓存或默认数据。",
            "团队对齐：确保 BFF 与对应 UI 团队对齐。",
        ],
        selfCheck: [
            "BFF 模式的定义是什么？",
            "BFF 如何实现团队自治？",
            "BFF 与通用 API Gateway 的区别是什么？",
            "什么时候应该使用 BFF 模式？",
            "BFF 的主要挑战是什么？",
            "如何处理多个 BFF 之间的代码重复？",
        ],
        extensions: [
            "研究 GraphQL 作为 BFF 层的实现方式。",
            "探索 BFF 在 Serverless 架构中的应用。",
            "学习 BFF 的测试策略和契约测试。",
            "了解 Micro Frontends 与 BFF 的结合。",
        ],
        sourceUrls: [
            "https://microservices.io/patterns/apigateway.html#backends-for-frontends",
            "https://samnewman.io/patterns/architectural/bff/",
        ],
    },
    "w8-3": {
        lessonId: "w8-3",
        background: [
            "【Access Token 模式】microservices.io：API Gateway 认证请求后，'passes an access token (e.g. JSON Web Token) that securely identifies the requestor in each request to the services'。",
            "【身份传播】OWASP：不应直接传递外部 Token，而是使用 'a data structure signed or encrypted by the trusted issuer'——如 Netflix 的 Passport 模型。",
            "【授权层级】OWASP 区分三种模式：边缘授权（集中在网关）、服务级授权（分散到各服务）、嵌入式 PDP（策略集中定义但本地执行）。",
            "【Rate Limiting】使用 Token Bucket 算法控制请求速率：令牌以固定速率生成，每个请求消耗一个令牌，超出返回 429 错误。",
            "【多层限流】AWS API Gateway 提供四层限流：AWS 账户级、单账户所有 API、单 API/阶段、单客户端（API Key）。",
        ],
        keyDifficulties: [
            "【边缘授权局限】OWASP：集中授权 'difficult to manage complex rule sets'，且可能成为单点故障。",
            "【Token 安全】外部 Token 不应在内部传播——使用内部签名结构（如 Passport）替代。",
            "【服务间认证】OWASP 推荐 mTLS（双向 TLS）或 Token-based 认证进行服务间通信。",
            "【限流算法选择】Token Bucket（允许突发）、Sliding Window（平滑）、Fixed Window（简单但有边界问题）。",
            "【分布式限流】多实例网关需要共享状态（如 Redis Cluster）实现全局限流。",
        ],
        handsOnPath: [
            "配置认证：在网关集成 OAuth2/OIDC Provider。",
            "实现 JWT 验证：验证 Token 签名和有效期。",
            "设计内部身份传播：创建内部签名结构传递用户身份。",
            "配置限流规则：设置不同层级的 Rate Limit。",
            "实现服务间 mTLS：配置双向 TLS 认证。",
            "监控安全事件：记录和告警认证失败和限流触发。",
        ],
        selfCheck: [
            "Access Token 模式如何工作？",
            "为什么不应该直接传递外部 Token 到内部服务？",
            "OWASP 推荐的三种授权模式是什么？",
            "Token Bucket 算法如何工作？",
            "什么是 mTLS？为什么用于服务间认证？",
            "如何实现分布式限流？",
        ],
        extensions: [
            "研究 OAuth2 和 OIDC 的详细流程。",
            "探索 Open Policy Agent (OPA) 实现策略即代码。",
            "学习 API 安全最佳实践（OWASP API Security Top 10）。",
            "了解 Zero Trust 架构在微服务中的应用。",
        ],
        sourceUrls: [
            "https://microservices.io/patterns/security/access-token.html",
            "https://cheatsheetseries.owasp.org/cheatsheets/Microservices_Security_Cheat_Sheet.html",
        ],
    },
    "w8-4": {
        lessonId: "w8-4",
        background: [
            "【Kong Gateway】Kong 是 'a lightweight, fast, and flexible cloud-native API gateway'，支持 Control Plane + Data Plane 架构，适合混合云和多云环境。",
            "【Apache APISIX】APISIX 是 'an open source, dynamic, scalable, and high-performance cloud native API gateway'，Apache 顶级项目，使用 etcd 存储配置。",
            "【Envoy Proxy】Envoy 是 'an L7 proxy and communication bus designed for large modern service oriented architectures'，运行在独立进程中，语言无关。",
            "【架构差异】Kong/APISIX 是传统 API Gateway；Envoy 同时是 Service Mesh 数据平面和边缘代理。",
            "【协议支持】Envoy 支持 HTTP/1.1、HTTP/2、HTTP/3(alpha)、gRPC、TCP、UDP、Redis、MongoDB、PostgreSQL 等。",
        ],
        keyDifficulties: [
            "【选型考量】Kong 企业功能成熟但部分收费；APISIX 完全开源、性能高；Envoy 功能强大但配置复杂。",
            "【学习曲线】Kong 和 APISIX 更易上手（声明式配置）；Envoy 需要理解 xDS API 和动态配置。",
            "【生态系统】Kong 插件生态丰富；APISIX 与 Apache 生态集成好；Envoy 与 Istio 等 Service Mesh 集成。",
            "【部署模式】Kong 支持传统、Hybrid、DB-less；APISIX 依赖 etcd；Envoy 支持静态和动态配置。",
            "【可观测性】三者都支持 Prometheus、Datadog 等，Envoy 的统计和追踪能力最为强大。",
        ],
        handsOnPath: [
            "评估需求：确定功能需求、性能要求、团队技能。",
            "部署 Kong：使用 Docker 快速部署 Kong Gateway。",
            "部署 APISIX：运行 quickstart 脚本部署 APISIX。",
            "配置路由：在选定网关中配置服务路由。",
            "添加插件：配置认证、限流、日志等插件。",
            "性能测试：使用负载测试工具对比不同网关性能。",
        ],
        selfCheck: [
            "Kong、APISIX、Envoy 各自的定位是什么？",
            "三种网关在架构上有什么区别？",
            "什么情况下选择 Kong？什么情况下选择 APISIX？",
            "Envoy 为什么适合 Service Mesh？",
            "如何评估 API Gateway 的性能？",
            "DB-less 模式的优缺点是什么？",
        ],
        extensions: [
            "研究 Istio 如何使用 Envoy 作为数据平面。",
            "探索 Kong Enterprise 与开源版的差异。",
            "学习使用 Terraform/Pulumi 管理网关配置。",
            "了解 GraphQL Gateway（如 Apollo Gateway）的选型。",
        ],
        sourceUrls: [
            "https://apisix.apache.org/docs/apisix/getting-started/",
            "https://www.envoyproxy.io/docs/envoy/latest/intro/what_is_envoy",
        ],
    },
}

export const week8Quizzes: Record<string, QuizQuestion[]> = {
    "w8-1": [
        {
            id: "w8-1-q1",
            question: "根据 microservices.io，API Gateway 的定义是什么？",
            options: [
                "分布式数据库",
                "应用的单一入口，路由和组合请求到服务",
                "消息队列",
                "服务注册中心",
            ],
            answer: 1,
            rationale: "microservices.io 定义 API Gateway 为 'a single entry point into the application, routing and composing requests to services'。",
        },
        {
            id: "w8-1-q2",
            question: "API Gateway 解决哪些微服务架构问题？",
            options: [
                "只解决性能问题",
                "细粒度 API、客户端多样性、网络差异、动态基础设施、协议多样性",
                "只解决安全问题",
                "只解决数据存储问题",
            ],
            answer: 1,
            rationale: "microservices.io 列出问题：Fine-grained APIs、Client diversity、Network variations、Dynamic infrastructure、Protocol diversity。",
        },
        {
            id: "w8-1-q3",
            question: "API Gateway 的核心职责有哪些？",
            options: [
                "只做路由",
                "请求路由、请求组合、认证授权、API 翻译、服务发现、弹性处理",
                "只做认证",
                "只做负载均衡",
            ],
            answer: 1,
            rationale: "microservices.io 列出职责：Request routing、Request composition、Authentication、API translation、Service discovery、Circuit breaker。",
        },
        {
            id: "w8-1-q4",
            question: "AWS API Gateway 支持哪三种 API 类型？",
            options: [
                "SOAP、REST、GraphQL",
                "REST APIs、HTTP APIs、WebSocket APIs",
                "TCP、UDP、HTTP",
                "同步、异步、混合",
            ],
            answer: 1,
            rationale: "AWS 文档列出三种类型：REST APIs、HTTP APIs、WebSocket APIs。",
        },
        {
            id: "w8-1-q5",
            question: "为什么推荐使用事件驱动架构实现网关？",
            options: [
                "实现简单",
                "处理高负载时性能更好，避免阻塞 I/O",
                "成本更低",
                "更安全",
            ],
            answer: 1,
            rationale: "microservices.io 推荐：'an event-driven/reactive approach is best if it must scale to handle high loads'。",
        },
        {
            id: "w8-1-q6",
            question: "API Gateway 的主要劣势是什么？",
            options: [
                "不支持路由",
                "增加运维复杂性和网络跳数",
                "性能太低",
                "不支持认证",
            ],
            answer: 1,
            rationale: "microservices.io 指出：'It is yet another highly available component that must be developed, deployed, and managed'，并增加网络跳数。",
        },
        {
            id: "w8-1-q7",
            question: "microservices.io 推荐的 JVM 网关实现技术是什么？",
            options: [
                "Servlet",
                "NIO 库如 Netty、Spring Reactor",
                "JSP",
                "EJB",
            ],
            answer: 1,
            rationale: "microservices.io 推荐：'JVM options include NIO-based libraries like Netty and Spring Reactor'。",
        },
        {
            id: "w8-1-q8",
            question: "API Gateway 如何处理服务实例发现？",
            options: [
                "硬编码服务地址",
                "使用 Client-side 或 Server-side Discovery 模式",
                "不需要服务发现",
                "直接访问数据库",
            ],
            answer: 1,
            rationale: "microservices.io 指出网关使用 'client-side or server-side patterns' 进行服务发现。",
        },
        {
            id: "w8-1-q9",
            question: "API Gateway 如何减少客户端的网络调用？",
            options: [
                "缓存所有数据",
                "聚合多服务请求为单次调用",
                "压缩响应",
                "使用更快的协议",
            ],
            answer: 1,
            rationale: "microservices.io 指出优势：'Reduces round-trips by aggregating multi-service requests into single calls'。",
        },
        {
            id: "w8-1-q10",
            question: "AWS API Gateway 的 WebSocket APIs 适用于什么场景？",
            options: [
                "批量数据处理",
                "全双工、实时通信",
                "文件上传",
                "数据库查询",
            ],
            answer: 1,
            rationale: "AWS 文档：WebSocket APIs 'Enable stateful, full-duplex communication between client and server'。",
        },
        {
            id: "w8-1-q11",
            question: "API Gateway 如何处理协议多样性？",
            options: [
                "拒绝非标准协议",
                "在 Web 标准和内部协议之间进行翻译",
                "强制所有服务使用 HTTP",
                "忽略协议差异",
            ],
            answer: 1,
            rationale: "microservices.io 指出优势：'Translates between public web standards and internal protocols'。",
        },
        {
            id: "w8-1-q12",
            question: "API Gateway 应该避免什么？",
            options: [
                "路由请求",
                "包含过多业务逻辑，应聚焦横切关注点",
                "认证授权",
                "限流保护",
            ],
            answer: 1,
            rationale: "最佳实践：网关应聚焦横切关注点（路由、认证、限流），业务逻辑应留在后端服务。",
        },
    ],
    "w8-2": [
        {
            id: "w8-2-q1",
            question: "根据 Sam Newman，BFF 模式的定义是什么？",
            options: [
                "通用后端服务",
                "每种用户体验一个后端，紧密耦合到特定 UI",
                "数据库代理",
                "消息队列",
            ],
            answer: 1,
            rationale: "Sam Newman 定义 BFF 为 'one backend per user experience'，紧密耦合到特定 UI。",
        },
        {
            id: "w8-2-q2",
            question: "BFF 的核心优势是什么？",
            options: [
                "减少代码量",
                "聚焦和简洁，每个 BFF 只服务单一 UI 类型",
                "提高数据库性能",
                "减少网络延迟",
            ],
            answer: 1,
            rationale: "Sam Newman 指出优势：'Focus and Simplicity—Each BFF serves a single UI type, making it smaller and more manageable'。",
        },
        {
            id: "w8-2-q3",
            question: "BFF 如何实现团队自治？",
            options: [
                "所有团队共享代码",
                "前后端由同一团队控制，无需跨团队协调",
                "使用统一的 API",
                "共享数据库",
            ],
            answer: 1,
            rationale: "Sam Newman 指出：'Teams controlling both frontend and backend can iterate both quickly without cross-team coordination'。",
        },
        {
            id: "w8-2-q4",
            question: "什么情况下应该使用 BFF 模式？",
            options: [
                "只有一种客户端类型",
                "多种 UI 需要不同功能、需要服务端数据聚合、UI 和后端团队分离",
                "所有客户端需求相同",
                "不需要数据聚合",
            ],
            answer: 1,
            rationale: "Sam Newman 列出适用场景：Multiple UI types、Significant server-side data aggregation、UI developed separately from backend。",
        },
        {
            id: "w8-2-q5",
            question: "Sam Newman 举的电商 wishlist 例子说明了什么？",
            options: [
                "BFF 不需要调用后端服务",
                "BFF 协调多个服务调用（至少 3 个），并处理部分失败",
                "BFF 只调用一个服务",
                "BFF 不处理错误",
            ],
            answer: 1,
            rationale: "Sam Newman 举例：BFF coordinates 'at least 3 calls' to different services, managing parallel execution and graceful degradation。",
        },
        {
            id: "w8-2-q6",
            question: "BFF 与通用 API Gateway 的区别是什么？",
            options: [
                "没有区别",
                "BFF 针对特定客户端优化，API Gateway 是通用入口",
                "BFF 更复杂",
                "API Gateway 更快",
            ],
            answer: 1,
            rationale: "BFF 为每种客户端类型定制 API，而 API Gateway 是通用入口处理横切关注点。",
        },
        {
            id: "w8-2-q7",
            question: "BFF 的主要挑战是什么？",
            options: [
                "性能太高",
                "多个 BFF 之间可能存在代码重复",
                "不支持多客户端",
                "无法聚合数据",
            ],
            answer: 1,
            rationale: "主要挑战包括多个 BFF 之间的代码重复，需要提取共享库或下沉到微服务。",
        },
        {
            id: "w8-2-q8",
            question: "BFF 应该聚焦于什么？",
            options: [
                "核心业务逻辑",
                "展示适配，避免包含核心业务逻辑",
                "数据存储",
                "消息传递",
            ],
            answer: 1,
            rationale: "BFF 应聚焦于「展示适配」（为特定客户端优化数据格式），核心业务逻辑应在后端服务。",
        },
        {
            id: "w8-2-q9",
            question: "BFF 如何避免成为架构瓶颈？",
            options: [
                "使用更大的服务器",
                "减少单体 API 团队，让 UI 团队直接控制 BFF",
                "增加数据库",
                "减少客户端类型",
            ],
            answer: 1,
            rationale: "Sam Newman 指出：'BFFs eliminate the architectural middleman problem where frontend teams depend on separate backend teams'。",
        },
        {
            id: "w8-2-q10",
            question: "BFF 团队应该如何组织？",
            options: [
                "独立的 BFF 团队",
                "与对应 UI 团队对齐，由同一团队维护",
                "由运维团队维护",
                "由数据库团队维护",
            ],
            answer: 1,
            rationale: "Sam Newman 强调 BFF 'typically maintained by the same team building that UI'。",
        },
        {
            id: "w8-2-q11",
            question: "如何处理多个 BFF 之间的代码重复？",
            options: [
                "忽略重复",
                "提取共享库或将逻辑下沉到后端微服务",
                "合并所有 BFF",
                "删除重复的 BFF",
            ],
            answer: 1,
            rationale: "处理代码重复的方法：提取共享库供多个 BFF 使用，或将通用逻辑下沉到后端微服务。",
        },
        {
            id: "w8-2-q12",
            question: "BFF 需要处理什么降级场景？",
            options: [
                "不需要处理降级",
                "部分后端服务失败时返回缓存或默认数据",
                "完全拒绝请求",
                "重启所有服务",
            ],
            answer: 1,
            rationale: "Sam Newman 举例：BFF 需要 'managing parallel execution and graceful degradation when some services fail'。",
        },
    ],
    "w8-3": [
        {
            id: "w8-3-q1",
            question: "根据 microservices.io，Access Token 模式如何工作？",
            options: [
                "每个服务独立认证",
                "API Gateway 认证后传递 JWT 到后端服务",
                "不需要认证",
                "客户端直接访问服务",
            ],
            answer: 1,
            rationale: "microservices.io 描述：'The API Gateway authenticates the request and passes an access token (e.g. JSON Web Token) that securely identifies the requestor'。",
        },
        {
            id: "w8-3-q2",
            question: "OWASP 为什么不建议直接传递外部 Token 到内部服务？",
            options: [
                "性能原因",
                "安全风险，应使用内部签名结构（如 Netflix Passport）",
                "格式不兼容",
                "Token 太大",
            ],
            answer: 1,
            rationale: "OWASP 建议：'Rather than passing external access tokens internally, use a data structure signed or encrypted by the trusted issuer'。",
        },
        {
            id: "w8-3-q3",
            question: "OWASP 推荐的三种授权模式是什么？",
            options: [
                "同步、异步、混合",
                "边缘授权、服务级授权（分散或集中 PDP）、嵌入式 PDP",
                "JWT、OAuth、SAML",
                "读、写、删除",
            ],
            answer: 1,
            rationale: "OWASP 区分：Edge-Level Authorization、Service-Level Authorization（Decentralized or Centralized PDP）、Embedded PDP。",
        },
        {
            id: "w8-3-q4",
            question: "Token Bucket 算法如何工作？",
            options: [
                "固定拒绝所有请求",
                "令牌以固定速率生成，每个请求消耗一个令牌，无令牌则拒绝",
                "随机生成令牌",
                "无限制通过",
            ],
            answer: 1,
            rationale: "Token Bucket 算法：'tokens are added at a steady rate, each request consumes a token, if no tokens remain, the request is denied'。",
        },
        {
            id: "w8-3-q5",
            question: "AWS API Gateway 提供哪四层限流？",
            options: [
                "只有一层",
                "AWS 账户级、单账户所有 API、单 API/阶段、单客户端",
                "只有客户端级",
                "只有 API 级",
            ],
            answer: 1,
            rationale: "AWS 文档：AWS throttling limits、per-account limits、per-API/per-stage limits、per-client limits。",
        },
        {
            id: "w8-3-q6",
            question: "什么是 mTLS？",
            options: [
                "单向 TLS",
                "双向 TLS，服务双方互相验证证书",
                "不加密的 TLS",
                "压缩协议",
            ],
            answer: 1,
            rationale: "OWASP 描述 mTLS：'Each microservice uses public/private key pairs for mutual identification'。",
        },
        {
            id: "w8-3-q7",
            question: "边缘授权的主要局限是什么？",
            options: [
                "太安全",
                "难以管理复杂规则集，可能成为单点故障",
                "性能太高",
                "太简单",
            ],
            answer: 1,
            rationale: "OWASP 指出：边缘授权 'difficult to manage complex rule sets'，且可能成为单点故障。",
        },
        {
            id: "w8-3-q8",
            question: "Netflix 的 Passport 模型是什么？",
            options: [
                "用户登录界面",
                "HMAC 保护的内部身份结构，不暴露给外部",
                "护照扫描系统",
                "第三方认证服务",
            ],
            answer: 1,
            rationale: "OWASP 举例：Netflix's Passport 是 'an HMAC-protected structure containing user identity never exposed externally'。",
        },
        {
            id: "w8-3-q9",
            question: "请求超过限流阈值时返回什么 HTTP 状态码？",
            options: [
                "200 OK",
                "429 Too Many Requests",
                "500 Internal Server Error",
                "404 Not Found",
            ],
            answer: 1,
            rationale: "文档指出：'Clients may receive 429 Too Many Requests error responses' when rate limit is exceeded。",
        },
        {
            id: "w8-3-q10",
            question: "嵌入式 PDP（Policy Decision Point）的优势是什么？",
            options: [
                "集中管理所有决策",
                "策略集中定义但本地执行，减少网络调用",
                "不需要策略",
                "完全分散的策略",
            ],
            answer: 1,
            rationale: "OWASP 描述：'Centralized with Embedded PDP: Rules are centrally defined but evaluated locally, minimizing external dependencies'。",
        },
        {
            id: "w8-3-q11",
            question: "如何实现分布式限流？",
            options: [
                "每个实例独立限流",
                "使用共享状态（如 Redis Cluster）实现全局限流",
                "不需要限流",
                "只在一个实例限流",
            ],
            answer: 1,
            rationale: "分布式限流需要共享状态，'Redis Cluster automatically handles data sharding by dividing keys across hash slots'。",
        },
        {
            id: "w8-3-q12",
            question: "Access Token 模式的主要好处是什么？",
            options: [
                "减少代码量",
                "安全传递身份信息，服务可验证请求者授权",
                "提高性能",
                "减少存储",
            ],
            answer: 1,
            rationale: "microservices.io 列出好处：'The identity of the requestor is securely passed around' and 'Services can verify that the requestor is authorized'。",
        },
    ],
    "w8-4": [
        {
            id: "w8-4-q1",
            question: "Kong Gateway 的定义是什么？",
            options: [
                "数据库",
                "轻量、快速、灵活的云原生 API 网关",
                "消息队列",
                "容器编排平台",
            ],
            answer: 1,
            rationale: "Kong 文档描述：'a lightweight, fast, and flexible cloud-native API gateway'。",
        },
        {
            id: "w8-4-q2",
            question: "Apache APISIX 使用什么存储配置？",
            options: [
                "MySQL",
                "etcd",
                "PostgreSQL",
                "MongoDB",
            ],
            answer: 1,
            rationale: "APISIX 文档说明：使用 etcd 存储配置，quickstart 会部署 'containerized APISIX and etcd via Docker'。",
        },
        {
            id: "w8-4-q3",
            question: "Envoy 的定义是什么？",
            options: [
                "数据库代理",
                "为大型现代服务架构设计的 L7 代理和通信总线",
                "负载均衡器",
                "消息队列",
            ],
            answer: 1,
            rationale: "Envoy 文档定义：'an L7 proxy and communication bus designed for large modern service oriented architectures'。",
        },
        {
            id: "w8-4-q4",
            question: "Envoy 支持哪些协议？",
            options: [
                "只支持 HTTP",
                "HTTP/1.1、HTTP/2、HTTP/3、gRPC、TCP、UDP、Redis、MongoDB、PostgreSQL",
                "只支持 TCP",
                "只支持 gRPC",
            ],
            answer: 1,
            rationale: "Envoy 文档：支持 'HTTP/1.1, HTTP/2, and HTTP/3 (alpha)', 'TCP, UDP, HTTP, Redis, MongoDB, and PostgreSQL'。",
        },
        {
            id: "w8-4-q5",
            question: "Kong 支持的架构模式有哪些？",
            options: [
                "只有单节点",
                "传统模式、Hybrid 模式、DB-less 模式",
                "只有集群模式",
                "只有云模式",
            ],
            answer: 1,
            rationale: "Kong 文档提到部署灵活性：'traditional mode, hybrid mode, and DB-less configurations'。",
        },
        {
            id: "w8-4-q6",
            question: "Envoy 为什么适合 Service Mesh？",
            options: [
                "配置简单",
                "独立进程运行，语言无关，支持动态配置",
                "只支持 Java",
                "不支持负载均衡",
            ],
            answer: 1,
            rationale: "Envoy 'runs as a self-contained service, enabling it to work across heterogeneous environments' with 'Dynamic Configuration'。",
        },
        {
            id: "w8-4-q7",
            question: "APISIX 的主要特性有哪些？",
            options: [
                "只有路由功能",
                "动态路由、动态证书、A/B 测试、金丝雀发布、限流、监控",
                "只有安全功能",
                "只有监控功能",
            ],
            answer: 1,
            rationale: "APISIX 文档列出：'Dynamic routing, certificate handling, A/B testing, canary releases, rate limiting, monitoring'。",
        },
        {
            id: "w8-4-q8",
            question: "Kong 的架构模型是什么？",
            options: [
                "单体架构",
                "Control Plane 和 Data Plane",
                "只有 Data Plane",
                "P2P 架构",
            ],
            answer: 1,
            rationale: "Kong 文档描述：'Control Plane and Data Plane model'。",
        },
        {
            id: "w8-4-q9",
            question: "Envoy 的 Out-of-Process 设计有什么优势？",
            options: [
                "性能更低",
                "语言无关，可以在异构环境中工作",
                "更难部署",
                "需要特定语言",
            ],
            answer: 1,
            rationale: "Envoy 文档：Out-of-Process 设计 'enabling it to work across heterogeneous environments (Java, C++, Go, PHP, Python, etc.)'。",
        },
        {
            id: "w8-4-q10",
            question: "如何快速部署 APISIX？",
            options: [
                "需要复杂配置",
                "运行 quickstart 脚本：curl -sL https://run.api7.ai/apisix/quickstart | sh",
                "只能从源码编译",
                "只能在云上部署",
            ],
            answer: 1,
            rationale: "APISIX 文档：'Running a simple installation script: curl -sL https://run.api7.ai/apisix/quickstart | sh'。",
        },
        {
            id: "w8-4-q11",
            question: "Envoy 使用什么 API 进行动态配置？",
            options: [
                "REST API",
                "xDS API",
                "GraphQL",
                "SOAP",
            ],
            answer: 1,
            rationale: "Envoy 文档提到：'Dynamic Configuration: Consumes layered APIs (xDS) for centralized management'。",
        },
        {
            id: "w8-4-q12",
            question: "三种网关中哪个与 Service Mesh（如 Istio）集成最紧密？",
            options: [
                "Kong",
                "Envoy",
                "APISIX",
                "都一样紧密",
            ],
            answer: 1,
            rationale: "Envoy 被设计为 Service Mesh 数据平面，与 Istio 等深度集成：'serves as both a service-mesh component and edge/front proxy'。",
        },
    ],
}
