import type { LessonGuide } from "../types"
import type { QuizQuestion } from "@/lib/types"

export const week1Guides: Record<string, LessonGuide> = {
    "w1-1": {
        lessonId: "w1-1",
        background: [
            "【架构定义】microservices.io：单体架构将应用构建为 'a single deployable unit with one database'，所有子域存在于统一组件中，所有操作都是本地调用而非分布式。",
            "【核心优势】官方文档列出单体架构的四大优势：Simple interactions（组件间通信直接）、ACID transactions（传统事务保证）、Efficiency（无网络延迟）、Zero coupling（无服务间耦合）。",
            "【MonolithFirst 策略】Martin Fowler 提出即使预见微服务需求，新项目也应从单体开始：'Begin new projects as monoliths...focus on speed and rapid feedback cycles during initial development phases'。",
            "【边界发现】Fowler 强调：'refactoring of functionality between services is much harder than it is in a monolith'，单体阶段是发现正确服务边界的最佳时机。",
            "【Majestic Monolith】DHH 认为单体架构被不公平地贬低，对于小团队（如 12 名程序员）和大型复杂应用，刻意构建的集成系统可能优于过早采用微服务。",
        ],
        keyDifficulties: [
            "【规模陷阱】官方文档警告：随着应用增长，单体会变得 'difficult to understand and maintain'，单一组件的复杂性成为开发瓶颈。",
            "【团队协调】多团队共享代码库需要大量协调：'Development teams share codebases, requiring coordination'，这与微服务的团队自治形成鲜明对比。",
            "【技术限制】官方文档：'The application uses a single technology stack, which might not be ideal'——单体无法根据子域需求选择最优技术栈。",
            "【扩展困境】无法按特性隔离扩展：'Cannot segregate subdomains based on specific requirements'，必须整体扩展而非按需扩展。",
            "【部署风险】构建和测试整个应用耗时更长，部署频率受限，每次发布都是高风险事件。",
        ],
        handsOnPath: [
            "评估当前系统：列出所有子域/模块，标记它们的技术栈需求和扩展需求是否一致。",
            "分析团队结构：团队是否需要独立部署？是否存在代码库协调的痛点？",
            "检查部署频率：当前从代码提交到生产的周期是多长？是否满足业务需求？",
            "识别技术债务：单体中是否存在无法升级的依赖？是否有子域被技术栈限制？",
            "绘制依赖图：使用工具（如 Structure101）分析模块间耦合度，识别潜在的服务边界。",
        ],
        selfCheck: [
            "单体架构的四大核心优势是什么？为什么微服务难以获得这些优势？",
            "MonolithFirst 策略的核心论点是什么？什么情况下应该遵循这个建议？",
            "DHH 为什么称单体为 'Majestic'？他认为什么规模的团队适合单体架构？",
            "单体架构的主要缺点有哪些？这些缺点在什么规模下会变得显著？",
            "如何判断你的系统是否应该从单体开始？有哪些关键指标？",
            "Fowler 建议的三种单体到微服务的过渡策略是什么？",
        ],
        extensions: [
            "研究 Basecamp/HEY 如何使用单体架构支持大规模产品。",
            "阅读 Shopify 的 'Deconstructing the Monolith' 系列，了解何时以及如何拆分。",
            "探索模块化单体（Modular Monolith）作为单体与微服务之间的中间方案。",
            "了解 Fowler 提到的 'Sacrificial Architecture' 概念——有时重写比重构更明智。",
        ],
        sourceUrls: [
            "https://microservices.io/patterns/monolithic.html",
            "https://martinfowler.com/bliki/MonolithFirst.html",
            "https://signalvnoise.com/svn3/the-majestic-monolith/",
        ],
    },
    "w1-2": {
        lessonId: "w1-2",
        background: [
            "【官方定义】microservices.io：微服务架构 'structures an application as a set of loosely coupled, deployable/executable components organized around business capabilities'。",
            "【Martin Fowler 定义】'an approach to developing a single application as a suite of small services, each running in its own process'，强调独立部署和轻量级通信机制。",
            "【九大特征】Fowler 文章定义了微服务的九大核心特征：Componentization via Services、Organized Around Business Capabilities、Products Not Projects、Smart Endpoints and Dumb Pipes 等。",
            "【Conway's Law】团队按业务能力组织，而非技术层：'Cross-functional teams owning full technology stacks (UI, database, logic)'，组织结构映射系统设计。",
            "【模式语言】Chris Richardson 创建了完整的微服务模式语言，涵盖十大类别：Architectural Style、Service Boundaries、Refactoring、Collaboration、Testing、Deployment 等。",
        ],
        keyDifficulties: [
            "【分布式复杂性】官方文档：'Complex distributed operations'——远程调用带来延迟和失败风险，这是单体架构中不存在的。",
            "【最终一致性】Fowler：'Decentralized data management eliminates distributed transactions'，开发者必须处理一致性窗口和数据不一致问题。",
            "【服务边界】Fowler 警告：'Difficulty determining optimal service boundaries'——错误的边界会导致复杂性转移到服务间连接。",
            "【运维成本】microservices.io：微服务需要成熟的 DevOps 文化和更高技能水平，'Complexity isn't eliminated, it's merely shifted...to the interconnections between services'。",
            "【重构困难】跨服务边界的重构比单体内重构困难得多：'Refactoring challenges across service boundaries'。",
        ],
        handsOnPath: [
            "绘制系统上下文图：识别外部系统、用户类型和核心业务流程。",
            "使用事件风暴识别领域事件、聚合和潜在服务边界。",
            "为一个简单场景设计两个服务的交互：定义 API、数据流和错误处理。",
            "模拟分布式失败：如果服务 B 不可用，服务 A 应该如何响应？",
            "设计一个跨服务的业务流程：考虑事务一致性、补偿逻辑。",
        ],
        selfCheck: [
            "微服务架构的官方定义是什么？与 SOA 的主要区别是什么？",
            "Martin Fowler 定义的九大微服务特征是什么？哪些是最关键的？",
            "'Smart Endpoints and Dumb Pipes' 原则意味着什么？为什么要避免智能中间件？",
            "微服务的主要优势是什么？这些优势在什么条件下才能实现？",
            "微服务的主要缺点有哪些？Fowler 的建议是什么？",
            "什么是 'Products Not Projects' 理念？Amazon 的 'you build, you run it' 如何体现这一理念？",
            "微服务模式语言包含哪些主要类别？",
        ],
        extensions: [
            "深入研究 Netflix 的微服务架构演进历史。",
            "探索 Service Mesh（如 Istio）如何简化微服务通信和治理。",
            "了解 Domain-Driven Design (DDD) 如何指导服务边界划分。",
            "研究 API Gateway 模式和 Backend-for-Frontend (BFF) 模式。",
        ],
        sourceUrls: [
            "https://microservices.io/patterns/microservices.html",
            "https://martinfowler.com/articles/microservices.html",
            "https://microservices.io/patterns/",
        ],
    },
    "w1-3": {
        lessonId: "w1-3",
        background: [
            "【力量模型隐喻】Chris Richardson 借用天体物理学概念：Dark Energy（暗能量）代表推动服务分解的斥力，Dark Matter（暗物质）代表抵抗分解、推动聚合的引力。",
            "【五大暗能量力量】推动分解：1) Simple Components（简单组件易于理解维护）2) Team Autonomy（团队自治）3) Fast Deployment Pipeline（快速部署）4) Multiple Technology Stacks（技术多样性）5) Segregate by Characteristics（按特性隔离）。",
            "【五大暗物质力量】抵抗分解：1) Simple Interactions（简单交互）2) Efficient Interactions（高效通信）3) Prefer ACID over BASE（事务一致性）4) Minimize Runtime Coupling（减少运行时耦合）5) Minimize Design-Time Coupling（减少设计时耦合）。",
            "【架构设计策略】Richardson：'design an architecture that minimizes the repulsive forces within components AND minimizes the attractive forces between components'——平衡两种力量。",
            "【权衡视角】Fowler 文章强调三大权衡：Strong Module Boundaries vs Distribution Complexity、Independent Deployment vs Eventual Consistency、Technology Diversity vs Operational Complexity。",
        ],
        keyDifficulties: [
            "【分布式成本】Fowler：'Remote calls introduce performance latency and failure risks absent in monolithic systems'——分布式带来单体中不存在的问题。",
            "【最终一致性挑战】'Your update was received by the pink node, but your get request was handled by the green node'——数据可能暂时不一致。",
            "【Microservice Premium】Fowler：只有系统足够复杂才能证明微服务开销合理，简单系统的开销超过收益。",
            "【DevOps 成熟度】成功依赖于团队质量、协作、代码纪律和架构演进——这些因素比架构风格更重要。",
            "【过度分解风险】过细的服务划分会导致暗物质力量（如通信开销、一致性问题）压倒暗能量带来的好处。",
        ],
        handsOnPath: [
            "为你的系统评估每个暗能量力量：哪些力量推动你走向微服务？强度如何？",
            "为你的系统评估每个暗物质力量：哪些力量阻止你分解？当前的操作有多少是跨子域的？",
            "绘制力量图：将子域放在图上，用箭头表示暗能量（向外）和暗物质（向内）。",
            "识别关键操作：列出核心业务流程，标记它们涉及哪些子域。",
            "模拟架构决策：如果将某两个子域分离为独立服务，暗物质力量会如何增加？",
        ],
        selfCheck: [
            "什么是暗能量和暗物质力量模型？这个隐喻如何帮助架构决策？",
            "列出五种暗能量力量。哪种力量对你的组织最重要？",
            "列出五种暗物质力量。哪种力量在你的系统中最强？",
            "Fowler 提到的三大微服务权衡是什么？",
            "什么是 'Microservice Premium'？如何判断你的系统是否值得支付这个代价？",
            "为什么说微服务的成功更依赖于团队因素而非架构本身？",
        ],
        extensions: [
            "观看 Chris Richardson 的 QCon 演讲：Dark Energy, Dark Matter and the Microservices Patterns。",
            "探索 Assemblage 方法——Richardson 的微服务架构定义流程。",
            "研究如何使用力量模型评估现有架构的演进方向。",
            "了解如何通过 Saga 和 CQRS 等模式缓解暗物质力量。",
        ],
        sourceUrls: [
            "https://microservices.io/post/microservices/2021/11/30/dark-matter-dark-energy.html",
            "https://martinfowler.com/articles/microservice-trade-offs.html",
            "https://www.youtube.com/watch?v=GBTdnfD6s5Q",
        ],
    },
    "w1-4": {
        lessonId: "w1-4",
        background: [
            "【三大前提条件】Fowler 定义微服务的三大必备能力：1) Rapid Provisioning（快速供应：数小时内启动新服务器）2) Basic Monitoring（基础监控：技术和业务层面）3) Rapid Application Deployment（快速部署：数小时内完成部署流水线）。",
            "【DevOps 文化】三大能力都依赖于 DevOps 文化——开发与运维团队的紧密协作，这是微服务成功的组织基础。",
            "【反方观点】Stefan Tilkov 文章 'Don't start with a monolith' 认为单体不可避免地创造过度耦合：'the parts will become extremely tightly coupled to each other. That's the very definition of a monolith'。",
            "【边界机会】Tilkov 认为新系统正是建立架构边界的最佳时机：'Building a new system is precisely when architectural boundaries should be established'。",
            "【模式语言价值】Microservices Patterns 书籍提供了实用的模式目录，采用 'a balanced, pragmatic approach, exploring both the benefits and drawbacks'。",
        ],
        keyDifficulties: [
            "【耦合不可逆】Tilkov 警告：'Separating a mature monolith is extremely challenging'——大多数组织难以成功拆解成熟的单体。",
            "【IDE 陷阱】单一项目中重构的便利性实际上使未来模块化更困难：'The convenience of refactoring within a single IDE project actually makes future modularization harder'。",
            "【前提条件缺失】许多组织在不具备三大前提条件的情况下尝试微服务，导致失败。",
            "【过度设计风险】Tilkov 也承认：'Well-structured monoliths may not need microservices anyway'——结构良好的单体可能根本不需要微服务。",
            "【评估标准模糊】如何量化 'sufficiently complex' 系统？如何判断团队是否具备微服务能力？",
        ],
        handsOnPath: [
            "评估快速供应能力：从申请到获得新服务器/容器需要多长时间？",
            "评估监控能力：是否有技术监控（错误率、可用性）和业务监控（订单量、转化率）？",
            "评估部署能力：从代码提交到生产部署的完整流水线需要多长时间？",
            "评估 DevOps 文化：开发和运维团队的协作程度如何？是否有共同的责任感？",
            "决策矩阵：列出微服务的利弊，结合你的团队和系统情况打分。",
        ],
        selfCheck: [
            "Fowler 定义的三大微服务前提条件是什么？你的组织满足几项？",
            "为什么 DevOps 文化是微服务成功的基础？",
            "Tilkov 反对 MonolithFirst 的主要论点是什么？",
            "什么情况下应该直接从微服务开始而非单体？",
            "如何评估你的系统是否 'sufficiently complex' 以证明微服务的合理性？",
            "Fowler 和 Tilkov 的观点如何调和？有没有中间方案？",
        ],
        extensions: [
            "阅读完整的 Microservices Patterns 书籍，系统学习所有模式。",
            "研究模块化单体（Modular Monolith）作为折中方案。",
            "探索特征开关（Feature Toggles）如何实现渐进式架构演进。",
            "了解 Strangler Fig 模式如何安全地从单体迁移到微服务。",
        ],
        sourceUrls: [
            "https://martinfowler.com/bliki/MicroservicePrerequisites.html",
            "https://martinfowler.com/articles/dont-start-monolith.html",
            "https://microservices.io/book",
        ],
    },
}

export const week1Quizzes: Record<string, QuizQuestion[]> = {
    "w1-1": [
        {
            id: "w1-1-q1",
            question: "根据 microservices.io，单体架构的定义是什么？",
            options: [
                "多个独立部署的服务组成的系统",
                "一个可部署单元包含所有子域和一个数据库",
                "按业务能力组织的分布式系统",
                "使用消息队列通信的服务集合",
            ],
            answer: 1,
            rationale: "microservices.io 定义单体架构为 'a single deployable unit with one database'，所有子域存在于统一组件中。",
        },
        {
            id: "w1-1-q2",
            question: "以下哪个不是单体架构的核心优势？",
            options: [
                "Simple interactions（简单交互）",
                "ACID transactions（事务保证）",
                "Independent deployment（独立部署）",
                "Zero coupling between services（无服务间耦合）",
            ],
            answer: 2,
            rationale: "独立部署是微服务的优势，不是单体的优势。单体架构的优势包括 Simple interactions、ACID transactions、Efficiency 和 Zero coupling。",
        },
        {
            id: "w1-1-q3",
            question: "Martin Fowler 的 MonolithFirst 策略的核心建议是什么？",
            options: [
                "永远不要使用微服务",
                "即使预见微服务需求，新项目也应从单体开始",
                "直接从微服务开始以避免重构",
                "单体和微服务应该同时开发",
            ],
            answer: 1,
            rationale: "Fowler 建议 'Begin new projects as monoliths, even if you anticipate eventual need for microservices'，因为初期应专注于快速反馈和验证。",
        },
        {
            id: "w1-1-q4",
            question: "根据 Fowler，为什么在单体阶段发现服务边界更好？",
            options: [
                "单体的性能更好",
                "单体内重构比跨服务重构容易得多",
                "单体不需要服务边界",
                "微服务不支持重构",
            ],
            answer: 1,
            rationale: "Fowler 强调 'refactoring of functionality between services is much harder than it is in a monolith'，单体阶段是发现正确边界的最佳时机。",
        },
        {
            id: "w1-1-q5",
            question: "DHH 在 'The Majestic Monolith' 中认为什么规模的团队适合单体架构？",
            options: [
                "只有 1-2 人的团队",
                "约 12 名程序员的小团队",
                "超过 100 人的大团队",
                "任何规模的团队",
            ],
            answer: 1,
            rationale: "DHH 以他的团队（12 名程序员）为例，认为小团队配合大型复杂应用更适合刻意构建的单体架构。",
        },
        {
            id: "w1-1-q6",
            question: "单体架构的主要技术限制是什么？",
            options: [
                "无法使用数据库",
                "必须使用单一技术栈，可能不是各子域的最优选择",
                "无法进行单元测试",
                "不支持 API 开发",
            ],
            answer: 1,
            rationale: "官方文档指出 'The application uses a single technology stack, which might not be ideal'，无法根据子域需求选择最优技术。",
        },
        {
            id: "w1-1-q7",
            question: "Fowler 提到的三种单体到微服务过渡策略中，哪个是 '从边缘逐步提取服务'？",
            options: [
                "Sacrificial Architecture",
                "Coarse-to-fine scaling",
                "Gradual peeling approach",
                "Big Bang rewrite",
            ],
            answer: 2,
            rationale: "Fowler 描述的 'Gradual peeling approach' 是从单体边缘逐步提取微服务，同时保持稳定的核心。",
        },
        {
            id: "w1-1-q8",
            question: "根据 DHH，为什么大公司的架构模式对小公司可能不适用？",
            options: [
                "小公司没有足够的预算",
                "大规模组织的模式在小规模下往往是相反的",
                "小公司的技术能力不足",
                "大公司使用专有技术",
            ],
            answer: 1,
            rationale: "DHH 指出 'The patterns that make sense for organizations orders of magnitude larger than yours, are often the exact opposite ones'。",
        },
        {
            id: "w1-1-q9",
            question: "单体架构在扩展性方面的主要问题是什么？",
            options: [
                "无法水平扩展",
                "无法按子域特性隔离扩展，必须整体扩展",
                "扩展成本太高",
                "扩展需要停机",
            ],
            answer: 1,
            rationale: "官方文档指出 'Cannot segregate subdomains based on specific requirements'，单体必须整体扩展而非按需扩展。",
        },
        {
            id: "w1-1-q10",
            question: "Fowler 为什么说 MonolithFirst 的建议是 'tentative'（暂定的）？",
            options: [
                "因为他不确定自己的观点",
                "因为微服务是新技术",
                "因为可借鉴的经验和案例还相对较少",
                "因为单体架构正在被淘汰",
            ],
            answer: 2,
            rationale: "Fowler 承认 'there are relatively few anecdotes to learn from' 关于微服务采用模式，建议仍是暂定的。",
        },
        {
            id: "w1-1-q11",
            question: "DHH 认为保持单体架构的一个好处是什么？",
            options: [
                "可以使用更多的云服务",
                "强制代码库保持可被个人理解，而非被团队孤岛化",
                "可以雇佣更少的开发者",
                "可以避免使用数据库",
            ],
            answer: 1,
            rationale: "DHH 强调单体 'Forces the codebase to remain understandable by individuals, not siloed teams'，这是代码质量的保障。",
        },
        {
            id: "w1-1-q12",
            question: "根据官方文档，单体架构最适合什么阶段的项目？",
            options: [
                "已经有数百万用户的成熟产品",
                "需要多团队协作的大型项目",
                "小型应用或早期阶段项目",
                "需要使用多种技术栈的项目",
            ],
            answer: 2,
            rationale: "官方文档指出单体架构 'Best suited for smaller applications or early-stage projects'，随规模增长会变得困难。",
        },
    ],
    "w1-2": [
        {
            id: "w1-2-q1",
            question: "microservices.io 对微服务架构的官方定义是什么？",
            options: [
                "一个大型应用分解为多个数据库",
                "围绕业务能力组织的一组松耦合、可独立部署的组件",
                "使用 REST API 通信的任何分布式系统",
                "在云上运行的容器化应用",
            ],
            answer: 1,
            rationale: "microservices.io 定义微服务架构为 'a set of loosely coupled, deployable/executable components organized around business capabilities'。",
        },
        {
            id: "w1-2-q2",
            question: "Martin Fowler 定义的微服务核心特征中，'Smart Endpoints and Dumb Pipes' 意味着什么？",
            options: [
                "使用智能消息队列处理业务逻辑",
                "逻辑在服务中，通信协议保持简单",
                "端点需要人工智能",
                "管道需要复杂的中间件",
            ],
            answer: 1,
            rationale: "Fowler 强调 'Applications built from microservices aim to be as decoupled and as cohesive as possible'，逻辑在服务中，通信用简单协议。",
        },
        {
            id: "w1-2-q3",
            question: "微服务中 'Products Not Projects' 理念的核心是什么？",
            options: [
                "团队只负责开发，不负责运维",
                "团队持续拥有服务，实践 'you build, you run it'",
                "项目完成后移交给其他团队",
                "每个服务都是一个独立的产品线",
            ],
            answer: 1,
            rationale: "Fowler 引用 Amazon 的 'you build, you run it' 理念，强调团队持续拥有服务而非项目式移交。",
        },
        {
            id: "w1-2-q4",
            question: "微服务架构中 'Decentralized Data Management' 的含义是什么？",
            options: [
                "所有服务共享一个数据库",
                "每个服务管理自己的数据库，支持多语言持久化",
                "数据存储在客户端",
                "不使用数据库",
            ],
            answer: 1,
            rationale: "Fowler 描述 'Each service manages its own database' 和 'Polyglot persistence: different services use different storage technologies'。",
        },
        {
            id: "w1-2-q5",
            question: "Conway's Law 在微服务架构中如何体现？",
            options: [
                "系统设计决定组织结构",
                "团队按业务能力组织，组织结构映射系统设计",
                "技术决定业务",
                "所有团队共享代码库",
            ],
            answer: 1,
            rationale: "Fowler 指出团队按业务能力而非技术层组织，'Cross-functional teams owning full technology stacks'，体现 Conway's Law。",
        },
        {
            id: "w1-2-q6",
            question: "以下哪个是微服务架构的主要缺点？",
            options: [
                "无法独立部署",
                "分布式系统的复杂性和跨服务边界的重构困难",
                "必须使用单一技术栈",
                "无法扩展",
            ],
            answer: 1,
            rationale: "Fowler 列出的缺点包括 'Complexity in managing distributed systems' 和 'Refactoring challenges across service boundaries'。",
        },
        {
            id: "w1-2-q7",
            question: "微服务的 'Design for Failure' 原则意味着什么？",
            options: [
                "设计系统总是失败",
                "假设服务会失败，构建弹性机制如熔断器",
                "失败后重新设计系统",
                "不需要错误处理",
            ],
            answer: 1,
            rationale: "Fowler 强调 'Assume services will fail; build resilience' 和 'Circuit breaker patterns and timeout mechanisms'。",
        },
        {
            id: "w1-2-q8",
            question: "Chris Richardson 的微服务模式语言涵盖多少个主要类别？",
            options: [
                "3 个",
                "5 个",
                "10 个以上",
                "2 个",
            ],
            answer: 2,
            rationale: "模式语言涵盖十多个类别：Architectural Style、Service Boundaries、Refactoring、Collaboration、Testing、Deployment 等。",
        },
        {
            id: "w1-2-q9",
            question: "Fowler 对微服务的最终建议是什么？",
            options: [
                "所有项目都应该使用微服务",
                "从单体开始，保持模块化，当单体成为问题时再拆分",
                "永远不要使用微服务",
                "同时开发单体和微服务",
            ],
            answer: 1,
            rationale: "Fowler 建议 'begin with a monolith, keep it modular, and split it into microservices once the monolith becomes a problem'。",
        },
        {
            id: "w1-2-q10",
            question: "微服务的 'Evolutionary Design' 原则强调什么？",
            options: [
                "服务设计一次性完成，永不改变",
                "服务设计为可替换的，边界随理解演进",
                "设计必须遵循严格的标准",
                "所有服务必须同时更新",
            ],
            answer: 1,
            rationale: "Fowler 描述 'Services designed for replaceability, not permanence' 和 'Refactor component boundaries as understanding evolves'。",
        },
        {
            id: "w1-2-q11",
            question: "微服务架构中，为什么 'Decentralized Governance' 很重要？",
            options: [
                "可以避免任何标准",
                "各服务可根据需求选择技术，避免僵化的企业标准",
                "不需要任何治理",
                "所有决策都由一个中央团队做出",
            ],
            answer: 1,
            rationale: "Fowler 强调 'Technology choices vary per service based on requirements' 和 'Open standards preferred over rigid corporate mandates'。",
        },
        {
            id: "w1-2-q12",
            question: "Fowler 为什么说对微服务的长期效果判断还为时过早？",
            options: [
                "因为微服务是一个失败的实验",
                "因为还没有足够的时间和经验来做全面判断",
                "因为所有公司都成功采用了微服务",
                "因为技术在不断变化",
            ],
            answer: 1,
            rationale: "Fowler 承认 'Not enough time has passed for us to make a full judgement' about microservices' ultimate effectiveness。",
        },
    ],
    "w1-3": [
        {
            id: "w1-3-q1",
            question: "Chris Richardson 的力量模型中，'暗能量'（Dark Energy）代表什么？",
            options: [
                "推动服务聚合的引力",
                "推动服务分解的斥力",
                "数据库的存储容量",
                "网络通信的延迟",
            ],
            answer: 1,
            rationale: "Richardson 定义 Dark Energy 为 'repulsive forces that encourage decomposing subdomains into separate services'，是推动分解的力量。",
        },
        {
            id: "w1-3-q2",
            question: "以下哪个不是五大暗能量力量之一？",
            options: [
                "Simple Components（简单组件）",
                "Team Autonomy（团队自治）",
                "Efficient Interactions（高效交互）",
                "Fast Deployment Pipeline（快速部署）",
            ],
            answer: 2,
            rationale: "Efficient Interactions 是暗物质力量。五大暗能量力量是：Simple Components、Team Autonomy、Fast Deployment Pipeline、Multiple Technology Stacks、Segregate by Characteristics。",
        },
        {
            id: "w1-3-q3",
            question: "'暗物质'（Dark Matter）力量 'Prefer ACID over BASE' 的含义是什么？",
            options: [
                "优先使用 NoSQL 数据库",
                "传统事务一致性比最终一致性的分布式模式更简单",
                "酸性溶液比碱性溶液更好",
                "使用更多的分布式事务",
            ],
            answer: 1,
            rationale: "这个暗物质力量表示 'Transactional consistency is simpler than eventually consistent distributed patterns like sagas'。",
        },
        {
            id: "w1-3-q4",
            question: "Fowler 文章中提到的微服务三大权衡之一是什么？",
            options: [
                "成本 vs 收益",
                "Strong Module Boundaries vs Distribution Complexity",
                "开发 vs 测试",
                "前端 vs 后端",
            ],
            answer: 1,
            rationale: "Fowler 提到三大权衡：Strong Module Boundaries vs Distribution Complexity、Independent Deployment vs Eventual Consistency、Technology Diversity vs Operational Complexity。",
        },
        {
            id: "w1-3-q5",
            question: "什么是 'Microservice Premium'？",
            options: [
                "微服务的许可费用",
                "只有系统足够复杂才能证明微服务开销合理的门槛",
                "微服务的性能优势",
                "微服务的高级功能",
            ],
            answer: 1,
            rationale: "Fowler 指出微服务有 'Microservice Premium'，只有 'Systems are sufficiently complex to justify' 时才值得支付这个开销。",
        },
        {
            id: "w1-3-q6",
            question: "Richardson 建议的架构设计策略是什么？",
            options: [
                "最大化所有暗能量力量",
                "最小化组件内的斥力，同时最小化组件间的引力",
                "忽略所有力量",
                "只考虑暗物质力量",
            ],
            answer: 1,
            rationale: "Richardson 建议 'design an architecture that minimizes the repulsive forces within components AND minimizes the attractive forces between components'。",
        },
        {
            id: "w1-3-q7",
            question: "暗物质力量 'Minimize Runtime Coupling' 的目标是什么？",
            options: [
                "增加服务依赖",
                "减少服务间依赖以最大化可用性和减少延迟",
                "消除所有服务通信",
                "使用更多的同步调用",
            ],
            answer: 1,
            rationale: "这个暗物质力量旨在 'Reducing service dependencies to maximize availability and reduce latency'。",
        },
        {
            id: "w1-3-q8",
            question: "根据 Fowler，微服务引入的 'Distribution Complexity' 包括什么？",
            options: [
                "更简单的错误处理",
                "远程调用带来的延迟和失败风险",
                "更快的响应时间",
                "更少的代码量",
            ],
            answer: 1,
            rationale: "Fowler 指出 'Remote calls introduce performance latency and failure risks absent in monolithic systems'。",
        },
        {
            id: "w1-3-q9",
            question: "暗能量力量 'Segregate by Characteristics' 意味着什么？",
            options: [
                "所有服务使用相同的配置",
                "根据资源需求、可用性要求和安全需求分离服务",
                "按字母顺序组织服务",
                "使用相同的技术栈",
            ],
            answer: 1,
            rationale: "这个暗能量力量是 'Separating services based on resource needs, availability requirements, and security demands'。",
        },
        {
            id: "w1-3-q10",
            question: "Fowler 认为微服务成功最终依赖于什么？",
            options: [
                "使用最新的技术",
                "团队质量、协作、代码纪律和架构演进",
                "大量的服务器",
                "复杂的部署流程",
            ],
            answer: 1,
            rationale: "Fowler 强调 'Success ultimately depends on team quality, collaboration, code discipline, and architectural evolution—factors more influential than architectural style alone'。",
        },
        {
            id: "w1-3-q11",
            question: "最终一致性（Eventual Consistency）带来的挑战是什么？",
            options: [
                "数据永远不会一致",
                "更新可能被一个节点接收但读取在另一个节点处理，导致临时不一致",
                "需要更多的存储空间",
                "无法使用数据库",
            ],
            answer: 1,
            rationale: "Fowler 描述 'Your update was received by the pink node, but your get request was handled by the green node'，造成临时数据不一致。",
        },
        {
            id: "w1-3-q12",
            question: "暗物质力量 'Minimize Design-Time Coupling' 的目的是什么？",
            options: [
                "增加服务间的协调",
                "防止需要同步更改多个服务以保持生产力",
                "使所有服务使用相同的设计",
                "减少文档数量",
            ],
            answer: 1,
            rationale: "这个暗物质力量旨在 'Preventing synchronized changes across multiple services to maintain productivity'。",
        },
    ],
    "w1-4": [
        {
            id: "w1-4-q1",
            question: "Fowler 定义的三大微服务前提条件中，Rapid Provisioning 的要求是什么？",
            options: [
                "一个月内启动新服务器",
                "数小时内启动新服务器",
                "立即启动新服务器",
                "不需要新服务器",
            ],
            answer: 1,
            rationale: "Fowler 要求 'you should be able to fire up a new server in a matter of hours'，这需要大量的自动化基础设施。",
        },
        {
            id: "w1-4-q2",
            question: "Basic Monitoring 前提条件包括哪些方面？",
            options: [
                "只有技术监控",
                "技术监控和业务级监控",
                "只有业务监控",
                "不需要监控",
            ],
            answer: 1,
            rationale: "Fowler 强调需要 'Technical monitoring (error counts, service availability)' 和 'Business-level monitoring (tracking metrics like order volumes)'。",
        },
        {
            id: "w1-4-q3",
            question: "三大前提条件都依赖于什么组织基础？",
            options: [
                "大量的预算",
                "DevOps 文化——开发与运维的紧密协作",
                "专门的架构团队",
                "外包开发",
            ],
            answer: 1,
            rationale: "Fowler 强调 'All three capabilities depend on establishing DevOps culture—close collaboration between development and operations teams'。",
        },
        {
            id: "w1-4-q4",
            question: "Tilkov 在 'Don't start with a monolith' 中认为单体的核心问题是什么？",
            options: [
                "性能太差",
                "各部分会变得极度耦合",
                "无法使用数据库",
                "开发成本太高",
            ],
            answer: 1,
            rationale: "Tilkov 指出 'the parts will become extremely tightly coupled to each other. That's the very definition of a monolith'。",
        },
        {
            id: "w1-4-q5",
            question: "Tilkov 认为建立架构边界的最佳时机是什么？",
            options: [
                "系统成熟后",
                "构建新系统时",
                "重构时",
                "系统失败后",
            ],
            answer: 1,
            rationale: "Tilkov 认为 'Building a new system is precisely when architectural boundaries should be established'，不应推迟模块化决策。",
        },
        {
            id: "w1-4-q6",
            question: "根据 Tilkov，为什么后期拆分单体很困难？",
            options: [
                "技术过时",
                "单一 IDE 项目中的重构便利性实际上使未来模块化更困难",
                "团队人员流失",
                "预算不足",
            ],
            answer: 1,
            rationale: "Tilkov 指出 'The convenience of refactoring within a single IDE project actually makes future modularization harder, not easier'。",
        },
        {
            id: "w1-4-q7",
            question: "Rapid Application Deployment 前提条件的目标是什么？",
            options: [
                "一年部署一次",
                "部署流水线在数小时内完成",
                "手动部署",
                "不需要部署",
            ],
            answer: 1,
            rationale: "Fowler 要求 'a DeploymentPipeline that can execute in no more than a couple of hours'，完全自动化应是目标。",
        },
        {
            id: "w1-4-q8",
            question: "Tilkov 认为什么情况下应该直接从微服务开始？",
            options: [
                "所有新项目",
                "系统足够大、深入理解领域、需要独立交付各部分",
                "小型简单项目",
                "预算充足时",
            ],
            answer: 1,
            rationale: "Tilkov 建议当 'system is large enough, understand your domain deeply, need fast independent delivery of individual parts' 时直接使用微服务。",
        },
        {
            id: "w1-4-q9",
            question: "Microservices Patterns 书籍的方法论特点是什么？",
            options: [
                "只推荐微服务",
                "采用平衡、务实的方法，探索利弊两面",
                "只讨论单体架构",
                "不提供具体模式",
            ],
            answer: 1,
            rationale: "书籍采用 'a balanced, pragmatic approach, exploring both the benefits and drawbacks'，而非一味推崇微服务。",
        },
        {
            id: "w1-4-q10",
            question: "Fowler 强调这三大前提条件有什么特点？",
            options: [
                "只对微服务有用",
                "是任何系统架构都有益的基线能力",
                "只对单体有用",
                "可以在微服务生产后再建立",
            ],
            answer: 1,
            rationale: "Fowler 强调 'these aren't microservices-exclusive needs: they're baseline competencies beneficial for any system architecture'。",
        },
        {
            id: "w1-4-q11",
            question: "Tilkov 对 'Well-structured monoliths' 的观点是什么？",
            options: [
                "它们仍然需要拆分为微服务",
                "它们可能根本不需要微服务",
                "它们不存在",
                "它们比微服务更差",
            ],
            answer: 1,
            rationale: "Tilkov 承认 'Well-structured monoliths may not need microservices anyway'，好的单体可能不需要微服务。",
        },
        {
            id: "w1-4-q12",
            question: "如何调和 Fowler（MonolithFirst）和 Tilkov（Don't start with monolith）的观点？",
            options: [
                "两个观点完全矛盾，只能选择一个",
                "根据团队能力、领域理解和系统复杂度做具体判断",
                "总是选择微服务",
                "总是选择单体",
            ],
            answer: 1,
            rationale: "两个观点都强调具体情况具体分析：团队是否具备微服务能力、是否理解领域、系统是否足够复杂，需要根据这些因素做判断。",
        },
    ],
}
