import type { QuizQuestion } from "../types";

export const week16: Record<string, QuizQuestion[]> = {
  "w16-1": [
    {
      id: "w16-1-q1",
      question: "使用 etcdctl 需注意设置什么环境变量？",
      options: [
        "ETCDCTL_API=3，确保使用 v3 API",
        "KUBECONFIG",
        "PATH",
        "ETCDCTL_USE_V2",
      ],
      answer: 0,
      rationale: "etcd 备份/恢复官方示例要求显式设置 API 版本。",
    },
    {
      id: "w16-1-q2",
      question: "创建快照的命令示例？",
      options: [
        "etcdctl --endpoints=https://127.0.0.1:2379 --cacert=... --cert=... --key=... snapshot save backup.db",
        "etcdctl backup",
        "kubectl get etcd",
        "tar /var/lib/etcd",
      ],
      answer: 0,
      rationale: "官方指南使用 snapshot save 并提供证书与端点。",
    },
    {
      id: "w16-1-q3",
      question: "恢复 snapshot 时必须做什么？",
      options: [
        "使用 snapshot restore 到新的数据目录，并更新启动参数指向该目录",
        "直接覆盖旧数据目录并启动",
        "无需停止集群",
        "在运行中的 etcd 执行恢复",
      ],
      answer: 0,
      rationale: "恢复需离线，使用 restore 生成新 data-dir，再以新目录启动。",
    },
    {
      id: "w16-1-q4",
      question: "多节点 etcd 集群恢复后的 cluster-token/initial-cluster 配置应？",
      options: [
        "使用新的 token/cluster 配置，避免与旧集群产生冲突",
        "保持不变",
        "无需配置",
        "使用随机端口",
      ],
      answer: 0,
      rationale: "恢复新集群需更新集群标识，防止成员 ID 冲突。",
    },
    {
      id: "w16-1-q5",
      question: "如何验证 snapshot 完整性？",
      options: [
        "etcdctl snapshot status backup.db",
        "直接打开文件",
        "kubectl get secrets",
        "没有办法验证",
      ],
      answer: 0,
      rationale: "snapshot status 显示快照信息/校验。",
    },
    {
      id: "w16-1-q6",
      question: "Kubernetes Master 节点 etcd 数据目录默认位置？",
      options: [
        "/var/lib/etcd",
        "/etc/kubernetes/pki",
        "/var/log/etcd",
        "/opt/etcd",
      ],
      answer: 0,
      rationale: "kubeadm 默认 etcd 数据目录在 /var/lib/etcd。",
    },
    {
      id: "w16-1-q7",
      question: "从备份恢复到单节点测试环境的步骤包括？",
      options: [
        "停止 kube-apiserver/etcd -> restore 到新目录 -> 修改静态 Pod 清单使用新目录 -> 重启",
        "直接删除 kubelet",
        "仅重启 kube-proxy",
        "使用 kubectl apply backup.db",
      ],
      answer: 0,
      rationale: "官方 CKA 考点演示了离线恢复需要修改静态 Pod 清单。",
    },
    {
      id: "w16-1-q8",
      question: "快照跨版本兼容性注意？",
      options: [
        "主要兼容相邻小版本，跨大版本需谨慎并遵循发布说明",
        "完全兼容任何版本",
        "不可恢复",
        "只要同一云厂商即可",
      ],
      answer: 0,
      rationale: "etcd 建议同版本或兼容范围内恢复。",
    },
    {
      id: "w16-1-q9",
      question: "查看集群成员信息的命令？",
      options: [
        "etcdctl member list",
        "kubectl get etcd",
        "kubectl get nodes",
        "etcdctl peers",
      ],
      answer: 0,
      rationale: "member list 显示成员 ID/状态，恢复时常用。",
    },
    {
      id: "w16-1-q10",
      question: "为何建议定期做 etcd 备份？",
      options: [
        "防止数据损坏/误操作，快速恢复控制平面",
        "为了扩容节点",
        "减少日志",
        "提高 HPA 精度",
      ],
      answer: 0,
      rationale: "etcd 持有集群状态，备份是灾备关键环节。",
    },
  ],
  "w16-2": [
    {
      id: "w16-2-q1",
      question: "Pod 被标记 OOMKilled 的常见原因？",
      options: [
        "容器内存使用超过 limit，内核 OOM 杀死进程",
        "磁盘不足",
        "CPU 使用过低",
        "镜像不存在",
      ],
      answer: 0,
      rationale: "OOMKilled 由内核/容器 runtime 触发，通常因内存限制。",
    },
    {
      id: "w16-2-q2",
      question: "排查 OOMKilled 时应查看？",
      options: [
        "kubectl describe pod 事件、容器内存请求/限制、应用日志",
        "kube-proxy 日志",
        "仅节点数量",
        "etcd 证书",
      ],
      answer: 0,
      rationale: "描述信息与资源配置是首要线索。",
    },
    {
      id: "w16-2-q3",
      question: "CrashLoopBackOff 常见原因？",
      options: [
        "容器启动后立即退出（配置缺失、探针失败、依赖不可用等）",
        "镜像拉取失败",
        "节点宕机",
        "网络策略生效",
      ],
      answer: 0,
      rationale: "重复崩溃触发退避，需检查日志/探针/依赖。",
    },
    {
      id: "w16-2-q4",
      question: "排查 CrashLoopBackOff 的技巧？",
      options: [
        "kubectl logs --previous / 使用 sleep 包装启动 / 启用临时容器调试",
        "只看事件",
        "删除 Pod 即可",
        "修改 kube-proxy",
      ],
      answer: 0,
      rationale: "可查看前次日志或使用临时容器进入环境排查。",
    },
    {
      id: "w16-2-q5",
      question: "ImagePullBackOff 的主要原因？",
      options: [
        "镜像不存在/名称错误、私有仓库认证失败、网络不可达",
        "Pod 配额超限",
        "节点时间不同步",
        "Service 未创建",
      ],
      answer: 0,
      rationale: "事件中通常显示 ErrImagePull，需检查镜像/凭证/网络。",
    },
    {
      id: "w16-2-q6",
      question: "调试 ImagePullBackOff 的首要步骤？",
      options: [
        "kubectl describe pod 查看事件并验证 image/secret/registry 可达",
        "重启 API Server",
        "扩容节点",
        "修改 Deployment 名称",
      ],
      answer: 0,
      rationale: "事件信息指明拉取失败原因，如 401/404/timeout。",
    },
    {
      id: "w16-2-q7",
      question: "节点资源压力导致的驱逐现象？",
      options: [
        "Pod 状态显示 Evicted/Terminating，事件包含内存/磁盘压力",
        "显示 Running",
        "变为 Completed",
        "ImagePullBackOff",
      ],
      answer: 0,
      rationale: "kubelet 在压力下可能驱逐低优先级 Pod。",
    },
    {
      id: "w16-2-q8",
      question: "查看集群事件时间序列的命令？",
      options: [
        "kubectl get events --sort-by=.metadata.creationTimestamp",
        "kubectl logs kubelet",
        "kubectl top pods",
        "kubectl describe node",
      ],
      answer: 0,
      rationale: "排序事件有助于定位故障发生顺序。",
    },
    {
      id: "w16-2-q9",
      question: "镜像拉取私有仓库需确保？",
      options: [
        "imagePullSecret 已绑定，节点可访问 registry，证书/域名正确",
        "Pod 使用 hostNetwork",
        "节点有 GPU",
        "禁用 HPA",
      ],
      answer: 0,
      rationale: "认证/网络/证书问题常导致 ErrImagePull。",
    },
    {
      id: "w16-2-q10",
      question: "kubelet 日志在故障排查中的作用？",
      options: [
        "可提供调度/拉取/探针/驱逐等节点侧的详细错误信息",
        "无任何作用",
        "只记录 CPU 使用率",
        "仅记录网络策略",
      ],
      answer: 0,
      rationale: "节点侧日志有助于深入理解 Pod 失败原因。",
    },
  ],
  "w16-3": [
    {
      id: "w16-3-q1",
      question: "CKA 与 CKAD 的定位差异？",
      options: [
        "CKA 偏集群管理/运维/故障排查，CKAD 偏应用设计/开发",
        "两者相同",
        "CKA 仅考 Helm",
        "CKAD 只考网络",
      ],
      answer: 0,
      rationale: "官方考纲区分管理与应用侧技能。",
    },
    {
      id: "w16-3-q2",
      question: "考试形式是什么？",
      options: [
        "在线监考的实操命令行任务，需要在规定时间内完成",
        "选择题",
        "开放式论文",
        "线下笔试",
      ],
      answer: 0,
      rationale: "CKA/CKAD 皆为动手操作题。",
    },
    {
      id: "w16-3-q3",
      question: "官方允许的资料？",
      options: [
        "可访问 kubernetes.io/docs 和 GitHub 官方仓库（只读）",
        "可访问互联网任意网站",
        "必须离线",
        "可携带纸质资料",
      ],
      answer: 0,
      rationale: "考试允许查阅官方文档，禁止其他网站。",
    },
    {
      id: "w16-3-q4",
      question: "高效答题的技巧？",
      options: [
        "使用 kubectl 别名/自动补全、模板文件、先做高分题、保存关键命令历史",
        "逐题完整阅读手册后再做",
        "不需要规划时间",
        "全部使用 GUI",
      ],
      answer: 0,
      rationale: "时间管理与命令熟练度是通过考试关键。",
    },
    {
      id: "w16-3-q5",
      question: "考试环境切换集群的方式？",
      options: [
        "题目提供的 context 切换命令，或使用 kubectl config use-context <ctx>",
        "修改 /etc/hosts",
        "重启节点",
        "更换 kubelet",
      ],
      answer: 0,
      rationale: "每题可能有不同 context，需要正确切换。",
    },
    {
      id: "w16-3-q6",
      question: "为什么掌握命令式创建对象有帮助？",
      options: [
        "可快速生成 YAML 骨架（kubectl create/Run --dry-run=client -o yaml）节省时间",
        "考试禁止 YAML",
        "只能使用 GUI",
        "与考试无关",
      ],
      answer: 0,
      rationale: "命令式生成模板再编辑是提速常见技巧。",
    },
    {
      id: "w16-3-q7",
      question: "CKA/CKAD 时间/题量（以最新官方为准）通常是？",
      options: [
        "约 2 小时，十余道实操任务",
        "30 分钟，3 道题",
        "一整天",
        "无固定时间",
      ],
      answer: 0,
      rationale: "目前考试时长约 2 小时左右，题目数量十几道。",
    },
    {
      id: "w16-3-q8",
      question: "考场常见失分点？",
      options: [
        "忘记切 context/命名空间、未保存 YAML、覆盖现有资源、时间分配不均",
        "不会写代码",
        "网络不通",
        "缺少浏览器",
      ],
      answer: 0,
      rationale: "操作细节易出错，需谨慎检查。",
    },
    {
      id: "w16-3-q9",
      question: "练习资源推荐？",
      options: [
        "官方考纲任务、killer.sh/CKA 模拟环境、Kind/Minikube 本地练习",
        "仅阅读文档",
        "生产环境练习",
        "无可用资源",
      ],
      answer: 0,
      rationale: "实践练习是通过考试的关键。",
    },
    {
      id: "w16-3-q10",
      question: "CKA vs CKAD 通过分数？",
      options: [
        "需达到官方规定的及格线（通常 66% 左右，具体以当前公告为准）",
        "必须 100%",
        "只要提交即通过",
        "由考官主观评定",
      ],
      answer: 0,
      rationale: "考试有明确的通过分数线，以官方发布为准。",
    },
  ],
  "w16-4": [
    {
      id: "w16-4-q1",
      question: "构建个人云原生技能树的要点？",
      options: [
        "覆盖基础（容器/网络/存储）→ 编排/服务治理 → 安全/观测 → 自动化/IaC",
        "只学一种工具",
        "只看文档不实践",
        "随意排列",
      ],
      answer: 0,
      rationale: "体系化技能树有助于持续成长与复习。",
    },
    {
      id: "w16-4-q2",
      question: "作品集/简历中可展示什么？",
      options: [
        "实战项目、实验仓库、故障复盘、开源贡献、自动化脚本",
        "仅列出课程名称",
        "只写兴趣爱好",
        "不需要展示",
      ],
      answer: 0,
      rationale: "可量化的产出/代码仓库能证明能力。",
    },
    {
      id: "w16-4-q3",
      question: "与社区互动的方式？",
      options: [
        "参与 CNCF/项目 Issue/PR、KubeCon/Meetup、答疑分享",
        "只在内部群聊",
        "保持沉默",
        "关闭邮件",
      ],
      answer: 0,
      rationale: "社区参与能获取最新实践并建立人脉。",
    },
    {
      id: "w16-4-q4",
      question: "面试前的复盘重点？",
      options: [
        "梳理项目场景、技术决策、问题排查案例以及量化结果",
        "只背诵命令",
        "完全不准备",
        "只看八股",
      ],
      answer: 0,
      rationale: "具体案例与结果更能体现经验。",
    },
    {
      id: "w16-4-q5",
      question: "保持学习节奏的建议？",
      options: [
        "定期练习/写笔记/复盘错题，结合实战小项目迭代",
        "只在考试前突击",
        "每天更换方向",
        "依赖运气",
      ],
      answer: 0,
      rationale: "持续实践和复盘才能固化知识。",
    },
    {
      id: "w16-4-q6",
      question: "在团队推广云原生实践时，首要步骤？",
      options: [
        "从小范围 PoC/自动化脚本开始，度量收益后再逐步推广",
        "一次性全量替换",
        "忽略现有流程",
        "只做文档",
      ],
      answer: 0,
      rationale: "渐进式落地更易获得支持并降低风险。",
    },
    {
      id: "w16-4-q7",
      question: "面向生产运维应关注哪些指标？",
      options: [
        "稳定性（SLO/可用性）、成本、性能、安全合规",
        "只关注代码风格",
        "只关注节点数量",
        "只关注镜像大小",
      ],
      answer: 0,
      rationale: "生产环境需综合考虑可用性/成本/安全等目标。",
    },
    {
      id: "w16-4-q8",
      question: "如何规划后续深度学习路线？",
      options: [
        "根据兴趣/岗位选择专项（安全/数据面/运维/SRE），结合开源项目实践",
        "随机学习",
        "只做练习题",
        "完全停下学习",
      ],
      answer: 0,
      rationale: "定向深入 + 实践有助于成为领域专家。",
    },
    {
      id: "w16-4-q9",
      question: "在项目中沉淀知识的方式？",
      options: [
        "编写 Runbook/Playbook、自动化脚本、最佳实践文档",
        "仅口头传达",
        "完全不记录",
        "依赖第三方博客",
      ],
      answer: 0,
      rationale: "可复用的文档和工具能提升团队效率。",
    },
    {
      id: "w16-4-q10",
      question: "持续提升软技能的建议？",
      options: [
        "练习复盘表达/沟通，学会将技术影响转化为业务价值",
        "只写代码不交流",
        "避免分享",
        "忽略反馈",
      ],
      answer: 0,
      rationale: "沟通与复盘能力是工程师成长的重要部分。",
    },
  ],
};