import type { QuizQuestion } from "../types";

export const week10: Record<string, QuizQuestion[]> = {
  "w10-1": [
    {
      id: "w10-1-q1",
      question: "ArgoCD 的核心组件包括？",
      options: [
        "API Server/Server、Repo Server、Application Controller（可选 Dex）",
        "kube-scheduler 与 kube-proxy",
        "Flannel 与 Calico",
        "Helm Tiller",
      ],
      answer: 0,
      rationale: "官方架构：api-server 提供 UI/CLI，repo-server 渲染，controller 调和。",
    },
    {
      id: "w10-1-q2",
      question: "ArgoCD 管理的自定义资源是？",
      options: ["Application（以及 AppProject）", "Deployment", "ReplicaSet", "CRDDefinition"],
      answer: 0,
      rationale: "ArgoCD 通过 Application CRD 描述要同步的清单。",
    },
    {
      id: "w10-1-q3",
      question: "Repo Server 的职责是？",
      options: [
        "从 Git 拉取仓库并渲染 Kustomize/Helm/Plain YAML",
        "调度 Pod",
        "存储镜像",
        "提供 DNS",
      ],
      answer: 0,
      rationale: "repo-server 负责模板渲染与生成 manifests。",
    },
    {
      id: "w10-1-q4",
      question: "Application Controller 的作用是？",
      options: [
        "比较 Git 期望状态与集群实际状态并执行同步",
        "提供用户登录",
        "存储 Helm Chart",
        "管理节点",
      ],
      answer: 0,
      rationale: "controller 实现持续调和，确保资源与源匹配。",
    },
    {
      id: "w10-1-q5",
      question: "初始管理员密码获取方式？",
      options: [
        "来自 argocd-initial-admin-secret（data.password）",
        "使用 kubectl config view",
        "默认 admin/admin",
        "需要手工生成",
      ],
      answer: 0,
      rationale: "安装后 Secret 中存储初始密码，需修改后删除 Secret。",
    },
    {
      id: "w10-1-q6",
      question: "ArgoCD 支持哪些模板类型？",
      options: [
        "原生 YAML、Kustomize、Helm、Ksonnet（旧）、Jsonnet 等",
        "仅 YAML",
        "仅 Helm",
        "仅 Json",
      ],
      answer: 0,
      rationale: "repo-server 可渲染多种类型。",
    },
    {
      id: "w10-1-q7",
      question: "访问 ArgoCD API/UI 的常见方式？",
      options: [
        "kubectl port-forward svc/argocd-server -n argocd 8080:443",
        "直接访问 kube-apiserver",
        "ssh 到节点",
        "使用 CoreDNS",
      ],
      answer: 0,
      rationale: "文档提供 port-forward 方式快速访问 UI/API。",
    },
    {
      id: "w10-1-q8",
      question: "AppProject 的作用是？",
      options: [
        "定义一组 Application 的边界（源仓库/目标集群/命名空间/白名单）与 RBAC",
        "存储镜像",
        "提供网络策略",
        "管理日志",
      ],
      answer: 0,
      rationale: "项目用于隔离与授权，控制应用可访问的资源范围。",
    },
    {
      id: "w10-1-q9",
      question: "ArgoCD 采用哪种模式获取清单？",
      options: [
        "从 Git/OCI Registry 拉取声明式配置",
        "直接 watch etcd",
        "通过 kubelet 同步",
        "随机生成",
      ],
      answer: 0,
      rationale: "ArgoCD 将 Git/OCI 作为期望状态源。",
    },
    {
      id: "w10-1-q10",
      question: "argocd CLI 与 UI 认证的默认方式？",
      options: [
        "与 argocd-server 交互，使用用户名/密码或 SSO（Dex/OIDC）",
        "直接使用 kubeconfig",
        "不需要认证",
        "仅支持 TLS 客户端证书",
      ],
      answer: 0,
      rationale: "ArgoCD 有自己认证层，可集成 OIDC。",
    },
  ],
  "w10-2": [
    {
      id: "w10-2-q1",
      question: "自动同步的三要素是？",
      options: [
        "syncPolicy.automated 下可启用 prune、自愈（selfHeal）与自动 apply",
        "只需要手动点击 Sync",
        "仅依赖 webhook",
        "需要修改 kube-apiserver",
      ],
      answer: 0,
      rationale: "automated 模式可配置 prune/selfHeal 自动调和漂移。",
    },
    {
      id: "w10-2-q2",
      question: "Prune 的作用？",
      options: [
        "删除 Git 中已移除的资源，保持集群与源一致",
        "清理镜像缓存",
        "重启 Pod",
        "更新 Helm Chart",
      ],
      answer: 0,
      rationale: "Prune 防止残留资源，避免漂移。",
    },
    {
      id: "w10-2-q3",
      question: "SelfHeal 的含义？",
      options: [
        "检测到集群与期望不一致时自动重新同步恢复",
        "自动扩容",
        "自动修复节点",
        "自动更新 Helm repo",
      ],
      answer: 0,
      rationale: "SelfHeal 能在漂移时主动恢复状态。",
    },
    {
      id: "w10-2-q4",
      question: "使用 CLI 触发同步的命令？",
      options: ["argocd app sync <app>", "kubectl rollout sync", "helm sync", "argo sync"],
      answer: 0,
      rationale: "argocd CLI 提供 app sync 立即同步。",
    },
    {
      id: "w10-2-q5",
      question: "Sync Wave 用于？",
      options: [
        "通过注解/字段控制资源同步顺序（数字越小越先）",
        "控制回滚",
        "设置资源配额",
        "配置日志级别",
      ],
      answer: 0,
      rationale: "ArgoCD 支持 sync-wave 注解管理依赖顺序。",
    },
    {
      id: "w10-2-q6",
      question: "Sync Options: CreateNamespace=true 的效果？",
      options: [
        "目标命名空间不存在时自动创建",
        "强制删除命名空间",
        "启用 Helm",
        "忽略 CRD",
      ],
      answer: 0,
      rationale: "同步时可自动创建缺失的 namespace。",
    },
    {
      id: "w10-2-q7",
      question: "同步重试策略可配置什么？",
      options: [
        "重试次数与间隔（backoff），失败后可重试同步",
        "控制副本数",
        "修改 Helm 值",
        "更改 RBAC",
      ],
      answer: 0,
      rationale: "syncPolicy.retry 支持 backoff/limit 设置。",
    },
    {
      id: "w10-2-q8",
      question: "PrunePropagationPolicy/PruneLast 的用途？",
      options: [
        "控制删除级联方式（Foreground/Background）以及是否最后一步再删除",
        "控制日志",
        "调整健康检查",
        "设置超时",
      ],
      answer: 0,
      rationale: "可避免级联删除顺序问题。",
    },
    {
      id: "w10-2-q9",
      question: "Sync Windows 的作用？",
      options: [
        "定义允许/禁止同步的时间窗口，防止敏感时段自动变更",
        "设置 Pod 生命周期",
        "控制日志保留",
        "强制回滚",
      ],
      answer: 0,
      rationale: "Sync Windows 用于运维冻结或限制自动同步时间。",
    },
    {
      id: "w10-2-q10",
      question: "差异比对（Diff）模式可选择？",
      options: [
        "三方合并、忽略特定字段（例如 status/annotations）",
        "仅支持全量",
        "必须手动 patch",
        "只能忽略 metadata",
      ],
      answer: 0,
      rationale: "ArgoCD diff 设置可忽略某些字段，或开启 server-side apply 比对。",
    },
  ],
  "w10-3": [
    {
      id: "w10-3-q1",
      question: "在 ArgoCD 中使用 Kustomize 的常见方式？",
      options: [
        "Application.spec.source 指定 path，kustomize.namePrefix/overlays 等由 repo-server 构建",
        "必须先手动 kustomize build",
        "不支持 Kustomize",
        "只能结合 Helm",
      ],
      answer: 0,
      rationale: "ArgoCD 原生支持 Kustomize 渲染。",
    },
    {
      id: "w10-3-q2",
      question: "管理多环境（dev/prod）的常见做法？",
      options: [
        "为每个环境创建独立 Application，指向不同路径/overlay 或不同 values 文件",
        "在一个 Application 里写多个 namespace",
        "只能一个环境",
        "手动编辑 Pod",
      ],
      answer: 0,
      rationale: "多环境通过不同源路径/参数定义多应用。",
    },
    {
      id: "w10-3-q3",
      question: "Helm 参数在 ArgoCD 中如何覆盖？",
      options: [
        "在 source.helm.valueFiles/parameters 或 helm.parameters 中设置",
        "只能用默认值",
        "必须修改 Chart",
        "使用 ConfigMap",
      ],
      answer: 0,
      rationale: "Application 允许指定值文件和参数覆盖。",
    },
    {
      id: "w10-3-q4",
      question: "destination 字段包含哪些关键子字段？",
      options: [
        "server（集群 API 地址或 kubernetes.default.svc）与 namespace",
        "Pod IP 与端口",
        "镜像仓库地址",
        "Helm 仓库",
      ],
      answer: 0,
      rationale: "destination 指定目标集群与命名空间。",
    },
    {
      id: "w10-3-q5",
      question: "AppProject 可以限制什么？",
      options: [
        "允许的源仓库、目标集群/命名空间、可用资源白名单、同步窗口等",
        "只能限制副本数",
        "仅控制日志",
        "仅控制 Helm 版本",
      ],
      answer: 0,
      rationale: "Project 用于团队/环境隔离与安全限制。",
    },
    {
      id: "w10-3-q6",
      question: "同步时自动创建命名空间的选项？",
      options: [
        "syncOptions: [\"CreateNamespace=true\"]",
        "必须手工 kubectl create ns",
        "使用 Helm 钩子",
        "无法创建",
      ],
      answer: 0,
      rationale: "ArgoCD 支持在 syncOptions 中启用创建 namespace。",
    },
    {
      id: "w10-3-q7",
      question: "将目标修订版本设为特定 tag/commit 的字段？",
      options: [
        "targetRevision（支持 branch/tag/commit/hash）",
        "syncPolicy",
        "destination.namespace",
        "project",
      ],
      answer: 0,
      rationale: "Application.source.targetRevision 控制 checkout 的版本。",
    },
    {
      id: "w10-3-q8",
      question: "对 Helm Chart 使用特定 release 名的方式？",
      options: [
        "source.helm.releaseName 指定，或使用 metadata.name 默认",
        "必须与 Application 同名",
        "不可更改",
        "在 values.yaml 中写",
      ],
      answer: 0,
      rationale: "ArgoCD 可自定义 Helm release 名称。",
    },
    {
      id: "w10-3-q9",
      question: "多集群部署同一应用时需注意？",
      options: [
        "为不同 cluster/destination 创建独立 Application，并确保凭证/项目允许",
        "必须复制集群",
        "只能部署一个集群",
        "需要修改 kube-proxy",
      ],
      answer: 0,
      rationale: "ArgoCD 支持多个 destination，每个 Application 指定其目标。",
    },
    {
      id: "w10-3-q10",
      question: "对 Kubernetes 资源使用 Kustomize Patch 的路径是？",
      options: [
        "在 Kustomization.yaml 中指定 patches/overlays 目录",
        "在 Application.metadata 中指定",
        "通过 syncPolicy",
        "必须使用 Helm",
      ],
      answer: 0,
      rationale: "Kustomize overlays/patches 管理差异，ArgoCD 会调用 kustomize build。",
    },
  ],
  "w10-4": [
    {
      id: "w10-4-q1",
      question: "App of Apps 模式的核心做法是？",
      options: [
        "用一个“根” Application 部署其他子 Application 清单，实现级联管理",
        "使用 Helm 安装所有服务",
        "把所有资源放在一个 YAML",
        "只部署 ConfigMap",
      ],
      answer: 0,
      rationale: "根应用指向包含多个 Application 定义的目录，实现层次化管理。",
    },
    {
      id: "w10-4-q2",
      question: "使用 App of Apps 时需注意的删除行为是？",
      options: [
        "删除根应用会连带删除子应用及其托管资源（若启用自动清理）",
        "只删除根应用，不影响子应用",
        "会删除整个集群",
        "无法删除",
      ],
      answer: 0,
      rationale: "级联删除需谨慎，可通过同步策略控制。",
    },
    {
      id: "w10-4-q3",
      question: "为什么 App of Apps 适合集群引导/大规模服务？",
      options: [
        "可分层管理组件，按 Sync Wave 排序，便于拆分团队边界",
        "性能更高",
        "避免使用 Git",
        "减少 YAML 数量到 1 个",
      ],
      answer: 0,
      rationale: "层次化使复杂平台/多服务可控，支持分批同步。",
    },
    {
      id: "w10-4-q4",
      question: "AppProject 权限如何影响 App of Apps？",
      options: [
        "根/子应用必须被所属项目允许创建 Application 资源并访问对应目标",
        "项目不影响",
        "只需 root 应用权限",
        "需要 cluster-admin",
      ],
      answer: 0,
      rationale: "项目白名单需包含 applications 及目的地，否则创建失败。",
    },
    {
      id: "w10-4-q5",
      question: "同步顺序控制在 App of Apps 中如何实现？",
      options: [
        "使用 sync-wave 注解或资源 hook，确保依赖顺序",
        "无法控制顺序",
        "只能靠文件名排序",
        "通过 kube-scheduler",
      ],
      answer: 0,
      rationale: "同步波与 hook 可安排子应用/资源顺序。",
    },
    {
      id: "w10-4-q6",
      question: "根应用引用子应用清单的常见方式？",
      options: [
        "目录模式（directory）开启 recurse 或直接列出多个子 Application YAML",
        "必须使用 Helm Chart",
        "使用 ConfigMap",
        "仅单文件",
      ],
      answer: 0,
      rationale: "可指向包含多个应用定义的目录递归渲染。",
    },
    {
      id: "w10-4-q7",
      question: "避免循环依赖的注意点？",
      options: [
        "不要让子应用再次引用根目录或互相创建对方，保持单向层次",
        "允许任意互指",
        "使用 webhook",
        "依赖 kube-proxy",
      ],
      answer: 0,
      rationale: "循环会导致同步/删除异常，应保持树状结构。",
    },
    {
      id: "w10-4-q8",
      question: "App of Apps 中如何限制子应用的同步策略？",
      options: [
        "在子 Application 中单独设置 syncPolicy/automated/prune",
        "只能继承根应用",
        "无法限制",
        "通过 kubelet 配置",
      ],
      answer: 0,
      rationale: "每个子应用有自己的同步策略与项目限制。",
    },
    {
      id: "w10-4-q9",
      question: "对密钥/敏感配置的最佳实践？",
      options: [
        "结合密钥管理（Vault/SealedSecrets）或外部仓库，避免在 App of Apps 仓库明文存储",
        "直接写入 Git",
        "放在 argocd-cm",
        "通过 ConfigMap 明文存储",
      ],
      answer: 0,
      rationale: "App of Apps 也需遵循密钥管理原则，避免明文。",
    },
    {
      id: "w10-4-q10",
      question: "根应用通常部署到哪个命名空间？",
      options: [
        "argocd 或指定管理命名空间，便于隔离",
        "default",
        "kube-system 必须",
        "任意 Pod 命名空间均可无需考虑",
      ],
      answer: 0,
      rationale: "常将管理类应用放在 argocd 等专用 namespace 方便管理。",
    },
  ],
};