import type { QuizQuestion } from "../types";

export const week14: Record<string, QuizQuestion[]> = {
  "w14-1": [
    {
      id: "w14-1-q1",
      question: "4C 安全模型的层次分别是？",
      options: [
        "Cloud、Cluster、Container、Code",
        "CPU、Cache、Compiler、Code",
        "Client、Controller、Config、Code",
        "Cloud、Config、Cost、Cache",
      ],
      answer: 0,
      rationale: "NSA 等指南强调从云到代码的四层防护。",
    },
    {
      id: "w14-1-q2",
      question: "Pod Security Standards 的三个级别？",
      options: [
        "Privileged、Baseline、Restricted",
        "Admin、User、Guest",
        "High、Medium、Low",
        "None、Partial、Full",
      ],
      answer: 0,
      rationale: "K8s PSS 定义的安全基线与受限级别。",
    },
    {
      id: "w14-1-q3",
      question: "Restricted 模式通常禁止什么？",
      options: [
        "特权容器、hostNetwork/PID/IPC、rootfs 可写、提权能力等",
        "使用 ConfigMap",
        "使用 Service",
        "使用 Liveness 探针",
      ],
      answer: 0,
      rationale: "受限配置旨在最小化逃逸面。",
    },
    {
      id: "w14-1-q4",
      question: "NSA/CISA 指南强调的集群安全措施包括？",
      options: [
        "RBAC 最小权限、审计、NetworkPolicy、ETCD 加密、禁用匿名等",
        "关闭日志",
        "禁用 TLS",
        "所有组件运行为 root",
      ],
      answer: 0,
      rationale: "指南提供多项硬化建议覆盖控制面/节点。",
    },
    {
      id: "w14-1-q5",
      question: "镜像安全的基础做法？",
      options: [
        "使用最小化基础镜像、定期扫描、固定 tag/digest",
        "使用 latest 且不扫描",
        "在容器内下载依赖",
        "关闭健康检查",
      ],
      answer: 0,
      rationale: "镜像源与漏洞管理是容器层关键。",
    },
    {
      id: "w14-1-q6",
      question: "节点安全的常见措施？",
      options: [
        "限制 SSH、开启主机防火墙/SELinux/AppArmor、分离控制平面与工作节点",
        "允许任意 root 登录",
        "关闭 kubelet 认证",
        "禁用补丁更新",
      ],
      answer: 0,
      rationale: "硬化节点是 4C 模型中 Cluster/Cloud 层的重点。",
    },
    {
      id: "w14-1-q7",
      question: "为何建议开启 etcd 加密 Secret？",
      options: [
        "防止磁盘/备份泄露敏感数据",
        "减少 CPU",
        "提高调度速度",
        "改善网络延迟",
      ],
      answer: 0,
      rationale: "EncryptionConfiguration 可保护存储在 etcd 的敏感信息。",
    },
    {
      id: "w14-1-q8",
      question: "网络隔离的推荐做法？",
      options: [
        "使用 NetworkPolicy/防火墙限制东西向流量与入口出口",
        "仅依赖 kube-proxy",
        "只在节点上配置路由",
        "完全关闭网络",
      ],
      answer: 0,
      rationale: "网络策略是集群安全的重要一环。",
    },
    {
      id: "w14-1-q9",
      question: "代码层安全的例子？",
      options: [
        "安全编码、依赖管理、SAST/DAST、秘密管理",
        "仅依赖防火墙",
        "禁用日志",
        "使用 root 用户开发",
      ],
      answer: 0,
      rationale: "4C 最内层强调代码级安全与扫描。",
    },
    {
      id: "w14-1-q10",
      question: "PodSecurity（PSS 替代 PSP）在新版本中的实现方式？",
      options: [
        "通过 Pod Security Admission（命名空间级 enforce/audit/warn 模式）",
        "使用 PodSecurityPolicy",
        "使用 NodeSelector",
        "通过 kube-proxy",
      ],
      answer: 0,
      rationale: "PSA 控制器基于 namespace 标签执行 PSS，PSP 已弃用。",
    },
  ],
  "w14-2": [
    {
      id: "w14-2-q1",
      question: "Cosign 的核心功能是？",
      options: [
        "为容器镜像生成/验证签名（支持密钥或无密钥 OIDC/Fulcio）",
        "构建镜像",
        "部署 Kubernetes",
        "扫描漏洞",
      ],
      answer: 0,
      rationale: "Cosign 是 Sigstore 工具，用于签名与验证镜像/制品。",
    },
    {
      id: "w14-2-q2",
      question: "cosign verify 做什么？",
      options: [
        "从注册表/rekor 获取签名并验证镜像满足信任策略",
        "推送镜像",
        "删除镜像",
        "生成 SBOM",
      ],
      answer: 0,
      rationale: "verify 校验签名/证书链，保证镜像来源可信。",
    },
    {
      id: "w14-2-q3",
      question: "Admission 阶段如何阻止未签名镜像运行？",
      options: [
        "使用 Sigstore policy-controller/Kyverno/Gatekeeper 编写策略验证签名",
        "依赖 kube-proxy",
        "修改 Dockerfile",
        "重启 kubelet",
      ],
      answer: 0,
      rationale: "准入策略可校验签名，拒绝不符合供应链要求的镜像。",
    },
    {
      id: "w14-2-q4",
      question: "Cosign 支持的证明材料除了签名还有？",
      options: [
        "Attestation/SBOM，可用于记录构建元数据/合规性",
        "仅签名",
        "只能存储日志",
        "只支持漏洞报告",
      ],
      answer: 0,
      rationale: "Cosign 可存储/验证 attestations，如 SLSA 元数据。",
    },
    {
      id: "w14-2-q5",
      question: "Keyless 模式依赖什么？",
      options: [
        "OIDC 身份 + Fulcio（临时证书） + Rekor 透明日志",
        "离线私钥",
        "HSM 才能使用",
        "只能在本地使用",
      ],
      answer: 0,
      rationale: "Sigstore 提供基于 OIDC 的无密钥签名，证书记录在 Rekor。",
    },
    {
      id: "w14-2-q6",
      question: "为什么要固定镜像 digest 而非 tag？",
      options: [
        "digest 唯一对应镜像内容，可防止 tag 漂移或供应链攻击",
        "digest 更短",
        "tag 无法使用",
        "只为美观",
      ],
      answer: 0,
      rationale: "供应链安全强调不可变引用。",
    },
    {
      id: "w14-2-q7",
      question: "ImagePolicyWebhook 的用途？",
      options: [
        "在准入阶段调用外部服务验证镜像策略（如签名/漏洞）",
        "实现 HPA",
        "替代 kubelet",
        "配置网络策略",
      ],
      answer: 0,
      rationale: "ImagePolicyWebhook 可将镜像验证交给外部策略服务。",
    },
    {
      id: "w14-2-q8",
      question: "SBOM 在供应链中的作用？",
      options: [
        "列出软件组成/依赖，便于漏洞追踪与合规审计",
        "提升性能",
        "减少镜像大小",
        "只用于计费",
      ],
      answer: 0,
      rationale: "SBOM 帮助快速定位受影响组件。",
    },
    {
      id: "w14-2-q9",
      question: "构建到部署的可信链条需要什么？",
      options: [
        "可信源代码、受控构建（签名）、制品存储、准入验证与运行时监控",
        "仅签名",
        "只需扫描漏洞",
        "只需要 RBAC",
      ],
      answer: 0,
      rationale: "供应链安全覆盖全生命周期，从源到运行都需验证。",
    },
    {
      id: "w14-2-q10",
      question: "policy-controller（Sigstore）主要作用？",
      options: [
        "在准入时校验 Cosign 签名/公钥/证书策略",
        "创建 Pod",
        "管理 HPA",
        "生成 Helm Chart",
      ],
      answer: 0,
      rationale: "Sigstore policy-controller 提供准入验证，拒绝不合规镜像。",
    },
  ],
  "w14-3": [
    {
      id: "w14-3-q1",
      question: "OPA Gatekeeper 策略由哪些对象组成？",
      options: [
        "ConstraintTemplate（定义 Rego 逻辑）与 Constraint（实例化具体限制）",
        "只需要 ConfigMap",
        "只用 Rego 文件",
        "CRD 与 Deployment 无关",
      ],
      answer: 0,
      rationale: "Gatekeeper 使用模板+约束分离策略逻辑与实例。",
    },
    {
      id: "w14-3-q2",
      question: "Kyverno 策略类型包括？",
      options: [
        "validate、mutate、generate（加上 verifyImages）",
        "仅 validate",
        "仅 mutate",
        "仅 generate",
      ],
      answer: 0,
      rationale: "Kyverno 提供验证/变更/生成/镜像签名校验等能力。",
    },
    {
      id: "w14-3-q3",
      question: "两者的规则执行位置？",
      options: [
        "都通过 Admission Webhook 拦截请求（可配置 enforce/audit/dry-run）",
        "运行在 kube-proxy",
        "仅运行在客户端",
        "只在 etcd 中",
      ],
      answer: 0,
      rationale: "Gatekeeper/Kyverno 作为准入控制器工作。",
    },
    {
      id: "w14-3-q4",
      question: "编写 Gatekeeper 规则使用哪种语言？",
      options: [
        "Rego（OPA 策略语言）",
        "Lua",
        "Python",
        "YAML 纯配置",
      ],
      answer: 0,
      rationale: "ConstraintTemplate 中的逻辑使用 Rego。",
    },
    {
      id: "w14-3-q5",
      question: "Kyverno 与 Gatekeeper 的主要差异？",
      options: [
        "Kyverno 使用原生 YAML 声明规则，支持 mutate/generate；Gatekeeper 基于 Rego",
        "Gatekeeper 只能 mutate",
        "Kyverno 不能验证",
        "两者完全相同",
      ],
      answer: 0,
      rationale: "Kyverno 以 YAML 为主，Gatekeeper 使用 Rego。",
    },
    {
      id: "w14-3-q6",
      question: "策略库/样例的来源？",
      options: [
        "官方/社区提供的 policy library（如 Pod 安全、镜像仓库限制）",
        "必须自己写",
        "只在商业版提供",
        "需要修改内核",
      ],
      answer: 0,
      rationale: "两者社区均提供丰富示例可直接应用。",
    },
    {
      id: "w14-3-q7",
      question: "Audit 模式的意义？",
      options: [
        "只记录违规但不拦截请求，便于观察影响",
        "自动修复",
        "关闭策略",
        "必须与 enforce 一起用",
      ],
      answer: 0,
      rationale: "审计模式帮助评估策略效果，逐步启用。",
    },
    {
      id: "w14-3-q8",
      question: "Kyverno verifyImages 用途？",
      options: [
        "在准入时验证镜像签名（如 Cosign），拒绝未签名镜像",
        "生成镜像",
        "扫描漏洞",
        "替代 HPA",
      ],
      answer: 0,
      rationale: "Kyverno 支持镜像签名验证，常用于供应链安全。",
    },
    {
      id: "w14-3-q9",
      question: "Gatekeeper Sync 配置的作用？",
      options: [
        "将集群资源同步到 OPA 数据库供约束引用",
        "同步镜像到节点",
        "同步 etcd",
        "同步 kubeconfig",
      ],
      answer: 0,
      rationale: "Sync 允许规则访问集群资源数据作为输入。",
    },
    {
      id: "w14-3-q10",
      question: "逐步推广策略的实践？",
      options: [
        "先在 audit 模式观察，再切换 enforce，配合排除/命名空间选择器",
        "直接全局 enforce",
        "不需要测试",
        "全部禁用",
      ],
      answer: 0,
      rationale: "渐进式发布降低误拦风险，使用 namespaceSelector/exclude 控制范围。",
    },
  ],
  "w14-4": [
    {
      id: "w14-4-q1",
      question: "Falco 的检测原理是？",
      options: [
        "通过内核模块/eBPF 捕获系统调用，与规则匹配检测异常行为",
        "读取 Pod 日志",
        "扫描镜像",
        "使用 kubelet 事件",
      ],
      answer: 0,
      rationale: "Falco 监控 syscalls，利用规则识别可疑行为。",
    },
    {
      id: "w14-4-q2",
      question: "在 Kubernetes 中部署 Falco 的常见方式？",
      options: [
        "以 DaemonSet 形式运行，覆盖所有节点",
        "部署为 CronJob",
        "仅在控制平面节点",
        "以 ConfigMap 运行",
      ],
      answer: 0,
      rationale: "DaemonSet 确保每个节点都有探针。",
    },
    {
      id: "w14-4-q3",
      question: "Falco 规则常见检测哪些行为？",
      options: [
        "特权提升、在容器内执行 shell、修改敏感文件/二进制、意外的网络访问",
        "CPU 使用率过高",
        "节点磁盘空间",
        "Pod 重启次数",
      ],
      answer: 0,
      rationale: "默认规则涵盖常见攻击/越权行为。",
    },
    {
      id: "w14-4-q4",
      question: "Falco 的输出渠道包括？",
      options: [
        "stdout/文件、syslog、gRPC、webhook/Slack 等",
        "仅 stdout",
        "只能写数据库",
        "没有输出",
      ],
      answer: 0,
      rationale: "Falco 支持多种告警输出方式。",
    },
    {
      id: "w14-4-q5",
      question: "为什么需要自定义/调优规则？",
      options: [
        "适配业务场景、减少误报并覆盖特定风险",
        "为了提高性能",
        "因为默认规则无效",
        "只能这样才能运行",
      ],
      answer: 0,
      rationale: "自定义规则可降低噪声并捕获特定威胁。",
    },
    {
      id: "w14-4-q6",
      question: "Falco 运行需要哪些权限？",
      options: [
        "需要访问内核事件（通常以特权/HostPID/HostNetwork 或 eBPF 特权运行）",
        "无需任何权限",
        "只需用户态",
        "需要修改 etcd",
      ],
      answer: 0,
      rationale: "捕获 syscalls 需相应 host 权限或加载 eBPF/内核模块。",
    },
    {
      id: "w14-4-q7",
      question: "使用 eBPF 运行 Falco 的好处？",
      options: [
        "避免内核模块依赖，更易兼容托管环境",
        "性能更差",
        "无法捕获系统调用",
        "需要重启节点",
      ],
      answer: 0,
      rationale: "eBPF 方式减少对内核模块的要求，适合受限环境。",
    },
    {
      id: "w14-4-q8",
      question: "Falco 如何与 Kubernetes 元数据关联？",
      options: [
        "通过 kube-apiserver 获取 Pod/命名空间/标签信息，丰富告警上下文",
        "写入 ConfigMap",
        "读取 etcd 数据目录",
        "不支持关联",
      ],
      answer: 0,
      rationale: "Falco 可查询 API 获取资源标签以增强告警可读性。",
    },
    {
      id: "w14-4-q9",
      question: "Falco Helm chart 提供哪些便利？",
      options: [
        "快速部署 DaemonSet/配置规则/输出，支持启用 eBPF/driver 选项",
        "只能安装单节点",
        "不支持自定义",
        "没有输出配置",
      ],
      answer: 0,
      rationale: "Helm chart 封装安装与配置选项，便于定制。",
    },
    {
      id: "w14-4-q10",
      question: "运行时安全与事前策略的关系？",
      options: [
        "运行时监控（Falco）补充准入/签名等预防手段，提供实时检测与响应",
        "完全替代准入控制",
        "与策略无关",
        "仅用于性能优化",
      ],
      answer: 0,
      rationale: "安全需要预防+检测+响应多层防护。",
    },
  ],
};