import type { QuizQuestion } from "../types";

export const week13: Record<string, QuizQuestion[]> = {
  "w13-1": [
    {
      id: "w13-1-q1",
      question: "Service Mesh 主要解决哪些微服务难题？",
      options: [
        "流量治理（熔断/重试/灰度）、可观测性、零信任安全（mTLS）等",
        "只解决存储问题",
        "仅提供日志聚合",
        "只提升 CPU 性能",
      ],
      answer: 0,
      rationale: "官方介绍指出 Mesh 侧重流量控制、观测与安全。",
    },
    {
      id: "w13-1-q2",
      question: "Sidecar 模式如何拦截流量？",
      options: [
        "通过 iptables 重定向 Pod 进出流量到 Envoy 代理",
        "直接修改应用代码",
        "使用物理负载均衡器",
        "依赖 kube-proxy",
      ],
      answer: 0,
      rationale: "Sidecar 通过流量劫持透明代理应用流量。",
    },
    {
      id: "w13-1-q3",
      question: "Service Mesh 的数据面和控制面分别是什么？",
      options: [
        "数据面是每个 Pod 的 Sidecar 代理，控制面负责策略下发与证书管理",
        "数据面是 API Server，控制面是 kubelet",
        "数据面是 etcd，控制面是 scheduler",
        "两者相同",
      ],
      answer: 0,
      rationale: "典型 Mesh 架构分为代理数据面与集中控制面。",
    },
    {
      id: "w13-1-q4",
      question: "mTLS 在网格中的作用？",
      options: [
        "提供服务间双向认证与加密，强化零信任",
        "仅用于压缩流量",
        "只在入口网关生效",
        "替代应用级认证",
      ],
      answer: 0,
      rationale: "Mesh 下发证书并自动建立 mTLS 通道。",
    },
    {
      id: "w13-1-q5",
      question: "引入服务网格的成本是？",
      options: [
        "增加资源开销与运维复杂度，需要权衡",
        "完全无开销",
        "必须修改内核",
        "需要停机",
      ],
      answer: 0,
      rationale: "Sidecar/控制面会占用资源并带来管理复杂度。",
    },
    {
      id: "w13-1-q6",
      question: "SPIFFE ID 在网格中用于？",
      options: [
        "标识服务身份（如 spiffe://cluster.local/ns/ns/sa/sa），配合 mTLS 授权",
        "标识节点 CPU",
        "标识 Helm Chart",
        "替代 Pod 名称",
      ],
      answer: 0,
      rationale: "Mesh 通常采用 SPIFFE 规范的身份标识。",
    },
    {
      id: "w13-1-q7",
      question: "流量治理能力通常无需？",
      options: [
        "修改业务代码，利用 sidecar 透明实现重试/超时/熔断",
        "安装应用 SDK",
        "更改 kube-proxy",
        "修改 Dockerfile",
      ],
      answer: 0,
      rationale: "Mesh 目标是透明下推网络策略，减少业务改动。",
    },
    {
      id: "w13-1-q8",
      question: "常见的可观测性增强包括？",
      options: [
        "自动生成指标、分布式追踪上下文与访问日志",
        "只记录 CPU 使用率",
        "只记录事件",
        "关闭日志",
      ],
      answer: 0,
      rationale: "Sidecar 可自动上报指标/追踪/访问日志。",
    },
    {
      id: "w13-1-q9",
      question: "没有服务网格也可实现上述能力吗？",
      options: [
        "可以，但需在应用或边车自行实现；网格提供统一落地与策略管理",
        "完全不行",
        "必须改内核",
        "只能用硬件",
      ],
      answer: 0,
      rationale: "Mesh 统一实现但并非唯一方式，需权衡引入成本。",
    },
    {
      id: "w13-1-q10",
      question: "Service Mesh Interface (SMI) 的目标是？",
      options: [
        "为不同 Mesh 提供通用 API 规范，简化可移植性",
        "实现 K8s 网络策略",
        "替代 Istio 控制面",
        "提供日志收集",
      ],
      answer: 0,
      rationale: "SMI 提供抽象标准，便于在不同 Mesh 之间切换。",
    },
  ],
  "w13-2": [
    {
      id: "w13-2-q1",
      question: "Istio 控制面的核心组件是？",
      options: [
        "istiod（整合 Pilot/Citadel/Galley 功能）",
        "kube-proxy",
        "Envoy Proxy",
        "CoreDNS",
      ],
      answer: 0,
      rationale: "istiod 负责配置分发、证书签发等。",
    },
    {
      id: "w13-2-q2",
      question: "Sidecar 代理在 Istio 中通常使用？",
      options: ["Envoy", "Nginx", "HAProxy", "Envoy 或 Nginx 随机"],
      answer: 0,
      rationale: "Istio 数据面默认 Envoy。",
    },
    {
      id: "w13-2-q3",
      question: "启用自动注入 Sidecar 的常见方式？",
      options: [
        "在 Namespace 加标签 istio-injection=enabled 或使用 revision 标签",
        "编辑 kubelet",
        "必须手工在 Pod 定义中添加容器",
        "通过 Service 注解",
      ],
      answer: 0,
      rationale: "标签触发 mutating webhook 注入 sidecar。",
    },
    {
      id: "w13-2-q4",
      question: "istioctl install --set profile=demo 的作用？",
      options: [
        "安装带示例配置的 demo profile，适合本地测试",
        "仅安装数据面",
        "卸载 Istio",
        "创建 Ingress",
      ],
      answer: 0,
      rationale: "demo profile 安装全套组件供体验使用。",
    },
    {
      id: "w13-2-q5",
      question: "Sidecar 与 istiod 通信使用的协议？",
      options: [
        "xDS（gRPC）下发配置/证书",
        "HTTP REST",
        "TCP 原始套接字",
        "仅通过文件",
      ],
      answer: 0,
      rationale: "Envoy 通过 xDS API 接收路由与证书更新。",
    },
    {
      id: "w13-2-q6",
      question: "Istio Ingress Gateway 的作用？",
      options: [
        "网格入口，承载 Gateway/VirtualService 规则并暴露到集群外部",
        "替代 kube-proxy",
        "存储日志",
        "管理 Pod 生命周期",
      ],
      answer: 0,
      rationale: "Ingress Gateway 是暴露网格流量的 L4/L7 入口。",
    },
    {
      id: "w13-2-q7",
      question: "安装后验证 Istio 健康的命令？",
      options: [
        "istioctl verify-install",
        "kubectl get istio",
        "helm status istio",
        "curl istiod",
      ],
      answer: 0,
      rationale: "官方推荐 verify-install 进行组件检查。",
    },
    {
      id: "w13-2-q8",
      question: "控制面升级/多版本并存的方式？",
      options: [
        "使用 revision 标签安装多个 istiod，逐步迁移命名空间",
        "只能全量覆盖升级",
        "需删除数据面",
        "必须停机",
      ],
      answer: 0,
      rationale: "修订版支持灰度控制面，便于逐步迁移。",
    },
    {
      id: "w13-2-q9",
      question: "iptables 重定向由哪个组件完成？",
      options: [
        "istio-init（或 istio-cni）为 Pod 设置流量劫持规则",
        "kube-proxy",
        "istiod",
        "Prometheus",
      ],
      answer: 0,
      rationale: "init 容器或 CNI 插件负责插入重定向规则。",
    },
    {
      id: "w13-2-q10",
      question: "Istio 安装会创建哪些 CRD？",
      options: [
        "VirtualService、DestinationRule、Gateway、ServiceEntry、PeerAuthentication 等",
        "只有 Deployment",
        "仅 NetworkPolicy",
        "没有 CRD",
      ],
      answer: 0,
      rationale: "Istio 依赖一系列 CRD 定义流量/安全策略。",
    },
  ],
  "w13-3": [
    {
      id: "w13-3-q1",
      question: "VirtualService 与 DestinationRule 的关系？",
      options: [
        "VirtualService 定义路由规则，DestinationRule 定义目标子集/策略（如 TLS/熔断）",
        "两者相同",
        "VirtualService 定义 Pod 模板",
        "DestinationRule 用于入口",
      ],
      answer: 0,
      rationale: "二者配合实现路由与后端策略。",
    },
    {
      id: "w13-3-q2",
      question: "如何实现金丝雀流量切分？",
      options: [
        "在 VirtualService 中设置 weighted routes（如 90/10）指向不同 subset",
        "修改 Service 类型",
        "使用 HPA",
        "通过 ConfigMap",
      ],
      answer: 0,
      rationale: "使用权重路由到不同版本的 subset。",
    },
    {
      id: "w13-3-q3",
      question: "subset 在 DestinationRule 中如何定义？",
      options: [
        "通过 labels selector（如 version: v1/v2）指定 Pod 子集",
        "按节点选择",
        "按端口选择",
        "随机选择",
      ],
      answer: 0,
      rationale: "子集基于 Pod 标签，与 VirtualService 路由匹配。",
    },
    {
      id: "w13-3-q4",
      question: "实现故障注入的资源是？",
      options: [
        "VirtualService（fault: abort/delay）",
        "DestinationRule",
        "ServiceEntry",
        "PeerAuthentication",
      ],
      answer: 0,
      rationale: "VirtualService 支持注入延迟/错误模拟故障。",
    },
    {
      id: "w13-3-q5",
      question: "熔断/连接池配置在哪里？",
      options: [
        "DestinationRule 的 trafficPolicy（connectionPool、outlierDetection、retries）",
        "VirtualService",
        "Gateway",
        "Pod 模板",
      ],
      answer: 0,
      rationale: "后端连接策略在 DestinationRule 中定义。",
    },
    {
      id: "w13-3-q6",
      question: "请求超时与重试通常配置在哪？",
      options: [
        "VirtualService 的 http.timeout/retries",
        "Deployment",
        "Service",
        "Gateway",
      ],
      answer: 0,
      rationale: "路由层配置超时和重试策略。",
    },
    {
      id: "w13-3-q7",
      question: "流量镜像（shadow traffic）的配置？",
      options: [
        "VirtualService 中 mirror/mirror_percent 将流量副本发送到另一个目标",
        "DestinationRule",
        "Gateway",
        "HPA",
      ],
      answer: 0,
      rationale: "镜像用于无影响地观测新版本。",
    },
    {
      id: "w13-3-q8",
      question: "基于 Header 的路由属于？",
      options: [
        "VirtualService 匹配条件（match headers/cookies）",
        "Service",
        "Deployment",
        "ConfigMap",
      ],
      answer: 0,
      rationale: "VirtualService 支持按 header/cookie 路由。",
    },
    {
      id: "w13-3-q9",
      question: "ServiceEntry 的作用？",
      options: [
        "将外部服务纳入网格，定义可访问的主机/端口/协议",
        "控制访问日志",
        "管理 mTLS",
        "配置 HPA",
      ],
      answer: 0,
      rationale: "ServiceEntry 声明外部/虚拟服务供 Envoy 识别。",
    },
    {
      id: "w13-3-q10",
      question: "Gateway 资源用于？",
      options: [
        "声明网格入口/出口监听端口/协议，与 VirtualService 组合路由",
        "替代 Service",
        "配置节点亲和",
        "管理卷",
      ],
      answer: 0,
      rationale: "Gateway 定义 L4/L6 入口，VirtualService 指定路由。",
    },
  ],
  "w13-4": [
    {
      id: "w13-4-q1",
      question: "Istio 中启用 mTLS 的资源是？",
      options: [
        "PeerAuthentication（设置 mtls mode: STRICT/PERMISSIVE 等）",
        "VirtualService",
        "Gateway",
        "Deployment",
      ],
      answer: 0,
      rationale: "PeerAuthentication 控制入站 mTLS 策略。",
    },
    {
      id: "w13-4-q2",
      question: "服务身份在 Istio 中通常使用什么格式？",
      options: [
        "SPIFFE ID：spiffe://<trust-domain>/ns/<namespace>/sa/<serviceaccount>",
        "Pod IP",
        "Node 名称",
        "随机 UUID",
      ],
      answer: 0,
      rationale: "Istio 证书中使用 SPIFFE ID 作为主体。",
    },
    {
      id: "w13-4-q3",
      question: "AuthorizationPolicy 可以基于哪些条件？",
      options: [
        "主体(principals)/源 IP/命名空间/请求方法/路径等",
        "仅 Pod 名称",
        "只能基于节点",
        "只能允许全部",
      ],
      answer: 0,
      rationale: "授权策略支持多维度匹配请求。",
    },
    {
      id: "w13-4-q4",
      question: "证书由谁签发并分发给 Sidecar？",
      options: [
        "istiod（Citadel 功能）通过 SDS 向 Envoy 分发证书/密钥",
        "kube-proxy",
        "CoreDNS",
        "kubectl",
      ],
      answer: 0,
      rationale: "istiod 担任 CA，下发证书给 sidecar。",
    },
    {
      id: "w13-4-q5",
      question: "启用全局 STRICT mTLS 的常见做法？",
      options: [
        "在 mesh/default 命名空间创建 PeerAuthentication mtls: STRICT 并逐步覆盖例外",
        "修改 kubelet",
        "通过 Deployment 注解",
        "需要重启集群",
      ],
      answer: 0,
      rationale: "全局策略可通过 mesh-wide PeerAuthentication 设置严格模式。",
    },
    {
      id: "w13-4-q6",
      question: "入口网关 TLS 终止需要哪些资源？",
      options: [
        "Gateway 定义端口/证书引用，VirtualService 定义路由",
        "仅 VirtualService",
        "仅 DestinationRule",
        "仅 ConfigMap",
      ],
      answer: 0,
      rationale: "Gateway 管理 listener/TLS，VirtualService 绑定路由。",
    },
    {
      id: "w13-4-q7",
      question: "Sidecar 注入与安全策略的关系？",
      options: [
        "未注入 Sidecar 的 Pod 无法享受 mTLS/授权策略，需要确保关键命名空间开启注入",
        "无关系",
        "授权策略自动作用所有 Pod",
        "只影响 Ingress",
      ],
      answer: 0,
      rationale: "策略依赖 Envoy 执行，未注入则无法 enforcement。",
    },
    {
      id: "w13-4-q8",
      question: "启用 RBAC 授权的默认行为？",
      options: [
        "未匹配的请求默认拒绝（ALLOW-ALL 需显式配置）",
        "默认允许全部",
        "只检查 mTLS",
        "只作用外部流量",
      ],
      answer: 0,
      rationale: "AuthorizationPolicy 默认为拒绝未知请求，需明确规则。",
    },
    {
      id: "w13-4-q9",
      question: "Egress 流量控制可用的资源是？",
      options: [
        "ServiceEntry + egress Gateway + VirtualService，实现外部访问管控/审计",
        "NetworkPolicy",
        "只需 Ingress",
        "HPA",
      ],
      answer: 0,
      rationale: "Istio 支持 egress gateway/ServiceEntry 控制出口流量。",
    },
    {
      id: "w13-4-q10",
      question: "为何建议定期轮换网格证书？",
      options: [
        "减少长期凭证被盗风险，符合零信任原则",
        "提升性能",
        "避免日志过大",
        "与安全无关",
      ],
      answer: 0,
      rationale: "证书轮换是安全最佳实践，Istio 支持自动续期。",
    },
  ],
};