import type { QuizQuestion } from "../types";

export const week11: Record<string, QuizQuestion[]> = {
  "w11-1": [
    {
      id: "w11-1-q1",
      question: "Prometheus 默认的采集模型是？",
      options: [
        "Pull：定期从目标端点抓取 /metrics 暴露的指标",
        "Push：目标主动推送到 Prometheus",
        "仅通过日志收集",
        "依赖消息队列",
      ],
      answer: 0,
      rationale: "架构文档指出 Prom 采用拉取模式，必要时可用 Pushgateway 适配短任务。",
    },
    {
      id: "w11-1-q2",
      question: "Exporter 的作用是？",
      options: [
        "将系统/应用指标暴露为 Prometheus 可抓取的 HTTP 接口",
        "存储 TSDB 数据",
        "提供告警通知",
        "替代 Service Discovery",
      ],
      answer: 0,
      rationale: "Exporter 负责适配不同系统并以文本格式导出指标。",
    },
    {
      id: "w11-1-q3",
      question: "Prometheus TSDB 的存储单元是？",
      options: [
        "以时间块（block）存储，默认每 2 小时一个 block，包含 chunk/WAL",
        "单个大文件",
        "MySQL 表",
        "只存内存不落盘",
      ],
      answer: 0,
      rationale: "存储引擎使用 2h block，带索引/chunk，WAL 加速写入。",
    },
    {
      id: "w11-1-q4",
      question: "prometheus.yml 中 scrape_configs 的作用？",
      options: [
        "定义抓取目标、间隔、relabel/service discovery 配置",
        "配置告警接收人",
        "设置 Grafana 地址",
        "指定日志格式",
      ],
      answer: 0,
      rationale: "抓取配置决定 Prom 如何发现并采集目标。",
    },
    {
      id: "w11-1-q5",
      question: "Alerting 规则触发后如何处理？",
      options: [
        "推送到 Alertmanager 进行分组、路由、通知与静默",
        "直接发邮件",
        "存入 TSDB",
        "写入 kube-apiserver",
      ],
      answer: 0,
      rationale: "Prometheus 将告警发送给 Alertmanager，再由后者通知。",
    },
    {
      id: "w11-1-q6",
      question: "Remote Write 的用途？",
      options: [
        "将采集数据流式发送到远端存储/长时序数据库",
        "发送日志",
        "推送配置",
        "导出 Grafana Dashboard",
      ],
      answer: 0,
      rationale: "Remote Write 允许扩展存储/聚合，如 Cortex/Mimir/VictoriaMetrics。",
    },
    {
      id: "w11-1-q7",
      question: "Pushgateway 适用于什么场景？",
      options: [
        "短生命周期/批处理任务无法被定期拉取时临时上报指标",
        "长时间运行服务",
        "存储日志",
        "替代 Alertmanager",
      ],
      answer: 0,
      rationale: "Pushgateway 缓存短任务指标供 Prom 抓取，不适合一般服务。",
    },
    {
      id: "w11-1-q8",
      question: "Prometheus 暴露的指标格式是？",
      options: [
        "文本 exposition 格式（# HELP/# TYPE + name value）",
        "JSON",
        "CSV",
        "XML",
      ],
      answer: 0,
      rationale: "标准指标格式是纯文本，包含 HELP/TYPE 与样本行。",
    },
    {
      id: "w11-1-q9",
      question: "常见的服务发现方式包括？",
      options: [
        "Kubernetes 服务发现、文件静态配置、Consul、DNS 等",
        "只能静态配置",
        "仅支持 AWS",
        "必须使用 etcd",
      ],
      answer: 0,
      rationale: "Prometheus 支持多种 SD 插件，K8s 集成是常见用法。",
    },
    {
      id: "w11-1-q10",
      question: "保留时长与存储容量如何控制？",
      options: [
        "--storage.tsdb.retention.time/size 或通过 flags/配置调整",
        "无法控制，固定 15 天",
        "仅能通过删除数据目录",
        "必须修改源码",
      ],
      answer: 0,
      rationale: "retention 选项可设置时间或大小限制。",
    },
  ],
  "w11-2": [
    {
      id: "w11-2-q1",
      question: "PromQL 中 rate 与 irate 的差别？",
      options: [
        "rate 使用整个区间回归估算平均速率；irate 仅使用最后两个点反映瞬时速率",
        "两者相同",
        "irate 只能用于 gauge",
        "rate 只看最后一个点",
      ],
      answer: 0,
      rationale: "rate 平滑，irate 敏感；文档建议监控趋势用 rate。",
    },
    {
      id: "w11-2-q2",
      question: "sum by (job) (rate(http_requests_total[5m])) 的含义？",
      options: [
        "按 job 维度汇总 5 分钟窗口内每秒请求速率",
        "计算当前瞬时值",
        "过滤掉 job 标签",
        "求最大值",
      ],
      answer: 0,
      rationale: "sum by 聚合，rate 计算每秒增量。",
    },
    {
      id: "w11-2-q3",
      question: "直方图分位数常用组合是？",
      options: [
        "histogram_quantile(0.95, sum by (le) (rate(<metric>_bucket[5m])))",
        "avg_over_time(metric[5m])",
        "quantile(0.95, metric)",
        "max by (le) (metric)",
      ],
      answer: 0,
      rationale: "官方示例使用 rate + sum by (le) 再计算分位。",
    },
    {
      id: "w11-2-q4",
      question: "向量匹配 on()/ignoring() 的作用？",
      options: [
        "定义二元运算匹配时参与或忽略的标签集合",
        "控制采样频率",
        "设置告警级别",
        "过滤 NaN",
      ],
      answer: 0,
      rationale: "PromQL 二元运算需要明确标签匹配规则。",
    },
    {
      id: "w11-2-q5",
      question: "increase(counter[1h]) 返回什么？",
      options: [
        "过去 1 小时内计数器的增长总量",
        "当前值",
        "每秒速率",
        "最大值",
      ],
      answer: 0,
      rationale: "increase 适用于 counter，返回区间增量。",
    },
    {
      id: "w11-2-q6",
      question: "offset 关键字的作用？",
      options: [
        "取过去/未来偏移时间的样本用于对比（如 rate(http_requests_total[5m] offset 1h)）",
        "偏移标签值",
        "设置时间戳格式",
        "延迟告警",
      ],
      answer: 0,
      rationale: "offset 允许在表达式中引用过去时间的序列。",
    },
    {
      id: "w11-2-q7",
      question: "label_replace 的用途？",
      options: [
        "基于正则添加/修改标签值",
        "删除时间序列",
        "计算速率",
        "设置告警阈值",
      ],
      answer: 0,
      rationale: "label_replace 可在聚合前调整标签，文档给出示例。",
    },
    {
      id: "w11-2-q8",
      question: "Group 左/右（on()/ignoring() + group_left/right）的含义？",
      options: [
        "在向量匹配时允许一对多，保留左/右侧的额外标签",
        "控制算术运算优先级",
        "只在 sum 使用",
        "决定时间窗口大小",
      ],
      answer: 0,
      rationale: "group_left/right 解决一对多匹配并携带额外标签。",
    },
    {
      id: "w11-2-q9",
      question: "absent() 函数用于？",
      options: [
        "当没有匹配的时间序列时返回 1，用于检测缺失/掉线",
        "计算绝对值",
        "返回空结果",
        "统计样本数量",
      ],
      answer: 0,
      rationale: "absent 用于告警缺失数据等场景。",
    },
    {
      id: "w11-2-q10",
      question: "PromQL gauge 与 counter 的区别是？",
      options: [
        "gauge 可上升下降，counter 单调递增（重启归零）",
        "两者相同",
        "counter 只用于内存",
        "gauge 必须 reset",
      ],
      answer: 0,
      rationale: "指标类型文档明确 gauge 可上下波动，counter 单调递增。",
    },
  ],
  "w11-3": [
    {
      id: "w11-3-q1",
      question: "Grafana 添加数据源的常见步骤？",
      options: [
        "在 UI/配置中选择数据源类型（如 Prometheus）并填入 URL/认证信息",
        "必须修改数据库",
        "需要重启 Prometheus",
        "只能通过命令行",
      ],
      answer: 0,
      rationale: "数据源配置可以通过 UI 或 Provisioning 文件。",
    },
    {
      id: "w11-3-q2",
      question: "导入社区 Dashboard 的方式？",
      options: [
        "在 Dashboard -> Import 中输入 ID/上传 JSON",
        "只能手工重建",
        "需要连接数据库",
        "使用 helm install",
      ],
      answer: 0,
      rationale: "Grafana 支持通过 JSON/ID 快速导入。",
    },
    {
      id: "w11-3-q3",
      question: "变量（Templating）的作用？",
      options: [
        "让用户在面板中切换数据集（如集群/namespace），复用同一查询模板",
        "控制登录权限",
        "改变存储周期",
        "启用告警",
      ],
      answer: 0,
      rationale: "变量可动态替换查询参数，提高复用性。",
    },
    {
      id: "w11-3-q4",
      question: "Grafana Explore 模式用于？",
      options: [
        "临时 ad-hoc 查询/调试，快速查看数据源返回",
        "导出 Dashboard",
        "管理用户",
        "配置告警",
      ],
      answer: 0,
      rationale: "Explore 便于交互式排查指标或日志。",
    },
    {
      id: "w11-3-q5",
      question: "Dashboard 可视化类型的示例？",
      options: [
        "Graph/Time series、Table、Stat、Heatmap 等",
        "只有表格",
        "仅文本",
        "只能折线",
      ],
      answer: 0,
      rationale: "Grafana 提供多种可视化组件。",
    },
    {
      id: "w11-3-q6",
      question: "Grafana Alert（8+）基于什么？",
      options: [
        "基于数据源查询的 Alert Rule，支持多数据源与通知渠道",
        "仅基于 Prometheus 规则",
        "只能发送邮件",
        "需要修改 kubelet",
      ],
      answer: 0,
      rationale: "Grafana 内置告警可跨数据源配置通知。",
    },
    {
      id: "w11-3-q7",
      question: "Provisioning Dashboard/DataSource 的好处？",
      options: [
        "以代码/配置文件管理仪表板和数据源，便于版本化与自动化部署",
        "只能手工调整",
        "会禁用 UI",
        "仅适用于本地",
      ],
      answer: 0,
      rationale: "声明式配置提升一致性和可重复性。",
    },
    {
      id: "w11-3-q8",
      question: "使用 Prometheus 数据源查询时，时间区间如何决定？",
      options: [
        "由面板/URL 的 from/to 参数控制，Grafana 会附带 step（分辨率）",
        "固定 5 分钟",
        "由 Prometheus 决定",
        "与告警无关",
      ],
      answer: 0,
      rationale: "Grafana 将 UI 选择的时间窗口传给数据源。",
    },
    {
      id: "w11-3-q9",
      question: "分享 Dashboard 时应注意？",
      options: [
        "导出时可去除敏感数据源信息，或使用 snapshot 仅含渲染数据",
        "必须公开数据源密码",
        "无法共享",
        "只能截图",
      ],
      answer: 0,
      rationale: "Snapshot/导出可选择是否包含实时数据与凭证。",
    },
    {
      id: "w11-3-q10",
      question: "常见的权限控制做法？",
      options: [
        "使用组织/团队/用户角色（Viewer/Editor/Admin）限制 Dashboard 编辑与数据访问",
        "Grafana 不支持权限",
        "只能通过网络隔离",
        "需要修改 Prometheus",
      ],
      answer: 0,
      rationale: "Grafana 内置分级权限与团队管理。",
    },
  ],
  "w11-4": [
    {
      id: "w11-4-q1",
      question: "Alertmanager 的主要职责是？",
      options: [
        "接收 Prometheus 告警，进行分组、去重、抑制与通知路由",
        "存储指标",
        "生成 Dashboard",
        "调度 Pod",
      ],
      answer: 0,
      rationale: "Alertmanager 负责告警后处理与通知。",
    },
    {
      id: "w11-4-q2",
      question: "路由树（route）配置的核心字段包括？",
      options: [
        "receiver、matchers、group_by、group_wait/interval/timeout",
        "promQL",
        "数据源",
        "kubeconfig",
      ],
      answer: 0,
      rationale: "路由控制如何分组和发送到接收器。",
    },
    {
      id: "w11-4-q3",
      question: "抑制（inhibit rules）的作用？",
      options: [
        "当高优先级/主告警存在时，静音相关低优先级告警",
        "延长告警时间",
        "提高告警频率",
        "删除告警",
      ],
      answer: 0,
      rationale: "抑制规则防止同一事件产生噪声告警。",
    },
    {
      id: "w11-4-q4",
      question: "Silence 与 Inhibit 的区别？",
      options: [
        "Silence 是临时静默基于匹配器；Inhibit 依赖另一告警触发才静默",
        "两者相同",
        "Silence 只能在 CLI 使用",
        "Inhibit 只能静默全部告警",
      ],
      answer: 0,
      rationale: "Silence 是手工/时间窗口静默，Inhibit 是告警间依赖。",
    },
    {
      id: "w11-4-q5",
      question: "Alertmanager HA 的特点？",
      options: [
        "多个实例通过 gossip 协调状态，需共享或同步 silence/notification 状态",
        "必须使用单节点",
        "依赖 etcd",
        "与 Prometheus 无法同时 HA",
      ],
      answer: 0,
      rationale: "官方建议至少两个实例，使用 mesh 同步静默等状态。",
    },
    {
      id: "w11-4-q6",
      question: "常见的通知渠道（receivers）包括？",
      options: [
        "Email、Slack/Webhook、PagerDuty/OPS 工具等",
        "仅 Email",
        "只能写文件",
        "仅短信",
      ],
      answer: 0,
      rationale: "Alertmanager 支持多种 receiver 类型及自定义 webhook。",
    },
    {
      id: "w11-4-q7",
      question: "group_wait/group_interval 的意义？",
      options: [
        "控制分组后的首个通知等待时间及后续通知间隔，避免告警风暴",
        "设置 CPU 配额",
        "定义告警级别",
        "用于 RBAC",
      ],
      answer: 0,
      rationale: "分组等待可聚合相似告警减少通知量。",
    },
    {
      id: "w11-4-q8",
      question: "resolve_timeout 的作用？",
      options: [
        "在未收到 resolved 通知时，自动在指定时间后标记告警已解决",
        "设置 HTTP 超时",
        "决定重试次数",
        "控制日志输出",
      ],
      answer: 0,
      rationale: "resolve_timeout 保护在长时间无更新时自动标记结束。",
    },
    {
      id: "w11-4-q9",
      question: "模板化通知消息使用的语言是？",
      options: [
        "Go template，Alertmanager 支持在消息中引用标签/注释",
        "Jinja2",
        "Mustache",
        "无模板功能",
      ],
      answer: 0,
      rationale: "Alertmanager 使用 Go 模板定制通知内容。",
    },
    {
      id: "w11-4-q10",
      question: "Prometheus 如何找到 Alertmanager？",
      options: [
        "在 prometheus.yml 中配置 alerting > alertmanagers 地址列表",
        "通过 Service Discovery 自动发现",
        "写入 etcd",
        "需要部署在同一 Pod",
      ],
      answer: 0,
      rationale: "Prom 配置 alertmanagers 节点以推送告警。",
    },
  ],
};