import type { LessonGuide } from "../types"
import type { QuizQuestion } from "@/lib/types"

export const week2Guides: Record<string, LessonGuide> = {
    "w2-1": {
        lessonId: "w2-1",
        background: [
            "【池化模型定义】AWS SaaS Lens：'Pool Model—Architecture where tenants share resources (classic multi-tenancy)'——池化模型是所有租户共享资源的经典多租户模式。",
            "【共享数据库模式】Azure 文档描述：'All tenants share a single database, and rows are tagged with a tenant identifier'——所有租户共享单一数据库，通过租户标识符标记行数据。",
            "【RLS 机制】PostgreSQL 文档：'Row-Level Security restricts which rows users can access on a per-user basis'——行级安全在用户级别限制可访问的行，提供细粒度访问控制。",
            "【默认拒绝】PostgreSQL RLS 启用后采用 default-deny 策略：'Once enabled, no rows are visible until policies are created'——启用后默认不可见任何行，需创建策略才能访问。",
            "【成本优势】Azure 指出池化模式：'Provides the highest density of tenants to infrastructure, so it tends to come at the lowest financial cost'——租户密度最高，成本最低。",
        ],
        keyDifficulties: [
            "【隔离弱化】Azure 警告：'Sacrifices tenant isolation'——共享表模式牺牲了租户隔离，需要额外机制保证数据安全。",
            "【Noisy Neighbor】Azure 描述风险：'One tenant's workload impacts others'——一个租户的工作负载会影响其他租户的性能。",
            "【策略类型】PostgreSQL 区分两种策略类型：PERMISSIVE（用 OR 组合）和 RESTRICTIVE（用 AND 组合），需要正确组合使用。",
            "【绕过情况】PostgreSQL 警告：'Superusers always bypass RLS, Roles with BYPASSRLS attribute bypass RLS, Table owners bypass RLS'——需注意特权角色绕过问题。",
            "【恢复复杂】Azure 指出：'Point-in-time restore for single tenant is complex'——单租户的时间点恢复在共享模式下非常复杂。",
        ],
        handsOnPath: [
            "创建多租户测试表：CREATE TABLE orders (id INT, tenant_id INT, data TEXT);",
            "启用 RLS：ALTER TABLE orders ENABLE ROW LEVEL SECURITY;",
            "创建租户隔离策略：CREATE POLICY tenant_isolation ON orders USING (tenant_id = current_setting('app.tenant_id')::int);",
            "测试隔离：SET app.tenant_id = '1'; SELECT * FROM orders;",
            "验证跨租户访问被阻止：SET app.tenant_id = '2'; 确认无法看到租户 1 的数据",
            "强制表所有者也遵守 RLS：ALTER TABLE orders FORCE ROW LEVEL SECURITY;",
        ],
        selfCheck: [
            "池化模型的核心优势和风险是什么？",
            "PostgreSQL RLS 的 USING 和 WITH CHECK 子句有什么区别？",
            "如何防止超级用户绕过 RLS？",
            "PERMISSIVE 和 RESTRICTIVE 策略类型如何组合？",
            "共享表模式下如何实现单租户的数据恢复？",
            "如何监控和缓解 Noisy Neighbor 问题？",
        ],
        extensions: [
            "研究 MySQL 8.0 的行级安全替代方案（视图 + 应用层过滤）",
            "探索 Citus 的多租户分布式 PostgreSQL 实现",
            "了解 Azure SQL Database 的 RLS 实现差异",
            "研究应用层 vs 数据库层隔离的性能对比",
        ],
        sourceUrls: [
            "https://learn.microsoft.com/en-us/azure/azure-sql/database/saas-tenancy-app-design-patterns?view=azuresql",
            "https://www.postgresql.org/docs/current/ddl-rowsecurity.html",
            "https://docs.aws.amazon.com/wellarchitected/latest/saas-lens/silo-pool-and-bridge-models.html",
        ],
    },
    "w2-2": {
        lessonId: "w2-2",
        background: [
            "【孤岛定义】AWS 白皮书：'Silo isolation—each tenant runs a fully isolated stack of resources'——孤岛隔离让每个租户运行完全隔离的资源栈。",
            "【完全隔离边界】AWS 描述：'Full-Stack Isolation Boundary—Each tenant's complete environment is encapsulated as a separate, independent stack'——每个租户环境都封装为独立的栈。",
            "【实现方式】AWS 提供多种实现：'VPC per tenant—Network isolation' 或 'Account per tenant—AWS account-level isolation'——可以用 VPC 或账户实现隔离。",
            "【Azure 视角】Azure 指出单租户印记优势：'Highest level of isolation, Avoids the noisy neighbor problem, Enables tenant-specific customization'。",
            "【合规支持】AWS 强调：'Satisfies strict regulatory isolation requirements for regulated environments'——满足受监管环境的严格隔离要求。",
        ],
        keyDifficulties: [
            "【成本挑战】Azure 警告：'High infrastructure costs per tenant, Must provision for peak workload per tenant'——每租户基础设施成本高，需按峰值配置。",
            "【扩展限制】AWS 指出：'There are limits on the number of accounts that can be provisioned'——账户数量有限制，1000+ 租户变得难以管理。",
            "【运维复杂】AWS 描述：'Decentralized Management—Difficult to achieve single pane of glass monitoring'——去中心化管理难以实现统一监控。",
            "【敏捷性降低】AWS 警告：'Decentralized nature slows feature deployment and unified customer experience updates'——分散架构减慢部署速度。",
            "【经济损失】AWS 指出：'Loses SaaS economies of scale; idle resources during off-peak periods'——失去规模经济，非高峰期资源闲置。",
        ],
        handsOnPath: [
            "设计 VPC-per-Tenant 架构图：每个租户一个 VPC，共享服务层连接",
            "使用 Terraform 创建租户 VPC 模板，实现自动化 Provisioning",
            "配置跨 VPC 访问：Transit Gateway 或 VPC Peering 连接共享服务",
            "实现租户专属 KMS 密钥管理：每租户独立加密密钥",
            "设置统一监控：CloudWatch 跨账户监控聚合",
            "测试故障隔离：模拟单租户故障，验证不影响其他租户",
        ],
        selfCheck: [
            "孤岛模型适合什么类型的客户和场景？",
            "VPC-per-Tenant 和 Account-per-Tenant 的权衡是什么？",
            "如何在孤岛模型中实现统一监控和运维？",
            "孤岛模型如何影响 SaaS 的规模经济？",
            "什么因素会导致组织选择孤岛模型而非池化模型？",
            "如何估算孤岛模型的 TCO 相比池化模型的增加？",
        ],
        extensions: [
            "研究 AWS Control Tower 实现多账户管理自动化",
            "探索 Kubernetes Namespace 作为轻量级孤岛的可行性",
            "了解 Cell-Based Architecture 作为孤岛模型的进阶形式",
            "分析 Slack 等 SaaS 产品的企业客户专用部署策略",
        ],
        sourceUrls: [
            "https://docs.aws.amazon.com/whitepapers/latest/saas-tenant-isolation-strategies/silo-isolation.html",
            "https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/approaches/overview",
            "https://docs.aws.amazon.com/wellarchitected/latest/saas-lens/full-stack-isolation.html",
        ],
    },
    "w2-3": {
        lessonId: "w2-3",
        background: [
            "【桥接定义】AWS 定义：'Bridge Model—Mixed-mode architecture combining silo and pool approaches'——桥接模型是结合孤岛和池化的混合架构。",
            "【分层隔离】Azure 指出：'Your user interface tier might be shared, middle tier shared, data tier isolated'——不同层可以采用不同隔离级别。",
            "【分层决策】AWS 解释：'Some microservices use silo model, others use pool model based on regulatory profile, data sensitivity, noisy neighbor concerns'。",
            "【租户分层】AWS 描述：'Tiered isolation—offering different isolation models to different customer segments based on their service tier'——按服务层级提供不同隔离。",
            "【定价关联】AWS 指出：'Standard Tier (Pooled) → Lower price; Premium Tier (Silo) → Substantially higher price'——池化标准层低价，孤岛高级层高价。",
        ],
        keyDifficulties: [
            "【复杂度增加】Azure 警告：混合模式需要在代码中同时支持多租户和单租户逻辑，'Codebase must support both models'。",
            "【迁移挑战】Azure 指出：'Cross-deployment tenant tracking required, Migration complexity'——需要跨部署跟踪租户，迁移复杂。",
            "【限制孤岛】AWS 警告：'SaaS providers typically minimize silo tier offerings'——应限制孤岛选项，否则规模经济崩溃。",
            "【版本一致】AWS 要求：'Premium silo customers often must run the same product version as the pooled environment'——高级客户也需运行相同版本。",
            "【隐藏选项】AWS 建议：'Private pricing options are often undisclosed to limit demand'——通常不公开宣传孤岛选项以限制需求。",
        ],
        handsOnPath: [
            "绘制混合隔离架构图：标注每层的隔离策略（共享 vs 隔离）",
            "设计租户分层策略：Free/Basic → 池化，Standard → 混合，Enterprise → 孤岛",
            "实现 API Gateway 分层限流：不同层级不同 QPS 限制",
            "配置数据库混合策略：小租户共享表，大租户独立 Schema",
            "设置分层监控告警：不同层级不同 SLA 阈值",
            "实现租户层级升级流程：从池化迁移到孤岛的自动化",
        ],
        selfCheck: [
            "桥接模型如何平衡成本与隔离？",
            "什么因素决定某个微服务应该用孤岛还是池化？",
            "如何设计租户分层定价策略？",
            "为什么 SaaS 提供商通常限制孤岛选项的可见性？",
            "如何实现租户从池化层升级到孤岛层？",
            "混合模式下如何保持产品版本一致性？",
        ],
        extensions: [
            "研究 Stripe 的客户分层架构策略",
            "探索 Feature Flag 在租户分层中的应用",
            "了解 AWS API Gateway Usage Plans 的分层限流实现",
            "分析大型 SaaS 产品（如 Salesforce）的 Edition 策略",
        ],
        sourceUrls: [
            "https://docs.aws.amazon.com/whitepapers/latest/saas-tenant-isolation-strategies/tier-based-isolation.html",
            "https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/approaches/storage-data",
            "https://docs.aws.amazon.com/prescriptive-guidance/latest/saas-multitenant-api-access-authorization/avp-design-tiered.html",
        ],
    },
    "w2-4": {
        lessonId: "w2-4",
        background: [
            "【决策维度】Azure 提出五个关键因素：'Business objectives, Compliance, Scale, Automation, SLAs/SLOs'——业务目标、合规、规模、自动化、SLA。",
            "【动态策略】AWS 描述：'Dynamic Policy Generation—policies are generated at runtime instead of storing individual IAM policies for each tenant'——运行时生成策略而非预存。",
            "【Token Vending Machine】AWS 模式：'Isolation Manager queries token vending machine to get tenant-scoped token'——隔离管理器查询 TVM 获取租户范围的令牌。",
            "【策略模板】AWS 描述：'Pre-defined template files containing IAM policy structure with placeholders for tenant context'——预定义策略模板，填充租户上下文。",
            "【权衡矩阵】Azure 提供对比：Standalone（高隔离高成本）、Database-per-Tenant（高隔离低成本）、Sharded（最低成本最低隔离）。",
        ],
        keyDifficulties: [
            "【策略大小限制】AWS 警告：'Inline policy has a limit of 2,048 characters'——内联策略有字符限制，需注意组合策略大小。",
            "【模板管理】AWS 建议：'Own content versioning and deployment of policy templates through your CI/CD pipeline'——通过 CI/CD 管理策略模板版本。",
            "【ABAC vs 动态策略】AWS 对比：'ABAC lets you rely more directly on IAM, Dynamic policies easier to manage for frequently changed role definitions'。",
            "【开发者抽象】AWS 建议：'Hide policy mechanism details from developers to reduce errors'——对开发者隐藏策略细节以减少错误。",
            "【选择困难】Azure 指出：'The choice depends on balancing isolation, cost, scalability, and management complexity'——需平衡多个维度。",
        ],
        handsOnPath: [
            "使用 Azure/AWS 决策树评估你的多租户需求",
            "创建 IAM 策略模板：定义 DynamoDB 表的租户隔离策略模板",
            "实现 Token Vending Machine：从 JWT 提取租户 ID 并生成 STS 临时凭证",
            "测试动态策略生成：验证不同租户获得正确的资源访问范围",
            "建立策略模板 CI/CD：版本控制和自动化部署策略模板",
            "设计决策文档：记录隔离模型选择的理由和权衡",
        ],
        selfCheck: [
            "选择隔离模型需要考虑哪五个关键维度？",
            "什么是 Token Vending Machine 模式？它解决什么问题？",
            "动态策略生成相比静态策略有什么优势？",
            "IAM 内联策略的字符限制是多少？如何处理？",
            "ABAC 和动态策略生成各自适合什么场景？",
            "如何为开发者抽象隔离策略的复杂性？",
        ],
        extensions: [
            "研究 AWS Verified Permissions 的多租户策略管理",
            "探索 OPA（Open Policy Agent）在多租户策略中的应用",
            "了解 Google Cloud 的 VPC Service Controls 多租户实现",
            "分析 SpiceDB/Zanzibar 风格的关系型授权在多租户中的应用",
        ],
        sourceUrls: [
            "https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/considerations/tenancy-models",
            "https://docs.aws.amazon.com/whitepapers/latest/saas-tenant-isolation-strategies/run-time-policy-based-isolation-with-iam.html",
            "https://docs.aws.amazon.com/whitepapers/latest/saas-tenant-isolation-strategies/scaling-and-managing-pool-isolation-policies.html",
        ],
    },
}

export const week2Quizzes: Record<string, QuizQuestion[]> = {
    "w2-1": [
        {
            id: "w2-1-q1",
            question: "根据 AWS SaaS Lens，池化模型的定义是什么？",
            options: [
                "每个租户独立资源的架构",
                "租户共享资源的经典多租户架构",
                "混合孤岛和共享的架构",
                "按层级分配资源的架构",
            ],
            answer: 1,
            rationale: "AWS SaaS Lens 定义：'Pool Model—Architecture where tenants share resources (classic multi-tenancy)'。",
        },
        {
            id: "w2-1-q2",
            question: "PostgreSQL 启用 RLS 后，默认行为是什么？",
            options: [
                "所有行对所有用户可见",
                "只有管理员可以看到数据",
                "没有行可见，直到创建策略",
                "只有表所有者可以看到数据",
            ],
            answer: 2,
            rationale: "PostgreSQL 文档指出：'Once enabled, a default-deny policy applies—no rows are visible until policies are created'。",
        },
        {
            id: "w2-1-q3",
            question: "在 PostgreSQL RLS 中，哪些角色可以绕过 RLS？",
            options: [
                "只有应用程序用户",
                "超级用户、BYPASSRLS 属性角色、表所有者",
                "只有数据库管理员",
                "没有角色可以绕过 RLS",
            ],
            answer: 1,
            rationale: "PostgreSQL 文档警告：'Superusers always bypass RLS, Roles with BYPASSRLS attribute bypass RLS, Table owners bypass RLS'。",
        },
        {
            id: "w2-1-q4",
            question: "Azure 指出共享表模式（池化模型）的主要风险是什么？",
            options: [
                "成本过高",
                "部署复杂",
                "牺牲租户隔离，Noisy Neighbor 问题",
                "不支持扩展",
            ],
            answer: 2,
            rationale: "Azure 警告池化模式：'Sacrifices tenant isolation' 和 'One tenant's workload impacts others'。",
        },
        {
            id: "w2-1-q5",
            question: "PostgreSQL RLS 的 PERMISSIVE 和 RESTRICTIVE 策略如何组合？",
            options: [
                "PERMISSIVE 用 AND，RESTRICTIVE 用 OR",
                "PERMISSIVE 用 OR，RESTRICTIVE 用 AND",
                "两者都用 OR",
                "两者都用 AND",
            ],
            answer: 1,
            rationale: "PostgreSQL 文档说明：'PERMISSIVE (default) Combined with OR; RESTRICTIVE Combined with AND'。",
        },
        {
            id: "w2-1-q6",
            question: "根据 Azure 文档，池化模型的成本优势来自什么？",
            options: [
                "使用更便宜的硬件",
                "减少人员成本",
                "租户密度最高，基础设施利用率最高",
                "减少网络带宽",
            ],
            answer: 2,
            rationale: "Azure 指出：'Provides the highest density of tenants to infrastructure, so it tends to come at the lowest financial cost'。",
        },
        {
            id: "w2-1-q7",
            question: "在 PostgreSQL RLS 中，USING 子句控制什么？",
            options: [
                "只控制 INSERT 操作",
                "控制可见性（SELECT、UPDATE、DELETE）",
                "只控制 DELETE 操作",
                "控制表结构修改",
            ],
            answer: 1,
            rationale: "PostgreSQL 文档说明：'USING: Controls visibility (SELECT, UPDATE, DELETE)'。",
        },
        {
            id: "w2-1-q8",
            question: "Azure 描述的多租户共享数据库模式中，如何标识租户数据？",
            options: [
                "使用独立的 Schema",
                "使用独立的表",
                "行数据标记租户标识符",
                "使用独立的数据库实例",
            ],
            answer: 2,
            rationale: "Azure 描述：'All tenants share a single database, and rows are tagged with a tenant identifier'。",
        },
        {
            id: "w2-1-q9",
            question: "如何强制表所有者也遵守 RLS 策略？",
            options: [
                "无法实现",
                "使用 ALTER TABLE FORCE ROW LEVEL SECURITY",
                "删除表所有者权限",
                "创建 RESTRICTIVE 策略",
            ],
            answer: 1,
            rationale: "PostgreSQL 文档提供命令：'ALTER TABLE table_name FORCE ROW LEVEL SECURITY'。",
        },
        {
            id: "w2-1-q10",
            question: "Azure 指出共享表模式下单租户数据恢复的挑战是什么？",
            options: [
                "恢复速度太慢",
                "时间点恢复对单租户非常复杂",
                "需要停机才能恢复",
                "恢复数据会丢失",
            ],
            answer: 1,
            rationale: "Azure 指出：'Point-in-time restore for single tenant is complex' 在共享模式下。",
        },
        {
            id: "w2-1-q11",
            question: "PostgreSQL RLS 策略中，WITH CHECK 子句的作用是什么？",
            options: [
                "控制可见性",
                "控制修改操作（INSERT、UPDATE）",
                "控制表结构",
                "控制索引创建",
            ],
            answer: 1,
            rationale: "PostgreSQL 文档说明：'WITH CHECK: Controls modification (INSERT, UPDATE)'。",
        },
        {
            id: "w2-1-q12",
            question: "根据 AWS，池化模型的核心优势是什么？",
            options: [
                "隔离性最强",
                "合规性最好",
                "规模经济、可管理性、敏捷性、成本效率",
                "性能最高",
            ],
            answer: 2,
            rationale: "AWS 列出池化模型优势：'Economies of scale, Manageability, Agility, Cost efficiency'。",
        },
    ],
    "w2-2": [
        {
            id: "w2-2-q1",
            question: "根据 AWS 白皮书，孤岛隔离的核心特征是什么？",
            options: [
                "所有租户共享资源",
                "每个租户运行完全隔离的资源栈",
                "租户共享数据库但隔离计算",
                "租户共享计算但隔离数据库",
            ],
            answer: 1,
            rationale: "AWS 白皮书定义：'Silo isolation—each tenant runs a fully isolated stack of resources'。",
        },
        {
            id: "w2-2-q2",
            question: "AWS 描述的孤岛模型实现方式包括哪些？",
            options: [
                "只有共享数据库",
                "VPC per tenant 或 Account per tenant",
                "只有容器隔离",
                "只有网络隔离",
            ],
            answer: 1,
            rationale: "AWS 提供多种实现：'VPC per tenant—Network isolation' 或 'Account per tenant—AWS account-level isolation'。",
        },
        {
            id: "w2-2-q3",
            question: "根据 Azure，单租户印记（Deployment Stamps）的主要优势不包括？",
            options: [
                "最高隔离级别",
                "避免 Noisy Neighbor 问题",
                "成本最低",
                "支持租户特定定制",
            ],
            answer: 2,
            rationale: "Azure 指出单租户印记优势：'Highest level of isolation, Avoids noisy neighbor problem, Enables tenant-specific customization'，但成本是最高的而非最低。",
        },
        {
            id: "w2-2-q4",
            question: "AWS 警告孤岛模型在什么规模下变得难以管理？",
            options: [
                "10+ 租户",
                "100+ 租户",
                "1000+ 租户",
                "10000+ 租户",
            ],
            answer: 2,
            rationale: "AWS 指出：'There are limits on the number of accounts that can be provisioned...1000+ tenants become unmanageable'。",
        },
        {
            id: "w2-2-q5",
            question: "孤岛模型如何减少故障影响范围（Blast Radius）？",
            options: [
                "通过更好的错误处理",
                "通过故障隔离到单个租户环境，防止级联到其他租户",
                "通过更快的恢复速度",
                "通过冗余部署",
            ],
            answer: 1,
            rationale: "AWS 描述：'Failures within a given tenant's environment will likely be constrained to that environment, preventing cascade failures'。",
        },
        {
            id: "w2-2-q6",
            question: "根据 AWS，孤岛模型失去的 SaaS 核心优势是什么？",
            options: [
                "安全性",
                "规模经济，资源在非高峰期闲置",
                "可靠性",
                "合规性",
            ],
            answer: 1,
            rationale: "AWS 指出：'Loses SaaS economies of scale; idle resources during off-peak periods'。",
        },
        {
            id: "w2-2-q7",
            question: "AWS 描述的孤岛模型运维挑战是什么？",
            options: [
                "部署太快",
                "难以实现统一监控（single pane of glass）",
                "成本太低",
                "隔离太弱",
            ],
            answer: 1,
            rationale: "AWS 描述：'Decentralized Management—Difficult to achieve single pane of glass monitoring'。",
        },
        {
            id: "w2-2-q8",
            question: "Azure 指出孤岛模型的成本特征是什么？",
            options: [
                "最低成本",
                "中等成本",
                "高基础设施成本，需按峰值配置",
                "成本可忽略",
            ],
            answer: 2,
            rationale: "Azure 警告：'High infrastructure costs per tenant, Must provision for peak workload per tenant'。",
        },
        {
            id: "w2-2-q9",
            question: "孤岛模型最适合什么类型的客户？",
            options: [
                "成本敏感的小客户",
                "需要最低延迟的客户",
                "有严格隔离和合规要求的受监管环境客户",
                "只需要基本功能的客户",
            ],
            answer: 2,
            rationale: "AWS 强调：'Satisfies strict regulatory isolation requirements for regulated environments'。",
        },
        {
            id: "w2-2-q10",
            question: "Account-per-Tenant 模型相比 VPC-per-Tenant 的主要限制是什么？",
            options: [
                "网络延迟更高",
                "账户数量有限制，影响大规模扩展",
                "安全性较低",
                "不支持加密",
            ],
            answer: 1,
            rationale: "AWS 指出：'There are limits on the number of accounts that can be provisioned, which may exclude you from selecting the account-based model'。",
        },
        {
            id: "w2-2-q11",
            question: "孤岛模型如何完全消除 Noisy Neighbor 问题？",
            options: [
                "通过更好的资源调度",
                "通过提供完全专用的环境，没有跨租户共享",
                "通过限流",
                "通过优先级队列",
            ],
            answer: 1,
            rationale: "AWS 描述：'Silo addresses this by offering a dedicated environment with no potential noisy neighbor scenarios'。",
        },
        {
            id: "w2-2-q12",
            question: "根据 AWS，尽管孤岛模型是独立部署，它仍然与其他租户共享什么？",
            options: [
                "数据库",
                "计算资源",
                "身份认证、入驻和运营体验",
                "存储",
            ],
            answer: 2,
            rationale: "AWS 指出孤岛模型仍然：'maintains shared: identity, onboarding, and operational experience'。",
        },
    ],
    "w2-3": [
        {
            id: "w2-3-q1",
            question: "根据 AWS，桥接模型的定义是什么？",
            options: [
                "所有资源完全共享",
                "所有资源完全隔离",
                "结合孤岛和池化的混合架构",
                "只隔离数据库",
            ],
            answer: 2,
            rationale: "AWS 定义：'Bridge Model—Mixed-mode architecture combining silo and pool approaches'。",
        },
        {
            id: "w2-3-q2",
            question: "根据 Azure，在分层隔离中，哪些层可以采用不同的隔离级别？",
            options: [
                "只有数据层",
                "只有计算层",
                "UI 层、中间层、数据层都可以不同",
                "所有层必须相同",
            ],
            answer: 2,
            rationale: "Azure 指出：'Your user interface tier might be shared, middle tier shared, data tier isolated'——不同层可以采用不同隔离级别。",
        },
        {
            id: "w2-3-q3",
            question: "AWS 描述的分层定价策略中，池化标准层和孤岛高级层的价格关系是什么？",
            options: [
                "价格相同",
                "标准层更贵",
                "标准层低价，高级层大幅高价",
                "高级层免费",
            ],
            answer: 2,
            rationale: "AWS 指出：'Standard Tier (Pooled) → Lower price; Premium Tier (Silo) → Substantially higher price'。",
        },
        {
            id: "w2-3-q4",
            question: "AWS 建议 SaaS 提供商如何处理孤岛选项？",
            options: [
                "大力推广孤岛选项",
                "限制孤岛选项可见性，使用私有定价",
                "完全不提供孤岛选项",
                "免费提供孤岛选项",
            ],
            answer: 1,
            rationale: "AWS 建议：'SaaS providers typically minimize silo tier offerings' 和 'Private pricing options are often undisclosed to limit demand'。",
        },
        {
            id: "w2-3-q5",
            question: "AWS 描述的分层部署模型包括哪三个层级？",
            options: [
                "小型、中型、大型",
                "标准层、企业层、高级层",
                "免费、付费、企业",
                "基础、专业、旗舰",
            ],
            answer: 1,
            rationale: "AWS 描述三个层级：'Standard Tier, Enterprise Tier, Premium Tier'。",
        },
        {
            id: "w2-3-q6",
            question: "Azure 指出混合模式的代码挑战是什么？",
            options: [
                "性能太低",
                "代码库必须同时支持多租户和单租户模式",
                "安全性太差",
                "部署太慢",
            ],
            answer: 1,
            rationale: "Azure 警告：'Codebase must support both models' 在混合模式下。",
        },
        {
            id: "w2-3-q7",
            question: "根据 AWS，微服务选择孤岛还是池化模型的决策因素包括什么？",
            options: [
                "只考虑成本",
                "合规要求、数据敏感性、Noisy Neighbor 关注",
                "只考虑性能",
                "只考虑开发速度",
            ],
            answer: 1,
            rationale: "AWS 解释：'Decision factors: regulatory profile, data sensitivity, noisy neighbor concerns'。",
        },
        {
            id: "w2-3-q8",
            question: "AWS 要求高级孤岛客户必须做什么？",
            options: [
                "使用不同的产品版本",
                "运行与池化环境相同的产品版本",
                "自行管理基础设施",
                "不使用共享服务",
            ],
            answer: 1,
            rationale: "AWS 要求：'Premium silo customers often must run the same product version as the pooled environment'。",
        },
        {
            id: "w2-3-q9",
            question: "AWS API Gateway 如何实现分层限流？",
            options: [
                "使用 IP 白名单",
                "使用与 API Key 关联的 Usage Plans",
                "使用防火墙规则",
                "使用负载均衡器",
            ],
            answer: 1,
            rationale: "AWS 描述：'API Gateway usage plans associated with API keys...use one usage plan for each tenant tier with separate API keys'。",
        },
        {
            id: "w2-3-q10",
            question: "Azure 的垂直分区部署（Vertically Partitioned）示例是什么？",
            options: [
                "所有客户使用相同部署",
                "试用客户用共享基础设施，企业客户用专用部署",
                "按地理位置分区",
                "按数据类型分区",
            ],
            answer: 1,
            rationale: "Azure 示例：'Trial customers on shared infrastructure; enterprise customers on dedicated deployments'。",
        },
        {
            id: "w2-3-q11",
            question: "为什么 SaaS 提供商要限制孤岛选项的采用？",
            options: [
                "孤岛更不安全",
                "如果太多客户选择孤岛，规模经济会崩溃",
                "孤岛更难使用",
                "孤岛功能更少",
            ],
            answer: 1,
            rationale: "AWS 警告：'If too many customers choose silo, economies of scale collapse'。",
        },
        {
            id: "w2-3-q12",
            question: "AWS 分层部署模型中，策略变更如何管理？",
            options: [
                "统一推送到所有层级",
                "可以分别为每个层级独立部署",
                "只能手动更新",
                "不支持策略变更",
            ],
            answer: 1,
            rationale: "AWS 描述：'Changes to policies can be rolled out separately for each tier'。",
        },
    ],
    "w2-4": [
        {
            id: "w2-4-q1",
            question: "根据 Azure，选择租户模型需要考虑的五个关键维度是什么？",
            options: [
                "成本、性能、安全、可用性、可扩展性",
                "业务目标、合规、规模、自动化、SLA/SLO",
                "开发、测试、部署、运维、监控",
                "用户、数据、应用、网络、存储",
            ],
            answer: 1,
            rationale: "Azure 提出五个关键因素：'Business objectives, Compliance, Scale, Automation, SLAs/SLOs'。",
        },
        {
            id: "w2-4-q2",
            question: "AWS Token Vending Machine 模式的作用是什么？",
            options: [
                "生成用户密码",
                "查询隔离管理器获取租户范围的令牌",
                "管理数据库连接",
                "处理支付交易",
            ],
            answer: 1,
            rationale: "AWS 描述：'Isolation Manager queries token vending machine to get tenant-scoped token'。",
        },
        {
            id: "w2-4-q3",
            question: "AWS 动态策略生成相比静态策略的主要优势是什么？",
            options: [
                "更高的性能",
                "避免 IAM 策略数量限制，运行时生成",
                "更好的安全性",
                "更简单的代码",
            ],
            answer: 1,
            rationale: "AWS 描述：'Dynamic Policy Generation—policies are generated at runtime instead of storing individual IAM policies for each tenant'，解决策略数量限制。",
        },
        {
            id: "w2-4-q4",
            question: "AWS IAM 内联策略的字符限制是多少？",
            options: [
                "1,024 字符",
                "2,048 字符",
                "4,096 字符",
                "10,240 字符",
            ],
            answer: 1,
            rationale: "AWS 警告：'Inline policy has a limit of 2,048 characters'。",
        },
        {
            id: "w2-4-q5",
            question: "AWS 策略模板的作用是什么？",
            options: [
                "存储用户偏好",
                "预定义策略结构，用租户上下文填充占位符",
                "管理数据库 Schema",
                "处理网络配置",
            ],
            answer: 1,
            rationale: "AWS 描述：'Pre-defined template files containing IAM policy structure with placeholders for tenant context'。",
        },
        {
            id: "w2-4-q6",
            question: "根据 Azure 权衡矩阵，Database-per-Tenant 模式的特征是什么？",
            options: [
                "最低隔离，最低成本",
                "高隔离，低成本（通过弹性池）",
                "最高成本，最低隔离",
                "中等隔离，中等成本",
            ],
            answer: 1,
            rationale: "Azure 对比：'Database-per-Tenant—High isolation, Low cost (elastic pools can share resources)'。",
        },
        {
            id: "w2-4-q7",
            question: "AWS 建议如何管理策略模板的版本和部署？",
            options: [
                "手动更新每个租户",
                "通过 CI/CD 管道版本控制和部署",
                "不需要版本控制",
                "使用数据库存储",
            ],
            answer: 1,
            rationale: "AWS 建议：'Own content versioning and deployment of policy templates through your CI/CD pipeline'。",
        },
        {
            id: "w2-4-q8",
            question: "AWS 比较 ABAC 和动态策略生成时，ABAC 更适合什么场景？",
            options: [
                "频繁变更的角色定义",
                "广泛的 SaaS 应用，除非需要频繁变更角色定义",
                "只适合小型系统",
                "只适合单租户",
            ],
            answer: 1,
            rationale: "AWS 对比：'ABAC is suitable for a wide range of SaaS applications, unless your use case requires support for frequently changed role definitions'。",
        },
        {
            id: "w2-4-q9",
            question: "AWS 建议如何减少开发者在隔离策略上的错误？",
            options: [
                "提供更多培训",
                "对开发者隐藏策略机制细节",
                "增加代码审查",
                "使用更严格的类型检查",
            ],
            answer: 1,
            rationale: "AWS 建议：'Hide policy mechanism details from developers to reduce errors'。",
        },
        {
            id: "w2-4-q10",
            question: "根据 Azure，选择隔离模型需要平衡哪些因素？",
            options: [
                "只考虑成本",
                "隔离、成本、可扩展性、管理复杂度",
                "只考虑性能",
                "只考虑安全性",
            ],
            answer: 1,
            rationale: "Azure 指出：'The choice depends on balancing isolation, cost, scalability, and management complexity'。",
        },
        {
            id: "w2-4-q11",
            question: "AWS 动态策略生成过程中，Token Vending Machine 从哪里提取租户 ID？",
            options: [
                "数据库查询",
                "JWT 令牌的 Claims",
                "请求头",
                "Cookie",
            ],
            answer: 1,
            rationale: "AWS 描述：'The Token Vending Machine call will hydrate templates with the tenant extracted from the claims of a JWT'。",
        },
        {
            id: "w2-4-q12",
            question: "AWS 描述的策略模板变更如何应用到所有租户？",
            options: [
                "需要单独更新每个租户的策略",
                "通过模板更新统一应用到所有租户",
                "无法更新现有策略",
                "需要重新部署整个系统",
            ],
            answer: 1,
            rationale: "AWS 描述策略模板优势：'Changes to isolation policies can be applied globally without updating individual tenant policies'。",
        },
    ],
}
