import type { LessonGuide } from "../types"
import type { QuizQuestion } from "@/lib/types"

export const week1Guides: Record<string, LessonGuide> = {
    "w1-1": {
        lessonId: "w1-1",
        background: [
            "【核心定义】AWS 白皮书：'SaaS is fundamentally a business model rather than a purely technical architecture strategy'——SaaS 本质上是商业模式而非纯技术架构策略，多租户是实现这一商业模式的技术手段。",
            "【价值主张】多租户通过共享基础设施实现规模经济：降低运维成本、简化升级部署、统一管理体验，这是 SaaS 相比传统软件的核心优势。",
            "【隔离模型】AWS 定义三种主要模式：Fully Shared（完全共享）、Mixed Tenancy（混合模式）、Fully Siloed（完全隔离），每种模式在成本与隔离之间有不同权衡。",
            "【Azure 视角】Azure 架构指南强调：多租户不要求所有组件都共享，'Not all components must be shared—only some components'，这为混合策略提供了理论基础。",
            "【关键区别】单租户（Single-Tenant）每客户独立部署，隔离性强但成本高；多租户（Multi-Tenant）共享部署，成本低但需要额外的隔离机制。",
        ],
        keyDifficulties: [
            "【概念混淆】AWS 明确指出：'Multi-tenancy doesn't define SaaS'——多租户不等于 SaaS，SaaS 的本质是集中管理和运营，隔离模式可以多样化。",
            "【模式选择】三种隔离模式各有适用场景：池化模式成本最低但隔离最弱，孤岛模式隔离最强但成本最高，桥接模式需要在不同层采用不同策略。",
            "【成本权衡】AWS 指出 100 个租户在单租户模式下意味着 100 倍基础设施成本，而多租户模式可以大幅降低边际成本。",
            "【定义租户】Azure 强调需要先定义'租户'的含义：B2B 场景通常是组织，B2C 场景可能是个人或家庭，定义不同会影响整体架构设计。",
        ],
        handsOnPath: [
            "绘制你的 SaaS 产品架构图，标注哪些组件是共享的、哪些是隔离的",
            "列出当前客户的隔离需求：合规要求、性能要求、定制化需求",
            "计算单租户 vs 多租户的 TCO：基础设施成本、运维成本、升级成本",
            "分析现有系统的隔离边界：数据库、计算、网络、存储各层的隔离程度",
            "制定隔离策略路线图：从当前状态到目标状态的演进路径",
        ],
        selfCheck: [
            "能否清晰解释多租户与单租户的本质区别？",
            "你的 SaaS 产品中，'租户'的定义是什么？",
            "为什么说 SaaS 是商业模式而非技术架构？",
            "三种隔离模式（池化/孤岛/桥接）各自的适用场景是什么？",
            "如何计算多租户架构相比单租户的成本节约？",
            "Mixed Tenancy 模式下，哪些资源适合共享，哪些适合隔离？",
        ],
        extensions: [
            "研究 AWS Well-Architected SaaS Lens 的五大支柱如何应用于多租户架构",
            "分析 Salesforce、Slack 等成功 SaaS 产品的多租户实现策略",
            "探索 Kubernetes 多租户模式与传统虚拟化多租户的差异",
            "了解 Serverless 架构如何简化多租户实现",
        ],
        sourceUrls: [
            "https://docs.aws.amazon.com/whitepapers/latest/saas-architecture-fundamentals/re-defining-multi-tenancy.html",
            "https://learn.microsoft.com/en-us/azure/architecture/guide/saas-multitenant-solution-architecture/",
            "https://aws.amazon.com/solutions/guidance/multi-tenant-architectures-on-aws/",
        ],
    },
    "w1-2": {
        lessonId: "w1-2",
        background: [
            "【ARR 为王】BVP 报告：'ARR is the North Star for cloud companies'——年度经常性收入是衡量 SaaS 公司成功的核心指标，多租户架构直接影响 ARR 的可扩展性。",
            "【增长基准】BVP 数据：$1-10M ARR 阶段平均增长率约 200%，$50-100M ARR 阶段降至约 60%，多租户架构需要支撑这种高速增长。",
            "【留存关键】Net Retention（净留存）在早期阶段可达 140%，意味着现有客户的扩展收入超过流失，多租户的弹性定价是实现这一目标的关键。",
            "【成本分摊】AWS SaaS Lens：成本分摊需要两类数据——租户消耗数据（使用百分比）和 AWS 账单数据（基础设施成本），两者结合才能计算真实的租户成本。",
            "【CAC 回收】a16z 指南：SaaS 的 CAC Payback 目标因客户类型而异——SMB <12 个月，中型市场 <18 个月，企业级 <24 个月。",
        ],
        keyDifficulties: [
            "【计量挑战】AWS 指出：在共享资源环境中将消耗归因到具体租户是核心难题，需要平衡计量精度与实施复杂度。",
            "【LTV 计算】a16z 警告：常见错误是用收入而非净利润计算 LTV，正确公式是 (ARR × 毛利率) ÷ (流失率 + 折现率)。",
            "【成本失衡】AWS 示例：可能出现基础层（最低收入）消耗最多基础设施成本的情况，这表明定价与架构存在错配。",
            "【毛利率】BVP 数据：SaaS 公司毛利率通常稳定在 65-70%，过低说明交付效率有问题，多租户架构是提升毛利率的关键。",
        ],
        handsOnPath: [
            "计算你的 SaaS 产品的关键指标：ARR、MRR、毛利率、流失率",
            "设计租户消耗计量方案：API 调用、存储、计算资源的追踪机制",
            "构建成本分摊模型：将 AWS/云账单分配到各租户",
            "分析 LTV/CAC 比率：确保大于 3:1 的健康水平",
            "绘制单位经济模型：每个租户的边际成本与边际收入",
        ],
        selfCheck: [
            "ARR 和 MRR 的区别是什么？为什么 ARR 是 SaaS 的核心指标？",
            "如何避免在 ARR 计算中包含非经常性收入？",
            "什么是健康的 LTV/CAC 比率？你的产品处于什么水平？",
            "如何设计租户消耗计量方案？最小侵入式和精细化方案各有什么优缺点？",
            "Net Retention 超过 100% 意味着什么？",
            "如何识别和处理成本与收入不匹配的租户层级？",
        ],
        extensions: [
            "研究 Usage-Based Pricing 模式及其对多租户架构的要求",
            "了解 FinOps 实践如何优化多租户成本管理",
            "探索 AWS Cost Explorer 和 CloudWatch 的租户级成本追踪能力",
            "分析 PLG（Product-Led Growth）模式下的多租户经济学",
        ],
        sourceUrls: [
            "https://www.bvp.com/atlas/scaling-to-100-million",
            "https://docs.aws.amazon.com/wellarchitected/latest/saas-lens/expenditure-awareness.html",
            "https://a16z.com/16-startup-metrics/",
        ],
    },
    "w1-3": {
        lessonId: "w1-3",
        background: [
            "【数据隔离】Azure 指南：'Strong identity strategy and authorization processes that account for both tenant and user identity'——需要同时考虑租户身份和用户身份的双层认证授权。",
            "【性能隔离】Azure 定义 Noisy Neighbor 问题：'One tenant's unusual usage patterns can degrade system performance for all tenants'——一个租户的异常使用模式会影响所有租户。",
            "【隔离边界】AWS 白皮书强调：'Tenant isolation is separate from general security mechanisms'——租户隔离与一般安全机制是分开的，认证授权不等于隔离。",
            "【合规挑战】Azure 指出：'Some customers may refuse all forms of multitenancy'——某些客户可能拒绝任何形式的多租户，高合规行业往往要求专用基础设施。",
            "【跨租户漏洞】OWASP 项目定义：'Cross-tenant vulnerability permits malicious actors to breach isolation boundaries'——跨租户漏洞允许恶意攻击者突破隔离边界。",
        ],
        keyDifficulties: [
            "【认证 ≠ 隔离】AWS 明确指出：'The fact that a tenant user is authenticated does not mean that your system has achieved isolation'——用户已认证不等于实现了隔离。",
            "【泄露风险】Azure 警告：共享基础设施时，应用代码必须可靠地使用租户标识符分离数据，必须测试验证一个租户的数据不会泄露到另一个。",
            "【常见错误】OWASP 列出：配置不当的容器、过于宽松的防火墙规则、不充分的数据清理程序是常见的 SaaS 安全错误。",
            "【扩展限制】Azure 指出：单一共享部署面临 Azure 资源配额限制、非线性成本增加、数据库吞吐量耗尽等风险。",
        ],
        handsOnPath: [
            "审计当前系统的租户隔离边界：数据库、缓存、文件存储、消息队列",
            "设计跨租户访问测试用例：验证一个租户无法访问另一个租户的数据",
            "实施 Noisy Neighbor 监控：识别资源消耗异常的租户",
            "评估合规要求：列出不同客户群体的隔离需求等级",
            "审查 OWASP Cloud Tenant Isolation 检查清单",
        ],
        selfCheck: [
            "为什么认证和授权不等于租户隔离？",
            "什么是 Noisy Neighbor 问题？有哪些缓解策略？",
            "如何测试验证租户数据隔离的有效性？",
            "OWASP 列出的 SaaS 常见安全错误有哪些？",
            "高合规行业（如金融、医疗）对多租户有什么特殊要求？",
            "如何在共享表模式下防止数据泄露？",
        ],
        extensions: [
            "深入研究 OWASP Top 10 2025 中与多租户相关的风险（A01 Broken Access Control）",
            "了解 SOC 2、HIPAA、GDPR 对多租户系统的合规要求",
            "探索 AWS IAM 和 Azure RBAC 在多租户隔离中的应用",
            "研究 Chaos Engineering 在多租户系统中的应用",
        ],
        sourceUrls: [
            "https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/considerations/tenancy-models",
            "https://docs.aws.amazon.com/whitepapers/latest/saas-architecture-fundamentals/tenant-isolation.html",
            "https://owasp.org/www-project-cloud-tenant-isolation/",
        ],
    },
    "w1-4": {
        lessonId: "w1-4",
        background: [
            "【隔离心态】AWS 白皮书：'Isolation is a foundational element, not optional'——隔离是基础要素而非可选项，每个多租户系统都必须实施隔离措施。",
            "【决策维度】Azure 提出五个决策维度：业务目标、合规要求、规模预期、自动化能力、SLA/SLO 承诺。",
            "【部署印记】Azure 推荐 Deployment Stamps Pattern：使用专用基础设施印记，可以是单租户印记（一个租户一个印记）或多租户印记（多个租户共享一个印记）。",
            "【混合策略】AWS 建议：可以为高价值租户分配孤岛式基础设施，同时将其他租户合并到共享环境，实现安全与成本的双重优化。",
            "【逻辑隔离】AWS 强调：'Isolation can be logical, not just physical'——隔离可以是逻辑的而非物理的，共享资源模式通过策略实现逻辑隔离。",
        ],
        keyDifficulties: [
            "【工具限制】AWS 警告：'If no out-of-the-box solution exists, build one yourself'——如果没有现成解决方案，应该自建而非降低隔离要求。",
            "【基础设施即代码】Azure 建议：使用 Bicep、Terraform 或 Azure SDK 实现自动化部署，这对管理多租户部署至关重要。",
            "【分布式系统挑战】Martin Fowler 模式库涉及：分区（Fixed/Key-Range Partitions）、复制（Leader-Followers）、共识（Paxos/Majority Quorum），这些是多租户分布式系统的基础。",
            "【演进路径】Azure 建议：'Start multitenant, add single-tenant deployments as customers demand it'——从多租户开始，根据客户需求逐步添加单租户部署。",
        ],
        handsOnPath: [
            "使用五维度框架评估你的多租户需求：业务目标、合规、规模、自动化、SLA",
            "设计租户分层策略：基础层、专业层、企业层分别采用什么隔离级别",
            "创建 Deployment Stamps 架构图：展示租户到印记的映射关系",
            "准备基础设施即代码模板：Terraform 或 Bicep 定义租户资源",
            "制定隔离级别升级路径：当客户需要更强隔离时如何迁移",
        ],
        selfCheck: [
            "为什么说隔离是基础要素而非可选项？",
            "Azure 提出的五个决策维度分别是什么？",
            "什么是 Deployment Stamps Pattern？它如何支持多租户？",
            "逻辑隔离与物理隔离有什么区别？各自适用什么场景？",
            "如何设计租户分层策略来平衡成本与隔离需求？",
            "为什么建议从多租户开始而非从单租户开始？",
        ],
        extensions: [
            "深入研究 AWS Well-Architected SaaS Lens 的完整框架",
            "了解 Kubernetes Namespace 和 Network Policy 在多租户中的应用",
            "探索 Service Mesh（Istio）如何增强多租户隔离",
            "研究 Cell-Based Architecture 作为 Deployment Stamps 的进阶模式",
        ],
        sourceUrls: [
            "https://docs.aws.amazon.com/whitepapers/latest/saas-tenant-isolation-strategies/the-isolation-mindset.html",
            "https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/approaches/overview",
            "https://martinfowler.com/articles/patterns-of-distributed-systems/",
        ],
    },
}

export const week1Quizzes: Record<string, QuizQuestion[]> = {
    "w1-1": [
        {
            id: "w1-1-q1",
            question: "根据 AWS 白皮书，SaaS 的本质是什么？",
            options: [
                "一种纯技术架构策略",
                "一种商业模式，而非纯技术架构策略",
                "一种数据库设计模式",
                "一种网络部署方案",
            ],
            answer: 1,
            rationale: "AWS 白皮书明确指出：'SaaS is fundamentally a business model rather than a purely technical architecture strategy'，强调 SaaS 本质是商业模式。",
        },
        {
            id: "w1-1-q2",
            question: "AWS 定义的三种主要隔离模式不包括以下哪一种？",
            options: [
                "Fully Shared（完全共享）",
                "Mixed Tenancy（混合模式）",
                "Virtual Isolation（虚拟隔离）",
                "Fully Siloed（完全隔离）",
            ],
            answer: 2,
            rationale: "AWS 白皮书定义了三种模式：Fully Shared、Mixed Tenancy 和 Fully Siloed，没有 Virtual Isolation 这个分类。",
        },
        {
            id: "w1-1-q3",
            question: "根据 Azure 架构指南，关于多租户组件共享的描述，哪个是正确的？",
            options: [
                "所有组件都必须共享才算多租户",
                "不需要所有组件共享，只需要部分组件共享",
                "只有数据库必须共享",
                "只有计算资源必须共享",
            ],
            answer: 1,
            rationale: "Azure 指南明确指出：'Not all components must be shared—only some components'，多租户不要求所有组件都共享。",
        },
        {
            id: "w1-1-q4",
            question: "在 AWS 的 Mixed Tenancy 模式中，以下哪种组合是有效的？",
            options: [
                "共享计算 + 共享存储（所有租户）",
                "共享计算 + 独立存储（每租户）",
                "共享网络 + 共享安全组",
                "独立账户 + 共享 VPC",
            ],
            answer: 1,
            rationale: "AWS 白皮书示例中，Mixed Tenancy 模式可以是 'Order Service: Shared compute + Separate storage per tenant'，即共享计算但独立存储。",
        },
        {
            id: "w1-1-q5",
            question: "根据 AWS 多租户指南，Silo Model 使用什么作为隔离边界？",
            options: [
                "仅使用数据库 Schema",
                "仅使用行级安全策略",
                "独立的数据库实例或 VPC",
                "仅使用应用层过滤",
            ],
            answer: 2,
            rationale: "AWS 指南描述 Silo Model：'Separate tenant data into a database instance per tenant'，使用独立数据库实例或 VPC 作为最强隔离边界。",
        },
        {
            id: "w1-1-q6",
            question: "AWS 多租户指南中的 Pool Model 使用什么机制分隔租户数据？",
            options: [
                "独立的 AWS 账户",
                "独立的 VPC",
                "行级安全（Row-Level Security）特性",
                "独立的数据库实例",
            ],
            answer: 2,
            rationale: "AWS 指南指出 Pool Model：'Implements row-level security features to partition tenant data within shared tables'，使用行级安全分隔共享表中的数据。",
        },
        {
            id: "w1-1-q7",
            question: "根据 Azure 指南，在 B2B SaaS 中，'租户'通常映射到什么？",
            options: [
                "单个用户",
                "用户组或家庭",
                "客户组织（可能包括部门、区域、环境）",
                "API 密钥",
            ],
            answer: 2,
            rationale: "Azure 指南指出 B2B 场景：'Map tenants to customer organizations (consider divisions, regions, dev/prod environments)'。",
        },
        {
            id: "w1-1-q8",
            question: "AWS 白皮书关于多租户定义的关键观点是什么？",
            options: [
                "多租户等同于 SaaS",
                "多租户必须完全共享所有资源",
                "多租户不定义 SaaS，集中管理运营才是关键",
                "多租户只适用于小规模系统",
            ],
            answer: 2,
            rationale: "AWS 明确指出：'Multi-tenancy doesn't define SaaS'，SaaS 由集中管理和运营（collective management and operation）定义。",
        },
        {
            id: "w1-1-q9",
            question: "根据 AWS 指南，Bridge Model 的特点是什么？",
            options: [
                "所有资源完全隔离",
                "所有资源完全共享",
                "将租户隔离到共享数据库实例内的专用 Schema",
                "使用 VPC Peering 连接租户",
            ],
            answer: 2,
            rationale: "AWS 指南描述 Bridge Model：'Isolates each tenant into dedicated schemas within shared database instances'。",
        },
        {
            id: "w1-1-q10",
            question: "Azure 指南中，多租户可以存在于以下哪些场景？",
            options: [
                "仅 SaaS 场景",
                "仅企业内部场景",
                "SaaS 和非 SaaS 场景都可以",
                "仅公有云场景",
            ],
            answer: 2,
            rationale: "Azure 指南指出多租户 'Can exist in both SaaS and non-SaaS scenarios'，例如企业内部的多部门共享平台。",
        },
        {
            id: "w1-1-q11",
            question: "AWS 指南建议什么情况下使用混合架构（Hybrid）？",
            options: [
                "所有租户需求完全相同时",
                "为高价值租户提供孤岛式基础设施，其他租户使用共享环境",
                "预算极其有限时",
                "仅开发测试环境",
            ],
            answer: 1,
            rationale: "AWS 指南建议：'Allocating siloed infrastructure to high-value tenants while consolidating others, optimizing both security and spending'。",
        },
        {
            id: "w1-1-q12",
            question: "根据 Azure 指南，选择租户模型时首先应该做什么？",
            options: [
                "选择数据库类型",
                "定义什么是'租户'",
                "确定云提供商",
                "设计 API 接口",
            ],
            answer: 1,
            rationale: "Azure 指南强调：'Start by defining what a tenant means for your organization'，定义租户是架构决策的第一步。",
        },
    ],
    "w1-2": [
        {
            id: "w1-2-q1",
            question: "根据 BVP 报告，什么是云公司的'North Star'指标？",
            options: [
                "MRR（月度经常性收入）",
                "ARR（年度经常性收入）",
                "GMV（商品交易总额）",
                "DAU（日活跃用户）",
            ],
            answer: 1,
            rationale: "BVP 报告明确指出：'ARR is the North Star for cloud companies'，ARR 是衡量云公司成功的核心指标。",
        },
        {
            id: "w1-2-q2",
            question: "根据 BVP 数据，$1-10M ARR 阶段的 SaaS 公司平均增长率约为？",
            options: [
                "约 60%",
                "约 115%",
                "约 200%",
                "约 300%",
            ],
            answer: 2,
            rationale: "BVP 报告数据：'$1-10MM ARR: ~200% average growth'，早期阶段增长率最高。",
        },
        {
            id: "w1-2-q3",
            question: "a16z 指南中，健康的 LTV/CAC 比率应该是多少？",
            options: [
                "大于 1:1",
                "大于 2:1",
                "大于 3:1",
                "大于 5:1",
            ],
            answer: 2,
            rationale: "a16z 指南指出：'If LTV is 3X or greater than CAC, that's a good sign that the business model is working'。",
        },
        {
            id: "w1-2-q4",
            question: "根据 a16z，计算 LTV 时常见的错误是什么？",
            options: [
                "使用年度数据而非月度数据",
                "使用收入或毛利润而非净利润",
                "忽略季节性因素",
                "使用历史数据而非预测数据",
            ],
            answer: 1,
            rationale: "a16z 警告：'A common mistake is to estimate the LTV as a present value of revenue or even gross margin instead of calculating it as net profit'。",
        },
        {
            id: "w1-2-q5",
            question: "AWS SaaS Lens 指出，计算租户成本需要哪两类数据？",
            options: [
                "收入数据和利润数据",
                "租户消耗数据和 AWS 账单数据",
                "用户数据和流量数据",
                "合同数据和发票数据",
            ],
            answer: 1,
            rationale: "AWS SaaS Lens 指出需要两类数据：'Tenant Consumption Data—What resources each tenant used (%)' 和 'AWS Billing Data—Infrastructure costs from AWS bill'。",
        },
        {
            id: "w1-2-q6",
            question: "根据 BVP 数据，SaaS 公司的毛利率通常稳定在什么水平？",
            options: [
                "40-50%",
                "55-60%",
                "65-70%",
                "80-85%",
            ],
            answer: 2,
            rationale: "BVP 报告指出：'Gross Margins remain stable at 65-70% across all scales'，代表软件交付效率。",
        },
        {
            id: "w1-2-q7",
            question: "根据 a16z，面向企业客户的 CAC Payback 目标期限是多少？",
            options: [
                "<6 个月",
                "<12 个月",
                "<18 个月",
                "<24 个月",
            ],
            answer: 3,
            rationale: "a16z 指出：'If you sell to large enterprises, 18-24 months'，企业客户的回收周期更长。",
        },
        {
            id: "w1-2-q8",
            question: "AWS SaaS Lens 中的'最小侵入式'消耗计量方法使用什么技术？",
            options: [
                "在每个微服务中嵌入监控代码",
                "使用 Lambda 授权器从 JWT 提取租户上下文并发布事件",
                "直接查询数据库访问日志",
                "使用网络流量分析",
            ],
            answer: 1,
            rationale: "AWS 描述最小侵入式模型：'Use AWS Lambda authorizer to inspect API calls, Extract tenant context from JWT tokens, Publish activity events'。",
        },
        {
            id: "w1-2-q9",
            question: "根据 BVP 报告，早期 SaaS 公司（$1-10M ARR）的 Net Retention 平均值约为？",
            options: [
                "100%",
                "120%",
                "140%",
                "160%",
            ],
            answer: 2,
            rationale: "BVP 报告：'Net Retention shows expansion revenue, averaging 140% at early stages ($1-10MM)'。",
        },
        {
            id: "w1-2-q10",
            question: "a16z 指出，什么是 B2B 公司经济模型更重要的驱动因素？",
            options: [
                "首次合同金额（ACV）",
                "扩展收入（体现在 Net Dollar Retention）",
                "市场营销支出",
                "产品功能数量",
            ],
            answer: 1,
            rationale: "a16z 指出：'The economics of B2B companies are more driven by expansion than up front ACV. Net Dollar Retention is the best indicator'。",
        },
        {
            id: "w1-2-q11",
            question: "AWS SaaS Lens 建议将计量重点放在哪里？",
            options: [
                "所有服务均匀分配",
                "代表成本最大百分比的服务",
                "用户最频繁使用的服务",
                "最新上线的服务",
            ],
            answer: 1,
            rationale: "AWS SaaS Lens 建议：'ROI Focus: Concentrate metering on services representing largest % of costs'。",
        },
        {
            id: "w1-2-q12",
            question: "AWS SaaS Lens 举例的成本失衡场景是什么？",
            options: [
                "高级层消耗最多成本但收入最低",
                "基础层（最低收入）消耗最多基础设施成本",
                "所有层级成本与收入完全匹配",
                "中间层成本最高但收入最低",
            ],
            answer: 1,
            rationale: "AWS 示例：'Basic tier (lowest revenue) consuming most infrastructure costs, while Advanced tier (highest revenue) has smaller cost footprint'。",
        },
    ],
    "w1-3": [
        {
            id: "w1-3-q1",
            question: "根据 Azure 指南，多租户数据隔离需要考虑哪两种身份？",
            options: [
                "管理员身份和普通用户身份",
                "租户身份和用户身份",
                "内部身份和外部身份",
                "人类身份和服务身份",
            ],
            answer: 1,
            rationale: "Azure 指南指出：'Strong identity strategy and authorization processes that account for both tenant and user identity'。",
        },
        {
            id: "w1-3-q2",
            question: "Azure 如何定义 Noisy Neighbor 问题？",
            options: [
                "租户数据被其他租户访问",
                "一个租户的异常使用模式影响所有租户的性能",
                "租户之间的网络延迟过高",
                "租户配置冲突",
            ],
            answer: 1,
            rationale: "Azure 定义：'One tenant's unusual usage patterns can degrade system performance for all tenants'。",
        },
        {
            id: "w1-3-q3",
            question: "根据 AWS 白皮书，关于认证和隔离的关系，哪个描述是正确的？",
            options: [
                "用户认证后就自动实现了隔离",
                "认证是隔离的充分条件",
                "用户已认证不代表系统已实现隔离",
                "隔离只需要认证不需要授权",
            ],
            answer: 2,
            rationale: "AWS 明确指出：'The fact that a tenant user is authenticated does not mean that your system has achieved isolation'。",
        },
        {
            id: "w1-3-q4",
            question: "OWASP 列出的 SaaS 常见安全错误包括以下哪些？",
            options: [
                "使用过于复杂的密码策略",
                "配置不当的容器、过于宽松的防火墙规则",
                "过度使用加密",
                "日志记录过于详细",
            ],
            answer: 1,
            rationale: "OWASP 列出：'Improperly configured containers, Firewall rules lacking appropriate restrictions, Inadequate data cleansing procedures'。",
        },
        {
            id: "w1-3-q5",
            question: "根据 Azure 指南，Noisy Neighbor 问题的缓解策略不包括以下哪一项？",
            options: [
                "水平分区部署（如独立数据库共享应用层）",
                "为性能敏感客户部署单租户基础设施",
                "增加共享资源的容量上限",
                "使用资源配额和监控",
            ],
            answer: 2,
            rationale: "Azure 列出的缓解策略包括水平分区、单租户部署和资源配额，但单纯增加容量不能从根本上解决问题。",
        },
        {
            id: "w1-3-q6",
            question: "根据 AWS 白皮书，租户隔离与一般安全机制的关系是什么？",
            options: [
                "租户隔离是一般安全机制的一部分",
                "租户隔离与一般安全机制是分开的独立概念",
                "一般安全机制包含所有隔离需求",
                "两者完全相同",
            ],
            answer: 1,
            rationale: "AWS 强调：'Tenant isolation is separate from general security mechanisms'，两者是独立的概念。",
        },
        {
            id: "w1-3-q7",
            question: "OWASP Cloud Tenant Isolation 项目的目标是什么？",
            options: [
                "制定云安全合规标准",
                "记录导致隔离逃逸的常见架构缺陷",
                "提供免费的安全扫描工具",
                "认证安全的 SaaS 产品",
            ],
            answer: 1,
            rationale: "OWASP 项目目标包括：'Document vulnerabilities: Compile common architectural flaws enabling isolation escapes'。",
        },
        {
            id: "w1-3-q8",
            question: "根据 Azure 指南，高合规客户通常有什么特殊要求？",
            options: [
                "更低的价格",
                "更多的功能",
                "专用基础设施和增强的隔离",
                "更快的响应时间",
            ],
            answer: 2,
            rationale: "Azure 指出：'High-compliance customers may demand dedicated infrastructure'，合规要求往往推动向单租户部署。",
        },
        {
            id: "w1-3-q9",
            question: "Azure 指南中，完全多租户部署（Fully Multitenant）的主要风险不包括？",
            options: [
                "数据隔离复杂性和泄露风险",
                "Noisy Neighbor 问题",
                "成本过高",
                "Azure 资源配额限制",
            ],
            answer: 2,
            rationale: "完全多租户部署的成本是最低的，风险包括数据隔离复杂性、Noisy Neighbor 和资源配额限制。",
        },
        {
            id: "w1-3-q10",
            question: "OWASP 将跨租户漏洞描述为什么类型的安全风险？",
            options: [
                "传统的网络安全风险",
                "云应用特有的新型安全风险",
                "客户端安全风险",
                "物理安全风险",
            ],
            answer: 1,
            rationale: "OWASP 描述：'A new type of security risk that is characteristic of cloud-based applications'。",
        },
        {
            id: "w1-3-q11",
            question: "根据 Azure 指南，共享基础设施时应用代码必须做什么？",
            options: [
                "禁止任何跨租户通信",
                "可靠地使用租户标识符分离数据",
                "为每个请求创建新的数据库连接",
                "加密所有内存数据",
            ],
            answer: 1,
            rationale: "Azure 指出：'Application code must reliably separate tenant data using tenant identifiers in databases'。",
        },
        {
            id: "w1-3-q12",
            question: "Azure 指南建议对多租户系统进行什么类型的测试？",
            options: [
                "仅功能测试",
                "仅性能测试",
                "验证租户数据隔离和 Noisy Neighbor 场景测试",
                "仅安全渗透测试",
            ],
            answer: 2,
            rationale: "Azure 建议：'Verify tenant data isolation (no accidental leakage), Test noisy neighbor scenarios, Use Azure Chaos Studio to simulate faults'。",
        },
    ],
    "w1-4": [
        {
            id: "w1-4-q1",
            question: "根据 AWS 白皮书，关于隔离的基本原则是什么？",
            options: [
                "隔离是可选的高级功能",
                "隔离是基础要素，不是可选项",
                "隔离只在企业版需要",
                "隔离可以后期添加",
            ],
            answer: 1,
            rationale: "AWS 明确指出：'Isolation is a foundational element, not optional'，隔离是每个多租户系统必须实施的基础要素。",
        },
        {
            id: "w1-4-q2",
            question: "Azure 提出的选择租户模型的五个决策维度不包括以下哪一项？",
            options: [
                "业务目标",
                "合规要求",
                "技术栈偏好",
                "规模预期",
            ],
            answer: 2,
            rationale: "Azure 的五个决策维度是：业务目标、合规要求、规模预期、自动化能力、SLA/SLO 承诺，不包括技术栈偏好。",
        },
        {
            id: "w1-4-q3",
            question: "根据 AWS 白皮书，当没有现成工具支持隔离需求时应该怎么做？",
            options: [
                "降低隔离要求",
                "选择其他云平台",
                "自建解决方案",
                "放弃多租户架构",
            ],
            answer: 2,
            rationale: "AWS 警告：'If no out-of-the-box solution exists, build one yourself'，不应降低隔离要求。",
        },
        {
            id: "w1-4-q4",
            question: "Azure 推荐的 Deployment Stamps Pattern 是什么？",
            options: [
                "所有租户共享一个部署",
                "每个租户一个独立的云账户",
                "使用专用基础设施印记，可以单租户或多租户",
                "使用容器化部署所有服务",
            ],
            answer: 2,
            rationale: "Azure 推荐：'Deployment Stamps Pattern—dedicated infrastructure stamps that can serve single-tenant or multitenant stamps'。",
        },
        {
            id: "w1-4-q5",
            question: "根据 AWS 白皮书，隔离可以是什么形式？",
            options: [
                "只能是物理隔离",
                "只能是逻辑隔离",
                "可以是逻辑的，不一定是物理的",
                "必须同时是物理和逻辑隔离",
            ],
            answer: 2,
            rationale: "AWS 强调：'Isolation can be logical, not just physical'，共享资源模式通过策略实现逻辑隔离也是有效的。",
        },
        {
            id: "w1-4-q6",
            question: "Azure 指南建议 SaaS 产品应该如何演进？",
            options: [
                "从单租户开始，逐步转向多租户",
                "从多租户开始，根据客户需求添加单租户部署",
                "始终保持单租户架构",
                "始终保持多租户架构",
            ],
            answer: 1,
            rationale: "Azure 建议：'Start multitenant, add single-tenant deployments as customers demand it'。",
        },
        {
            id: "w1-4-q7",
            question: "根据 AWS 白皮书，隔离边界不应该仅依赖什么？",
            options: [
                "数据库层隔离",
                "网络层隔离",
                "开发人员的自觉性",
                "应用层隔离",
            ],
            answer: 2,
            rationale: "AWS 指出：'Don't rely on developer discipline alone. Implement shared mechanisms that apply isolation rules automatically'。",
        },
        {
            id: "w1-4-q8",
            question: "Azure 指南中，垂直分区部署（Vertically Partitioned）的特点是什么？",
            options: [
                "所有资源完全隔离",
                "所有资源完全共享",
                "混合单租户和多租户部署",
                "按地理区域分区",
            ],
            answer: 2,
            rationale: "Azure 描述：'Mix of single-tenant and multitenant deployments. Example: Trial customers on shared infrastructure; enterprise customers on dedicated'。",
        },
        {
            id: "w1-4-q9",
            question: "根据 Martin Fowler 的分布式系统模式，Fixed Partitions 模式的作用是什么？",
            options: [
                "提高查询性能",
                "保持数据到分区的映射在集群大小变化时不变",
                "减少网络延迟",
                "简化部署流程",
            ],
            answer: 1,
            rationale: "Martin Fowler 模式库描述：'Keep the number of partitions fixed to keep the mapping of data to partition unchanged when the size of a cluster changes'。",
        },
        {
            id: "w1-4-q10",
            question: "Azure 指南建议使用什么来实现自动化部署？",
            options: [
                "手动脚本",
                "GUI 控制台",
                "Infrastructure as Code（Bicep、Terraform）",
                "命令行工具",
            ],
            answer: 2,
            rationale: "Azure 建议：'Use Infrastructure as Code for automated deployment: Bicep files, Terraform templates, Azure SDKs'。",
        },
        {
            id: "w1-4-q11",
            question: "根据 AWS 白皮书，高合规领域通常需要什么级别的隔离？",
            options: [
                "仅逻辑隔离即可",
                "共享策略方式即可",
                "专用数据库等资源级隔离",
                "无特殊要求",
            ],
            answer: 2,
            rationale: "AWS 指出：'High-compliance industries often require: dedicated databases per tenant. Shared policy-based approaches may be insufficient'。",
        },
        {
            id: "w1-4-q12",
            question: "Azure 指南中，租户（Tenant）和部署（Deployment/Stamp）的关系是什么？",
            options: [
                "必须是一对一关系",
                "可以是多对一（多个租户映射到一个部署）或一对一",
                "必须是多对多关系",
                "租户就是部署",
            ],
            answer: 1,
            rationale: "Azure 说明映射关系：'One-to-many: Multiple tenants → Single deployment' 或 'One-to-one: One tenant → One deployment'。",
        },
    ],
}
